### PR TITLE
make-iso9660-image: produce stable GPT disk GUID

### LINKED ISSUE #74047: nixos.iso_minimal has a nondeterministic disk guid
**Describe the bug**

When building `nixos.iso_minimal.x86_64-linux` twice, the GPT partition has a different GUID.

**To Reproduce**
1. `nix-build ./nixos/release-combined.nix -A nixos.iso_minimal.x86_64-linux`
2. `nix-build ./nixos/release-combined.nix -A nixos.iso_minimal.x86_64-linux --check --keep-failed`
3. use `gdisk` to see the GUID is not consistent (or `diffoscope` at `0x00000238`, https://en.wikipedia.org/wiki/GUID_Partition_Table)

**Expected behavior**
A deterministic GUID

**Additional context**
For additional background on why it's helpful for builds to be reproducible, see https://reproducible-builds.org/

I'd be happy to help hunt down and fix this problem further, but this is rather new territory for me, so I'd appreciate any help

### PR DESCRIPTION
**Pull request by raboof**
By generating a version-5 GUID based on $out (which contains
the derivation hash) and preventing isohybrid from overwriting
the GPT table (which already is populated correctly by xorriso).

Tested by booting from UEFI USB disk

Fixes #74047

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

### CODE REVIEW

File: nixos/lib/make-iso9660-image.sh [hunk 1]
```diff
@@ -100,6 +100,7 @@ done
 mkdir -p $out/iso
 
 xorriso="xorriso
+ -boot_image any gpt_disk_guid=`uuid -v 5 daed2280-b91e-42c0-aed6-82c825ca41f3 $out | tr -d -`
```
Comment (jtojnar) [inline nixos/lib/make-iso9660-image.sh]: `$()` substitution is generally preferred:

```suggestion
 -boot_image any gpt_disk_guid=$(uuid -v 5 daed2280-b91e-42c0-aed6-82c825ca41f3 $out | tr -d -)
```

**Comment by raboof** [comment]
I guess the main thing to consider here is whether dropping  `--uefi` from the `isohybrid` invocation is safe. It *seems* safe from my tests, but looking at the image with `cfdisk` it changed quite a lot (it is now 1 big partition instead of 2 separate ones).

**Comment by samueldr** [comment]
From the Syslinux documentation (wiki)

> Alternatively, the ISO 9660 production program **"xorriso" can enhance its results by isohybrid, if an MBR template file from the local Syslinux installation is provided**. The names of these files match the "isohdp[fp]x*.bin" pattern and are to be found in Syslinux under the "./[bios/]mbr" directory or installed as, for example, "/usr/lib/syslinux/isohdpfx.bin".   
> [...]  
> The resulting ISO image needs no further treatment by isohybrid tools. 
— https://wiki.syslinux.org/wiki/index.php?title=Isohybrid

It looks like the `isohybrid` from Syslinux can be removed entirely, as long as `xorriso` is given the appropriate files to embed.

There is also a section about UEFI documenting the proper invocation for `xorriso`.

**Comment by raboof** [comment]
> It looks like the isohybrid from Syslinux can be removed entirely

Good find - looks like the needed xorriso flags were already being passed in. My laptop can indeed still boot from the iso-written-to-USBdisk with `isohybrid` skipped entirely. Updated the PR.

File: nixos/lib/make-iso9660-image.sh [hunk 2]
```diff
@@ -117,15 +118,6 @@ xorriso="xorriso
 
 $xorriso -output $out/iso/$isoName
 
-if test -n "$usbBootable"; then
```
Comment (bobvanderlinden) [inline nixos/lib/make-iso9660-image.sh]: I'm not sure whether we can remove isohybrid. It could very well be that the parameters passed to `xorriso` are already sufficient, but from what I remember there were quite a few systems we needed to support. Make sure to test this on a UEFI machine, a legacy bios machine and an OSX machine.

If we're indeed removing this, we might as well remove the `usbBootable` options from `make-iso9660-image.nix`. Might be better to do this in a separate PR.

**Comment by raboof** [comment]
Also successfully tested on an old `HP Compaq gw687aw` machine from USB.

So left to test:
- [ ] OSX
- [ ] Booting from an actual CD instead of USB?

**Comment by raboof** [comment]
I have burnt the above ISO to a DVD-R and verified I could boot from it both on an old non-UEFI system and on a recent UEFI system.

**Comment by raboof** [comment]
And I've tested booting from the ISO on an OSX machine as well, now, too. Held the 'C' button to boot from the CD. This put me into a grub shell (probably we held the 'C' too long?), but after giving the `normal` command on the grub prompt it successfully booted the installation.

**Comment by raboof** [comment]
I have also tested that when applying this change together with #75484, `nix-build ./nixos/release-combined.nix -A nixos.iso_minimal.x86_64-linux -I nixpkgs=~/nixpkgs-r13y --check` now succeeds

**Comment by domenkozar** [comment]
@GrahamcOfBorg test installer

File: nixos/lib/make-iso9660-image.sh (hunk 2 above)
Comment (raboof) [reply nixos/lib/make-iso9660-image.sh]: (I've since tested this both on UEFI, non-UEFI and OSX machines. agreed to do further refactoring in a separate PR)

**Comment by raboof** [comment]
Since #75484 has now been merged I rebased & squashed this, and verified `nix-build --check` is still succeeding.

I think this should be good to go now?

**Comment by raboof** [comment]
@GrahamcOfBorg test installer

File: nixos/lib/make-iso9660-image.sh [hunk 3]
```diff
@@ -100,6 +100,7 @@ done
 mkdir -p $out/iso
 
 xorriso="xorriso
+ -boot_image any gpt_disk_guid=$(uuid -v 5 daed2280-b91e-42c0-aed6-82c825ca41f3 $out | tr -d -)
```
Comment (timokau) [inline nixos/lib/make-iso9660-image.sh:103]: Where does the `daed2280-b91e-42c0-aed6-82c825ca41f3` come from? Is it chosen arbitrarily? How does it influence the result and how does it work together with `$out`?

I think a comment explaining why we fix the guid and why we chose the parameters like this would be good. Then this should be good to go. You seem to have done sufficient testing.

**Review by timokau — CHANGES_REQUESTED** [review]

File: nixos/lib/make-iso9660-image.sh (hunk 3 above)
Comment (raboof) [reply nixos/lib/make-iso9660-image.sh:103]: It is an arbitrary constant.

Version-3 and Version-5 UUID's are derived from the combination of a value ($out) and a namespace (this random constant).

The reasoning behind having a namespace is so that 2 independent applications generating a UUID for the same value will generate different UUID's (though the chance of that being a problem seems pretty slim in this particular case).

I'll add a comment.

**Review by timokau — APPROVED** [review]
Thanks!
