### PR TITLE
cc-wrapper: Allow user to override -target for clang

### LINKED ISSUE #176128: clang won't build for bpf target
### Describe the bug

I'd like to build bpf object (`clang -target bpf -g ...`) files but am unable to do so.

### Steps To Reproduce
1. clone https://github.com/libbpf/libbpf-bootstrap
2. cd libbpf-bootstrap
3. nix-shell -p clang libbpf
4. clang -O2 -target bpfel -g -c minimal.bpf.c
5. readelf -h minimal.bpf.o | e:grep Machine:
6. get: `  Machine:                           Advanced Micro Devices X86-64`, want: `  Machine:                           Linux BPF`

### Expected behavior

I expect clang to honor the `-target` I specify so that I can generate bpf object files. I was able to verify that just `-target ...` and `-fstack-protector-strong` are getting in the way of generating valid eBPF files. I did so by copying the wrapper script that is `clang` and seeing the final full command line that is actually invoking the real clang binary:

<details>
<summary>Unmodified exec line (doesn't work)</summary>

```shell
#!/usr/bin/env bash
out=minimal.bpf.unmod.o
/nix/store/p6dr62inbahm1q40xf4hl7l5p1ivghfj-clang-11.1.0/bin/clang \
	-fPIC \
	-Wformat \
	-Wformat-security \
	-Werror=format-security \
	-fstack-protector-strong \
	--param ssp-buffer-size=4 \
	-O2 \
	-D_FORTIFY_SOURCE=2 \
	-fno-strict-overflow \
	-O2 \
	-target bpf \
	-g \
	-c minimal.bpf.c \
	-o $out \
	-B/nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210/lib/ \
	-idirafter /nix/store/a0s1vq35j3g6aa757v7yg0a001l01ng4-glibc-2.34-210-dev/include \
	-target x86_64-unknown-linux-gnu \
	-B/nix/store/d7q0qfm12hb59wj63wyjs0hrdhmmapfz-gcc-11.3.0/lib/gcc/x86_64-unknown-linux-gnu/11.3.0 \
	--gcc-toolchain=/nix/store/d7q0qfm12hb59wj63wyjs0hrdhmmapfz-gcc-11.3.0 \
	-B/nix/store/a469w4h9bs21y3499i9sa0fzzjqfwx2m-clang-11.1.0-lib/lib \
	-resource-dir=/nix/store/r2h2gkjsr0xmxk1s0bx6p4v2czpc3km8-clang-wrapper-11.1.0/resource-root \
	-B/nix/store/r2h2gkjsr0xmxk1s0bx6p4v2czpc3km8-clang-wrapper-11.1.0/bin/ \
	-frandom-seed=4f2mdhgyns \
	-isystem /nix/store/74qg7k17vf31v4pckf8j31q0rdrzpgcp-libbpf-0.7.0/include \
	-isystem /nix/store/2lfvz4d6a4iqriqakw4qpg94bzr3c8z5-compiler-rt-libc-11.1.0-dev/include \
	-isystem /nix/store/74qg7k17vf31v4pckf8j31q0rdrzpgcp-libbpf-0.7.0/include \
	-isystem /nix/store/2lfvz4d6a4iqriqakw4qpg94bzr3c8z5-compiler-rt-libc-11.1.0-dev/include \
	-isystem /nix/store/74qg7k17vf31v4pckf8j31q0rdrzpgcp-libbpf-0.7.0/include \
	-isystem /nix/store/2lfvz4d6a4iqriqakw4qpg94bzr3c8z5-compiler-rt-libc-11.1.0-dev/include

readelf -h $out | grep Machine:
```
</details>

<details>
<summary>Modified exec (works)</summary>

```shell
#!/usr/bin/env bash
out=minimal.bpf.mod.o
/nix/store/p6dr62inbahm1q40xf4hl7l5p1ivghfj-clang-11.1.0/bin/clang \
	-fPIC \
	-Wformat \
	-Wformat-security \
	-Werror=format-security \
	--param ssp-buffer-size=4 \
	-O2 \
	-D_FORTIFY_SOURCE=2 \
	-fno-strict-overflow \
	-O2 \
	-target bpf \
	-g \
	-c minimal.bpf.c \
	-o $out \
	-B/nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210/lib/ \
	-idirafter /nix/store/a0s1vq35j3g6aa757v7yg0a001l01ng4-glibc-2.34-210-dev/include \
	-B/nix/store/d7q0qfm12hb59wj63wyjs0hrdhmmapfz-gcc-11.3.0/lib/gcc/x86_64-unknown-linux-gnu/11.3.0 \
	--gcc-toolchain=/nix/store/d7q0qfm12hb59wj63wyjs0hrdhmmapfz-gcc-11.3.0 \
	-B/nix/store/a469w4h9bs21y3499i9sa0fzzjqfwx2m-clang-11.1.0-lib/lib \
	-resource-dir=/nix/store/r2h2gkjsr0xmxk1s0bx6p4v2czpc3km8-clang-wrapper-11.1.0/resource-root \
	-B/nix/store/r2h2gkjsr0xmxk1s0bx6p4v2czpc3km8-clang-wrapper-11.1.0/bin/ \
	-frandom-seed=4f2mdhgyns \
	-isystem /nix/store/74qg7k17vf31v4pckf8j31q0rdrzpgcp-libbpf-0.7.0/include \
	-isystem /nix/store/2lfvz4d6a4iqriqakw4qpg94bzr3c8z5-compiler-rt-libc-11.1.0-dev/include \
	-isystem /nix/store/74qg7k17vf31v4pckf8j31q0rdrzpgcp-libbpf-0.7.0/include \
	-isystem /nix/store/2lfvz4d6a4iqriqakw4qpg94bzr3c8z5-compiler-rt-libc-11.1.0-dev/include \
	-isystem /nix/store/74qg7k17vf31v4pckf8j31q0rdrzpgcp-libbpf-0.7.0/include \
	-isystem /nix/store/2lfvz4d6a4iqriqakw4qpg94bzr3c8z5-compiler-rt-libc-11.1.0-dev/include

readelf -h $out | grep Machine:
```
</details>

<details>
<summary>runs</summary>

```
[11:13:57]-[~/cloned/github.com/libbpf/libbpf-bootstrap/examples/c]─[manny@zennix]> 
./bad.sh 
  Machine:                           Advanced Micro Devices X86-64
                                                                                                                                                                      
[11:13:58]-[~/cloned/github.com/libbpf/libbpf-bootstrap/examples/c]─[manny@zennix]> 
./good.sh 
clang-11: warning: argument unused during compilation: '--gcc-toolchain=/nix/store/d7q0qfm12hb59wj63wyjs0hrdhmmapfz-gcc-11.3.0' [-Wunused-command-line-argument]
readelf: Warning: unable to apply unsupported reloc type 10 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 1 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 10 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 1 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 10 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 1 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 10 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 1 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 10 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 1 to section .debug_info
readelf: Warning: unable to apply unsupported reloc type 10 to section .debug_info
  Machine:                           Linux BPF
                                                                                                                                                                      
[11:14:00]-[~/cloned/github.com/libbpf/libbpf-bootstrap/examples/c]─[manny@zennix]> 
diff -u bad.sh good.sh 
--- bad.sh	2022-06-03 11:13:39.685645805 -0400
+++ good.sh	2022-06-03 11:13:55.424661960 -0400
@@ -1,11 +1,10 @@
 #!/usr/bin/env bash
-out=minimal.bpf.unmod.o
+out=minimal.bpf.mod.o
 /nix/store/p6dr62inbahm1q40xf4hl7l5p1ivghfj-clang-11.1.0/bin/clang \
 	-fPIC \
 	-Wformat \
 	-Wformat-security \
 	-Werror=format-security \
-	-fstack-protector-strong \
 	--param ssp-buffer-size=4 \
 	-O2 \
 	-D_FORTIFY_SOURCE=2 \
@@ -17,7 +16,6 @@
 	-o $out \
 	-B/nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210/lib/ \
 	-idirafter /nix/store/a0s1vq35j3g6aa757v7yg0a001l01ng4-glibc-2.34-210-dev/include \
-	-target x86_64-unknown-linux-gnu \
 	-B/nix/store/d7q0qfm12hb59wj63wyjs0hrdhmmapfz-gcc-11.3.0/lib/gcc/x86_64-unknown-linux-gnu/11.3.0 \
 	--gcc-toolchain=/nix/store/d7q0qfm12hb59wj63wyjs0hrdhmmapfz-gcc-11.3.0 \
 	-B/nix/store/a469w4h9bs21y3499i9sa0fzzjqfwx2m-clang-11.1.0-lib/lib \
```
</details>

### Additional context

I tracked this down to cc-wrapper inserting the `-target ` via `clang-wrapper-*/nix-support/cc-cflags` which ends up living in `extraAfter`. I'd like for it be be in `extraBefore` instead so that I can override it. This is deep in the guts of CC support so wanted to open up an issue for discussion for this before trying to mess around with a PR.

I can see why the `-target` was added to the wrapper, I suspect to require use of crossSystem or similar to get a clang that will build for that arch/system but I'm not so sure thats possible for `bpf` (`wasm` too?) that don't have a libc and other common tools (binutils?)...

### Notify maintainers

@Ericson2314 (for cc-wrapper)
@lovek323  @dtzWill @primeos (for clang)

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.17.7, NixOS, 22.05 (Quokka), 22.05pre377845.43ff6cb1c02`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0`
 - channels(root): `"nixos"`
 - channels(manny): `"home-manager, nixos-21.11-21.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by mmlb**
###### Description of changes

Only sets -target in wrapped compiler if none is provided by the user. This is especially helpful for generating bpf objects.

Fixes #176128

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mmlb** [comment]
ping @Mindavi for review too

**Comment by mmlb** [comment]
I couldn't find anything in the repo that sets `-target` (as expected) which leads me to believe that its relatively safe.

**Comment by mmlb** [comment]
@06kellyjac give this a try

**Comment by Ericson2314** [comment]
Also I don't think this is a good fix for https://github.com/NixOS/nixpkgs/issues/176128, because clang might try to produce a far binary for *both* arches instead. What you want is logic in cc-wrapper itself to only add a `-target ...` if the user didn't already pass one themselves.

**Comment by mmlb** [comment]
> Also I don't think this is a good fix for #176128, because clang might try to produce a far binary for _both_ arches instead.

I find this surprising if true, got any links to documentation? So far everything I've seen to generate fat binaries or bundles is very much opt in with either clang args (clang offload bundler) or different tools (lipo, but I think this is osx only)

> What you want is logic in cc-wrapper itself to only add a `-target ...` if the user didn't already pass one themselves.

Setting aside the fat binaries, I think this makes sense anyway so will look into updating `cc-wrapper`.

**Comment by mmlb** [comment]
Hey @Ericson2314 I've rebased on-top of staging and re-targted the PR accordingly. Also made it so -target should only show up once in the final params just once. This ends up causing a full rebuild of clang which then ripples out, this did not happen with the previous approach, just an fyi.

**Comment by Mindavi** [comment]
I feel like there was a reason for the if, elif chaining, but maybe it's just how it was written.

Could that be because we're using a very old bash on MacOS and this is used during bootstrap or something? Hopefully someone else can confirm or deny.

@happysalada do you know?

**Comment by mmlb** [comment]
> I feel like there was a reason for the if, elif chaining, but maybe it's just how it was written.
> 
> Could that be because we're using a very old bash on MacOS and this is used during bootstrap or something? Hopefully someone else can confirm or deny.
> 
> @happysalada do you know?

I thought it might have been due to sh vs bash, but I verified that dash supports case and so I'd suspect old bash would too.

**Comment by mmlb** [comment]
`case` is in posix sh (see 2.9.4 in https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_09) so should be ok to use for old mac bash.

**Comment by Mindavi** [comment]
Thanks for checking! It does look nicer with case IMO, so that's good.

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh [hunk 1]
```diff
@@ -170,6 +160,10 @@ if [ "$dontLink" != 1 ]; then
     export NIX_LINK_TYPE_@suffixSalt@=$linkType
 fi
 
+if [ "$setClangTarget" == 1 ]; then
+    extraAfter+=(-target $clangTarget)
```
Comment (06kellyjac) [inline pkgs/build-support/cc-wrapper/cc-wrapper.sh:164]: @Mindavi ^

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh [hunk 2]
```diff
@@ -29,6 +29,8 @@ cc1=0
 cxxInclude=1
 cxxLibrary=1
 cInclude=1
+setClangTarget=0
+clangTarget=none
```
Comment (Ericson2314) [inline pkgs/build-support/cc-wrapper/cc-wrapper.sh:33]:
```suggestion
```

File: pkgs/build-support/cc-wrapper/default.nix [hunk 3]
```diff
@@ -216,6 +216,7 @@ stdenv.mkDerivation {
         export named_cxx=${targetPrefix}g++
       elif [ -e $ccPath/clang ]; then
         wrap ${targetPrefix}clang $wrapper $ccPath/clang
+        substituteInPlace $ccPath/clang --replace setClangTarget=0 setClangTarget=1 --replace clangTarget=none clangTarget=${targetPlatform.config}
```
Comment (Ericson2314) [inline pkgs/build-support/cc-wrapper/default.nix:219]: Don't need
```suggestion
```

File: pkgs/build-support/cc-wrapper/default.nix [hunk 4]
```diff
@@ -216,6 +216,7 @@ stdenv.mkDerivation {
         export named_cxx=${targetPrefix}g++
       elif [ -e $ccPath/clang ]; then
```
Comment (Ericson2314) [inline pkgs/build-support/cc-wrapper/default.nix:217]:
```suggestion
      elif [ -e $ccPath/clang ]; then
        export clangTarget=${targetPlatform.config}
```

File: pkgs/build-support/cc-wrapper/default.nix [hunk 5]
```diff
@@ -226,6 +227,7 @@ stdenv.mkDerivation {
         ln -s ${targetPrefix}g++ $out/bin/${targetPrefix}c++
       elif [ -e $ccPath/clang++ ]; then
         wrap ${targetPrefix}clang++ $wrapper $ccPath/clang++
+        substituteInPlace $ccPath/clang++ --replace setClangTarget=0 setClangTarget=1 --replace clangTarget=none clangTarget=${targetPlatform.config}
```
Comment (Ericson2314) [inline pkgs/build-support/cc-wrapper/default.nix:230]:
```suggestion
        export clangTarget=${targetPlatform.config}
        wrap ${targetPrefix}clang++ $wrapper $ccPath/clang++
```

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh (hunk 1 above)
Comment (mmlb) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh:164]: :man_facepalming: great catch. I'll actually remove the old bit in the next push.

[the remark this answers is not in the document]
Comment (mmlb) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh:164]: @Ericson2314 will empty @ variables also be substituted with empty string/nothing or do they get skipped over and left as is?

We still need some way to pass `setClangTarget` from default.nix into cc-wrapper.sh. I can either do something like `export setClangTarget=1` and then instead of of `if [ $setClangTarget...` I can do `if [ @isClang@`. But if unknown @ vars are left as empty then I can do something like:

```
clangTarget=@clanTarget@

...

case $p in
...
-target) clangTarget=$p2
...
esac

...

if [ -n $clangTarget ]; then
    extraAfter+=(-target $clangTarget)
fi
```

File: pkgs/build-support/cc-wrapper/default.nix (hunk 5 above)
Comment (mmlb) [reply pkgs/build-support/cc-wrapper/default.nix:230]: ack

File: pkgs/build-support/cc-wrapper/default.nix (hunk 4 above)
Comment (mmlb) [reply pkgs/build-support/cc-wrapper/default.nix:217]: ack

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh (hunk 2 above)
Comment (mmlb) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh:33]: ack

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh (hunk 1 above)
[the remark this answers is not in the document]
Comment (Ericson2314) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh:164]: I would call `setClangTarget` `needsTarget` and just it `0` or `1` based on the whether is clang in default.nix

Let's try to make sure all variables to substitute are defined to *something* at build time,

[the remark this answers is not in the document]
Comment (mmlb) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh:164]: :+1:, also just read from https://nixos.org/manual/nixpkgs/stable/#fun-substituteAll that unknown @ vars are left as is so wouldn't work the way I laid it out in the snippet above.

[the remark this answers is not in the document]
Comment (mmlb) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh]: Should be good now.

Comment (mmlb) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh]: Removed the old code: https://github.com/NixOS/nixpkgs/pull/176152/files#diff-ad7b67d4a92a2db43281c9c45aa74c32341a554fbca0b6b25be593f4648abb5eL300-L307

File: pkgs/build-support/cc-wrapper/default.nix [hunk 6]
```diff
@@ -208,13 +208,16 @@ stdenv.mkDerivation {
...
+      export needsTarget=0
 
       if [ -e $ccPath/${targetPrefix}gcc ]; then
         wrap ${targetPrefix}gcc $wrapper $ccPath/${targetPrefix}gcc
         ln -s ${targetPrefix}gcc $out/bin/${targetPrefix}cc
         export named_cc=${targetPrefix}gcc
         export named_cxx=${targetPrefix}g++
       elif [ -e $ccPath/clang ]; then
+        needsTarget=1
+        export clangTarget=${targetPlatform.config}
```
Comment (Ericson2314) [inline pkgs/build-support/cc-wrapper/default.nix:220]: Cause the other rename I would call this `defaultTarget` too.

Comment (mmlb) [reply pkgs/build-support/cc-wrapper/default.nix:220]: will fix

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh (hunk 1 above)
Comment (Mindavi) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh]: Nice, now it makes more sense :)

File: pkgs/build-support/cc-wrapper/default.nix (hunk 6 above)
Comment (mmlb) [reply pkgs/build-support/cc-wrapper/default.nix]: updated

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh [hunk 7]
```diff
@@ -38,35 +39,23 @@ nParams=${#params[@]}
...
-        cc1=1
-    fi
+
+    case "$p" in
+        -[cSEM] | -MM) dontLink=1 ;;
+        -cc1) cc1=1 ;;
+        -nostdinc) cInclude=0 cxxInclude=0 ;;
+        -nostdinc++) cxxInclude=0 ;;
+        -nostdlib) cxxLibrary=0 ;;
+        -target|--target=*) needsTarget=0;;
```
Comment (Mindavi) [inline pkgs/build-support/cc-wrapper/cc-wrapper.sh:49]: Is this automatically passed through?

Comment (mmlb) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh:49]: Yep params comes from https://github.com/NixOS/nixpkgs/pull/176152/files#diff-5b214d4b19e3f1e9146a43659772fb2e7a5830badc02d53087ea62f5f5860b93R34
and params is maybe reset in the NIX_ENFORCE_PURITY if branch, but that basically filters out any -I/-L/-isystem args that `badPath` doesn't like from params. similar happens for march/mtune=native filtering.

So in the end ${params[@]} ends up with the params provided by the caller possibly without any impure paths or mtune/march flags

**Comment by mmlb** [comment]
@Ericson2314 @Mindavi how do you all feel about this?

```diff
@@ -76,19 +76,13 @@ if [[ "${NIX_ENFORCE_PURITY:-}" = 1 && -n "$NIX_STORE" ]]; then
     while (( "$n" < "$nParams" )); do
         p=${params[n]}
         p2=${params[n+1]:-} # handle `p` being last one
-        if [ "${p:0:3}" = -L/ ] && badPath "${p:2}"; then
-            skip "${p:2}"
-        elif [ "$p" = -L ] && badPath "$p2"; then
-            n+=1; skip "$p2"
-        elif [ "${p:0:3}" = -I/ ] && badPath "${p:2}"; then
-            skip "${p:2}"
-        elif [ "$p" = -I ] && badPath "$p2"; then
-            n+=1; skip "$p2"
-        elif [ "$p" = -isystem ] && badPath "$p2"; then
-            n+=1; skip "$p2"
-        else
-            rest+=("$p")
-        fi
+
+        case "$p" in
+            -L/* | -I/*) badPath "${p:2}" && skip "${p:2}" && continue ;;
+            -L | -I | -isystem) badPath "$p2" && skip "$p2" && continue ;;
+        esac
+
+        rest+=("$p")
         n+=1
     done
     # Old bash empty array hack
```

I originally skipped over looking over this use of params because I didn't need to mess with it but when I went looking to make sure params will have -target to answer @Mindavi 's question I noticed that this too may look better as a case statement. Should I change this one too?

**Comment by Ericson2314** [comment]
@mmlb I like the sound of those. Just be careful with the `n+=1` I think you do need more of it as before we got (in affect) `n+=2` in certain cases.

**Comment by mmlb** [comment]
> @mmlb I like the sound of those. Just be careful with the `n+=1` I think you do need more of it as before we got (in effect) `n+=2` in certain cases.

Yep, I totally missed that in the snippet. The actual commit has it though. I ended simplifying what I had in the snippet further too.

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh [hunk 8]
```diff
@@ -81,29 +70,29 @@ fi
...
-        fi
         n+=1
+
+        path=""
+        case "$p" in
+            -I/* | -L/*) path=${p:2} ;;
+            -I | -L | -isystem) path=$p2 n+=1 ;;
+        esac
+
+        if badPath "$path"; then
```
Comment (Ericson2314) [inline pkgs/build-support/cc-wrapper/cc-wrapper.sh:87]:
```suggestion
        if test -N "$path" && badPath "$path"; then
```
I am not sure `badPath` should be happy with the empty path, an in any case I rather not rely on that.

Comment (mmlb) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh:87]: badPath is happy with the empty case since it returns early if $path != /* basically. But yeah I can be explicit about it.

**Comment by mmlb** [comment]
I'm looking into why glibc isn't building anymore :/

**Comment by Ericson2314** [comment]
Last thing from me, check out https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/bintools-wrapper/add-darwin-ldflags-before.sh from @thefloweringash. Perhaps we want to do the same thing for this? Then any compiler that doesn't need the stuff doesn't have the code in its wrapper.

I like that as a first step to modularizing the wrappers and prevent mass rebuilds in the future. (changing the Clang-only bits wouldn't cause a rebuild of things just using GCC.)

**Comment by mmlb** [comment]
hmm I'm trying to build `gcc` and on staging I'm getting

```
nix-build --check -A gcc 2>&1 |tail
  /nix/store/wjbv1k6yigmb280wrvc1gkv8cnrsacij-glibc-2.34.tar.xz
  /nix/store/wp9v6jcv4vdxp8vwrfsb3q6qfalf2n5l-libunistring-1.0.tar.gz
  /nix/store/x4jhvxj104vdciivf1zvijncyd4rd3dp-mpc-1.2.1.tar.gz
  /nix/store/x9v0hmr76dm68pijzldzxks01iqzag1z-isl-0.20.tar.xz
  /nix/store/y3yiminrckvhf35fh9q42vjwi0npznji-acl-2.3.1.tar.gz
  /nix/store/ycj1q918l6852kndr75rlwmw43k5ybys-texinfo-6.8.tar.xz
  /nix/store/z1wfvm57izp9mdx3svdm8ayvw9f24bsr-bash51-002
  /nix/store/z4amhpapl83iwjxkq9p9lylkh0ffyq1d-bash51-013
  /nix/store/zpa3bjjp3awz7db16dl58cwi7b4jrl26-python-setup-hook.sh
error: some outputs of '/nix/store/s6sz5wka3cqgmbgkrvaw5pm72hik3d6h-gcc-wrapper-11.3.0.drv' are not valid, so checking is not possible
```

**Comment by Mindavi** [comment]
Remove the --check, for starters?

**Comment by mmlb** [comment]
> Last thing from me, check out https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/bintools-wrapper/add-darwin-ldflags-before.sh from @thefloweringash. Perhaps we want to do the same thing for this? Then any compiler that doesn't need the stuff doesn't have the code in its wrapper.
> 
> I like that as a first step to modularizing the wrappers and prevent mass rebuilds in the future. (changing the Clang-only bits wouldn't cause a rebuild of things just using GCC.)

Yeah I'll take a look at doing similar, agree that clang stuff shouldn't cause gcc to rebuild. Ideally the opposite would be true but making cc-wrapper and co agnostic would be more work than I'd want right now :smile: .

**Comment by mmlb** [comment]
It *looks* like the fail is in the case that handles -I/, -I, -L/, -L, -isystem. My build is still going, but I'm pretty sure it would have failed by now. I'll wait until this build is done and then go about debugging why that case is failing. Of course its the one that was "obvious" and I didn't try testing ... :grin:

**Comment by mmlb** [comment]
@Ericson2314 how's this look?

**Comment by Ericson2314** [comment]
I would tweak the names and make them consistent, but otherwise looks good!

**Comment by mmlb** [comment]
> I would tweak the names and make them consistent, but otherwise looks good!

Can you elaborate? I copied the naming scheme used in bintools-wrapper:
`add-darwin-ldflags-before.sh` -> `add-clang-cflags-before.sh`
`add-local-ldflags-before.sh` -> `add-local-cflags-before.sh`

Do you want me to prefix `-cflags` with `cc`?

**Comment by Mindavi** [comment]
Does this file already exist or is it missing: add-local-cflags-before.sh?

**Comment by Ericson2314** [comment]
@mmlib I don't know why bintools wrapper uses two different names either. Do you, @thefloweringash?

**Comment by Ericson2314** [comment]
I don't understand why the file in the Nixpkgs src has one name (with .sh) and the file "installed" as part of the built wrapper has a different name (still with .sh). I get it when we strip the .sh on install (e.g. installing something to `bin/`) but I don't get why for something very internal like this.

I also don't understand why anything is called "local". What does "local" mean here?

Finally, I don't like the use of "clang" because this applies equally well to any compiler that would accept `-target`. Just as we renamed the variables in bash to get rid of "clang" we should also rename the file to get rid of "clang".

**Comment by mmlb** [comment]
ah gotcha. Yeah I think the idea is that there's an "interface" and clang and gcc can both implement it by having a file named `local-cc-cflags-before.sh` dropped into $out somewhere. I think that makes some sense. The other option would be instead of file names we'd source all files in a dir that match a pattern but that would be up to collation order and would be totally different than what is being done currently, and idk if its even warranted tbh.

I took `local` as an indicator that file has code to run vs just a list of values to be read, open to w/e name makes sense to show that distinction.

re clang vs more fine grained names. I can rename so its just for target, but some of the other files here are specific to the tool not to the features so I went with that too since only clang does -target and thus yagni.

Sounds like you want me to rename from clang -> target and maybe come up with something else more relevant than `local`. I'll do the former rn and maybe come up with a better name than local. We can discuss that separately.

**Comment by Ericson2314** [comment]
OK that makes some sense we can live with this for now.

**Review by Ericson2314 — APPROVED** [review]

**Comment by mmlb** [comment]
> (the approval and some old junk queued up from before acidently)

what do you mean?

**Comment by Mindavi** [comment]
John means that he had some comments in an 'open review' and they were submitted when he merged/approved. That wasn't the intention since they were stale.

**Comment by Ericson2314** [comment]
Yes exactly. Thanks.

**Comment by mmlb** [comment]
ah, gotcha.
