### PR TITLE
dotnet/update.sh: fix error when output path contains spaces

### LINKED ISSUE #367413: `dotnet-sdk`’s update script fails if path to Nixpkgs contains spaces
## Describe the bug

`dotnet-sdk`’s update script fails if the path to your Nixpkgs clone contains spaces.

## Steps To Reproduce

1. Clone the Nixpkgs repo into a directory that contains spaces by running this command:
    ```
    git clone https://github.com/NixOS/nixpkgs.git 'Path that contains spaces'
    ```

2. Change directory into the Nixpkgs repo:

    ```
    cd 'Path that contains spaces'
    ```

3. Run `dotnet-sdk`’s update script:

    ```
    nix-shell maintainers/scripts/update.nix --argstr skip-prompt true --argstr package dotnet-sdk
    ```

## Expected behavior

<pre><samp>
Going to be running update for following packages:
 - dotnet-sdk-wrapped-8.0.404

Running update for:
 - dotnet-sdk-wrapped-8.0.404: UPDATING ...
 - dotnet-sdk-wrapped-8.0.404: DONE.

Packages updated!
</samp></pre>

## Actual behavior

<pre><samp>
Going to be running update for following packages:
 - dotnet-sdk-wrapped-8.0.404

Running update for:
 - dotnet-sdk-wrapped-8.0.404: UPDATING ...
 - dotnet-sdk-wrapped-8.0.404: ERROR

--- SHOWING ERROR LOG FOR dotnet-sdk-wrapped-8.0.404 ----------------------

error:
       … while calling the 'deepSeq' builtin
         at «string»:6:21:
            5|                 fetchNupkg = { ... }: {};
            6|             }); (x: builtins.deepSeq x x) [
             |                     ^
            7|                 runtime_8_0.version

       … while calling the 'import' builtin
         at «string»:1:7:
            1| with (import /home/jayman/Documents/Home/VC/Git/Partially mine/nixpkgs/master/pkgs/development/compilers/dotnet/versions/8.0.nix {
             |       ^
            2|                 buildAspNetCore = { ... }: {};

       error: path '/home/jayman/Documents/Home/VC/Git/Partially' does not exist
/home/jayman/Documents/Home/VC/Git/Partially mine/nixpkgs/master/pkgs/development/compilers/dotnet/update.sh: line 295: versions[0]: unbound variable

--- SHOWING ERROR LOG FOR dotnet-sdk-wrapped-8.0.404 ----------------------
The update script for dotnet-sdk-wrapped-8.0.404 failed with exit code 1
</samp></pre>

## Metadata

<pre><samp> - system: `"x86_64-linux"`
 - host os: `Linux 6.12.5, NixOS, 24.11 (Vicuna), 24.11.711615.1c6e20d41d6a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos-24.11"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

</samp></pre>

## Notify maintainers

- @kuznero
- @mdarocha
- @corngood

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by corngood**
Fixes: #367413

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

File: pkgs/development/compilers/dotnet/update.sh [hunk 1]
```diff
@@ -283,7 +283,7 @@ update() {
     if [ "$patch_specified" == false ] && [ -f "$output" ]; then
         local -a versions
         IFS= readarray -d '' versions < <(
-            nix-instantiate --eval --json -E "with (import $output {
+            nix-instantiate --eval --json -E "with (import \"$output\" {
```
Comment (corngood) [inline pkgs/development/compilers/dotnet/update.sh:286]: This is a big hacky.  I'm not sure if there's a good way to escape a nix string from bash.

Comment (GGG-KILLER) [reply pkgs/development/compilers/dotnet/update.sh:286]: Worst case you could probably use `builtins.readFile`, but i don't know if that's really needed.

**Review by GGG-KILLER — APPROVED** [review]
LGTM

File: pkgs/development/compilers/dotnet/update.sh (hunk 1 above)
Comment (corngood) [reply pkgs/development/compilers/dotnet/update.sh]: I've changed it to use `--argstr`, which should be robust.

**Review by GGG-KILLER — APPROVED** [review]
