### PR TITLE
pkgs/build-support: cc-wrapper.sh not detecting c++ files by extension

### LINKED ISSUE #357281: cc wrapper script not detecting cpp files/adding c++ standard includes without '-xc++'
## Describe the bug

The cc-wrapper script won't add the c++ standard include paths when compiling with `*.cpp/*.cxx/...` files and without `-xc++`. This breaks for example the `clang` package when used with build systems that expect it to detect c++ source files, i. e: `xmake`.

## Steps To Reproduce

1. install the clang package
2. try to compile a simple `test.cpp` with `clang test.cpp`
3. clang complains about missing c++ standard headers

## Expected behavior
It finds the standard headers and fails to link to a valid executable due to not linking with libstdc++/libc++. e.g gcc follows the expected behaviour, it fails to link:
```console
[nix-shell:~/]$ gcc test.cc 
/nix/store/pbixrqd120nnw8a0ygfpm3mnwlr1mbj7-binutils-2.43.1/bin/ld: /tmp/nix-shell-55971-0/ccGMZAHj.o: in function `main':
test.cc:(.text.startup+0x10): undefined reference to `std::cout'
/nix/store/pbixrqd120nnw8a0ygfpm3mnwlr1mbj7-binutils-2.43.1/bin/ld: test.cc:(.text.startup+0x15): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
/nix/store/pbixrqd120nnw8a0ygfpm3mnwlr1mbj7-binutils-2.43.1/bin/ld: test.cc:(.text.startup+0x3e): undefined reference to `std::ostream::put(char)'
/nix/store/pbixrqd120nnw8a0ygfpm3mnwlr1mbj7-binutils-2.43.1/bin/ld: test.cc:(.text.startup+0x46): undefined reference to `std::ostream::flush()'
/nix/store/pbixrqd120nnw8a0ygfpm3mnwlr1mbj7-binutils-2.43.1/bin/ld: test.cc:(.text.startup+0x57): undefined reference to `std::ctype<char>::_M_widen_init() const'
/nix/store/pbixrqd120nnw8a0ygfpm3mnwlr1mbj7-binutils-2.43.1/bin/ld: test.cc:(.text.startup+0x81): undefined reference to `std::__throw_bad_cast()'
```

## Additional context

How the issue was found: xmake-io/xmake#5842

## Metadata

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.7, NixOS, 24.11 (Vicuna), 24.11.20241111.dc460ec`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - nixpkgs: `/nix/store/4r8s42c9mwfvgdlxv0izb1cmlzrsb5nz-source`
```

## Notify maintainers

@Ericson2314
@RossComputerGuy 
@lovek323 
@dtzWill 
@alyssais 
@rrbutani 

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by GasInfinity**
Closes #357281

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).
---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by RossComputerGuy — CHANGES_REQUESTED** [review]
Please no merge commits, just rebasing is fine. Also, please follow the CONTRIBUTING.md for commit & PR naming.

**Comment by GasInfinity** [comment]
Hi @RossComputerGuy, thanks for checking this. My bad for not reading completely the commit conventions. I've also seen that since this fix causes a mass rebuild, the changes go to staging. Should I change the target branch for the merge?

**Comment by RossComputerGuy** [comment]
> I've also seen that since this fix causes a mass rebuild, the changes go to staging. Should I change the target branch for the merge?

Yes, please retarget this PR to staging.

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh [hunk 1]
```diff
@@ -56,6 +56,8 @@ while (( "$n" < "$nParams" )); do
                 c++*) isCxx=1 ;;
             esac
             ;;
+        # check common c++ file extensions
+        *.C|*.H|*.cc|*.CC|*.cp|*.hh|*.ccm|*.cpp|*.CPP|*.c++|*.C++|*.cxx|*.CXX|*.hpp|*.hxx|*.c++m|*.cppm|*.cxxm) isCxx=1 ;;
```
Comment (paparodeo) [inline pkgs/build-support/cc-wrapper/cc-wrapper.sh:60]: I don't think that `isCxx` is correct from looking at what macOS clang does. it seems like we just want to bring in the c++ include file if these file extensions are set -- also where did the list of file extensions come from? they should match the ones clang uses.

Comment (GasInfinity) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh:60]: Hey @paparodeo, those are taken from what [clang](https://github.com/llvm/llvm-project/blob/main/clang/lib/Driver/Types.cpp#L299-L369) checks. I could add a comment for more context.

Comment (paparodeo) [reply pkgs/build-support/cc-wrapper/cc-wrapper.sh:61]: > Edit: What should be done instead of `isCxx`? From what I've seen, it should behave like `-xc++` which is what clang does.

you're right. I thought `isCxx` was adding `-lc++` but it isn't.

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh [hunk 2]
```diff
@@ -56,6 +56,9 @@ while (( "$n" < "$nParams" )); do
                 c++*) isCxx=1 ;;
             esac
             ;;
+        # check common c++ file extensions
+        # taken from clang: https://github.com/llvm/llvm-project/blob/4d6a5fc702e568b0456c4d8f9e2307eb6d81e955/clang/lib/Driver/Types.cpp#L299-L369
+        *.C|*.H|*.cc|*.CC|*.cp|*.hh|*.ccm|*.cpp|*.CPP|*.c++|*.C++|*.cxx|*.CXX|*.hpp|*.hxx|*.c++m|*.cppm|*.cxxm) isCxx=1 ;;
```
Comment (FliegendeWurst) [inline pkgs/build-support/cc-wrapper/cc-wrapper.sh:61]: If these are supposed to be for C++, why are *.c, *.h included?

**Review by FliegendeWurst — APPROVED** [review]

**Comment by trofi** [comment]
Bisect says that 8e3b8e080571ee2c8a2bf6c31a4f10b093547d93 `pkgs/build-support: cc-wrapper.sh not detecting c++ files by extension` broke `firefox` build in `staging` as:

```
$ nix build --no-link -f. firefox -L
...
firefox-unwrapped>  0:19.44(B checking the wasm C++ linker can find wasi libraries...(B(B
firefox-unwrapped>  0:19.44(B DEBUG: Creating `/build/conftestolmlqq1v.cpp` with content:(B(B
firefox-unwrapped>  0:19.44(B DEBUG: | int(B(B
firefox-unwrapped>  0:19.44(B DEBUG: | main(void)(B(B
firefox-unwrapped>  0:19.44(B DEBUG: | {(B(B
firefox-unwrapped>  0:19.44(B DEBUG: |(B(B
firefox-unwrapped>  0:19.44(B DEBUG: |   ;(B(B
firefox-unwrapped>  0:19.44(B DEBUG: |   return 0;(B(B
firefox-unwrapped>  0:19.44(B DEBUG: | }(B(B
firefox-unwrapped>  0:19.44(B DEBUG: Executing: `/nix/store/hc02rmqkpq1py5mjvsf90j8ly8dyn6k9-wasm32-unknown-wasi-clang-wrapper-19.1.6/bin/wasm32-unknown-wasi-c++ /build/conftestolmlqq1v.cpp --sysroot=/nix/store/s70hvdpvbwrknhwaz30pi5xhwb0g0d0p-wasi-sysroot`(B(B
firefox-unwrapped>  0:19.44(B DEBUG: The command returned non-zero exit status 1.(B(B
firefox-unwrapped>  0:19.44(B DEBUG: Its error output was:(B(B
firefox-unwrapped>  0:19.44(B DEBUG: | wasm-ld: error: unable to find library -lc(B(B
firefox-unwrapped>  0:19.44(B DEBUG: | clang++: error: linker command failed with exit code 1 (use -v to see invocation)(B(B
firefox-unwrapped>  0:19.44(B ERROR: Cannot find wasi libraries or problem with the wasm linker. Please fix the problem. Or build with --without-wasm-sandboxed-libraries.(B(B
firefox-unwrapped> *** Fix above errors and then restart with "./mach build"
```

**Comment by mweinelt** [comment]
Feel free to reapply, when it doesn't break the firefox anymore.

**Comment by emilazy** [comment]
I am not sure this patch is correct even aside from the Firefox issues; looking at `.C` and `.H` seems a bit dubious on case‐insensitive filesystems (but maybe Clang behaves the same way?), and I’m not sure this will do the right thing for mixed languages in one invocation. (Besides all the other issues of trying to heuristically parse compiler command lines in shell.)

I’d prefer to fix this issue by following the general path of doing less in the wrappers rather than more. We should let compilers handle this kind of thing when we can; they’re good at it.

**Comment by GasInfinity** [comment]
Oops, never thought that this simple patch would break firefox, weirdly. However, I don't know of any other way to fix the issue that this fix was trying to solve. I think the title is missing some context, the real problem is that some compilers like `clang` expect the standard cpp include paths to be present when compiling cpp source, not that the compiler doesn't change to cpp mode when compiling with cpp files.

As nixpkgs wraps the compiler invocation with a script and that same script adds the cpp standard include paths I thought that just checking for the extension as a lot of compilers do would solve this as a quick way.

I'd be glad to get some help as I'm not very experienced with the nixpkgs codebase and this was the only way I thought of fixing the issue. Maybe someone could give me a pointer to how this could be fixed?

In the meantime, as this is a very niche usecase that only affects some build systems like `xmake` when using clang to build cpp, I'll reopen the issue linked to this PR.

This was a quick and dirty way to fix it. Sorry for the inconvenience.

**Comment by emilazy** [comment]
No harm done, it’s only in `staging` so only a couple of contributors have been hit by this so far :)

The long‐term plan involves moving more functionality into compiler drivers and configuring them with fixed flags and configuration files rather than having a wrapper that re‐parses the whole command line. So we’d hope that we can, say, specify C++ include directories for the compiler to use only when compiling C++, and let it determine whether it is or not by itself. The ideal is that we wouldn’t be parsing any flags ourselves at all. That’s a pretty long road, though, since our wrappers do some weird stuff and the compiler frontends aren’t always that flexible; it would require working with upstream and thinking hard about what functionality we need and how to provide it. If we can solve the immediate issue with this PR then it should be okay to bring this approach back temporarily, but probably anything like this we do in these wrappers will never be wholly correct.

FWIW, in this case I suspect the issue was https://github.com/GasInfinity-Forks/nixpkgs/blob/8e3b8e080571ee2c8a2bf6c31a4f10b093547d93/pkgs/build-support/cc-wrapper/cc-wrapper.sh#L181-L183 and perhaps that might be exposing some other problem in our WASM machinery (i.e. some dubious value of `NIX_CXXSTDLIB_LINK` for the platform).
