### PR TITLE
yarnInstallHook: fix temporary directory location

### LINKED ISSUE #342151: yarnInstallHook tmp directory polluting result
### Describe the bug

`yarnInstallHook` is currently using `mktemp -d yarnInstallHook.XXXXXX` this command creates the temporary directory inside the current working directory instead of in `/tmp`.

This can cause the generated directory to be included in the final package, as I'm assuming `yarn pack` accidentally picked it up.
I encountered this while working on https://github.com/NixOS/nixpkgs/pull/342145 and https://github.com/NixOS/nixpkgs/pull/342153

### Expected behavior
The temporary directory is not included in the output

### Possible solutions
- use `mktemp -d`
- use `mktemp -d --suffix=-yarnInstallHook` (output is of the format `/tmp/tmp.XXXXXXXXXX-yarnInstallHook`)
  - note: this isn't really used across nixpkgs
- use something else

### Notify maintainers
@lelgenio 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.51, NixOS, 24.11 (Vicuna), 24.11.20240915.9299cdf`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/i6ljzmbd9jk67xnxlwqs7kv3wap56j05-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by lelgenio**
Currently the directory is being created in `$src/yarnInstallHook.XXXXXX`

Giving the directory a readable name is not particularly useful.

Fixes: https://github.com/NixOS/nixpkgs/issues/342151

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by lelgenio** [comment]
Result of `nixpkgs-review pr 342608` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>5 packages built:</summary>
  <ul>
    <li>blade-formatter</li>
    <li>codefresh</li>
    <li>element-call</li>
    <li>postlight-parser</li>
    <li>yarnInstallHook</li>
  </ul>
</details>

**Review by TomaSajt — APPROVED** [review]
Thanks, LGTM

File: pkgs/build-support/node/fetch-yarn-deps/yarn-install-hook.sh [hunk 1]
```diff
@@ -17,7 +17,7 @@ yarnInstallHook() {
         --offline
     )
 
-    local -r tmpDir="$(mktemp -d yarnInstallHook.XXXXXX)"
```
Comment (doronbehar) [inline pkgs/build-support/node/fetch-yarn-deps/yarn-install-hook.sh:20]: Thanks for catching that. I wonder why we used a temporary directory at all, but I don't mind that much now.

**Review by doronbehar — APPROVED** [review]

**Comment by doronbehar** [comment]
Verified that the patch indeed makes the `node_modules` dir not get polluted by the temporary directory.
