### PR TITLE
factorio: download using token, not password

### LINKED ISSUE #46267: Factorio downloads fail to login
## Issue description
I recently returned to Nixos after a break, and have been trying to update my packages. However, Factorio fails to download it's files from the game's fileserver.
I am using Nixos 18.03, with a nixos-unstable as a user channel.

Here is a typical attempt at installing Factorio (it doesn't matter which channel I build it with)
```
[OMITTED@nixos:~]$ nix-env -iA unstable.factorio
installing 'factorio-alpha-0.16.51'
these derivations will be built:
  /nix/store/b75nfira5bb2fxk54aby0wgmlrnji7fs-factorio_alpha_x64-0.16.51.tar.xz.drv
  /nix/store/kvs48bb8wa9kgj2nxra8sfwrf3q7hqhn-factorio-alpha-0.16.51.drv
building '/nix/store/b75nfira5bb2fxk54aby0wgmlrnji7fs-factorio_alpha_x64-0.16.51.tar.xz.drv'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8833  100  8833    0     0  11486      0 --:--:-- --:--:-- --:--:-- 11471
**** Processing: stdin:/// ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   353  100   192  100   161    252    211 --:--:-- --:--:-- --:--:--   464
Login failed
Please set username and password with config.nix,
or /etc/nix/nixpkgs-config.nix if on NixOS.

Example:
{
  packageOverrides = pkgs: rec {
    factorio = pkgs.factorio.override {
      username = "<username or email address>";
      password = "<password>";
    };
  };
}
builder for '/nix/store/b75nfira5bb2fxk54aby0wgmlrnji7fs-factorio_alpha_x64-0.16.51.tar.xz.drv' failed with exit code 1
cannot build derivation '/nix/store/kvs48bb8wa9kgj2nxra8sfwrf3q7hqhn-factorio-alpha-0.16.51.drv': 1 dependencies couldn't be built
error: build of '/nix/store/kvs48bb8wa9kgj2nxra8sfwrf3q7hqhn-factorio-alpha-0.16.51.drv' failed
```

The factorio attribute is overridden using the following overlay.
`~/nix-cherries/factorio` is just a copy of `unstable/pkgs/games/factorio` I made to help my investigations, the issue still exists with the stock derivation. 
```
self: super: {
    factorio = super.factorio.override {
        username = "nullvoid";
        password = "………………";
    };
}
```

Some fiddling with `fetch.sh` show that curl is giving the following output. I also able to see that the username and password ARE being passed correctly to `fetch.sh`.
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```
I suspect the problem is that the login page has recaptcha on it, but I have no idea how to solve the issue either way.

### Steps to reproduce
1. Override the factorio derivation to set username and password
2. run `nix-env -iA nixos.factorio`
3. observe the failure to login (`fetch.sh` assumes all failures to login are because you haven't set your username and password)

## Technical details
```
[OMITTED@nixos:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.67, NixOS, 18.03.133187.8c172c44265 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(OMITTED): `"unstable-18.09pre150708.083220867c7"`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

```

cc @Baughn @elitak since you're listed in maintainers for Factorio. Sorry if this is bad form!

### PR DESCRIPTION
**Pull request by elitak**
Downloads were broken by upstream devs' addition of CAPTCHA to the login form.

Changed all references of password to token and used the new GET request + query string to fetch the files.

Fixes #46267

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

File: pkgs/games/factorio/fetch.sh [hunk 1]
```diff
@@ -14,42 +14,32 @@ curl="curl \
...
-    echo '  };'
-    echo '}'
-
-    exit 1
-fi
+Example:
+{
+  packageOverrides = pkgs: rec {
+    factorio = pkgs.factorio.override {
+      username = "<username or email address>";
```
Comment (nbp) [inline pkgs/games/factorio/fetch.sh]: nit: Insert a comment saying that this is confidential data and that it should not be shared.
follow-up: Use overlays instead of packageOverrides.

**Comment by elitak** [comment]
We can do without the customized `fetchurl` now, but I would like to find a way to inject the error message. The only method I can think of is to nest overrideDerivation alongside override to add a `postBuild` hook, but that gets pretty messy.

**Comment by elitak** [comment]
I figured out I should use `preHook` and `failureHook`. I added the info about factorio.com/profile. I will squash these commits after review, but they are close to final, now.

**Comment by Mic92** [comment]
@GrahamcOfBorg eval

**Comment by elitak** [comment]
I removed the warning now that 403 is returned, and changed the semantics of the `experimental` package function option to include stable builds.

@GrahamcOfBorg eval

**Comment by joachifm** [comment]
Is this ready?

**Comment by elitak** [comment]
Yes.
