### PR TITLE
switch-to-configuration-ng: fix systemd reexec/reload

### LINKED ISSUE #378535: switch-to-configuration-ng: failed to restart sysinit-reactivation.target
### Nixpkgs version

- Stable (24.11)

### Describe the bug

I'm using [`system.autoUpgrade.enable`](https://search.nixos.org/options?channel=24.11&show=system.autoUpgrade.enable&from=0&size=50&sort=relevance&type=packages&query=autoupgrade) (very recently changed to a custom module, but problem happened before) with a flake to upgrade my systems every night (this only happens on a specific system out of 5 that have this module enabled). However, sometimes (2-3 times a week), this unit fails on activation because of a timeout restarting `sysinit-reactivation.target`.

Here are the full logs for `nixos-rebuild-switch-to-configuration.service` and `sysinit-reactivation.target`:

```
Feb 01 04:08:42 hera systemd[1]: Starting /nix/store/4f8fpfwab9x8xcw1y1di7mmc6aszhxga-nixos-system-hera-24.11.20250126.4e96537/bin/switch-to-configuration switch...
Feb 01 04:08:42 hera systemd[1]: Started /nix/store/4f8fpfwab9x8xcw1y1di7mmc6aszhxga-nixos-system-hera-24.11.20250126.4e96537/bin/switch-to-configuration switch.
Feb 01 04:08:42 hera nixos-upgrade-start[628103]: Installing Lanzaboote to "/boot"...
Feb 01 04:08:42 hera nixos-upgrade-start[628103]: Collecting garbage...
Feb 01 04:08:42 hera nixos-upgrade-start[628103]: Successfully installed Lanzaboote.
Feb 01 04:08:43 hera nixos[628100]: switching to system configuration /nix/store/4f8fpfwab9x8xcw1y1di7mmc6aszhxga-nixos-system-hera-24.11.20250126.4e96537
Feb 01 04:08:43 hera nixos-upgrade-start[628100]: activating the configuration...
Feb 01 04:08:43 hera nixos-upgrade-start[628136]: [agenix] creating new generation in /run/agenix.d/6
Feb 01 04:08:43 hera nixos-upgrade-start[628136]: [agenix] decrypting secrets...
/// ...
Feb 01 04:08:43 hera nixos-upgrade-start[628136]: [agenix] symlinking new secrets to /run/agenix (generation 6)...
Feb 01 04:08:43 hera nixos-upgrade-start[628136]: [agenix] removing old secrets (generation 5)...
Feb 01 04:08:44 hera nixos-upgrade-start[628136]: [agenix] chowning...
Feb 01 04:08:44 hera nixos-upgrade-start[628136]: setting up /etc...
Feb 01 04:08:49 hera nixos-upgrade-start[628100]: restarting sysinit-reactivation.target
Feb 01 04:08:54 hera nixos-upgrade-start[628100]: Failed to restart sysinit-reactivation.target: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Feb 01 04:09:02 hera nixos-upgrade-start[628100]: the following new units were started: run-credentials-acme\x2dfirefly3\x2dcsv.hera.diogotc.com.service.mount
Feb 01 04:09:02 hera nixos[628100]: switching to system configuration /nix/store/4f8fpfwab9x8xcw1y1di7mmc6aszhxga-nixos-system-hera-24.11.20250126.4e96537 failed (status 4)
Feb 01 04:09:02 hera systemd[1]: nixos-rebuild-switch-to-configuration.service: Main process exited, code=exited, status=4/NOPERMISSION
Feb 01 04:09:02 hera systemd[1]: nixos-rebuild-switch-to-configuration.service: Failed with result 'exit-code'.
Feb 01 04:09:02 hera systemd[1]: nixos-rebuild-switch-to-configuration.service: Consumed 1.860s CPU time, 16.4M memory peak, 5.5M read from disk.
```

```
Feb 01 04:08:55 hera systemd[1]: Stopped target Reactivate sysinit units.
Feb 01 04:08:55 hera systemd[1]: Stopping Reactivate sysinit units...
Feb 01 04:08:55 hera systemd[1]: Reached target Reactivate sysinit units.
```

Looking at the timestamps, it seems like the activation script tries to restart `sysinit-reactivation.target` at 04:08:49, but it only does at 04:08:55. It appears that systemd doesn't reply through dbus or something and reaches the [timeout of 5 seconds](https://github.com/NixOS/nixpkgs/blob/666e1b3f09c267afd66addebe80fb05a5ef2b554/pkgs/by-name/sw/switch-to-configuration-ng/src/src/main.rs#L885).
My theory is that the system is under load and something freezes, taking too long to run, but I have no way to verify this claim at the moment.

### Steps to reproduce

Unfortunately I'm unsure how to reliably reproduce this. I'd appreciate some pointers on how to get some logs that could help figure out the root of the problem.

### Expected behaviour

Activation should complete successfully

### Screenshots

_No response_

### Relevant log output

```console

```

### Additional context

Config: https://github.com/diogotcorreia/dotfiles/tree/c115fd5eb54875107079ffd343201d2945a8898c (host `hera`)

_Maybe_ related to https://github.com/NixOS/nixpkgs/issues/313696

I'm going to try and increase the timeout from 5 seconds to 10 seconds and report back, but that might be a dirty fix instead of fixing the underlying issue.

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.72, NixOS, 24.11 (Vicuna), 24.11.20250126.4e96537`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.11`
 - nixpkgs: `/nix/store/50yickar04m51aqnc43gxf45g2i0n3k9-source`

### Notify maintainers

@jmbaur 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by jmbaur**
According to systemd's D-Bus API documentation, a `Reloading` signal will be sent with the value `false` will be sent when reloading has finished (indicating that reloading is not active). The entire reloading sequence has two signals, the with the first value indicating that reloading has started (active = true). Thus, we must wait for the active value to be false before we can continue.

Fixes https://github.com/NixOS/nixpkgs/issues/378535

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [x] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jmbaur** [comment]
@ofborg test switchTest

File: pkgs/by-name/sw/switch-to-configuration-ng/src/src/main.rs [hunk 1]
```diff
@@ -1691,9 +1691,11 @@ won't take effect until you reboot the system.
     if restart_systemd {
         eprintln!("restarting systemd...");
         _ = systemd.reexecute(); // we don't get a dbus reply here
+        *systemd_is_reloading.borrow_mut() = true;
```
Comment (diogotcorreia) [inline pkgs/by-name/sw/switch-to-configuration-ng/src/src/main.rs]: Shouldn't this be the other way around? I think it causes a race condition: if reexec/reload finishes before we change `systemd_is_reloading` then we'll hang forever.

Comment (jmbaur) [reply pkgs/by-name/sw/switch-to-configuration-ng/src/src/main.rs]: ah of course, thank you! fixed

**Review by diogotcorreia — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 476759 --additional-package nixosTests.switchTest`
Commit: `f5aeb5ef47ee9a576412014a603b3534fce0e2e0`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.switchTest</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>switch-to-configuration-ng</li>
  </ul>
</details>

**Comment by jmbaur** [comment]
@diogotcorreia does this fix the issue for you? :smile: 

I think it would be wise for us to employ the systemd default timeout for daemon reload/reexec ([which is twice that of the normal timeout](https://github.com/systemd/systemd/blob/5366dbdbd44ba4dc0c914dd4daa1a5297e0b2bde/src/basic/constants.h#L18)) here as well, to prevent the issue of a reload/reexec never finishing and us ending up looping forever. Does it sound cool if I include that here?

**Comment by jmbaur** [comment]
@ofborg test switchTest

**Review by diogotcorreia — APPROVED** [review]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 476759 --additional-package nixosTests.switchTest`
Commit: `039a1bee5f01e703d8a1d7e9c24ece8645270635`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.switchTest</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>switch-to-configuration-ng</li>
  </ul>
</details>
