### PR TITLE
stdenv: create `env-vars` file before writing data to it

### LINKED ISSUE #335016: Darwin shows `install: skipping file '/dev/fd/63', as it was replaced while being copied` when building derivations
### Describe the bug

I started seeing this message when building derivations on Darwin:

```
install: skipping file '/dev/fd/63', as it was replaced while being copied
```

Multiple times, in multiple phases.

It also happens in ofborg. See for example: https://github.com/NixOS/nixpkgs/pull/334542/checks?check_run_id=28783170448

### Steps To Reproduce

- Build a derivation on Darwin. It happens with any derivation as I have been doing multiple `nixpkg-review`s

### Expected behavior

There should not be any error message related to `install`. It may be innocuous so far but I'd rather not see errors.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(smancill): `"darwin, nixpkgs-23.11-darwin, unstable"`
 - nixpkgs: `/Users/smancill/.nix-defexpr/channels/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by LeSuisse**
## Description of changes

This fixes the regression introduced by c47a1e701df7f00352b8cf401fa79c0d2f5fcc59 on Darwin. The creation of the file using `install` and process substitution does not work on Darwin, you get the following complain:
```
install: skipping file '/dev/fd/63', as it was replaced while being copied
```

Fixes #335016

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Review by viraptor — APPROVED** [review]
Tested locally. I'm not familiar with this functionality enough to tell if it works, but the error is gone and isolated testing of the commands does the right thing.

**Comment by emilazy** [comment]
Maybe we could do `export 2>/dev/null | install -m 0600 /dev/stdin`? Not sure if it’d be any better.

**Comment by viraptor** [comment]
@emilazy `install: /dev/stdin: Inappropriate file type or format`
It just doesn't like special files.

**Comment by LeSuisse** [comment]
I added a comment :)

**Comment by n8henrie** [comment]
nit on the comment (English), consider: 

> On darwin, install(1) cannot be called with /dev/stdin or fd from process substitution

Could also consider adding a link to the issue.

File: pkgs/stdenv/generic/setup.sh [hunk 1]
```diff
@@ -1121,7 +1121,10 @@ substituteAllInPlace() {
 # the environment used for building.
 dumpVars() {
     if [ "${noDumpEnvVars:-0}" != 1 ]; then
-        install -m 0600 <(export 2>/dev/null) "$NIX_BUILD_TOP/env-vars" || true
+        # Darwin do not like install(1) being called with /dev/stdin or fd from process substitution
+        # so we first create the file and then write to it
```
Comment (isabelroses) [inline pkgs/stdenv/generic/setup.sh:1125]: Just some small grammar changes on the comment
```suggestion
        # Darwin does not like install(1) being called with /dev/stdin or fd from process substitution
        # so first we create the file and then write to it
```

**Review by n8henrie — APPROVED** [review]

**Review by isabelroses — APPROVED** [review]

File: pkgs/stdenv/generic/setup.sh [hunk 2]
```diff
@@ -1121,7 +1121,11 @@ substituteAllInPlace() {
 # the environment used for building.
 dumpVars() {
     if [ "${noDumpEnvVars:-0}" != 1 ]; then
-        install -m 0600 <(export 2>/dev/null) "$NIX_BUILD_TOP/env-vars" || true
+        # On darwin, install(1) cannot be called with /dev/stdin or fd from process substitution
+        # so first we create the file and then write to it
+        # See https://github.com/NixOS/nixpkgs/issues/335016
+        install -m 0600 /dev/null "$NIX_BUILD_TOP/env-vars" || true
+        export 2>/dev/null >| "$NIX_BUILD_TOP/env-vars" || true
     fi
```
Comment (smancill) [inline pkgs/stdenv/generic/setup.sh:1129]: I believe that the idea of #331576 is *not* to write the `env-vars` file if it doesn't have the right permissions.

But the current sequence of commands in this PR means that if the `install` fails for some reason, then the `export` will still write to the file.

I think this could be better:

``` sh
{
    touch $NIX_BUILD_TOP/env-vars" &&
    chmod 600 $NIX_BUILD_TOP/env-vars" &&
    export 2>/dev/null >| "$NIX_BUILD_TOP/env-vars"
} || true
```

while also being more clear about the intent.

Comment (LeSuisse) [reply pkgs/stdenv/generic/setup.sh:1131]: Thanks, yeah that was indeed why I attempted to do it in one pass initially.

**Review by smancill — APPROVED** [review]

File: pkgs/stdenv/generic/setup.sh [hunk 3]
```diff
@@ -1121,7 +1121,13 @@ substituteAllInPlace() {
 # the environment used for building.
 dumpVars() {
     if [ "${noDumpEnvVars:-0}" != 1 ]; then
-        install -m 0600 <(export 2>/dev/null) "$NIX_BUILD_TOP/env-vars" || true
+        # On darwin, install(1) cannot be called with /dev/stdin or fd from process substitution
+        # so first we create the file and then write to it
+        # See https://github.com/NixOS/nixpkgs/issues/335016
+        {
+            install -m 0600 /dev/null "$NIX_BUILD_TOP/env-vars" && \
```
Comment (n8henrie) [inline pkgs/stdenv/generic/setup.sh:1128]: nit: `\` is unnecessary, `&&` should result in a line continuation

File: pkgs/stdenv/generic/setup.sh [hunk 4]
```diff
@@ -1121,7 +1121,13 @@ substituteAllInPlace() {
...
+            export 2>/dev/null >| "$NIX_BUILD_TOP/env-vars"
+        } || true
```
Comment (n8henrie) [inline pkgs/stdenv/generic/setup.sh:1130]: I'm still unclear on why we want to `|| true` this; the whole point of this issue and PR is that "this is a problem." It certainly would be nice to pick up on problems here sooner (i.e. in CI prior to merge into master / unstable) due to a failure rather than later. If we didn't `|| true`, we might not be dealing with this issue in the first place. Just my 2¢.

**Review by n8henrie — CHANGES_REQUESTED** [review]

File: pkgs/stdenv/generic/setup.sh (hunk 4 above)
Comment (smancill) [reply pkgs/stdenv/generic/setup.sh:1130]: It's not in the scope of this PR or the previous one to change that. It was al ready there, and it was almost 9 years ago: 774f74b8757d6c9809825d3c14fbe313db1378cf.

Comment (emilazy) [reply pkgs/stdenv/generic/setup.sh:1130]: It looks like now that `$NIX_BUILD_TOP` isn’t shared among builds(!), the motivation for the `|| true` no longer applies?

Comment (smancill) [reply pkgs/stdenv/generic/setup.sh:1130]: My point is that we are getting sidetracked. Can we just get this merged and discuss the implications of failing the command or not in a different issue?

The `|| true` was already there so nothing is changed in that regard.

Comment (n8henrie) [reply pkgs/stdenv/generic/setup.sh:1130]: > It's not critical if it fails, thus it can be ignored.

If the functionality is truly so unimportant as to not be worth "fixing right," should it just be removed? That would accomplish the goal of silencing the complaint and decrease maintenance burden.

But if there is room between being "critical" at best and being "unworthy of keeping in the codebase" at worst, it seems reasonable to make sure it works. It does not seem very "nix" to be satisfied with "yeah it works sometimes, and when it doesn't we just ignore it."

That said, I agree it is not in the "scope" of this issue to address it, so I won't bring it up again here.

Comment (emilazy) [reply pkgs/stdenv/generic/setup.sh:1130]: Sure, let’s fix this as it is and then do a follow‐up PR.

**Review by viraptor — APPROVED** [review]

**Review by isabelroses — APPROVED** [review]

File: pkgs/stdenv/generic/setup.sh (hunk 3 above)
Comment (LeSuisse) [reply pkgs/stdenv/generic/setup.sh]: Done, thanks.

**Review by viraptor — APPROVED** [review]

**Review by smancill — APPROVED** [review]
