### PR TITLE
compress-man-pages: symlink compressed manpages deterministically

### LINKED ISSUE #104708: graphviz: dot2gxl.1.gz symlink target is not consistent
**Describe the bug**

When building `graphviz` multiple times, `man/man1/dot2gxl.1.gz` may point to either `gv2gxl.1.gz` or `gxl2gv.1.gz`.

This is not a very important distinction, because `gv2gxl.1.gz` in turn symlinks to `gxl2gv.1.gz`. However, it would be nice to be consistent about that because it makes auditing a nixpkgs cache for unexpected data harder (see 'reproducible builds').

**To Reproduce**
1. `nix-build <nixpkgs> -A graphviz --check`

**Expected behavior**

This should produce the same output as hydra every time, but doesn't.

**Additional context**

The non-gzipped manpages are replaced by symlinks in the `install-data-hook` target of `cmd/tools/Makefile`.

I guess this could be some race condition between the process that runs the `install-data-hook` and the process that replaced the manpages with their gzipped counterparts. However, it is unclear to me how/where the latter happens.

### PR DESCRIPTION
**Pull request by raboof**
For example graphviz has chained symlinked manpages: dot2gxl.1 is
a symlink to gv2gxl.1 which is a symlink to gxl2gv.1

The second loop replaces each non-compressed symlink to a compressed
symlink. The target is determined with 'readlink -f', which follows
links recursively until the first name that is not a link (so either
the 'target name' or the first 'dangling' symlink).

This means that if the loop converted dot2gxl.1 before converting
gv2gxl.1 it would add a symlink `dot2gxl.1.gz->gxl2gv.1.gz`. When
it converted gv2gxl.1 first, it would then add a
`dot2gxl.1.gz->gv2gxl.1.gz` symlink.

Both are 'correct', but it's weird the result depends on the order
in which 'find' returns the files. This PR makes the behaviour
deterministic.

fixes #104708

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

File: pkgs/build-support/setup-hooks/compress-man-pages.sh [hunk 1]
```diff
@@ -21,6 +21,7 @@ compressManPages() {
 
     # Point symlinks to compressed manpages.
     find "$dir"/share/man/ -type l -a '!' -regex '.*\.\(bz2\|gz\)$' -print0 \
+        | sort -z
```
Comment (SuperSandro2000) [inline pkgs/build-support/setup-hooks/compress-man-pages.sh:24]: I think this requires coreutils.

Comment (raboof) [reply pkgs/build-support/setup-hooks/compress-man-pages.sh]: That's correct. This script already uses `readlink` which also requires coreutils, so while I'm not sure where this dependency is specified I'm pretty sure it's already included.

**Review by prusnak — APPROVED** [review]

File: pkgs/build-support/setup-hooks/compress-man-pages.sh (hunk 1 above)
Comment (SuperSandro2000) [reply pkgs/build-support/setup-hooks/compress-man-pages.sh]: I thought it wasn't because the eval error mislead me.

**Comment by SuperSandro2000** [comment]
@FRidh just wanted to inform you about this if you see some random errors on staging with man pages.
