### PR TITLE
nixos-container: Fix `destroy` terminating before it's done. Fixes #32545

### LINKED ISSUE #32545: nixos-container destroy terminates before container is destroyed
`nixos-container destroy` currently issues a `machinectl terminate`, which is asynchronous. If a process in the container behaves badly and ignores shutdown, the container will in fact live on until systemd decides to send a SIGKILL (by default 90 seconds later).

At the same time, `nixos-container` deletes the entry in `/etc/containers/` immediately after issuing `machinectl terminate`.

As a result, `nixos-container` thinks the container is dead, while systemd thinks it's still alive and deactivating.

Apart from being confusing, this creates a bug for nixops, which calls `nixos-container`:

If during the 90 seconds, you try to deploy to a container again, nixops will use the same container name (e.g. `mycontainer--0`, where the index at the end seems to be the smallest index that doesn't exist in `/etc/containers/`), but fail to start because systemd claims that container still exists.

It seems a good way to fix that would be to either

1. make `nixos-container destroy` block until the container is actually destroyed
2. make `nixos-container destroy` block, but shorter (e.g. 5 seconds), then call `machinectl kill`
3. make whatever nixops calls to decide the next container index by querying systemd's information, not the the one from `nixos-container`

The first option seems like the cleanest -- I'd expect `destroy` to only terminate when it's really done.

The third option could be done in addition.

### PR DESCRIPTION
**Pull request by nh2**
nixos-container: Fix `destroy` terminating before it's done. Fixes #32545

This also fixes the race condition found in #32551.

And it fixes nixops's repeated destroy/deploy being broken
(https://github.com/NixOS/nixops/issues/809).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by nh2** [comment]
CC @domenkozar

**Comment by nh2** [comment]
CC @johbo @kevincox via https://github.com/NixOS/nixops/pull/759

**Comment by grahamc** [comment]
@GrahamcOfBorg eval

(sorry for the noise, master was broken by a merge)

File: pkgs/tools/virtualization/nixos-container/nixos-container.pl [hunk 1]
```diff
@@ -214,29 +214,32 @@ sub writeNixOSConfig {
...
     my $status = `systemctl show 'container\@$containerName'`;
     return $status =~ /ActiveState=active/;
 }
 
 sub terminateContainer {
+    my $leader = getLeader;
     system("machinectl", "terminate", $containerName) == 0
         or die "$0: failed to terminate container\n";
+    # Wait for the leader process to exit
+    while ( kill 0, $leader ) { sleep 1 }
```
Comment (orivej) [inline pkgs/tools/virtualization/nixos-container/nixos-container.pl]: `sleep 0.1` would probably be preferred, as it is less noticeable.

This solution is unsafe because leader PID may be freed and reused by an unrelated process while `terminateContainer` sleeps. `machinectl` (or `systemctl`) should be used for querying the status.

Comment (nh2) [reply pkgs/tools/virtualization/nixos-container/nixos-container.pl]: > sleep 0.1 would probably be preferred, as it is less noticeable.

@orivej I agree and I'd also prefer a shorter duration, but as far as I understand [from here](http://perldoc.perl.org/functions/sleep.html), in perl you can't sleep less than 1 second, unless you use the `Time::HiRes` module, which I don't know if it's available here. Improvements welcome.






> This solution is unsafe because leader PID may be freed and reused by an unrelated process while terminateContainer sleeps.

Yes

> machinectl (or systemctl) should be used for querying the status.

@orivej Do you know if there's a UUID or something like that provided by `machinectl`, or do we have to wait based on the name?

Comment (orivej) [reply pkgs/tools/virtualization/nixos-container/nixos-container.pl]: > as far as I understand [from here](http://perldoc.perl.org/functions/sleep.html), in perl you can't sleep less than 1 second, unless you use the `Time::HiRes` module, which I don't know if it's available here. Improvements welcome.

That page says that this module is shipped with Perl 5.8 and later, so you can easily use it.

> Do you know if there's a UUID or something like that provided by `machinectl`, or do we have to wait based on the name?

I don't know, I have not looked at `machinectl` before this PR.

Comment (domenkozar) [reply pkgs/tools/virtualization/nixos-container/nixos-container.pl]: I suggest we add a comment to improve reliability, this is an improvement on it's own compared to current implementation.

Comment (nh2) [reply pkgs/tools/virtualization/nixos-container/nixos-container.pl]: I have swithed to `Time::HiRes` as @orivej suggested, and added a TODO about switching away from PIDs in `nixos-container`.

Comment (nh2) [reply pkgs/tools/virtualization/nixos-container/nixos-container.pl]: I've filed a separate issue to track the removal of PID based logic, and found that `machinectl show` already provides an `Id` field we could use: https://github.com/NixOS/nixpkgs/issues/33171

**Comment by garbas** [comment]
@GrahamcOfBorg test containers-imperative

**Review by fpletz — APPROVED** [review]
NixOS tests runs and code looks good. Thanks!
