### PR TITLE
chroot-user: rewrite in C, drop CHROOTENV_EXTRA_BINDS

### LINKED ISSUE #19047: Rewrite chroot-user.rb in C/C++
`pkgs/build-support/build-fhs-userenv/chroot-user.rb` consists mostly of syscalls (including `fork()`). There are even Ruby-specific workarounds. C/C++ would be a better language for the task. This should also reduce closure size and startup time of FHS-sandboxed apps (Ruby needs to load itself and its libraries from disk).

### LINKED ISSUE #31104: buildFHSUserEnv doesn't work inside sandbox
## Issue description

`buildFHSUserEnv` doesn't work inside sandbox. It can sometimes be useful to build, or unpack something in an environment that has a lot of assumptions (say, self-extracting checksummed executable, or build system that expects FHS-compliant paths).

### Steps to reproduce

Given `/etc/nixos/configuration.nix` containing:

```
nix.useSandbox = true;
```

Given `example.nix`:

```
{ stdenv, buildFHSUserEnv }:

let
  buildEnv = buildFHSUserEnv {
    name = "example-build-env";
    runScript = "echo hello";
    targetPkgs = pkgs: [];
  };
in

stdenv.mkDerivation {
  name = "example";
  unpackPhase = ":";
  buildPhase = "${buildEnv}/bin/${buildEnv.name}";
  installPhase = "ln -s ${buildEnv} $out";
}
```

```
$ nix-build -E "with import <nixpkgs> {}; callPackage ./example.nix {}"
these derivations will be built:
  /nix/store/dm11jjsk39lh8lhi8l88pzvvw85d5c3h-example.drv
building path(s) ‘/nix/store/mq3nlfsalghxj87v41yc4wvkm8196mzs-example’
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
/nix/store/iwxs4nwk80arwkvqdjqcy74r34wcg3wl-chroot-user:45:in `block in make_fcall': No such file or directory (Errno::ENOENT)
	from /nix/store/iwxs4nwk80arwkvqdjqcy74r34wcg3wl-chroot-user:131:in `block in <main>'
	from /nix/store/iwxs4nwk80arwkvqdjqcy74r34wcg3wl-chroot-user:128:in `each'
	from /nix/store/iwxs4nwk80arwkvqdjqcy74r34wcg3wl-chroot-user:128:in `<main>'
builder for ‘/nix/store/dm11jjsk39lh8lhi8l88pzvvw85d5c3h-example.drv’ failed with exit code 1
```

## Technical details

* System: 18.03pre118631.66b63d2f5a (Impala)
* Nix version: 1.11.15
* Nixpkgs version: e2edccae47dc4972ec16bdeb6eb5374f7631fea8
* Sandboxing enabled: yes

/cc @abbradar

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

Resolves #19047, fixes #31104. Related: #16030

Rebuilt several small derivations that use `buildFHSUserEnv`, currently in the process of rebuilding Steam runtime, will tell how it goes. All good so far.

Runs ~70ms (4 times) faster than `chroot-user.rb` on my machine. Basically the same LOC count.

/cc @abbradar @bjornfor @Mic92 @spacekitteh 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by yegortimoshenko** [comment]
Fixed a few issues thanks to Valgrind, cleaned up.

**Comment by yegortimoshenko** [comment]
Fixed a few issues thanks to Valgrind, cleaned up. Runs ~70ms (4 times) faster than `chroot-user.rb` on my machine.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+
+    if (uid == -1)
+      errorf(EX_OSERR, "getuid");
+
+    if (gid == -1)
+      errorf(EX_OSERR, "getgid");
+
+    // If we are root, no need to create new user namespace.
+    if (uid == 0) {
+      unshare(CLONE_NEWNS);
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: Needs to check result.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+      // Mark all mounted filesystems as slave so changes
+      // don't propagate to the parent mount namespace.
+      mount(NULL, "/", NULL, MS_REC | MS_SLAVE, NULL);
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: Needs to check result.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+    } else {
+      // Create new mount and user namespaces. CLONE_NEWUSER
+      // requires a program to be non-threaded.
+      unshare(CLONE_NEWNS | CLONE_NEWUSER);
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: Needs to check result.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 4]
```diff
@@ -0,0 +1,181 @@
...
+
+  if (cpid == -1)
+    errorf(EX_OSERR, "fork");
+
+  if (cpid == 0) {
+    uid_t uid = getuid();
+    gid_t gid = getgid();
+
+    if (uid == -1)
+      errorf(EX_OSERR, "getuid");
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: Errno might be shadowed here by getgid call.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 5]
```diff
@@ -0,0 +1,181 @@
...
+    if(chdir("/") == -1)
+      errorf(EX_OSERR, "chdir");
+
+    argv++;
+
+    if (execvpe(argv[0], argv, env_build(env_whitelist, LEN(env_whitelist))) == -1)
+      errorf(EX_OSERR, "execvpe");
+  }
+
+  while (wait(NULL) > 0);
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: I would only wait for our child process here and exit with the same exit status:

I have here some code, I adapted from `nsenter`:
https://github.com/Mic92/nsattach/blob/master/nsattach.c#L376

**Review by Mic92 — CHANGES_REQUESTED** [review]

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 6]
```diff
@@ -0,0 +1,181 @@
...
+
+int main(int argc, char *argv[])
+{
+  if (argc < 2) {
+    fprintf(stderr, "Usage: %s command [arguments...]\n"
+                    "Requires Linux kernel >= 3.19 with CONFIG_USER_NS.\n", argv[0]);
+    exit(EX_USAGE);
+  }
+
+  char *root = mkdtemp(strdup("/tmp/chrootenvXXXXXX"));
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: nitpick: memory never freed.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 3 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Added checks, fixed `errno` shadowing after `getgid()`.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 6 above)
Comment (Mic92) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: the following works for me:

```c
#include <stdio.h>
#include <stdlib.h>
int main() {
  char template[] = "/tmp/chrootenvXXXXXX";
  char *root = mkdtemp(template);
  if (!root) {
    perror("mkdtemp()");
  } else {
    printf("see %s\n", root);
  }
}
```

Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Interesting, if I swap `template[]` with `*template` it results in segfault.

Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Switched to this.

Comment (orivej) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: `char *template = "string"` is a pointer to a constant which resides in the read only memory. `char template[] = "string"` is a mutable 7 bytes array (initialized with a string literal).

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 5 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Thanks! Now doing that.

Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Thanks, now doing that.

I've added signal handling code but no `SIGSTOP` handling. I don't think that is the right thing to do here because it means that sending `SIGCONT` to child process without repeating it to parent would result in parent being suspended indefinitely.

**Comment by yegortimoshenko** [comment]
@abbradar By the way, why do we bind-mount only certain dirs in `/`? We could just bind-mount every dir, which would also make `/host` mount unnecessary...

**Comment by yegortimoshenko** [comment]
I've fixed `/proc/self/{g,u}id_map` writes, Steam works.

**Comment by yegortimoshenko** [comment]
And on dropping `CHROOTENV_EXTRA_BINDS`: I'm normally against breaking reverse compatibility, but considering it's a rewrite, the scope of packages that use `buildFHSUserEnv` (currently 5 in tree) and the fact that it would take around 40 lines of code to implement, and the fact that it has been deprecated in favor of `/host`...

@bjornfor, I think you've requested that feature initially. Are you OK with it getting dropped?

**Comment by yegortimoshenko** [comment]
@abbradar On https://github.com/NixOS/nixpkgs/pull/16030#issuecomment-224134361:

I would really like to see experimental branch that uses `/etc/ld-nix.so.cache` to find libraries. This would fix https://github.com/NixOS/nixpkgs/issues/21109, RPG Maker MV on Steam, and probably quite a few other games too: it is common for games to have a start script that overrides `LD_LIBRARY_PATH`. Nagging game developers to fix the problem usually doesn't help.

**Comment by abbradar** [comment]
First of all, thank you for this rewrite! I have been delaying this for too much time ;)

We can indeed just bind-mount everything to `/`, good idea. Actually I planned to do something similar (link everything from `/host`) and also blacklist instead of whitelisting environment variables. This way we would be even closer to the surrounding environment (given that our aim is not isolation but providing FHS-compliant packages installed).

About `CHROOTENV_EXTRA_BINDS` -- if we move to this direction it could be OK to drop it but I'm not sure if there are not any clever usages of that in the wild (given that one can add arbitrary bind-mounts). Let's see what @bjornfor has to say on that.

On `/etc/ld-nix.so.cache` -- this won't actually help because one still needs `LD_LIBRARY_PATH` for things like `/run/opengl-driver`. I tried to add `NIX_LD_LIBRARY_PATH` some time ago but `ld.so`'s codebase is awful and I lost my motivation along the way. I have even mentioned problems with `LD_LIBRARY_PATH` during NixCon but not sure how to tackle that yet.

**Comment by yegortimoshenko** [comment]
@abbradar I will implement a blacklist (probably `*envp[]` filtered with `strncmp`, don't know a better approach) and bind-mount every dir in `/` (if `/host/host` exists, it probably should take precedence).

However, I'd prefer this PR to be mostly a feature parity rewrite.

> On /etc/ld-nix.so.cache -- this won't actually help because one still needs LD_LIBRARY_PATH for things like /run/opengl-driver. I tried to add NIX_LD_LIBRARY_PATH some time ago but ld.so's codebase is awful and I lost my motivation along the way. I have even mentioned problems with LD_LIBRARY_PATH during NixCon but not sure how to tackle that yet.

I see... I'll look into the linker. This fragment of `emultempl/elf32.em` looks promising:

```
if [ "x${NATIVE}" = xyes ] ; then
fragment <<EOF
	  if (command_line.rpath_link == NULL
	      && command_line.rpath == NULL)
	    {
	      lib_path = (const char *) getenv ("LD_RUN_PATH");
	      if (gld${EMULATION_NAME}_search_needed (lib_path, &n,
						      force))
		break;
	    }
	  lib_path = (const char *) getenv ("LD_LIBRARY_PATH");
	  if (gld${EMULATION_NAME}_search_needed (lib_path, &n, force))
	    break;
EOF
fi
```

**Comment by abbradar** [comment]
Let's proceed with feature parity first then and change semantics later, sounds good to me.

I can't look at the source right now but in my memory it was completely different -- something like using a global static buffer to read and then work with `LD_LIBRATY_PATH`, so it couldn't be called two times with two different variables without substantial rewrite or hacks. It would be very good if I was mistaken!

**Comment by yegortimoshenko** [comment]
@abbradar OK! I'll try to build `ld.so` with this patch and hopefully it will work:

```
diff -urNZ a/ld/emultempl/elf32.em b/ld/emultempl/elf32.em
--- a/ld/emultempl/elf32.em	2017-07-25 14:25:50.000000000 +0000
+++ b/ld/emultempl/elf32.em	2017-11-04 09:38:10.576667871 +0000
@@ -1418,6 +1418,10 @@
 	  lib_path = (const char *) getenv ("LD_LIBRARY_PATH");
 	  if (gld${EMULATION_NAME}_search_needed (lib_path, &n, force))
 	    break;
+
+	  lib_path = (const char *) getenv ("NIX_LD_LIBRARY_PATH");
+	  if (gld${EMULATION_NAME}_search_needed (lib_path, &n, force))
+	    break;
 EOF
 fi
 if [ "x${USE_LIBPATH}" = xyes ] ; then
```

**Comment by bjornfor** [comment]
> Let's see what @bjornfor has to say on that.

As per my comment in https://github.com/NixOS/nixpkgs/pull/16030#issuecomment-224215035 (thanks for the reminder!), I'm OK with removing CHROOTENV_EXTRA_BINDS.

**Comment by yegortimoshenko** [comment]
@abbradar I've got it mixed up, the patch above is for binutils `ld`, not glibc `ld.so`. However, good news! I have hacked in `NIX_LD_LIBRARY_PATH` support for `ld.so`, check it out: #31263

**Comment by abbradar** [comment]
Sorry, I've gotten ill so I won't be able to proceed with this and other PRs for a couple of days more at least (just a heads up).

**Comment by yegortimoshenko** [comment]
Get well! <(￣︶￣)>

I'll clean this up in the meantime.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 7]
```diff
@@ -0,0 +1,182 @@
...
+        errorf(EX_OSERR, "unshare");
+      // Mark all mounted filesystems as slave so changes
+      // don't propagate to the parent mount namespace.
+      if (mount(NULL, "/", NULL, MS_REC | MS_SLAVE, NULL) < 0)
+        errorf(EX_OSERR, "mount");
+    } else {
+      // Create new mount and user namespaces. CLONE_NEWUSER
+      // requires a program to be non-threaded.
+      if (unshare(CLONE_NEWNS | CLONE_NEWUSER) < 0)
+        errorf(EX_OSERR, "unshare");
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: `unshare` is not allowed on all linux distributions by default. On redhat and clones, it is required to set `kernel.unprivileged_userns_clone = 1`. Maybe the error message can reflect that if the return value of `unshare` is EPERM.

Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Thank you, good catch. Also Arch Linux has it disabled by default in kernel (requires `linux-userns` kernel from AUR), but Debian variants should be OK. Do you think it's appropriate to check for distro-specific files (like `/etc/redhat-release`) and print specific instructions?

Comment (Mic92) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: I would keep the error message generic to keep the code simple:

```
No permission to create username spaces as unprivileged user.
Please make sure that the kernel has usernamespace support enabled (`CONFIG_USER_NS=y`)
and it is enabled for unprivileged users (sysctl -w kernel.unprivileged_userns_clone=1).
```

Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: The problem is that I think `kernel.unprivileged_userns_clone` isn't in Torvalds' tree and most likely a RHEL-specific patch on top of it:

```
$ find /proc/sys/kernel -name unprivileged_\*
/proc/sys/kernel/unprivileged_bpf_disabled
/proc/sys/kernel/unprivileged_userns_apparmor_policy
```

Comment (Mic92) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: It is also available on ubuntu.

Comment (abbradar) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: This would also fail on old Linux kernels. We may want to have a nice generic error message, in lines of "You may have an old kernel or have CLONE_NEWUSER disabled by your distribution security settings."

Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: @abbradar, @Mic92: Got you. Hope they enable it by default at some point (and old kernels will be phased out of use), but for now going to print this stuff, supplemented by `sysctl` instructions if `/proc/sys/kernel/unprivileged_userns_clone` is present.

Arch Linux should have adopted this patch instead of disabling the option entirely...

**Comment by FRidh** [comment]
Is this ready?

**Comment by Mic92** [comment]
afaik only the error message is missing.

**Comment by yegortimoshenko** [comment]
Thank you a lot, @Mic92! This should now be ready to merge. No fancy `/proc/sys/kernel/unprivileged_ns_clone` handling, but this might be added later.

**Comment by vcunat** [comment]
BTW (hijacking this thread a little), the steam sandbox blocks network for me.  Even the old chroot binaries that used to work won't work anymore (and this PR doesn't fix it).  I suspect it's triggered by newer kernel (4.14 ATM but was broken with 4.13 as well), but I haven't confirmed that yet.  When I run all the sandbox except for steam command, I get
```
$ ping nixos.org   
ping: socket: Operation not permitted
```

**Comment by abbradar** [comment]
A heads up (I'm not able to read the complete thread right now) - I'm in a hospital and won't be able to work on this or other Nix things for a while. Feel free to merge if consensus is that it's ready - I can always review it and make changes later. 
-- 
Nikolay.
