### PR TITLE
nixos/nixos-installer: use temporary directory on target filesystem

### LINKED ISSUE #77481: nixos-install does not remove its temporary directory
**Describe the bug**
Each run of `nixos-install` leaves a temporary directory in $TMPDIR.

**To Reproduce**
Use `nixos-install`, then a new temporary directory is in $TMPDIR.

**Expected behavior**
The temporary directory is removed.

**Additional context**
This code is likely wrong:
https://github.com/NixOS/nixpkgs/blob/89e2c905b78258db29ffa4511b5933d5fe79e285/nixos/modules/installer/tools/nixos-install.sh#L93-L95

The `$tmpdir` reference should be escaped or `tmpdir` defined before the `trap`.

### PR DESCRIPTION
**Pull request by misuzu**
###### Motivation for this change
This should fix 'No space left on device' on systems with low amount of RAM when there is a need to build something like Linux kernel. 

Also fix https://github.com/NixOS/nixpkgs/issues/77481

How to test this:
* boot installer on machine with <=2G of RAM
* mount filesystems, generate config
* add this to configuration:
```nix
{
  boot.kernelPatches = [ {
    name = "crashdump-config";
    patch = null;
    extraConfig = ''
      CRASH_DUMP y
      DEBUG_INFO y
      PROC_VMCORE y
      LOCKUP_DETECTOR y
      HARDLOCKUP_DETECTOR y
    '';
  } ];
}
```
* start `nixos-install`

Without this patch `nix build` will fail to unpack kernel sources into `/tmp` (which is on `tmpfs` on installation).

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @Mic92

### CODE REVIEW

**Comment by xaverdh** [comment]
Maybe this should be behind a flag or something?

**Comment by misuzu** [comment]
> Maybe this should be behind a flag or something?

This should be default behavior. Installer should work under any conditions without obscure flags or environment variables.
Temporary directory can still be changed using `TMPDIR` environment variable by expert users but i don't see much reason to do so.

**Review by Mic92 — APPROVED** [review]

File: nixos/modules/installer/tools/nixos-install.sh [hunk 1]
```diff
@@ -83,8 +83,11 @@ if [[ ! -e $NIXOS_CONFIG && -z $system ]]; then
 fi
 
 # A place to drop temporary stuff.
+tmpdir="$(mktemp -d -p $mountPoint)"
 trap "rm -rf $tmpdir" EXIT
-tmpdir="$(mktemp -d)"
+
+# store temporary files on target filesystem by default
+export TMPDIR=${TMPDIR:-$tmpdir}
```
Comment (rasendubi) [inline nixos/modules/installer/tools/nixos-install.sh:90]: TMPDIR is unused?

Comment (misuzu) [reply nixos/modules/installer/tools/nixos-install.sh:90]: `TMPDIR`  is used by `nix build`.

Comment (rasendubi) [reply nixos/modules/installer/tools/nixos-install.sh:90]: ok, it's a canonical variable :) Looks good then

**Review by rasendubi — APPROVED** [review]

**Comment by rasendubi** [comment]
@GrahamcOfBorg test installer
