### PR TITLE
pythonRelaxDepsHook: remove version from pkg_name

### LINKED ISSUE #248185: pythonRelaxDepsHook fails to remove dependencies when `pythonRemoveDeps = true;`
### Describe the bug
`pythonRelaxDepsHook` is failing to remove requirements as requested by the setting of `pythonRemoveDeps`.

### Steps To Reproduce
Attempt to build
```nix
{ buildPythonPackage
, fetchFromGitHub
, pythonRelaxDepsHook
}:

buildPythonPackage rec {
  pname = "minichain";
  version = "unstable-2023-08-09";

  src = fetchFromGitHub {
    owner = "srush";
    repo = pname;
    rev = "b79ebc51bdedb836c9265eec2fcc21cd60b17327";
    hash = "sha256-h41Cdl78u92eZVYh3wbnqGmd3BcQOB2KPlOjc8Zf45Q=";
  };

  nativeBuildInputs = [ pythonRelaxDepsHook ];

  # Neither or these work:
  # pythonRemoveDeps = [ "datasets" ];
  pythonRemoveDeps = true;
}
```

Upon building:
```
...
Finished executing setuptoolsBuildPhase
installing
Executing pipInstallPhase
/build/source/dist /build/source
Processing ./minichain-0.3.1-py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement datasets (from minichain) (from versions: none)
ERROR: No matching distribution found for datasets
```

Tested on e1cf47876a2ee94302f0055892fb6e3c4433fb45. 

### Expected behavior
`pythonRelaxDepsHook` to remove the dependencies as https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#using-pythonrelaxdepshook-using-pythonrelaxdepshook specifies.

### Screenshots
n/a

### Additional context
n/a

### Notify maintainers
Latest committers to python-relax-deps-hook.sh: @delroth @thiagokokada @FRidh 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
❯   nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-153-generic, Ubuntu, 20.04.6 LTS (Focal Fossa), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(samuelainsworth): `"home-manager-22.11.tar.gz, nixgl"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by thiagokokada**
## Description of changes

Since the wheel file name is based on the package metadata instead of what we set in the derivation, if you set the version as `unstable-YYYYMMDD`, for example, the hook would silently fail. We will ignore the version now and just use a glob instead to match anything that has the package name in its path.

Fixes #248185.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/development/interpreters/python/hooks/python-relax-deps-hook.sh [hunk 1]
```diff
@@ -78,24 +78,24 @@ pythonRelaxDepsHook() {
...
 
     # We generally shouldn't have multiple wheel files, but let's be safer here
     for wheel in "$pkg_name"*".whl"; do
         @pythonInterpreter@ -m wheel unpack --dest "$unpack_dir" "$wheel"
         rm -rf "$wheel"
 
-        _pythonRelaxDeps "$metadata_file"
-        _pythonRemoveDeps "$metadata_file"
+        _pythonRelaxDeps $metadata_file
+        _pythonRemoveDeps $metadata_file
```
Comment (thiagokokada) [inline pkgs/development/interpreters/python/hooks/python-relax-deps-hook.sh:91]: The removal of quotes here is proposital since we need to expand the glob from `$metadata_file`.

Comment (FRidh) [reply pkgs/development/interpreters/python/hooks/python-relax-deps-hook.sh:91]: Best to add a comment then otherwise that get forgotten

Comment (thiagokokada) [reply pkgs/development/interpreters/python/hooks/python-relax-deps-hook.sh:92]: Done.

**Comment by thiagokokada** [comment]
Rebased to staging since this will generate a mass rebuild.

**Comment by thiagokokada** [comment]
@ofborg build ansible gitless python3Packages.python-lsp-server python3Packages.notify-py archivy

**Review by samuela — APPROVED** [review]
diff lgtm
