### PR TITLE
fetchzip: force UTF-8 compatible locale to unpack non-ASCII symbols

### LINKED ISSUE #176225: coq.src can't be built on darwin (UTF-8 file names?)
### Describe the bug

Hydra fails to fetch `coq.src` when ran on darwin, blocks even linux builds as `coq.src` is a fixed-output derivation: https://hydra.nixos.org/build/179179093/nixlog/1 (linux failure: https://hydra.nixos.org/build/179240004. )

### Steps To Reproduce

I think it's the following suspicious UTF-8 path:

```
$ nix-prefetch-url --unpack https://github.com/coq/coq/archive/V8.15.2.zip
error: cannot get archive member name: Pathname coq-8.15.2/test-suite/misc/deps/αβ/UT cannot be converted from UTF-8 to current locale.

$ nix-build -A coq.src
$ ls -1 result/test-suite/misc/deps
...
'#U03b1#U03b2'
```

### Expected behavior
darwin and linux should both be able to fetch the same tarball.

### Notify maintainers
@roconnor @thoughtpolice @vbgl @Zimmi48 

### Metadata

```console
nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.18.0, NixOS, 22.11 (Raccoon), 22.11pre382890.236cc2971ac`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.9.0pre20220530_af23d38`
 - channels(root): `"nixos"`
 - channels(slyfox): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos
```

### PR DESCRIPTION
**Pull request by trofi**
musl and darwin support UTF-8 locales without any extras. As a result
unzip can unpack UTF-8 filenames there as is. But on glibc without
locale archive presence files get mangled as:

    deps/αβ -> deps/#U03b1#U03b2

This makes `fetchzip` fixed-output derivations unstable.

Tested this change to fail in `coq.src` which was generated in system
that mangles UTF-8 symbols:

    $ nix build -f. coq.src --rebuild -L
    source> trying https://github.com/coq/coq/archive/V8.15.2.zip
    source>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    source>                                  Dload  Upload   Total   Spent    Left  Speed
    source>   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
    source> 100 8945k  100 8945k    0     0  1513k      0  0:00:05  0:00:05 --:--:-- 1989k
    source> unpacking source archive /build/V8.15.2.zip
    error: hash mismatch in fixed-output derivation '/nix/store/hrnyykm7wgw8vxisgq7hc2bg5gr0y6s8-source.drv':
             specified: sha256-h81nFqkuvZkMR7YLHy7laTq5yOhjMW+w6rYzncxvyD4=
                got:    sha256-DTspmwyD3Evl1CUmvUy2MonbLGUezvsHN3prmP9eK2I=

Note: it means that some of existing caches for fixed output
derivations become incorrect. It should not break already cached
tarballs on cache.nixos.org thus the impact should not be widespread.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/tools/archivers/unzip/setup-hook.sh [hunk 1]
```diff
@@ -1,5 +1,11 @@
...
 _tryUnzip() {
     if ! [[ "$curSrc" =~ \.zip$ ]]; then return 1; fi
-    unzip -qq "$curSrc"
+
+    # UTF-8 locale is needed for unzip on glibc to handle UTF-8 symbols:
+    #   https://github.com/NixOS/nixpkgs/issues/176225#issuecomment-1146617263
+    # Otherwise unzip unpacks escaped file names as if '-U' options was in effect.
+    #
+    # Pick en_US.UTF-8 as most possible to be present on glibc, musl and darwin.
+    LANG=en_US.UTF-8 unzip -qq "$curSrc"
```
Comment (K900) [inline pkgs/tools/archivers/unzip/setup-hook.sh:10]: C.UTF-8 maybe?

File: pkgs/build-support/fetchzip/default.nix [hunk 2]
```diff
@@ -5,7 +5,10 @@
 # (e.g. due to minor changes in the compression algorithm, or changes
 # in timestamps).
 
-{ lib, fetchurl, unzip }:
+# Have to pull in glibcLocales for unzip in setup-hook.sh to handle
+# UTF-8 aware locale:
```
Comment (SuperSandro2000) [inline pkgs/build-support/fetchzip/default.nix:9]: Please move the comment to nativeBuildInputs.

**Review by SuperSandro2000 — COMMENTED** [review]
Now we only need to find the ~10 packages which disabled tests because of that

File: pkgs/tools/archivers/unzip/setup-hook.sh (hunk 1 above)
Comment (trofi) [reply pkgs/tools/archivers/unzip/setup-hook.sh:10]: AFAIU `C.UTF-8` is not supported on macos. `musl` would probably work (not sure either).

File: pkgs/build-support/fetchzip/default.nix (hunk 2 above)
Comment (trofi) [reply pkgs/build-support/fetchzip/default.nix]: Sounds good! Moved.

**Review by SuperSandro2000 — COMMENTED** [review]
code wise this should be fine but I am not deep enough into fetchzip and reproducibility.

**Comment by trofi** [comment]
Before merging it Sandro also suggested finding up existing problematic tarballs. We can recalculate their hashes as part of this PR. I'll try to extract at least some of problematic ones.

List of suspects:
- [ ] coq.src:

**Comment by trofi** [comment]
@ofborg build coq_8_13.src coq_8_14.src coq_8_15.src eduli.src

**Comment by trofi** [comment]
@ofborg build coq_8_13.src coq_8_14.src coq_8_15.src coq_8_16.src eduli.src

**Comment by vcunat** [comment]
`glibcLocales` is over 200 MB due to containing **all** locales.  That's way too heavy for this use case, I believe.  With `.override { allLocales = false; }` we still get the locale we need with just around 3 MB.

**Comment by trofi** [comment]
> `glibcLocales` is over 200 MB due to containing **all** locales. That's way too heavy for this use case, I believe. With `.override { allLocales = false; }` we'd still get the locale we need with just around 3 MB.

Good point. Added shorter form of `glibcLocales` as:

```diff
+  glibcLocalesUtf8 =
+    if stdenv.hostPlatform.isLinux
+    then callPackage ../development/libraries/glibc/locales.nix { allLocales = false; }
+    else null;
```

and updated `fetchzip` to use it.

**Comment by SuperSandro2000** [comment]
> `glibcLocales` is over 200 MB due to containing **all** locales. That's way too heavy for this use case, I believe. With `.override { allLocales = false; }` we'd still get the locale we need with just around 3 MB.

We should reverse that default IMO. Most users are fine with C.UTF-8 plus their set locale and maybe en_US.UTF-8.

**Comment by vcunat** [comment]
Well, that's like a discussion for another topic.  For users it's mostly the NixOS `supportedLocales` option what's important.  That one is fed into this parameter, though (a bit surprisingly to me) it defaults to all locales, too.  Either way, I believe that's the main step to address.

File: pkgs/applications/science/logic/coq/default.nix [hunk 3]
```diff
@@ -43,13 +43,13 @@ let
...
+   "8.13.2".sha256     = "14d4alp35hngvga9m7cfp5d1nl62xdj0nm4811f2jjblk86gxxk4";
    "8.14.0".sha256     = "04y2z0qyvag66zanfyc3f9agvmzbn4lsr0p1l7ck6yjhqx7vbm17";
-   "8.14.1".sha256     = "0sx78pgx0qw8v7v2r32zzy3l161zipzq95iacda628girim7psnl";
+   "8.14.1".sha256     = "0xdqiabgm4lrm6d7lw544zd8xwb1cdcavsxvwwlqq6yid2rl2yli";
    "8.15.0".sha256     = "sha256:1ma76wfrpfsl72yh10w1ys2a0vi0mdc2jc79kdc8nrmxkhpw1nxx";
    "8.15.1".sha256     = "sha256:1dsa04jzkx5pw69pmxn0l55q4w88lg6fvz7clbga0bazzsfnsgd6";
-   "8.15.2".sha256     = "sha256:0gn8dz69scxnxaq6ycb3x34bjfk9wlp1y2xn8w69kg9fm4b6gkc7";
-   "8.16+rc1".sha256   = "sha256-dU+E0Mz7MVntbQIeG9I59ANBaHaXXSrjCRdoqZ5TO60=";
+   "8.15.2".sha256     = "sha256:0qibbvzrhsvs6w3zpkhyclndp29jnr6bs9i5skjlpp431jdjjfqd";
+   "8.16+rc1".sha256   = "sha256-hmZQ6rFIOZJwnAh23nKScJ3Nn+xqDRn5q2Tn82igpYE=";
```
Comment (Zimmi48) [inline pkgs/applications/science/logic/coq/default.nix:52]: The utf8 file names were introduced in Coq 8.7 (https://github.com/coq/coq/pull/1041), so I'm expecting that all the `sha256` since 8.7.0 have to be recomputed. The patch-level versions that are not the latest are not exposed (they are only accessible by overriding the derivation) but they should still be fixed or removed (preferably the former).

Comment (trofi) [reply pkgs/applications/science/logic/coq/default.nix]: Sounds good. Updated rest of hashes. Only 8.13.0+ were broken possibly by 9ffd16b3850536094ca36bc31520bb15a6d5a9ef. A bit of investigation below:

Extracted broken ones with the following hack:

```diff
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -33270,6 +33270,7 @@ with pkgs;
     coqPackages_8_15 coq_8_15
     coqPackages_8_16 coq_8_16
     coqPackages      coq
+    mkCoq
   ;

   coq2html = callPackage ../tools/typesetting/coq2html { };
diff --git a/pkgs/top-level/coq-packages.nix b/pkgs/top-level/coq-packages.nix
index 91894bfaa9e..332a6d2bcb3 100644
--- a/pkgs/top-level/coq-packages.nix
+++ b/pkgs/top-level/coq-packages.nix
@@ -167,5 +167,5 @@ in rec {
   coqPackages_8_16 = mkCoqPackages coq_8_16;
   coqPackages = recurseIntoAttrs coqPackages_8_15;
   coq = coqPackages.coq;
-
+  inherit mkCoq;
 }
```

```
$ for v in 8.5pl1 8.5pl2 8.5pl3 8.6.0 8.6.0 8.6.1 8.7.0 8.7.1 8.7.2 8.8.0 8.8.1 8.8.2 8.9.0 8.9.1 8.10.0 8.10.1 8.10.2 8.11.0 8.11.1 8.11.2 8.12.0 8.12.1 8.12.2 8.13.0 8.13.1 8.13.2 8.14.0 8.14.1 8.15.0 8.15.1 8.15.2 8.16+rc1; do echo $v; nix build --impure --expr 'with import ./. {}; (mkCoq "'$v'").src'; nix build --impure --expr 'with import ./. {}; (mkCoq "'$v'").src' --rebuild -L; done
8.5pl1
```

Surprisingly (or not so surprisingly) breakage started only from `8.13.0` (UTF-8 files do present in older tarballs).

Unpatched `fetchzip` indeed already fails to unpack existing `8.12.0` (patches one accepts the checksum):

```
$ nix build --no-link -f. -f. coq_8_12.src --rebuild
error: hash mismatch in fixed-output derivation '/nix/store/0gvwnzj4dlx9bc78dj08ynh0d0l6gqcr-source.drv':
         specified: sha256-VnSw25bINfpJUkwulJZKtZUXVbYBYF0JhvimAapj+qE=
            got:    sha256-p+ZNPssu78SObNSPo/2N92qTvl72MvXbx00wUoggth4=
```

This means `unzip` (?) behavior changed somewhat recently (or packaging was done on non-glibc). Trying to bisect:

```
# commit adding 8.12.0 to nixpkgs:
$ git checkout b8dfca143c5b9e632530720ab472bd54d9d21137
$ nix build --no-link -f. -f. coq_8_12.src --rebuild
# OK!

$ git bisect start origin/master b8dfca143c5b9e632530720ab472bd54d9d21137
$ git bisect run nix build --no-link -f. -f. coq_8_12.src --rebuild

commit 9ffd16b3850536094ca36bc31520bb15a6d5a9ef
Date:   Fri Aug 28 23:05:46 2020 +0200

    coqPackages: refactor
```

Looks like 9ffd16b3850536094ca36bc31520bb15a6d5a9ef did change from `fetchFromGitHub` (`.tar.gz`) to `fetchzip` (`.zip`) and introduced the discrepancy.

**Comment by SuperSandro2000** [comment]
Doing a PR right now to fix that. We can discuss this further there.

#177318

**Comment by trofi** [comment]
> pkgsCross.aarch64-android.stdenv

Good catch! I always wondered why we defined it non-null on musl (where it does not break, but builds unused glibc and locales). Proposed the fix as: https://github.com/NixOS/nixpkgs/pull/181384
