### PR TITLE
wrapGAppsHook: Fix #78803

### LINKED ISSUE #78803: wrapGAppsHook: make double wrapping workaround work again
**Describe the bug**
In https://github.com/NixOS/nixpkgs/pull/75465 I updated expressions like

###### Before
```nix
makeWrapperArgs = [
  "\${gappsWrapperArgs[@]}"
];

makeWrapperArgs = [
  "\${gappsWrapperArgs[@]}"
];
```

###### After
```nix
preFixup = ''
  makeWrapperArgs+=("''${gappsWrapperArgs[@]}")
'';

preFixup = ''
  qtWrapperArgs+=("''${gappsWrapperArgs[@]}")
'';
```

This was to fix https://github.com/NixOS/nixpkgs/issues/75443, what was done before was dangerous.

However the example doesn't produce complete wrappers, you'll notice `gappsWrapperArgs` is missing some important arguments.

Here's an example wrapper:
```
#! /nix/store/86ap9r7vjvcy44kskgms1yc1wxdsiq2z-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/bzvpdbzdy3a1qba8f9ynrzyz811c10pp-python3-3.7.6/bin:/nix/store/k620kyb8bpm2c0bisaaj01mz0caisc3l-lollypop-1.2.16/bin:/nix/store/5b2fz69b6awzqsjd3120b096sxh3jyw9-cairo-1.16.0-dev/bin:/nix/store/jznzbpm5icg0znzpjdbdd8b4a0nafqlf-freetype-2.10.1-dev/bin:/nix/store/qyv9k98syrc82r6805vnxnhw0rv6vlqp-bzip2-1.0.6.0.1-bin/bin:/nix/store/daykmk7a0r0qcm2g1y24asgzckl9hz67-libpng-apng-1.6.37-dev/bin:/nix/store/yxy8v5yhzd6jy6dfm4c19p1iv0mm5pmn-fontconfig-2.12.6-bin/bin:/nix/store/gy2lah8igrb83hnf55krg9il59x9v52b-expat-2.2.8-dev/bin:/nix/store/g59xwl0sddrb7pp8sz2fzsc51giwcj2h-glib-2.62.4-dev/bin:/nix/store/7f9bh6wv0a7sss0kh3nx7w3w779sysvy-gettext-0.20.1/bin:/nix/store/33lx4dinpf2phh1d95lxxd6s4jjk1qnw-glib-2.62.4-bin/bin:/nix/store/y88s9xjbf5i47nbympmpwyssj1l422q1-glib-2.62.4/bin:/nix/store/j82jzi20ri2s0bwr37zcjg2maz7mzm7m-python3.7-youtube-dl-2019.12.25/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
export GIO_EXTRA_MODULES='/nix/store/5v8xyqfhjy29dzg7m1mx67cvl86005d2-dconf-0.34.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
export GIO_EXTRA_MODULES='/nix/store/5v8xyqfhjy29dzg7m1mx67cvl86005d2-dconf-0.34.0-lib/lib/gio/modules'${GIO_EXTRA_MODULES:+':'}$GIO_EXTRA_MODULES
exec -a "$0" "/nix/store/k620kyb8bpm2c0bisaaj01mz0caisc3l-lollypop-1.2.16/bin/.lollypop-wrapped"  "$@"
```

it only has arguments fed in from this function:
https://github.com/NixOS/nixpkgs/blob/bb29376ce6847348f3b24ea8230e318c542b089d/pkgs/build-support/setup-hooks/wrap-gapps-hook.sh#L4

**Why it happens**
It's because of how `wrapGAppsHook` is written.
This works as expected and is documented as such in `wrapQtAppsHook` because it adds to the environment variables with [`addEnvHooks`](https://github.com/NixOS/nixpkgs/blob/bb29376ce6847348f3b24ea8230e318c542b089d/pkgs/development/libraries/qt-5/hooks/wrap-qt-apps-hook.sh#L34) and I guess [`preFixupPhases`](https://github.com/NixOS/nixpkgs/blob/bb29376ce6847348f3b24ea8230e318c542b089d/pkgs/development/libraries/qt-5/hooks/wrap-qt-apps-hook.sh#L65)

Noticed in https://github.com/NixOS/nixpkgs/pull/76283.

I'm not sure if I'm remembering this correctly, perhaps there's just an easier solution.

### PR DESCRIPTION
**Pull request by worldofpeace**
Add to gappsWrapperArgs in preFixupPhases.

###### Motivation for this change
Fix https://github.com/NixOS/nixpkgs/issues/78803 https://github.com/NixOS/nixpkgs/issues/75844

Test with packages in https://github.com/NixOS/nixpkgs/commit/abe3475df8fd133045cd01fb14e0d7013cecf66e

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/build-support/setup-hooks/wrap-gapps-hook.sh [hunk 1]
```diff
@@ -2,13 +2,43 @@
 gappsWrapperArgs=()
 
 find_gio_modules() {
-    if [ -d "$1/lib/gio/modules" ] && [ -n "$(ls -A "$1/lib/gio/modules")" ] ; then
+    if [ -d "$1"/lib/gio/modules ] && [ -n "$(ls -A $1/lib/gio/modules)" ] ; then
```
Comment (jtojnar) [inline pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: Why drop the quoting?

Comment (worldofpeace) [reply pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: Hmm, I think it could have either been `shellcheck` or `shellfmt` that did this.

Comment (worldofpeace) [reply pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: and wouldn't `"$(ls -A "$1/lib/gio/modules")"` be too much quoting?

Comment (worldofpeace) [reply pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: nope
```
In pkgs/build-support/setup-hooks/wrap-gapps-hook.sh line 5:
    if [ -d "$1/lib/gio/modules" ] && [ -n "$(ls -A $1/lib/gio/modules)" ] ; then
                                                    ^-- SC2086: Double quote to prevent globbing and word splitting.
```

weird, will fix.

**Comment by jtojnar** [comment]
Possibly also fixes https://github.com/NixOS/nixpkgs/issues/57638?

**Comment by worldofpeace** [comment]
> Possibly also fixes #57638?

I tried to add a function to help with https://github.com/NixOS/nixpkgs/issues/57638, but I still saw duplicates (usually 2).

**Comment by jtojnar** [comment]
Hmm, we would probably need to emulate `qtUnseenHostPath`.

**Comment by worldofpeace** [comment]
> Hmm, we would probably need to emulate `qtUnseenHostPath`.

I tried this exactly, at least I think I did.

**Comment by jtojnar** [comment]
Anyway, using `preFixupPhases` looks fine to me for #78803 within the limitations of the current builder.

Not sure why are you removing the prefix check, though.

**Comment by worldofpeace** [comment]
@jtojnar Should all replace `$prefix` with `${prefix:?}` throughout?

**Comment by jtojnar** [comment]
Only the first use should include `:?` since if the variable does not exist, the execution will stop there.

**Comment by worldofpeace** [comment]
> Only the first use should include `:?` since if the variable does not exist, the execution will stop there.

Fixed that.

**Comment by worldofpeace** [comment]
We're now on staging.

**Comment by worldofpeace** [comment]
backported to 20.03 in e8e569ce79897885fe9f59dd164413f9b7298c4c (staging-20.03)

**Comment by volth** [comment]
This broke `nm-applet` https://github.com/NixOS/nixpkgs/issues/84959
