### PR TITLE
Fix cycle detected in Darwin->Linux cross GCC

### LINKED ISSUE #88213: cycle detected in Darwin->Linux cross GCC
**Describe the bug**
When building a GCC for cross compiling from Darwin to Linux, the build fails with a "cycle detected" error.

**To Reproduce**

1. Check out Nixpkgs staging on a Darwin box.
2. `nix-build . --arg crossSystem '(import ./. {}).lib.systems.examples.gnu64' -A stdenv.cc`

**Expected behavior**
GCC compiles successfully, and can be used to produce Linux binaries.

**Screenshots**
```
cycle detected in the references of '/nix/store/51hmxfsm1s1089vcl6wxsm1vb6r0kar8-x86_64-unknown-linux-gnu-stage-final-gcc-debug-9.3.0' from '/nix/store/73vjzvxk0430rn4njhv09jnmqrz99h26-x86_64-unknown-linux-gnu-stage-final-gcc-debug-9.3.0-lib'
```

**Additional context**
The cycle:

* `51hmxfsm1s1089vcl6wxsm1vb6r0kar8-x86_64-unknown-linux-gnu-stage-final-gcc-debug-9.3.0/nix-support/propagated-build-inputs` includes `73vjzvxk0430rn4njhv09jnmqrz99h26-x86_64-unknown-linux-gnu-stage-final-gcc-debug-9.3.0-lib`
* `73vjzvxk0430rn4njhv09jnmqrz99h26-x86_64-unknown-linux-gnu-stage-final-gcc-debug-9.3.0-lib/x86_64-unknown-linux-gnu/lib/lib{asan,tsan,lsan,ubsan}.so*` refer to `51hmxfsm1s1089vcl6wxsm1vb6r0kar8-x86_64-unknown-linux-gnu-stage-final-gcc-debug-9.3.0`

**Notify maintainers**
@Synthetica9 

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"darwin, home-manager, nixpkgs-20.09pre221814.10100a97c89"`
 - channels(gaelan): `"darwin, home-manager, nixpkgs-20.09pre221814.10100a97c89"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

Channels are irrelevant, I'm using a checkout of staging.

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - gcc-unwrapped
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by matthewbauer**
Fixes #88213

### CODE REVIEW

**Comment by Gaelan** [comment]
@matthewbauer thanks for picking this up

**Comment by jonringer** [comment]
umm, was the right branch pushed @matthewbauer ?

**Comment by jonringer** [comment]
The commit you pushed contains a lot more than just your changes https://github.com/NixOS/nixpkgs/commit/25ac498482621dec5ed6f551dc1436bdc4812de8

**Comment by Mic92** [comment]
I think he merged master into staging.

**Comment by Mic92** [comment]
Which should be fine.

**Comment by jonringer** [comment]
it will still make git history awkward, and might cause some issues with git bisect

**Comment by jonringer** [comment]
plus, you generally want to push the changes from master to staging-next, then staging-next into staging, if you're trying to update the staging branches.

**Comment by Mic92** [comment]
I thought stuff goes to staging first before it goes to staging-next.

**Comment by jonringer** [comment]
if you want changes from master to be pushed to staging, generally you push them first to staging-next

**Comment by jonringer** [comment]
I can't find the original post, @FRidh would know better

**Comment by matthewbauer** [comment]
Oh ok, so origin/master should merge into origin/staging-next first then origin/staging?

**Comment by jonringer** [comment]
it does both

staging -> staging-next -> master: to bring changes from staging to master, but allowing for stabilization

master -> staging-next -> staging: to prevent staging and staging-next from diverging from master significantly (this is usually done after staging-next PR is completed, because it should have changes in master already in it)

master -> staging-next: done frequently in `staging-next` PR/stabilization period So that changes in master can be applied and rebuilt off of changes from staging.

**Comment by jonringer** [comment]
Like I said before, this probably won't affect "derivations" too much, but it could cause some awkwardness with `git bisect` creating "false positives" due to messed up git history. Also, it might cause a large amount of merge conflicts for people working on `staging-next`

**Comment by jonringer** [comment]
at the very least, the PR should have been open longer than 100s before getting merged

File: pkgs/development/compilers/gcc/builder.sh [hunk 1]
```diff
@@ -241,7 +241,7 @@ postInstall() {
     # More dependencies with the previous gcc or some libs (gccbug stores the build command line)
     rm -rf $out/bin/gccbug
 
-    if type "patchelf"; then
+    if [[ buildConfig == *"linux"* ]]; then
```
Comment (andersk) [inline pkgs/development/compilers/gcc/builder.sh:244]: `[[ buildConfig == *"linux"* ]]` is always false since `linux` is not a substring of the literal string `buildConfig`. Did you mean for this to be a variable or something?
