### PR TITLE
NixOS `apply` script

### LINKED ISSUE #82851: NixOS: switch-to-configuration script does not correctly add a boot entry when executed standalone
**Describe the bug**

Activating a NixOS configuration not through `nixos-rebuild switch`, but through `${(pkgs.nixos ./configuration.nix).toplevel}/bin/switch-to-configuration switch` does activate the configuration correctly, but does not correctly add a boot entry. 

The help text of the `switch-to-configuration` script states that `switch` should make this configuration the boot default. 

The concrete symptoms differ between the different boot loaders:
- For GRUB, the default boot is updated, but no boot entries for older generations are created.
- For systemd boot, the new generation is not even accessible through the default boot entry.

**To Reproduce**
Steps to reproduce the behavior on a UEFI system:
1. `cd /etc/nixos/`
2. Change something in `configuration.nix`
2. `sudo nix-build -E "with import <nixpkgs> { }; (nixos ./configuration.nix).toplevel"`
3. `result/bin/switch-to-configuration switch`
4. Observe that the change has been applied
5. Reboot
6. Observe that the change has been reverted

**Expected behavior**
The `switch-to-configuration` script should work in a standalone manner, and its help text should match its behaviour.

**Additional context**
The grub and systemd boot scripts in `nixos/modules/system/boot/loader/` assume that the target generation has been addded to `/nix/var/nix/profiles/system`. This happens when I run `nixos-rebuild switch`, but is not a part of the `switch-to-configuration` script.

A workaround is to run `nix-env -p /nix/var/nix/profiles/system --set ./result` before running `switch-to-configuration`.

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.24, NixOS, 19.09pre-git (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-19.09.2229.d7843c8add6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### LINKED ISSUE #258974: Reduce target host ssh roundtrip by moving `systemd-run` logic out of `nixos-rebuild`
When using `--target-host`, this is an extra ssh roundtrip that could be avoided if we make `switch-to-configuration` responsible for re-execing itself in `systemd-run` - ie move all the new logic into that command (or a custom wrapper for it).

_Originally posted by @roberth in https://github.com/NixOS/nixpkgs/pull/258571#discussion_r1345481867_

### LINKED ISSUE #266290: NixOS `apply` script [refactor + feature]
**Project description**

_Add an "apply" script to NixOS._

Audience:
 - deployment tool developers
 - power users (e.g. `nix run .#.nixosConfigurations.foo.config.system.build.apply`).

Benefits:

- Reduce the number of `--target-host` ssh roundtrips and `sudo` invocations (ie solve https://github.com/NixOS/nixpkgs/issues/258974)
- Provide a good interface for deployment tools that handle evaluation and build for their user.
  - `nixos-rebuild` is not suitable as a backend for most such tools because it can't take a toplevel path. Most `nixos-rebuild` functionality is redundant.
  - `switch-to-configuration` does not manage the profile. Changing this script breaks too much.
    That said, we have some currently incorrect documentation claiming that `switch-to-configuration switch` is equivalanet to `nixos-rebuild switch`.

Functionality:

Manage the profile link and initiate actions that need to run on the target host.

**Responsibilities of NixOS scripts**

- `nixos-rebuild`: UI, build and remote deployment. Specifically:
  - building a new Nix that matches the configuration
  - evaluation and realisation of the configuration
  - ssh to the target machine (if --target-host is specified)
- `apply`: Exactly the things that need to be done on the target host
  - set the profile to new path
    - or perform profile rollback, noting the "new" path
  - run the action safely and reproducibly in `systemd-run` if available
  - initiating the switch
  - initiating the installation of the bootloader
- `switch-to-configuration`:
   - the grunt work of actually switch and installing the bootloader

**Callers of the apply script**

The new apply script will be called and packaged in multiple ways:

- The `nixos-rebuild` package: For applying configurations that pre-date the toplevel/bin/apply script
- `toplevel/bin/apply`: The normal script for applying configurations. The script is copied into toplevel because it needs to hardcode the toplevel path. Deployment tools may call this directly.
- `system.build.apply`: Same script but not incorporated into toplevel in order to GC the activation stuff after activation has run (it's a tradeoff). Very optional to even use this.

**Interface**

- Similar to `switch-to-configuration`.
- Extra: a parameter that allows `pathToConfig` to be specified, which is useful when reusing the script implementation for deploying legacy (non-`apply`) configurations.
- Extra: default action. `switch`? This makes the command nicer to use when called directly by a user. Maybe the default action should be switch + timeout + rollback? At least for configurations that have such functionality. That's TBD, so perhaps the default should be postponed until that's done.

Out of scope: if we'll have a `nixos` command, it could have an `apply` subcommand that has `nixos-rebuild`-like functionality evaluates and builds before deferring to an `apply` script that has a very similar interface. For me this is reason to think about `apply` as a somewhat nice interface for users, because then it will be feasible to have an analogous interface in the `nixos apply` command.

**TODO**

- [ ] Make `nixos-rebuild` not write a result symlink. It performs a non-permanent deployment - not to be confused with `build-vm`, which is for testing "in isolation" (somewhat).
- [x] Write a test for `--target-host`. See `nixops_unstable` test for example of this kind of thing. Add it to `nixos-rebuild.tests`.
- [ ] Implement the apply script outside of `toplevel` and make `nixos-rebuild` use it in order to perform the steps after build. This includes reading the profile when it's a rollback instead of a new toplevel, as well as setting the new profile regardless of rollback vs new.
  - [ ] Clean up the control flow in a prep PR first?
- [ ] Add `apply` to `toplevel/bin`. Make `nixos-rebuild` call it when it knows that the script exists (ie not a rollback), or come up with an `sh` script that defers this compatibility logic to the remote?
- [ ] Update the manual. Most occurrences of `switch-to-configuration` should probably be changed to `apply`.

### PR DESCRIPTION
**Pull request by roberth**
## Description of changes

As proposed in https://github.com/NixOS/nixpkgs/issues/266290:

Introduce an "apply" script to NixOS, aimed at improving deployment processes for developers and power users. The script reduces SSH roundtrips and sudo invocations by refactoring deployment logic, moving systemd-run logic out of nixos-rebuild, and simplifying the management of the profile and actions on the target host. This change addresses limitations in nixos-rebuild and offers a more efficient backend for deployment tools

Observations and deviations from the original proposal:

- > initiating the installation of the bootloader
  
  This is already done by `switch-to-configuration`, and that's ok.
  
- > The new apply script will be called and packaged in multiple ways:
  > 
  >     * The `nixos-rebuild` package: For applying configurations that pre-date the toplevel/bin/apply script
  
  I have avoided this, to keep the new code path simple, devoid of conditional `ssh` calls.
  The equivalent code in `nixos-rebuild` is ok to go stale, because it is only needed for old releases anyway. We can remove that in, say, early 2026, when everyone has had more than enough time to migrate away from the unsupported releases.

- > `system.build.apply` [...] very optional

  Not done yet, and that's ok.

- > **Interface**
- > - Extra parameter that allows `pathToConfig` to be specified

  Unnecessarily complicated, and very low value once `apply` can be assumed to exist in, e.g. in January

- > - Extra: default action [...] TBD [...] should be postponed

  Not needed in this PR; feature creep; postponing

TODO:

- [x] update documentation about `switch-to-configuration switch` to reflect reality (of even before this PR), and/or point to `apply` instead.
- [x] release note

## Context

- Closes https://github.com/NixOS/nixpkgs/issues/266290
- Closes  #82851
- Closes https://github.com/NixOS/nixpkgs/issues/258974

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by roberth** [comment]
@ofborg test nixos-installer.simple
@ofborg test nixos-rebuild-install-bootloader
@ofborg test nixos-rebuild-specialisations
@ofborg test nixos-rebuild-specialisations-legacy
@ofborg test nixos-rebuild-target-host
@ofborg test nixos-rebuild-target-host-legacy
@ofborg test non-switchable-system 
@ofborg build nixosTests.apply
@ofborg test switchTest
@ofborg test switchTestNg

**Review by nikstur — APPROVED** [review]
Looks really good. Although I must admit I don't fully understand all the bash magic going on I'm pretty confident that this does the right thing.

**Comment by roberth** [comment]
Thanks for the review @nikstur :heart:

**Comment by bjornfor** [comment]
@roberth: Thank you for this PR! :tada:

**Comment by nikstur** [comment]
This will make testing generations (esp. for bootloader installers) soooo much easier!

**Comment by roberth** [comment]
That somehow reminded me that we could make this work with `nix run` now.
- https://github.com/NixOS/nixpkgs/pull/352374

**Comment by ElvishJerricco** [comment]
This has broken `nixos-rebuild switch` so that it no longer updates the profile, which has bad consequences including not updating the systemd-boot menu with new generations.

Considering this is a significant change to a critical nixos component, this probably shouldn't have been merged during 24.11 feature freeze.

**Comment by amnnku** [comment]
> This has broken `nixos-rebuild switch` so that it no longer updates the profile, which has bad consequences including not updating the systemd-boot menu with new generations.
> 
> Considering this is a significant change to a critical nixos component, this probably shouldn't have been merged during 24.11 feature freeze.

:-( is there a current workaround anyone has found? Been driving me mad the last day or so trying to figure out what I'd done wrong :)

File: pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh [hunk 1]
```diff
@@ -841,12 +840,56 @@ else # [ -n "$rollback" ]
...
+        cmd+=("--install-bootloader")
+    fi
+    targetHostSudoCmd "${cmd[@]}"
+elif [[ "$action" = switch || "$action" = boot || "$action" = test || "$action" = dry-activate ]]; then
+    # Legacy, without apply script, NixOS < 24.11
+
+    if [[ "$action" = switch || "$action" = boot ]]; then
+        if [[ -z "$rollback" ]]; then
+            : # We've already switched it so that hasApplyScript would check the right $pathToConfig
+        else
```
Comment (xaverdh) [inline pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh:887]: maybe the two branches here should be swapped?

Comment (roberth) [reply pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh:887]: I think you're right. I've done some testing yesterday, and I couldn't reproduce it with a VM using the new workflow, and indeed this mistake would only show any real effect on "legacy" configs without `apply`, because `apply switch` always sets the profile.
I then got bogged down in https://github.com/NixOS/nix/issues/11791. I might just have to skip that issue, even though it seems to add minutes to the test.
