### PR TITLE
Fix `separate-debug-info` with lld

### LINKED ISSUE #22840: Enhance separate-debug-info.sh to be compatible compatible with clang
## Issue description

As seen in this build job https://travis-ci.org/NixOS/nixpkgs/jobs/201821348 (relevant section reproduced below for archival), `separate-debug-info.sh` fails on clang, which is unfortunate for packages that would otherwise be portable between linux and osx.

### Steps to reproduce

Include `separate-debug-info.sh` into a osx-enabled build, as seen here: https://github.com/NixOS/nixpkgs/pull/22824/commits/53985c5529fd2b19bd1a76887f05a5c1197dc2da

### Faillog

```
===> LD
clang-3.7: warning: argument unused during compilation: '-Wa,--compress-debug-sections'
ld: unknown option: --compress-debug-sections=zlib
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
```

### PR DESCRIPTION
**Pull request by rrbutani**
###### Description of changes

This PR ultimately solves the same problem as #146275 but takes a slightly different approach: here we get `lld` to emit SHA1 hashes instead of relaxing the length requirement `separate-debug-info.sh` has.

This approach (and this PR) is _complementary_ to #146275's but if #146275 is merged we may want to switch back to letting `lld`/`mold`/etc use faster hashes if we wish to prioritize build time (link speed) over the (low) potential for collisions.
The commit messages within and #146275 have more discussion about this.

This PR also goes and:
  - re-enables `separateDebugInfo` for derivations using a `useLLVM` based stdenv
  - removes the workaround Firefox was using for `separate-debug-info.sh` being unhappy with `lld`'s shorter hashes

These fixes are applicable with #146275 _or_ the first commit of this PR (or both).

---

h/t to [@teh](https://github.com/NixOS/nixpkgs/commit/b86e62d30d4635ef3294d9c1c308f9c8b0061045#commitcomment-77916294) and [@symphorien](https://github.com/NixOS/nixpkgs/pull/146275#issuecomment-1445167145)

Closes #22840

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Review by lovesegfault — APPROVED** [review]

**Review by symphorien — APPROVED** [review]
sl built with pkgsLLVM.stdenv and separate debug info and firefox both have working debuginfo in gdb.

File: pkgs/build-support/bintools-wrapper/ld-wrapper.sh [hunk 1]
```diff
@@ -232,8 +232,11 @@ fi
 
 # Only add --build-id if this is a final link. FIXME: should build gcc
 # with --enable-linker-build-id instead?
+#
+# Note: `lld` interprets `--build-id` to mean `--build-id=fast`; GNU ld defaults
+# to SHA1.
 if [ "$NIX_SET_BUILD_ID_@suffixSalt@" = 1 ] && ! (( "$relocatable" )); then
-    extraAfter+=(--build-id)
+    extraAfter+=(--build-id="${NIX_BUILD_ID_STYLE:-sha1}")
```
Comment (SuperSandro2000) [inline pkgs/build-support/bintools-wrapper/ld-wrapper.sh:239]: Is there some ld-wrapper doc we should update with NIX_BUILD_ID_STYLE?

Comment (rrbutani) [reply pkgs/build-support/bintools-wrapper/ld-wrapper.sh:239]: Oh good point!

Maybe the [`separateDebugInfo` section in the manual](https://nixos.org/manual/nixpkgs/stable/#stdenv-separateDebugInfo) is a good place for this? It actually _already_ talks about how build-id is a SHA1 hash :slightly_smiling_face:

Comment (mweinelt) [reply pkgs/build-support/bintools-wrapper/ld-wrapper.sh:239]: Please write some documentation in a follow-up PR!
