### PR TITLE
prefetch-npm-deps: add support for npm alias schema in version spec

### LINKED ISSUE #266825: npm Prefetcher hangs with old lockfiles
### Describe the bug

Lily and I talked about this in Matrix, this is the requested issue.
Basically it all narrows down to this package lock: https://github.com/dasJ/broken-npm-test

### Steps To Reproduce
1. Build it
2. See it hangs forever
3. Update lock
4. See it works

### Expected behavior

It should either give an error or just work.

### Additional context

> frontend-npm-deps> [2023-11-10T23:15:37Z DEBUG isahc::handler] Could not resolve host: 16.0.0-beta.8

https://github.com/dasJ/broken-npm-test/blob/8c6d8ed9b180a66a81b133f68bf467e12bcbe3be/package-lock.json#L2817

https://docs.npmjs.com/cli/v10/using-npm/package-spec#aliases

If it helps narrowing the npm version down, the package-lock.json was created in September of 2020 and was last changed in September of 2021.

### PR DESCRIPTION
**Pull request by reinismu**
Before it would try to do Http request against "npm:string-width@4.2.3" which would fail after 15 minutes. While at it I improved errors.

### CODE REVIEW

File: pkgs/build-support/node/fetch-npm-deps/src/parse/lock.rs [hunk 1]
```diff
@@ -215,30 +215,41 @@ fn to_new_packages(
...
-                        }
-
-                        new_url.set_fragment(v.fragment());
-
-                        UrlOrString::Url(new_url)
-                    };
+        let resolved = match package.resolved {
+            Some(UrlOrString::Url(ref url)) => Some(url.clone()),
+            _ => None,
+        };
```
Comment (lilyinstarlight) [inline pkgs/build-support/node/fetch-npm-deps/src/parse/lock.rs:222]:
```suggestion
```

File: pkgs/build-support/node/fetch-npm-deps/src/parse/lock.rs [hunk 2]
```diff
@@ -215,30 +215,41 @@ fn to_new_packages(
...
 
-                    break;
+        if let UrlOrString::Url(v) = &package.version {
+            if v.scheme() == "npm" {
+                if let Some(resolved) = &resolved {
```
Comment (lilyinstarlight) [inline pkgs/build-support/node/fetch-npm-deps/src/parse/lock.rs:225]:
```suggestion
                if let Some(UrlOrString::Url(ref url)) = &package.resolved {
```

**Review by lilyinstarlight — COMMENTED** [review]
Apologies for taking so long to get back to this. This broadly looks good thank you!

Can you update your commit message to fit those specified by [`CONTRIBUTING.md`](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md), e.g. `prefetch-npm-deps: add support for npm alias schema in version spec`

I left one small suggestion below, but otherwise this looks fine and I appreciate you adding a test case!

**Review by lilyinstarlight — APPROVED** [review]
This looks lovely now, thank you for the contribution!

Edit: I also added backport labels since this seems to be a completely backwards-compatible change (given these deps failed before now)
