### PR TITLE
switch-to-configuration-ng: various mount-related fixes

### LINKED ISSUE #343975: switch-to-configuration-ng: Tries to stop transient mount units
### Describe the bug

Discovered in https://github.com/NixOS/nixpkgs/pull/343709
it seems that the new switch-to-configuration-ng will try to stop mount units that are not defined by NixOS. This is bad because it can break all kinds of desktop automount, nix-store mounts
or mounts generated by other services i.e. docker or zfs snapshots

### Steps To Reproduce

```
$ nix-build ./nixos/release.nix -A tests.nix-upgrade 
```

### Expected behavior

switch-to-configuration-ng should respect the IgnoreOnIsolate or Transient property of a unit and not stop those.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### LINKED ISSUE #398523: nixos/systemd-automounts: might cause orphaned mount units -> inhibiting switch generations
### Nixpkgs version

- Stable (24.11)

### Describe the bug

I tried to add a mount point to a samba share, I had some wrong config in there and samba/cifs failed to apply it. Thatfor I tried to revert back the config and not have that mountpoint at all.

But somehow the *.mount unit gets orphaned and I get this error on generation switch:
```
restarting sysinit-reactivation.target
Error: Failed to get unit tomb.mount

Caused by:
    Unit tomb.mount not loaded.
```

A reboot fixes this issue - obviously :)

### Steps to reproduce

1. example config that causes my problem
_notice that noatime and nodiratime are no valid options for a cifs mount._

```
  fileSystems."/tomb" = {
    device = "//nax/tomb";
    fsType = "cifs";
    options = [ "x-systemd.automount,noatime,nodiratime,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s, noauto, user=user,credentials=/home/user/.smb-secrets,workgroup=lan,uid=1000,gid=100"  ];
  };
```

2. apply the config via rebuild
3. Now you either remove that config or you just remove noatime,nodiratime and get different results:

if you've removed the config, your output will be:

```
restarting sysinit-reactivation.target
Error: Failed to get unit tomb.mount

Caused by:
    Unit tomb.mount not loaded.
```
```
↳ systemctl list-units  | grep tomb
14.04.2025 10:55:12

● tomb.automount                                                                                                                              not-found active waiting   tomb.automount
```

if you've removed the options noatime,nodiratime, your output will be:

```
restarting sysinit-reactivation.target
Error: Failed to open unit file /nix/store/w4swyfcxj7i8ak2kdv2dpwd4nmlh9vin-nixos-system-nixtop-desktop-24.11.20250412.26d499f/etc/systemd/system/tomb.mount

Caused by:
    No such file or directory (os error 2)
```
```
↳ systemctl list-units  | grep tomb
14.04.2025 10:57:00

  tomb.automount                                                                                                                              loaded active waiting   tomb.automount

```

### Expected behaviour

the generation switch is expected to apply the config with the changed or removed (auto)mount unit

### Screenshots

_No response_

### Relevant log output

```console

```

### Additional context

I had a quick chat with @ElvishJerricco on matrix, his thoughts on this:

> The code we use to switch between generations without rebooting is really complicated
> and has a lot of dedicated special handling for different systemd unit types
> it sounds like it's just not considering automounts robustly

### System metadata

this path will be fetched (0.02 MiB download, 0.06 MiB unpacked):
  /nix/store/szfi0xd0cwdaldhkp8vlgi7jfv662nmd-stdenv-linux
copying path '/nix/store/szfi0xd0cwdaldhkp8vlgi7jfv662nmd-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.87, NixOS, 24.11 (Vicuna), 24.11.20250412.26d499f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.14`
 - nixpkgs: `/nix/store/hzaj4d6ari2wq2cbg1j60n9zw42gnshy-source`

### Notify maintainers

@ElvishJerricco

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+label%3A%226.topic%3A+nixos%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by jmbaur**
Fixes #389928
Fixes #343975
Fixes #398523

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [x] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [ ] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jmbaur** [comment]
@ofborg test switchTest

File: pkgs/by-name/sw/switch-to-configuration-ng/src/src/main.rs [hunk 1]
```diff
@@ -219,29 +219,36 @@ fn get_active_units(
...
+                    Duration::from_millis(5000),
+                );
+
+                if following.is_empty() && state != "inactive" {
+                    Some((
+                        id,
+                        UnitState {
+                            state,
+                            substate,
+                            proxy,
```
Comment (ElvishJerricco) [inline pkgs/by-name/sw/switch-to-configuration-ng/src/src/main.rs:242]: I wonder if it's a good idea to store this proxy or if we should just extract the info we want here immediately and store that.

Comment (jmbaur) [reply pkgs/by-name/sw/switch-to-configuration-ng/src/src/main.rs:242]: I implemented it like that originally, then did a small refactor to just pass around the proxy, as this felt nicer since the proxy can be used to do any dbus-related things on that unit later on. I'm cool with either though.

Comment (ElvishJerricco) [reply pkgs/by-name/sw/switch-to-configuration-ng/src/src/main.rs:242]: As long as there's no resource penalty then sure. I'm not familiar enough with dbus to know if having a whack ton of objects laying around can be problematic.

**Review by Luflosi — APPROVED** [review]

**Review by ElvishJerricco — APPROVED** [review]
