### PR TITLE
wafHook: always enable parallel building

### LINKED ISSUE #136368: wafHook does not correctly honor NIX_BUILD_CORES
### Describe the bug
`wafHook` does not correctly honor `NIX_BUILD_CORES`. `wafHook` assumes `waf`, like `make`,  builds single jobs, unless parallel build is enabled with `-j <NUM>`. However, `waf` **by default** builds in parallel using all available CPU cores, unless overridden with `-j <NUM>`.

This leads to the unexpected situation where `enableParallelBuilding=false`, but the build is actually parallel using all available cores. All CPU cores are used, even when `NIX_BUILD_CORES=1` (e.g. via `nix-build --cores 1 ...`). Only when `enableParallelBuilding=true` and `NIX_BUILD_CORES=1`, the build is sequential using only 1 CPU core. This is counter-intuitive.

### Steps To Reproduce
1. Choose a package that uses `wafHook`, for example `hamster`.
2. Open `top`/`htop` in another terminal to observe CPU usage.
2. Build the package: `nix-build '<nixpkgs>' -A hamster --max-jobs 1 --cores 1 --check`
3. Observe that all CPUs are fully used and that there is no `-j 1` option among the reported `build flags`:
```console
$ nix-build '<nixpkgs>' -A hamster --max-jobs 1 --cores 1 --check
...
'configure' finished successfully (0.173s)
building
build flags: build
Waf: Entering directory `/build/source/build'
[  1/310] Compiling help/cs/cs.po
[  2/310] Compiling help/da/da.po
...
``` 

### Expected behavior
If `enableParallelBuilding=false`, the build shall use only 1 core and `-j 1` shall be among the build flags.

If `enableParallelBuilding=true`, the build shall use `NIX_BUILD_CORES` cores and `-j ${NIX_BUILD_CORES}` shall be among the build flags.

Packages that use `wafHook` probably should also set `enableParallelBuilding=true`.

### Notify maintainers
@vrthra 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.60, NixOS, 21.05.2717.bc1a0f56812 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.15`
 - channels(root): `"nixos-21.05.2717.bc1a0f56812"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
  - gaia
  - blockhash
  - glmark2
  - patchage
  - saldl
  - weighttp
  - clasp-common-lisp
  - semantik
  - aubio
  - ndn-cxx
  - ganv
  - ldb
  - non
  - ntk
  - raul
  - lilv
  - lv2
  - lvtk
  - serd
  - sord
  - sratom
  - suil
  - talloc
  - ntdb
  - tdb
  - tevent
  - ams-lv2
  - ardour
  - ardour_5
  - guitarix
  - fomp
  - hamster
  - jalv
  - kupfer
  - mda_lv2
  - mpv-unwrapped
  - pflask
  - xiphos
  - ingen
  - ns-3
  - jack2
  - wxmupen64plus
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by panicgh**
###### Motivation for this change

Fixes #136368.

Basically, `wafHook` uses all available cores for building when `enableParallelBuilding=false` or unset and ignores `NIX_BUILD_CORES` (or `nix-build --cores <N>`).

The suggestion in https://github.com/NixOS/nixpkgs/issues/136368#issuecomment-910175545 would have set all builds sequential unless `enableParallelBuilding=true`. This would have caused follow-up changes to several pkgs as indicated in the issue. Furthermore, the [recommendation](https://nixos.org/manual/nixpkgs/stable/#attributes-affecting-build-properties) seems to prefer parallel building if the build system has good support for it.

This PR instead mimics the implementations of e.g. `cmake` or `meson` and sets `enablesParallelBuilding=1` if it has not been set otherwise. Dependent packages do not have to be modified, but would correctly honor `NIX_BUILD_CORES`.

The disadvantage of this proposal is that the build uses all available cores if `enableParallelBuilding` is explicitly set to `false`.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
This is same as in cmake:
https://github.com/NixOS/nixpkgs/blob/a8f9539d0171a5ae9285692805c0b206cfee9fde/pkgs/development/tools/build-managers/cmake/setup-hook.sh#L124-L127
so must be good.

One thing: this needs to be rebased to staging, and, if possible, I would add a mention to the release notes.

**Comment by panicgh** [comment]
Sorry for the long delay, I didn't find the time to follow this up earlier.

> One thing: this needs to be rebased to staging, and, if possible, I would add a mention to the release notes.

I rebased the branch onto staging and added a few words to the 21.11 release notes. Sorry for the noise due to the rebase. Hopefully this is better now.

File: pkgs/development/tools/build-managers/wafHook/setup-hook.sh [hunk 1]
```diff
@@ -21,6 +21,11 @@ wafConfigurePhase() {
     echoCmd 'configure flags' "${flagsArray[@]}"
     python "$wafPath" "${flagsArray[@]}"
 
+    if ! [[ -v enableParallelBuilding ]]; then
+        enableParallelBuilding=1
+        echo "waf: enabled parallel building"
```
Comment (SuperSandro2000) [inline pkgs/development/tools/build-managers/wafHook/setup-hook.sh:26]:
```suggestion
```
don't think we need to log that tbh.

Comment (veprbl) [reply pkgs/development/tools/build-managers/wafHook/setup-hook.sh:26]: cmake does it, so it's fine to have here as well

Comment (panicgh) [reply pkgs/development/tools/build-managers/wafHook/setup-hook.sh:26]: I mark this conversation as resolved. Please reopen/open a new one if you strongly disagree and think further discussion is needed.

**Comment by veprbl** [comment]
Sorry for delay. I don't think there is a need to port it into 21.11, let's merge to staging now. I've temporarily reverted your nice release notes additions, let's revisit this to add them back for 22.05 at a later time.

**Comment by panicgh** [comment]
> I've temporarily reverted your nice release notes additions, let's revisit this to add them back for 22.05 at a later time.

Fine with me. Thanks for merging!
