### PR TITLE
xorg.libX11: fix compiling with llvm

### LINKED ISSUE #320436: Build failure: pkgsLLVM.xorg.libX11
### Steps To Reproduce

1. build `pkgsLLVM.xorg.libX11`

### Build log

```
libX11-x86_64-unknown-linux-gnu-1.8.9> checking if x86_64-unknown-linux-gnu-clang supports -Werror... yes
libX11-x86_64-unknown-linux-gnu-1.8.9> checking if x86_64-unknown-linux-gnu-clang supports -Werror=attributes... yes
libX11-x86_64-unknown-linux-gnu-1.8.9> Package xorg-macros was not found in the pkg-config search path.
libX11-x86_64-unknown-linux-gnu-1.8.9> Perhaps you should add the directory containing `xorg-macros.pc'
libX11-x86_64-unknown-linux-gnu-1.8.9> to the PKG_CONFIG_PATH environment variable
libX11-x86_64-unknown-linux-gnu-1.8.9> No package 'xorg-macros' found
libX11-x86_64-unknown-linux-gnu-1.8.9> checking whether make supports nested variables... (cached) yes
libX11-x86_64-unknown-linux-gnu-1.8.9> checking whether to build functional specifications... yes
libX11-x86_64-unknown-linux-gnu-1.8.9> checking for xmlto... no
libX11-x86_64-unknown-linux-gnu-1.8.9> configure: WARNING: xmlto not found - documentation targets will be skipped
libX11-x86_64-unknown-linux-gnu-1.8.9> checking for xsltproc... no
libX11-x86_64-unknown-linux-gnu-1.8.9> configure: WARNING: xsltproc not found - cannot transform XML documents
libX11-x86_64-unknown-linux-gnu-1.8.9> checking for X.Org SGML entities >= 1.10... no
libX11-x86_64-unknown-linux-gnu-1.8.9> checking how to run the C preprocessor... x86_64-unknown-linux-gnu-clang -E
libX11-x86_64-unknown-linux-gnu-1.8.9> checking for x86_64-unknown-linux-gnu-cpp... /nix/store/id84g2s5lmzkkmrmqb7yhrki5hvyymg6-x86_64-unknown-linux-gnu-clang-wrapper-17.0.6/bin/x86_64-unknown-linux-gnu-cpp
libX11-x86_64-unknown-linux-gnu-1.8.9> checking if /nix/store/id84g2s5lmzkkmrmqb7yhrki5hvyymg6-x86_64-unknown-linux-gnu-clang-wrapper-17.0.6/bin/x86_64-unknown-linux-gnu-cpp requires -undef... configure: error: /nix/store/id84g2s5lmzkkmrmqb7yhrki5hvyymg6-x86_64-unknown-linux-gnu-clang-wrapper-17.0.6/bin/x86_64-unknown-linux-gnu-cpp defines unix with or without -undef.  I don't know what to do
```

### Additional context

Discovered via the Nixpkgs LLVM Workspace project.

https://github.com/RossComputerGuy/nixpkgs-llvm-ws/runs/26297896092

### Notify maintainers

No maintainers, CC last person who touched @sdht0

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.158, NixOS, 24.05 (Uakari), 24.05.20240506.6ff120a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/run/current-system/nixpkgs`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by RossComputerGuy**
## Description of changes

Fixes #320436 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

File: pkgs/build-support/cc-wrapper/add-clang-cc-cflags-before.sh [hunk 1]
```diff
@@ -6,6 +6,6 @@ for p in "${params[@]}"; do
     esac
 done
 
-if $needsTarget; then
+if $needsTarget && ! [[ "${0/*cpp/cpp}" == "cpp" ]]; then
```
Comment (paparodeo) [inline pkgs/build-support/cc-wrapper/add-clang-cc-cflags-before.sh:9]:
```suggestion
if $needsTarget && [[ $0 != *cpp ]]; then
```

can just use the pattern matching available with `[[ ... ]]`

Comment (RossComputerGuy) [reply pkgs/build-support/cc-wrapper/add-clang-cc-cflags-before.sh]: Done

File: pkgs/build-support/cc-wrapper/add-clang-cc-cflags-before.sh [hunk 2]
```diff
@@ -6,6 +6,6 @@ for p in "${params[@]}"; do
     esac
 done
 
-if $needsTarget; then
+if $needsTarget && [[ $0 != *cpp ]]; then
```
Comment (philiptaron) [inline pkgs/build-support/cc-wrapper/add-clang-cc-cflags-before.sh:9]: This is pretty opaque. Under what conditions would `$0` not match the result of shell expanding `*cpp` in the current directory? Why is that the correct test?

Comment (RossComputerGuy) [reply pkgs/build-support/cc-wrapper/add-clang-cc-cflags-before.sh:9]: I'm not sure, it's what worked to prevent weird errors with cpp on aarch64. Is there a way to make it match as expected but less opaque?

Comment (paparodeo) [reply pkgs/build-support/cc-wrapper/add-clang-cc-cflags-before.sh:9]: > Under what conditions would `$0` not match the result of shell expanding `*cpp` in the current directory?

the shell is not expanding `*cpp` in the current directory. this is just a pattern match that `$0` doesn't end with cpp. `[[...]]` has different semantics than `[...]`

Comment (philiptaron) [reply pkgs/build-support/cc-wrapper/add-clang-cc-cflags-before.sh:9]: The way it's opaque to me: 

1. What is `$0` in this context? Is this `add-clang-cc-cflags-before.sh`, run as a script, or something else?
2. Why is this contingent on matching exactly one thing with a `cpp` suffix? What's in the build directory such that this is an OK thing to do?
3. Why do these flags need to be skipped in this case?

As an implementation detail, I'm fine with this terse line. Without explanation, though, I find it completely inscrutable. I'd expect a huge comment in front of it explaining what's going on. 🙂

Comment (RossComputerGuy) [reply pkgs/build-support/cc-wrapper/add-clang-cc-cflags-before.sh:9]: > 1. What is `$0` in this context?

Afaik, `$0` is always going to be executable name in a shell script.

We're needing this patch because without it, libX11 was failing to build on aarch64 because `-march=armv8-a` was being included and the LLVM cpp does not like that so it errors out.



> 2\. Why is this contingent on matching exactly one thing with a `cpp` suffix?

Because it is n

**Review by tomberek — COMMENTED** [review]
Built and run on x86_64-linux.
