### PR TITLE
gst_all_1.gst-plugins-good: dlopen libsoup_3 with an absolute path

### LINKED ISSUE #271960: gst_all_1.gst-plugins-good is missing soup, needed for radiotray-ng
### Describe the bug
[According to the GStreamer website,](
https://gstreamer.freedesktop.org/documentation/soup/souphttpsrc.html) the "good" plugins package should contain the "soup" plugin. However, the nix package `gst_all_1.gst-plugins-good` does not.

### Steps To Reproduce
1. install packages `gst_all_1.gstreamer.bin` and `gst_all_1.gst-plugins-good`
2. run `gst-inspect-1.0 | grep soup`

Result: nothing found.

As a result, `radiotray-ng` cannot play any streams, failing with "could not create souphttpsrc element".

### Expected behavior
`gst_all_1.gst-plugins-good` should include `soup`.

### Notify maintainers

`gst_all_1.gst-plugins-good`: @matthewbauer @lilyinstarlight
`radiotray-ng`: @dtzWill

### Metadata

```console
[chalice:~]$ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.11 (Tapir), 23.11.20231128.7c4c205`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `""`
 - channels(ashley): `""`
 - nixpkgs: `not found`

```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by ghost**
## Description of changes
fixes #271960 

the libgstsoup plugin in the gstreamer gst-pluggins-good loads the libsoup (2 or 3) via a call to g_module_open -- g_module_open is implemented by glib as a dlopen in the libgmodule.so library. This call fails for both darwin and linux as libsoup is not found in the runpath of the libgmodule.so object. This change patches [gstsouploader.c](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/e19428a802c2f4ee9773818aeb0833f93509a1c0/subprojects/gst-plugins-good/ext/soup/gstsouploader.c#L184) to fall back on an absolute path for libsoup_3 if libsoup (2 or 3) is not already loaded so the subsequent g_module_open succeeds.

consumers of gst-pluggins-good need to add glib-networking to enable TLS support

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

File: pkgs/development/libraries/gstreamer/good/extra-modules.sh [hunk 1]
```diff
@@ -0,0 +1,8 @@
+addGIOModulesLibPath () {
+    if [[ -d "$1/lib/gio/modules" && "$1" == *glib-networking* ]]
```
Comment (a-n-n-a-l-e-e) [inline pkgs/development/libraries/gstreamer/good/extra-modules.sh:2]:
```suggestion
    if [[ -d "$1/lib/gio/modules" && -n "$(ls -A "$1/lib/gio/modules")" ]]
```
should be more like [find_gio_modules](https://github.com/NixOS/nixpkgs/blob/ffa859d8048388564984368f5f88b84e34fe178b/pkgs/build-support/setup-hooks/wrap-gapps-hook/wrap-gapps-hook.sh#L4) and could also remove duplicates.

this is my first time making a setup hook and this is basically a copy of [gstreamer/core/setup-hook.sh](https://github.com/NixOS/nixpkgs/blob/ffa859d8048388564984368f5f88b84e34fe178b/pkgs/development/libraries/gstreamer/core/setup-hook.sh)

File: pkgs/development/libraries/gstreamer/good/extra-modules.sh [hunk 2]
```diff
@@ -0,0 +1,8 @@
...
+    then
+        export GIO_EXTRA_MODULES="${GIO_EXTRA_MODULES-}${GIO_EXTRA_MODULES:+:}$1/lib/gio/modules"
```
Comment (lilyinstarlight) [inline pkgs/development/libraries/gstreamer/good/extra-modules.sh:4]:
```suggestion
        addToSearchPath GIO_EXTRA_MODULES "$1/lib/gio/modules"
```

There's a helper function in stdenv to do this

I do almost wonder if this setup hook should be on `glib` or `glib-networking` too 🤔

**Review by lilyinstarlight — COMMENTED** [review]
Thank you for this! I'll try to give it a more proper review later, but I am gonna leave one comment for now

File: pkgs/development/libraries/gstreamer/good/extra-modules.sh (hunk 2 above)
Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/gstreamer/good/extra-modules.sh]: thanks. `addToSearchPath` is perfect.

[glib/setup-hook.sh](https://github.com/NixOS/nixpkgs/blob/79fee6027b432958825b0bb83a1538314327a8a6/pkgs/development/libraries/glib/setup-hook.sh) does seem like a better fit.

**Comment by a-n-n-a-l-e-e** [comment]
cc glib maintainers for adding GIO_EXTRA_MODULES in the setup-hook.sh
@bobby285271 @hedning @jtojnar @dasj19 @amaxine @lovek323 @7c6f434c

File: pkgs/development/libraries/gstreamer/good/extra-modules.sh (hunk 2 above)
Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/gstreamer/good/extra-modules.sh]: or maybe `glib-networking` is better for GIO_EXTRA_MODULES setup-hook. I'm less excited about polluting the env space with GIO_EXTRA_MODULES for all packages which use glib.

Comment (jtojnar) [reply pkgs/development/libraries/gstreamer/good/extra-modules.sh]: `glib-networking` is just one package providing a gio module so it does not feel right. We could make a separate setup hook and propagate it from `glib-networking` if we want.

File: pkgs/development/libraries/glib/setup-hook.sh [hunk 3]
```diff
@@ -1,3 +1,10 @@
+glibAddGioExtraModules() {
+    if [ -d "$1/lib/gio/modules" ] && [ -n "$(ls -A "$1/lib/gio/modules")" ] ; then
+        addToSearchPath GIO_EXTRA_MODULES "$1/lib/gio/modules"
+    fi
+}
+addEnvHooks "$hostOffset" glibAddGioExtraModules
```
Comment (jtojnar) [inline pkgs/development/libraries/glib/setup-hook.sh:6]: IIUC, the purpose of this is to make it work in nix-shell?

I think we might want to unify this with `wrapGAppsHook` so that we do not need to do the [wrapper hack](https://discourse.nixos.org/t/python-qt-woes/11808/2) for other variables.

Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/glib/setup-hook.sh:6]: with this change i am trying to prevent regressions where the binaries in  gst-plugins-base and gstreamer using https streams. since the libgstsoup.so plugin will work it requires the glib-networking module for https.

today, if you do:
```console
nix-shell -p gst_all_1.gst-plugins-good gst_all_1.gst-plugins-base gst_all_1.gstreamer gst_all_1.gst-plugins-ugly
gst-play-1.0 https://path/to/some.mp3
```
that will work as it uses the Curl plugin from the ugly.

but once i fix the loading of libsoup_3 it will fail as the libgstsoup.so plugin will be loaded from good but will fail to find glib-networking unless the GST_EXTRA_MODULES is set properly.

Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/glib/setup-hook.sh:6]: I misread your question the first time around...
> IIUC, the purpose of this is to make it work in nix-shell?

yes.

> I think we might want to unify this with `wrapGAppsHook` so that we do not need to do the [wrapper hack](https://discourse.nixos.org/t/python-qt-woes/11808/2) for other variables.

I don't understand this. today `nix-shell` and `nix develop` will have the required environment variables GST_PLUGIN_SYSTEM_PATH_1_0 so things like gst-play-1.0 will work. however, `nix shell` will not but `gst-play-`1.0` is already broken as it will fail to find any plugins.

i'm experimenting with adding a buildEnv to gstreamer which could wrap `gst-play-1.0` so `nix shell` could work eg:
```
nix shell --impure --expr 'with import ./. {}; gst_all_1.buildEnv { paths = with gst_all_1; [ gst-plugins-good gst-plugins-base gst-libav gstreamer ]; }'
```

maybe that's what you mean by using `wrapGAppsHook`?

Comment (jtojnar) [reply pkgs/development/libraries/glib/setup-hook.sh:6]: I meant that `wrapGAppsHook` does not set most of the environment variables in the builder, only pass them to the wrapper, so they are not available to the shell.

File: pkgs/development/libraries/gstreamer/good/default.nix [hunk 4]
```diff
@@ -102,8 +111,9 @@ stdenv.mkDerivation rec {
     gdk-pixbuf
     aalib
     libcaca
-    libsoup
+    libsoup_3
```
Comment (jtojnar) [inline pkgs/development/libraries/gstreamer/good/default.nix:114]: It should not be needed here, it is only checked by tests, which we do not run.

File: pkgs/development/libraries/gstreamer/good/default.nix [hunk 5]
```diff
@@ -143,6 +153,8 @@ stdenv.mkDerivation rec {
     libjack2
   ];
 
+  propagatedBuildInputs = libsoup_3.propagatedUserEnvPackages;
```
Comment (jtojnar) [inline pkgs/development/libraries/gstreamer/good/default.nix:156]: TBH, I would want to remove `propagatedUserEnvPackages`.

Comment (jtojnar) [reply pkgs/development/libraries/gstreamer/good/default.nix:156]: I think we should either decide that leaf packages/shells are responsible for pulling glib-networking, or that it should be a hard dependency of libsoup and try to load it internally. Not sure how feasible the latter is though, though I am definitely not a fan of this middle road.

Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/gstreamer/good/default.nix:156]: i see -- i assumed it was a workaround for the infinite recursion that happens if glib-networking is added the propogatedBuildInputs of libsoup_3.

Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/gstreamer/good/default.nix:156]: > I think we should either decide that leaf packages/shells are responsible for pulling glib-networking

this seems not ideal as that requires adding glib-networking to the 500-1000 packages that are using gstreamer. if a leaf package forgets to add it there is no hard failure. things work as long as there isn't https or proxies (?) used.

my preference would be to not use it at all nor libsoup and rely on the curl plugin but that plugin doesn't seek correctly and doesn't work on various encoded formats like opus, ogg, webp, etc.

> or that it should be a hard dependency of libsoup and try to load it internally. Not sure how feasible the latter is though, though I am definitely not a fan of this middle road.

putting it in propagatedBuildInputs for libsoup seems better than where it is now, except for the infinite recursion problem. from grepping around in the libsoup and glib source it is not clear to me how it is getting loaded but it seems that glib takes care of scanning and loading the modules in GIO_EXTRA_MODULES. the interface exists for libsoup regardless of if the module is loaded or not, glib just returns an error if libsoup tries to use the functionality and glib-networking is not loaded. perhaps glib provides an interface to explicitly load modules out of some directory rather than relying on GIO_EXTRA_MODULES -- in that case libsoup could request that glib-netwokring modules are loaded at startup.

still would need to solve the infinite recursion problem in the build tho.

File: pkgs/development/libraries/glib/setup-hook.sh (hunk 3 above)
Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/glib/setup-hook.sh:6]: > I meant that `wrapGAppsHook` does not set most of the environment variables in the builder, only pass them to the wrapper, so they are not available to the shell.

i'm still missing the core concept here. if the environment variables do not exist, then the gstreamer binaries will not work in nix-shell.

File: pkgs/development/libraries/gstreamer/good/default.nix (hunk 5 above)
Comment (jtojnar) [reply pkgs/development/libraries/gstreamer/good/default.nix:155]: Ah, it is actually `passthru.propagatedUserEnvPackages` not `propagatedUserEnvPkgs` so that does not do anything at all, opened a [PR to remove it](https://github.com/NixOS/nixpkgs/pull/276813). The latter would cause an infinite recursion since it just adds a reference to the listed derivations to `$out/nix-support/propagated-user-env-packages`, where `nix-env` (and apparently [also `nix shell` now](https://github.com/NixOS/nix/blob/e23983db824f9ea0ecdb6cab3739232b2554f2f5/doc/manual/src/release-notes/rl-2.1.md?plain=1#L35)).

> this seems not ideal as that requires adding glib-networking to the 500-1000 packages that are using gstreamer. if a leaf package forgets to add it there is no hard failure. things work as long as there isn't https or proxies (?) used.

I would expect most packages would not need networking, and if they do, it is an easy fix.

> except for the infinite recursion problem. from grepping around in the libsoup and glib source it is not clear to me how it is getting loaded

If you look use `--show-trace` as recommended by the error, you will get the following chain:

- libsoup-3.4.4
- glib-networking-2.78.0
- libproxy-0.4.18
- networkmanager-1.44.2
- fix-paths.patch
- openconnect-9.12
- stoken-0.93
- gtk+3-3.24.38
- tracker-3.6.0

This cycle should disappear after #272353 is merged.

Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/gstreamer/good/default.nix:155]: with the cycle removed, this patch to [libsoup/soup-init.c](https://gitlab.gnome.org/GNOME/libsoup/-/blob/2a592b114092b0105f9f27af17225a3b35c288f8/libsoup/soup-init.c) loads glib-networking on init.
```diff
diff --git a/libsoup/soup-init.c b/libsoup/soup-init.c
index 8a33c77..4814c4c 100644
--- a/libsoup/soup-init.c
+++ b/libsoup/soup-init.c
@@ -11,6 +11,7 @@
 
 #include <glib/gi18n-lib.h>
 #include <gmodule.h>
+#include <gio/gio.h>
 #include "gconstructor.h"
 
 #ifdef G_OS_WIN32
@@ -53,6 +54,8 @@ soup_init (void)
 
         if (soup2_is_loaded ())
                 g_error ("libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.");
+
+        g_io_modules_scan_all_in_directory_with_scope("@nixGlibNetworking@", g_io_module_scope_new (G_IO_MODULE_SCOPE_BLOCK_DUPLICATES));
 }
 
 #if defined (G_OS_WIN32)
```

File: pkgs/development/libraries/glib/setup-hook.sh (hunk 3 above)
Comment (jtojnar) [reply pkgs/development/libraries/glib/setup-hook.sh:6]: Right, I was talking about the current state, where most variables are not available in the shell but [some are](https://github.com/NixOS/nixpkgs/blob/d2a5f168590d7c5b3c4aa219a12a269ad7d703a9/pkgs/build-support/setup-hooks/wrap-gapps-hook/wrap-gapps-hook.sh#L30-L34). I was bringing it up since it might be worth considering doing the same for the rest of the variables.

Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/glib/setup-hook.sh:6]: this is still ambiguous. what are you trying to accomplish -- moving everything to env vars or moving away from using env vars?

File: pkgs/development/libraries/gstreamer/good/default.nix (hunk 5 above)
Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/gstreamer/good/default.nix:155]: > > this seems not ideal as that requires adding glib-networking to the 500-1000 packages that are using gstreamer. if a leaf package forgets to add it there is no hard failure. things work as long as there isn't https or proxies (?) used.
> 
> I would expect most packages would not need networking, and if they do, it is an easy fix.

i'd rather not break things in the first place. this seems like the least desirable option to me. what is wrong with putting glib-networking into the propogatedBuildInputs of libsoup?

**Comment by a-n-n-a-l-e-e** [comment]
@ofborg eval

File: pkgs/development/libraries/glib/setup-hook.sh (hunk 3 above)
Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/glib/setup-hook.sh:6]: anyway, i did not modify [wrap-gapps-hook.sh](https://github.com/NixOS/nixpkgs/blob/d2a5f168590d7c5b3c4aa219a12a269ad7d703a9/pkgs/build-support/setup-hooks/wrap-gapps-hook/wrap-gapps-hook.sh) to use the `GIO_EXTRA_MODULES` out of the environment when setting up the wrapper args just because I am not sure if exporting `GIO_EXTRA_MODULES` is a good thing to do in the builder.

exporting GIO_EXTRA_MODULES in the builder means that any program that uses glib in the builder after the env var is exported will load the modules, which seems undesirable.

if that seems like a non-issue then yes, i will update wrap-gapps-hook.sh to remove the duplicated code.

File: pkgs/development/libraries/gstreamer/good/default.nix (hunk 5 above)
Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/gstreamer/good/default.nix]: > i'd rather not break things in the first place. this seems like the least desirable option to me. what is wrong with putting glib-networking into the propogatedBuildInputs of libsoup?

while waiting for an answer to this i'll take a guess. the desire to minimize the closure size is greater than the desire to make it easy to produce a working package when using libsoup.

i sampled 70 leaf packages yesterday that directly included gst-plugins-good. 17% of them were some sort music program with capacity for streaming -- none of them worked though 2 required accounts so they could've worked. some crashed on launch. ones that linked directly with libsoup did not get glib-networking. I fixed one,
https://github.com/NixOS/nixpkgs/pull/276960

the rest i thought would be just as good removed from nixpkgs rather than spending any time on.

**Comment by a-n-n-a-l-e-e** [comment]
all glib changes removed and glib-networking needs to be added to leaf packages in order to get TLS support.

File: pkgs/development/libraries/gstreamer/good/default.nix (hunk 4 above)
Comment (a-n-n-a-l-e-e) [reply pkgs/development/libraries/gstreamer/good/default.nix:114]: ofborg eval kept failing with libsoup_3 removed so i added it back.

**Comment by a-n-n-a-l-e-e** [comment]
> Thank you for this! I'll try to give it a more proper review later, but I am gonna leave one comment for now

ping @lilyinstarlight

File: pkgs/development/libraries/gstreamer/good/default.nix [hunk 6]
```diff
@@ -102,8 +111,9 @@ stdenv.mkDerivation rec {
     gdk-pixbuf
     aalib
     libcaca
-    libsoup
+    libsoup_3
     libshout
+    libxml2
```
Comment (vcunat) [inline pkgs/development/libraries/gstreamer/good/default.nix:116]: Why is this added?  I fail to see any reason or comment about it.

Comment (jtojnar) [reply pkgs/development/libraries/gstreamer/good/default.nix:116]: libsoup_3 does not propagate it.

**Comment by vcunat** [comment]
I notice nothing wrong or risky here.
