### PR TITLE
nixos-generate-config: fix for swapless kernels

### LINKED ISSUE #49826: nixos-generate-config fails without swap
## Issue description

I'm reporting this for a friend of mine who wanted to install NixOS and ran into this issue. I hope that's okay.

The problem is: `nixos-generate-config` fails if you have `CONFIG_SWAP=n` in your host's kernel config (which, I think, is reasonable if you're compiling it yourself and don't need swap). I took a cursory look into `nixos-generate-config.pl` and saw that it reads from `/proc/swaps`. This fails, apparently, because the file doesn't exist on systems without swap support.

Can this be easily fixed by assuming there are no swap devices if the file cannot be found?

### PR DESCRIPTION
**Pull request by Synthetica9**
###### Motivation for this change

Fixes #49826 

I don't actually speak Perl, but this seems about right?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Review by lheckemann — APPROVED** [review]

File: nixos/modules/installer/tools/nixos-generate-config.pl [hunk 1]
```diff
@@ -314,14 +314,16 @@ sub findStableDevPath {
 
 # Generate the swapDevices option from the currently activated swap
 # devices.
-my @swaps = read_file("/proc/swaps");
-shift @swaps;
+my @swaps = read_file("/proc/swaps", err_mode => 'carp');
```
Comment (Infinisil) [inline nixos/modules/installer/tools/nixos-generate-config.pl]: Because I just spent 10 minutes trying to find the docs on this:

> The err_mode option has three possible values: quiet, carp, or the default, croak. In quiet mode, all errors will be silent. In carp mode, all errors will be emitted as warnings. And, in croak mode, all errors will be emitted as exceptions. Take a look at Try::Tiny or Syntax::Keyword::Try to see how to catch exceptions.

From https://metacpan.org/pod/File::Slurp#read_file
