### PR TITLE
wrapRustcWith: allow --sysroot to be overridden

### LINKED ISSUE #271736: Build failure: rustc 1.73.0 (cross-compilation)
### Steps To Reproduce

Tested with ab3ea20adfe05a2328b4991612912ef7db67af83.

1. build pkgs.pkgsCross.aarch64-multiplatform.rustc (also happens with armv7l-hf-multiplatform)

### Build log

```
Building stage0 library artifacts (x86_64-unknown-linux-gnu)
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/build/rustc-1.73.0-src/build/bootstrap/debug/rustc - --crate-name ___ --print=file-names -Ccodegen-units=10 -Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options '--check-cfg=values(bootstrap)' '--check-cfg=values(stdarch_intel_sde)' '--check-cfg=values(no_fp_fmt_parse)' '--check-cfg=values(no_global_oom_handling)' '--check-cfg=values(no_rc)' '--check-cfg=values(no_sync)' '--check-cfg=values(freebsd12)' '--check-cfg=values(freebsd13)' '--check-cfg=values(backtrace_in_libstd)' '--check-cfg=values(target_vendor,"unikraft")' '--check-cfg=values(target_env,"libnx")' '--check-cfg=values(target_os,"teeos")' '--check-cfg=values(target_arch,"asmjs","spirv","nvptx","xtensa","mips32r6","mips64r6","csky")' -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Csplit-debuginfo=off -Ctarget-feature=-crt-static -Cprefer-dynamic -Zinline-mir '-Zcrate-attr=doc(html_root_url="https://doc.rust-lang.org/1.73.0/")' --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: Option 'sysroot' given more than once

Build completed unsuccessfully in 0:00:11
make: *** [Makefile:12: all] Error 1
```

Full log: https://gist.github.com/2xsaiko/09032d1ca0b05ae38b88c1a15c81e9ff

### Additional context

Might be related to #267003 but seems to be a different error.

### Notify maintainers

@Havvy @figsoda @Mic92 @tjni @winterqt @zowoq

### Metadata

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.63, NixOS, 23.11 (Tapir), 23.11.20231121.cccc85f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

### Priorities

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by alyssais**
## Description of changes

It turns out that unlike a normal Unix program, if the --sysroot option is given more than once, rustc will error rather than using the last value given.  Therefore, we need to ensure we only add our default --sysroot argument if one hasn't been given explicitly on the wrapper's command line.

This fixes cross compilation of rustc.

Closes: https://github.com/NixOS/nixpkgs/issues/271736
Fixes: 8b51cdd3bea1 ("rustc: add a compiler wrapper")

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

File: pkgs/build-support/rust/rustc-wrapper/rustc-wrapper.sh [hunk 1]
```diff
@@ -1,6 +1,14 @@
 #!@shell@
 
-extraBefore=(@sysroot@)
+defaultSysroot=(@sysroot@)
+
+for arg; do
```
Comment (2xsaiko) [inline pkgs/build-support/rust/rustc-wrapper/rustc-wrapper.sh:5]: Every day I learn some crazy new bash syntax. :^)

File: pkgs/build-support/rust/rustc-wrapper/rustc-wrapper.sh [hunk 2]
```diff
@@ -1,6 +1,14 @@
...
+    if [ "$arg" = --sysroot ]; then
+        defaultSysroot=()
```
Comment (2xsaiko) [inline pkgs/build-support/rust/rustc-wrapper/rustc-wrapper.sh:7]:
```suggestion
    if [[ "$arg" = --sysroot ]]; then
        defaultSysroot=()
        break
```

absolutely nitpicking here btw

**Review by dblsaiko — APPROVED** [review]

File: pkgs/build-support/rust/rustc-wrapper/rustc-wrapper.sh (hunk 2 above)
Comment (alyssais) [reply pkgs/build-support/rust/rustc-wrapper/rustc-wrapper.sh:7]: I'd rather not break, because we'll probably want to add other flags here in the future.  Given that, it should probably be a `case` rather than an `if` though.  I'll change that.

**Comment by yu-re-ka** [comment]
With this change we should be able to revert the hacky fix of rust-hypervisor-firmware in https://github.com/NixOS/nixpkgs/pull/257345 cc @astro

**Review by dblsaiko — APPROVED** [review]

**Review by yu-re-ka — APPROVED** [review]
I have done only end to end tests

**Comment by yu-re-ka** [comment]
Do you mind if I merge this?
