### PR TITLE
extra-cmake-modules: Use associative array to recognize paths

### LINKED ISSUE #99308: O(n^2) complexity in kde-frameworks/extra-cmake-modules/setup-hook.sh
**Describe the bug**

The file `pkgs/development/libraries/kde-frameworks/extra-cmake-modules/setup-hook.sh` has this function:
```bash
ecmUnseenHostPath() {
    for pkg in "${ecmHostPathSeen[@]}"
    do
        if [ "${pkg:?}" == "$1" ]
        then
            return 1
        fi
    done

    ecmHostPathSeen+=("$1")
    return 0
}
```
Since this is called for every dependency, we get quadratic complexity. This may cause a non-trivial slowdown - building digikam I noticed it takes a few seconds just to get to `unpackPhase`, but there might be other causes. It also causes huge amounts of debug output when you add a `set -x` to `preHook` (about 600 MB for digikam).

We should use an associative array for this like stdenv does (see 8d76effc178747f0c8f456fe619c1b014736a6af).

**Notify maintainers**

@ttuegel

### PR DESCRIPTION
**Pull request by ttuegel**
Fixes #99308.

Use an associative array to recognize paths that have already been seen by the
host path hook. This takes advantage of fast lookup of associative array keys in
Bash. The previous solution scanned a linear array, which was accidentally
quadratic.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/development/libraries/kde-frameworks/extra-cmake-modules/setup-hook.sh [hunk 1]
```diff
@@ -59,19 +59,15 @@ xdgDataSubdirs=( \
     "wallpapers" "applications" "desktop-directories" "mime" "appdata" "dbus-1" \
 )
 
-ecmHostPathSeen=( )
+declare -gA ecmHostPath
```
Comment (happysalada) [inline pkgs/development/libraries/kde-frameworks/extra-cmake-modules/setup-hook.sh:62]: nit: how about `ecmSeenHostPaths`
I would like to add an `s` to the variable since it's an array.
I also liked the fact that `Seen` was included in the name to mark as the path as seen.
It's entirely a matter of style, so if you feel strongly around it, feel free to ignore.

File: pkgs/development/libraries/kde-frameworks/extra-cmake-modules/setup-hook.sh [hunk 2]
```diff
@@ -59,19 +59,15 @@ xdgDataSubdirs=( \
...
 
 ecmUnseenHostPath() {
```
Comment (happysalada) [inline pkgs/development/libraries/kde-frameworks/extra-cmake-modules/setup-hook.sh:64]: how about ecmEnsureUnseenHostPath ?
It's a bit of a mouthful but I feel it describes better the situation.
Again it's a matter of style, so feel free to ignore if not to your liking.

**Comment by happysalada** [comment]
The change looks good to me, I have a couple of nits in case they resonate with you.
