### PR TITLE
nixos-generate-config.pl, all-hardware.nix: Add support for Hyper-V

### LINKED ISSUE #13971: Issues with NixOS 15.09 installation on a Hyper-V Generation 2 VM on Windows 10 64-Bit
## Basic info

To make sure that we are on the same page:
- Kernel: (run `uname -a`)
- System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
- Nix version: (run `nix-env --version`)
- Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
## Describe your issue here

This is an installation issue so the fields above weren't quite applicable. 

I am trying to install NixOS 15.09 (15.09.1113.23395c4-x86_64) on a Generation 2 (UEFI-based) Hyper-V VM on Windows 10 64-bit v1511, but running into several issues. See below for details and repro steps. Happy to provide more info if needed.
### Expected result

Should successfully boot into LiveCD. 
VM should be responsive to keyboard input.
### Actual result

Runs into a similar issue as described in https://github.com/NixOS/nixpkgs/issues/9899:

```
waiting for device /dev/disk/by-uuid/... to appear...
Time out waiting for device /dev/disk/by-uuid/..., trying to mount anyway.
mounting /dev/disk/by-uuid/... on /...
mount: mounting /dev/disk/by-uuid... on /mnt/root/ failed: No such file or directory

An error occurred in stage 1 of the boot process, which must mount the root filesystem on /mnt-root and then start stage 2. Press one of the following keys:

i) to launch an interactive shell
f) to start an interactive shell having pid 1 (needed if you want to start stage 2's init manually)
r) to reboot immediately
*) to ignore the error and continue
```

In addition, the VM doesn't respond to any keyboard input through the Hyper-V VM connection at this point, so I can't actually debug it through a shell either.

Neither of these issues exist when installing on a Generation 1 Hyper-V VM.
### Steps to reproduce
1. Create a Generation 2 Hyper-V VM (Not reproducible on a Generation 1 VM, but https://github.com/NixOS/nixpkgs/issues/5872 is still a problem)
2. Disable Secure Boot in VM settings
3. Mount installation ISO, boot the VM and boot into the LiveCD

### PR DESCRIPTION
**Pull request by taku0**
###### Motivation for this change

To Install to Hyper-V virtual machine using the minimal installation CD.

Hyper-V generation 2 VM requires the `hv_storvsc` module to boot. So this PR adds the module to the installation CD and `hardware-configuration.nix`.

The `modesetting` X11 video driver does not seem to work for Hyper-V, so this PR adds the `fbdev` video driver to `hardware-configuration.nix`.

Fixes #13971 and #9899.

Confirmed that I can boot from the minimal installation CD, install NixOS with X11, and start X11 in the installed NixOS. 

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

File: nixos/modules/installer/tools/nixos-generate-config.pl [hunk 1]
```diff
@@ -277,6 +274,12 @@ sub usbCheck {
     push @imports, "<nixpkgs/nixos/modules/profiles/qemu-guest.nix>";
 }
 
+# Also for Hyper-V.
+if ($virt eq "microsoft" || $virt eq "kvm" || $virt eq "bochs") {
```
Comment (Mic92) [inline nixos/modules/installer/tools/nixos-generate-config.pl]: Why does `bochs` and `kvm` requires `hv_storvsc`?

Comment (taku0) [inline nixos/modules/installer/tools/nixos-generate-config.pl]: That was an editing error. Amended.
