### PR TITLE
`lib.types.submoduleWith`: Avoid `_key` collisions after `extendModules` (issue #168767)

### LINKED ISSUE #168767: Weird extendModules behaviour when used inside a submodule
### Describe the bug

When `extendModules` is used inside a submodule, strange collisions / "not defined" errors can happen

### Steps To Reproduce
1. From this flake:

```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs";
  outputs = {
    self,
    nixpkgs,
  }:
    with nixpkgs.lib; {
      lib.thing = evalModules {
        modules = [
          ({
            lib,
            extendModules,
            ...
          }: {
            options.sub = mkOption {
              default = {};
              type = types.submodule ({
                config,
                extendModules,
                ...
              }: {
                options.value = mkOption {
                  type = types.int;
                };

                options.specialisation = mkOption {
                  default = {};
                  inherit
                  (extendModules {
                    modules = [{specialisation = mkOverride 0 {};}];
                  })
                  type
                  ;
                };
              });
            };
          })
          {config.sub.value = 1;}
        ];
      };
    };
}

```

2. If we do `nix eval '.#lib.thing.config.sub.specialisation.value'`, we get:

```
error: The option `sub.specialisation.value' is used but not defined.
```

3. But if we add `{config.sub.specialisation.value = mkDefault 2;}` to the modules of `evalModules`, we get:

```
1
```

So from my understanding it wrongly assumes that the option isn't defined since it's not defined at the local level, but if defined locally still gets the global value afterwards.

4. Weirdly enough, if we add `{config.sub.specialisation.value = 2;}` instead (without the `mkDefault`), we get:

```
error: The option `sub.specialisation.value' has conflicting definition values:
       - In `<unknown-file>': 1
       - In `<unknown-file>': 2
```

But doing it in the same module as the setting of `config.sub.value` doesn't yield this error, and correctly reports back 2.

### Expected behavior

- Just setting `config.sub.value = 1` should be enough for `sub.specialisation.value == 1`.
- Also setting `config.sub.specialisation.value = 2` either in the same module or in another one should set the specialised value to 2.

### Additional context

The usecase I have for this is that I'm developing a deployment tool. At the top-level we define an attrset of nodes, whose configurations are submodules. I would like to have specialisation support at the node level, and came across `extendModules` by reading how NixOS does it.

### Notify maintainers

@roberth as the creator of `extendModules` (thank you a lot for that, by the way!)

### Metadata

N/A

### PR DESCRIPTION
**Pull request by roberth**
This fixes module key collisions induced by extendModules
when using anonymous modules.

TODO
 - [x] clean up
 - [x] ~consider more elegant solution, like calling unifyModuleSyntax in evalModules instead of in submoduleWith~
    - too big a change to evalModules semantics

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: lib/tests/modules.sh [hunk 1]
```diff
@@ -293,7 +293,7 @@ checkConfigOutput '^"a c"$' config.result ./functionTo/merging-attrs.nix
 
 # moduleType
 checkConfigOutput '^"a b"$' config.resultFoo ./declare-variants.nix ./define-variant.nix
-checkConfigOutput '^"a y z"$' config.resultFooBar ./declare-variants.nix ./define-variant.nix
+checkConfigOutput '^"a b y z"$' config.resultFooBar ./declare-variants.nix ./define-variant.nix
```
Comment (roberth) [inline lib/tests/modules.sh:296]: I didn't recognize the problem at the time.

The assertion looks for `attrNames config.variants.foo.variants.bar.attrs`.

```
    attrs.a = 1;
    variants.foo.attrs.b = 1;
    variants.bar.attrs.y = 1;
    variants.foo.variants.bar.attrs.z = 1;
    variants.foo.variants.foo.attrs.c = 3;
```

`b` occurs in the `foo` variant, so it should also occur in the `foo`+`bar` variant.

**Comment by roberth** [comment]
Ping @infinisil
