### PR TITLE
prefetch-npm-deps: fix reproducibility

### LINKED ISSUE #223964: buildNodePackage produces `ENOTCACHED` when referring to the same package via different hashes (?)
### Describe the bug

When a `package-lock.json` file contains references to the same package and version but by using a different hashing algorithm (e.g. sha1 and sha512), the subsequent `npm build` invocation in the sandbox seems to only find one of them, raising an `ENOTCACHED` error for the other.

### Steps To Reproduce

```nix
{lib, pkgs, ...}: {
  myPackage = pkgs.buildNpmPackage rec {
    pname = "immich-server";
    version = "1.52.1";
    src = pkgs.fetchgit {
      url = "https://github.com/immich-app/immich.git";
      rev = "34d300d1da296721d647c751169c4441ba33ec7d";
      sha256 = "15jap54jrk8gf79ifdfcvkkmhs3pf53r3skdsz0nylqbqa7gwkbr";
    };
    npmDepsHash = lib.readFile (pkgs.runCommand "immich-npm-deps" {} ''
      ${pkgs.prefetch-npm-deps}/bin/prefetch-npm-deps ${src}/package-lock.json > $out
    '');

    nativeBuildInputs = with pkgs; [
      pkg-config
      python3
    ];

    # Required for sharp
    buildInputs = with pkgs; [
      vips
    ];
  };
}
```

try to build the contained derivation and the following error will appear:

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/apsv8hkws0i4l77w0gikgp3zrczrv7xx-server
source root is server
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
Executing npmConfigHook
Configuring npm
Validating consistency between /tmp/nix-build-immich-server-1.52.1.drv-0/server/package-lock.json and /nix/store/b64hvf4lf576vsa2r9c0c406q886227m-immich-server-1.52.1-npm-deps/package-lock.json
Installing dependencies
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz failed: cache mode is 'only-if-cached' but no cached response is available.

npm ERR! Log files were not written due to an error writing to the directory: /nix/store/b64hvf4lf576vsa2r9c0c406q886227m-immich-server-1.52.1-npm-deps/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

ERROR: npm failed to install dependencies

Here are a few things you can try, depending on the error:
1. Set `makeCacheWritable = true`
  Note that this won't help if npm is complaining about not being able to write to the logs directory -- look above that for the actual error.
2. Set `npmFlags = [ "--legacy-peer-deps" ]`
```

The corresponding multiple definitions that can be found for color-name-1.1.3 in the lockfile are:
```
14888:        "color-name": {
14889-          "version": "1.1.3",
14890:          "resolved": "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz",
14891-          "integrity": "sha512-72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw=="
14892-        }

11988:        "color-name": {
11989-          "version": "1.1.3",
11990:          "resolved": "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz",
11991-          "integrity": "sha1-p9BVi9icQveV3UIyj3QIMcpTvCU="
11992-        },

[some other identical ones]
```

Nonetheless, both files seem to be available:

```
base64 -d <<< "p9BVi9icQveV3UIyj3QIMcpTvCU=" | xxd -pr
a7d0558bd89c42f795dd42328f740831ca53bc25

base64 -d <<< "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==" | xxd -pr

74ecbedc0b96ddadb035b64722e319a537208c6b8b53fb812ffb9b71917d3976c3a3c7dfe0ef32569e417f479f4bcb84a18a39ab8171edd63d3a04065e002c40
ls -l /nix/store/b64hvf4lf576vsa2r9c0c406q886227m-immich-server-1.52.1-npm-deps/_cacache/content-v2/sha1/a7/d0/558bd89c42f795dd42328f740831ca53bc25 /nix/store/b64hvf4lf576vsa2r9c0c406q886227m-immich-server-1.52.1-npm-deps/_cacache/content-v2/sha512/74/ec/bedc0b96ddadb035b64722e319a537208c6b8b53fb812ffb9b71917d3976c3a3c7dfe0ef32569e417f479f4bcb84a18a39ab8171edd63d3a04065e002c40
-r--r--r-- 1 root root 4.0K Jan  1  1970 /nix/store/b64hvf4lf576vsa2r9c0c406q886227m-immich-server-1.52.1-npm-deps/_cacache/content-v2/sha1/a7/d0/558bd89c42f795dd42328f740831ca53bc25
-r--r--r-- 1 root root 2.9K Jan  1  1970 /nix/store/b64hvf4lf576vsa2r9c0c406q886227m-immich-server-1.52.1-npm-deps/_cacache/content-v2/sha512/74/ec/bedc0b96ddadb035b64722e319a537208c6b8b53fb812ffb9b71917d3976c3a3c7dfe0ef32569e417f479f4bcb84a18a39ab8171edd63d3a04065e002c40
```

Regenerating the lockfile (and thus replacing all hashing algorithms with sha512) "fixes" the issue, or more likely works around it.

### Expected behavior

The original package-lock file should work without modifications.

### Notify maintainers

@winterqt

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

### PR DESCRIPTION
**Pull request by winterqt**
###### Description of changes

v1 lockfiles can contain multiple references to the same version of a
package, and these references can contain different `integrity` values,
such as one having SHA-1 and SHA-512, while another just has SHA-512.

Given that HashMap iteration order isn't defined, this causes
reproducibility issues, as a different integrity value could be chosen
each time.

Thanks to @lilyinstarlight for discovering this issue originally, as well
as the idea for the sorting-based implementation.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/build-support/node/fetch-npm-deps/src/main.rs [hunk 1]
```diff
@@ -1,67 +1,169 @@
...
 /// tarball into the lockfile.
 ///
 /// Thus, we remove this hash, to replace it with our own determinstic copies of dependencies from hosted Git providers.
-fn fixup_lockfile(mut lock: Map<String, Value>) -> anyhow::Result<Option<Map<String, Value>>> {
-    if lock
+fn fixup_lockfile(
+    mut lock: Map<String, Value>,
+    cache: &Option<HashMap<String, String>>,
+) -> anyhow::Result<Option<Map<String, Value>>> {
+    let mut fixed = false;
```
Comment (RaitoBezarius) [inline pkgs/build-support/node/fetch-npm-deps/src/main.rs:35]: A comment on what achieve `fixed` would be helpful

File: pkgs/build-support/node/fetch-npm-deps/src/main.rs [hunk 2]
```diff
@@ -1,67 +1,169 @@
...
+                            package
+                                .as_object_mut()
+                                .ok_or_else(|| anyhow!("package isn't a map"))?
+                                .remove("integrity");
+                        } else if let Some(cache_hashes) = cache {
+                            let cache_hash = cache_hashes
+                                .get(resolved)
+                                .expect("dependency should have a hash");
+
+                            if integrity != cache_hash {
```
Comment (RaitoBezarius) [inline pkgs/build-support/node/fetch-npm-deps/src/main.rs:73]: What does it mean to have this situation? (a comment here would help reading what happens)

File: pkgs/build-support/node/fetch-npm-deps/src/main.rs [hunk 3]
```diff
@@ -1,67 +1,169 @@
...
+    cache: &Option<HashMap<String, String>>,
+    fixed: &mut bool,
+) {
+    for dep in dependencies.values_mut() {
+        if let Some(Value::String(resolved)) = dep
+            .as_object()
+            .expect("v1 dep must be object")
+            .get("resolved")
+        {
+            if let Some(Value::String(integrity)) = dep
```
Comment (RaitoBezarius) [inline pkgs/build-support/node/fetch-npm-deps/src/main.rs:113]: nit: it seems the if here are following a different style: `if...\n{` rather than `if... {`

File: pkgs/build-support/node/fetch-npm-deps/src/main.rs (hunk 2 above)
Comment (lilyinstarlight) [reply pkgs/build-support/node/fetch-npm-deps/src/main.rs:73]: A dependency with the same resolved URL can have different hash types in different locations of the same package-lock.json file (e.g. sha1 and sha512) since for transitive upstream dependencies, it just imports whatever hash type was in their lockfile iirc (which is dumb it doesn't canonicalize resolved URL -> integrity hash but whatever, it's npm)

It's a problem because when npm goes to look up the URL + integrity hash in the cacache that we use in the fetcher, it won't find it if it's not the same hash type/value

I'll add a comment

File: pkgs/build-support/node/fetch-npm-deps/src/main.rs (hunk 3 above)
Comment (lilyinstarlight) [reply pkgs/build-support/node/fetch-npm-deps/src/main.rs:113]: You'll have to take that up with rustfmt. They decided the `{` should go on its own line when the conditional is already multiple lines

File: pkgs/build-support/node/fetch-npm-deps/src/main.rs (hunk 2 above)
Comment (lilyinstarlight) [reply pkgs/build-support/node/fetch-npm-deps/src/main.rs:80]: I've opted to update the doc comment on `fixup_lockfile` to clarify that particular situation and in general align with what exactly the function does

Let me know if this is still insufficient

**Comment by lilyinstarlight** [comment]
By the way, I've now confirmed all 46 npm FODs in nixpkgs still reproduce to the same hash after this change (and now some like `open-stage-control.npmDeps` won't randomly get a different hash sometimes)

<details>
<summary>FODs checked, by attr (required some local changes not in nixpkgs to get all of them exposed via attrs):</summary>

```
ansible-language-server.npmDeps
audiobookshelf.npmDeps
authelia.web.npmDeps
bitwarden.npmDeps
cdxgen.npmDeps
deltachat-desktop.npmDeps
docker-compose-language-service.npmDeps
dot-language-server.npmDeps
element-desktop.keytar.npmDeps
emscripten.nodeModules.npmDeps
evcc.npmDeps
forgejo.frontend.npmDeps
geph.gui.gephgui.npmDeps
hred.npmDeps
iosevka-comfy.comfy-duo.npmDeps
iosevka-comfy.comfy-fixed.npmDeps
iosevka-comfy.comfy-motion-duo.npmDeps
iosevka-comfy.comfy-motion-fixed.npmDeps
iosevka-comfy.comfy-motion.npmDeps
iosevka-comfy.comfy-wide-duo.npmDeps
iosevka-comfy.comfy-wide-fixed.npmDeps
iosevka-comfy.comfy-wide.npmDeps
iosevka-comfy.comfy.npmDeps
iosevka.npmDeps
kaufkauflist.npmDeps
lv_img_conv.npmDeps
matrix-appservice-irc.npmDeps
mongosh.npmDeps
mpvScripts.webtorrent-mpv-hook.npmDeps
open-stage-control.npmDeps
paperless-ngx.frontend.npmDeps
photoprism.frontend.npmDeps
pnpm-lock-export.npmDeps
sharing.npmDeps
sunshine.ui.npmDeps
terminal-stocks.npmDeps
torq.web.npmDeps
twspace-crawler.npmDeps
uptime-kuma.npmDeps
vaultwarden.webvault.npmDeps
vieb.npmDeps
vsce.npmDeps
webcord-vencord.vencord.npmDeps
webcord.npmDeps
zigbee2mqtt.npmDeps
zinc.webui.npmDeps
```
</details>

File: pkgs/build-support/node/fetch-npm-deps/src/main.rs (hunk 3 above)
Comment (RaitoBezarius) [reply pkgs/build-support/node/fetch-npm-deps/src/main.rs:120]: No problem

**Review by RaitoBezarius — APPROVED** [review]
LGTM

**Comment by CMCDragonkai** [comment]
This is not in 23.05 atm right?

**Comment by lilyinstarlight** [comment]
> This is not in 23.05 atm right?

This was merged before the 23.05 release, so it definitely is in 23.05. Are you having an issue still?

Feel free to open a new issue on nixpkgs if you are and ping me on it
