### PR TITLE
stdenv/setup.sh: Add version check to setup script

### LINKED ISSUE #71625: "bad substitution" error on darwin
**Describe the bug**
Since this commit:
https://github.com/NixOS/nixpkgs/commit/bbc5b22ad82f89d2605ab91073012b12cabe87c3
Whenever I run commands like:
`nix-shell -p hello`
I get the following error:
```
/nix/store/v94xrmhkljhb44v2shcpv74gxg1ii1f1-cctools-binutils-darwin-wrapper/nix-support/setup-hook: line 140: ${role_pre}${cmd^^}=${cmd}: bad substitution
```

**Additional context**
My default shell is zsh, which has been the cause of some issues at times.

**Metadata**
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `""`
 - channels(val): `"nixpkgs-20.03pre197510.4b0508a5853"`
 - nixpkgs: `/Users/val/.nix-defexpr/channels/nixpkgs`
```

Paging @xzfc in particular. Let me know how I can help!

### PR DESCRIPTION
**Pull request by matthewbauer**
Only bash 4+ works in setup.sh. To make sure this is obvious, we can
check BASH_VERSINFO to get the major version number of Bash.

While Bash 3 is pretty rare, it still comes stock in macOS.

We *could* provide a warning here for non-Bash shells, but it’s not
always clear whether they will work or not. Zsh should have no trouble
while busybox sh, fish, or any others. There’s no great way to detect
what feature set the shell supports.

Fixes #71625

### CODE REVIEW

File: pkgs/stdenv/generic/setup.sh [hunk 1]
```diff
@@ -1,6 +1,12 @@
 set -eu
 set -o pipefail
 
+if [ -n "${BASH_VERSINFO-}" ] && [ "${BASH_VERSINFO-}" -lt 4 ]; then
+    echo "Detected older Bash than is supported by Nixpkgs."
+    echo "You must install a newer version of Bash to continue."
```
Comment (worldofpeace) [inline pkgs/stdenv/generic/setup.sh:6]: how much newer? How about 
```
Detected Bash version that isn't supported by Nixpkgs (${BASH_VERSION})
Please install Bash 4 or greater to continue.
```

**Comment by SuperSandro2000** [comment]
please target staging.

**Comment by matthewbauer** [comment]
@worldofpeace Sorry for the delay! I've updated with your wording. Should be ready to merge, but I'll defer to someone else as this isn't exactly critical.

File: pkgs/stdenv/generic/setup.sh [hunk 2]
```diff
@@ -1,6 +1,12 @@
 set -eu
 set -o pipefail
 
+if [ -n "${BASH_VERSINFO-}" ] && [ "${BASH_VERSINFO-}" -lt 4 ]; then
```
Comment (SuperSandro2000) [inline pkgs/stdenv/generic/setup.sh:4]:
```suggestion
if [[ ${BASH_VERSINFO:0} -lt 4 ]]; then
```

Comment (matthewbauer) [reply pkgs/stdenv/generic/setup.sh:4]: In this case, we still need to support zsh which will not have BASH_VERSINFO set. I guess we could do `${BASH_VERSINFO:5}`, but that's kind of weird.

**Comment by SuperSandro2000** [comment]
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 108102` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>stdenv</li>
</ul>
</details>
