### PR TITLE
stdenv: re-add isMachO helper function

### LINKED ISSUE #138157: Flakes devShells recently broke with weird error
### Describe the bug

Trying to enter a devshell for a flake errors weirdly:

```
error: [json.exception.parse_error.101] parse error at line 55, column 178: syntax error while parsing value - invalid string: ill-formed UTF-8 byte; last read: '" \n    local fn=\"$1\";\n    local fd;\n    local magic;\n    exec {fd}< \"$fn\";\n    read -r -n 4 -u \"$fd\" magic;\n    exec {fd}>&-;\n    if [[ \"$magic\" = '�'
```

### Steps To Reproduce

1. Use `nixUnstable` with experimental features for `flakes` and `nix-command` enabled
2. Use `flake.nix` from below
3. run `nix develop` in the flake.

### Expected behavior

A dev shell is entered that has `gcc`

### Additional context

This has been observed so far on `nixpkgs-unstable`, `nixos-unstable` and `master`.

Personall I was able to confirm with the following commits (of which I can't say anmore which branch they belong to:

* 2bb5cbf7f8b99a8d1d6646abe5ab993f6823212f
* cbb95673926205f7a54af97ecfa32bc7be917603
* 47eaf6727bd362dac94eab91b7fdc876642d578b
* 90a37f3ed47fa4d35b077384daec8ad867596ae3

I have to admit though, that we are not sure if this is a problem of `nixUnstable` or `nixpkgs`.

What I can say though we had at least 2 versions of nix (nightly as shown below and `2.4pre20210908_3c56f62`) in the mix and it broke for both of them.

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix shell nixpkgs#nix-info -c nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.64, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20210915_1ec4efa`
 - channels(root): `"nixos-20.09beta1346.05334ad7852"`
 - channels(demo): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by winterqt**
###### Motivation for this change

This is a fixed version of #133808, which was reverted in #138186 because of https://github.com/NixOS/nix/issues/5262.

I tested this by copying to an external script, and like the previous PR, this requires `LC_ALL=C`. (thank you for noting that in the original PR @smancill, I wouldn't of realized that otherwise.)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by veprbl** [comment]
This needs to go to staging-next

**Comment by smancill** [comment]
This is the interdiff with previous PR:

``` diff
diff -u b/pkgs/stdenv/generic/setup.sh b/pkgs/stdenv/generic/setup.sh
--- b/pkgs/stdenv/generic/setup.sh
+++ b/pkgs/stdenv/generic/setup.sh
@@ -206,13 +206,13 @@
     read -r -n 4 -u "$fd" magic
     exec {fd}<&-
     # https://opensource.apple.com/source/lldb/lldb-310.2.36/examples/python/mach_o.py.auto.html
-    if [[ "$magic" = $'\xfe\xed\xfa\xcf' || "$magic" = $'\xcf\xfa\xed\xfe' ]]; then
+    if [[ "$magic" = $(echo -ne "\xfe\xed\xfa\xcf") || "$magic" = $(echo -ne "\xcf\xfa\xed\xfe") ]]; then
         # MH_MAGIC_64 || MH_CIGAM_64
         return 0;
-    elif [[ "$magic" = $'\xfe\xed\xfa\xce' || "$magic" = $'\xce\xfa\xed\xfe' ]]; then
+    elif [[ "$magic" = $(echo -ne "\xfe\xed\xfa\xce") || "$magic" = $(echo -ne "\xce\xfa\xed\xfe") ]]; then
         # MH_MAGIC || MH_CIGAM
         return 0;
-    elif [[ "$magic" = $'\xca\xfe\xba\xbe' || "$magic" = $'\xbe\xba\xfe\xca' ]]; then
+    elif [[ "$magic" = $(echo -ne "\xca\xfe\xba\xbe") || "$magic" = $(echo -ne "\xbe\xba\xfe\xca") ]]; then
         # FAT_MAGIC || FAT_CIGAM
         return 0;
     else
```

It's functionally the same, and I see that it doesn't break `declare` now:

``` bash
source is_macho.sh && declare -f isMachO
isMachO ()
{
    local fn="$1";
    local fd;
    local magic;
    exec {fd}< "$fn";
    read -r -n 4 -u "$fd" magic;
    exec {fd}>&-;
    if [[ "$magic" = $(echo -ne "\xfe\xed\xfa\xcf") || "$magic" = $(echo -ne "\xcf\xfa\xed\xfe") ]]; then
        return 0;
    else
        if [[ "$magic" = $(echo -ne "\xfe\xed\xfa\xce") || "$magic" = $(echo -ne "\xce\xfa\xed\xfe") ]]; then
            return 0;
        else
            if [[ "$magic" = $(echo -ne "\xca\xfe\xba\xbe") || "$magic" = $(echo -ne "\xbe\xba\xfe\xca") ]]; then
                return 0;
            else
                return 1;
            fi;
        fi;
    fi
}
```

File: pkgs/stdenv/generic/setup.sh [hunk 1]
```diff
@@ -197,6 +197,29 @@ isELF() {
...
+        return 0;
+    elif [[ "$magic" = $(echo -ne "\xfe\xed\xfa\xce") || "$magic" = $(echo -ne "\xce\xfa\xed\xfe") ]]; then
+        # MH_MAGIC || MH_CIGAM
+        return 0;
+    elif [[ "$magic" = $(echo -ne "\xca\xfe\xba\xbe") || "$magic" = $(echo -ne "\xbe\xba\xfe\xca") ]]; then
+        # FAT_MAGIC || FAT_CIGAM
+        return 0;
+    else
+        return 1;
+    fi
```
Comment (lovesegfault) [inline pkgs/stdenv/generic/setup.sh:220]: Please add a comment documenting why these highly unintuitive `$(echo -ne "...")`'s are needed. I could easily see myself looking at this code and getting rid of the echo's thinking they were nonsense.

**Review by lovesegfault — CHANGES_REQUESTED** [review]

**Review by smancill — APPROVED** [review]

**Comment by smancill** [comment]
My main doubt is still that `LC` needs to be `C` or `read` will not read 4 bytes, but when I put the function manually in a build hook of a random derivation it worked fine.

File: pkgs/stdenv/generic/setup.sh (hunk 1 above)
Comment (winterqt) [reply pkgs/stdenv/generic/setup.sh:220]: Not really sure how to word this, does this sound good?

```bash
# See https://github.com/NixOS/nixpkgs/pull/138334 and https://github.com/NixOS/nix/issues/5262 for the reasoning as to why these `echo -e` invocations are needed
```

**Comment by kira-bruneau** [comment]
@winterqt Thanks for this fix! Although, ideally this bug should be fixed in Nix. `get-env.sh` just needs to escape characters outside of the `0x20..0x7F` byte range with `\u`: https://github.com/NixOS/nix/issues/5262#issuecomment-922145950.

**Comment by winterqt** [comment]
> Although, ideally this bug should be fixed in Nix. `get-env.sh` just needs to escape characters outside of the `0x20..0x7F` byte range with `\u`: [NixOS/nix#5262 (comment)](https://github.com/NixOS/nix/issues/5262#issuecomment-922145950).

I agree. However, I think that having a working version of this function is better than not, while Nix is getting fixed. (see https://github.com/NixOS/nixpkgs/pull/133808#issuecomment-922020502)

I'll defer to others to see if we want to merge this or not.

File: pkgs/stdenv/generic/setup.sh (hunk 1 above)
Comment (smancill) [reply pkgs/stdenv/generic/setup.sh:220]: I think it would be good to be more detailed:

```
# nix uses 'declare -F' in get-env.sh to retrieve the loaded functions.
# If we use the $'string' syntax instead of 'echo -ne' then 'declare' will print the raw characters and break nix.
# See https://github.com/NixOS/nixpkgs/pull/138334 and https://github.com/NixOS/nix/issues/5262.
```

**Comment by winterqt** [comment]
(sorry about that extra review request Sebastian, was unsure if I should do that for the comment addition but decided not to bother you any more after it was too late)

**Review by veprbl — APPROVED** [review]
I did a quick test and it works, although only for LC_ALL=C, although that's not a fault of this PR.

Perhaps a better approach would be to convert it to do `[ "$(od -An -N4 -t x1 /bin/sh)" = " cf fa ed fe" ] && echo true || echo false`.

**Comment by sternenseemann** [comment]
Any reason why this can't be a darwin-specific setup hook? I don't imagine we'd need this on Linux.

**Comment by veprbl** [comment]
> Any reason why this can't be a darwin-specific setup hook? I don't imagine we'd need this on Linux.

You will have to copy-paste this to every setup hook where it's used or invent some system to import the bash code

**Comment by sternenseemann** [comment]
setup hooks are sourced, so as long as the order is alright (and you could add it early in the darwin stdenv), it should work just fine.

**Comment by veprbl** [comment]
> setup hooks are sourced, so as long as the order is alright (and you could add it early in the darwin stdenv), it should work just fine.

Yes, you would also need to implement fallbacks for each isMachO call on non-darwin system. Of course, with some hacks that should be possible, but I don't yet see the elegant solution here.

**Comment by vcunat** [comment]
I figured it could be useful when cross-compiling from a non-darwin.

**Comment by AndersonTorres** [comment]
Does it close the issues?

**Comment by winterqt** [comment]
This closes #138157, yes.
