### PR TITLE
deterministic-uname: init

### LINKED ISSUE #140175: libgtop is not reproducible
### Describe the bug

libgtop is not reproducible, since it embed the output of `uname -r / -s / -v / -m` into one of its binaries.

### Steps To Reproduce

See [r13y](https://r13y.com/iso_gnome/diff/a065a4a046ce2fd0b3d39fecfeee252e255cc6c62aee33a5e78fe2fe453c3325-b88c54c2ca5f90e44b548e9a1fcd0934bb14d599e4b194c275731d6250daa8a4.html) or build on 2 machines with different kernel versions.

Report attached since r13y will not keep it, I think:
[diffoscope-report-r13y.html.txt](https://github.com/NixOS/nixpkgs/files/7269057/diffoscope-report-r13y.html.txt)

### Expected behavior

libgtop build should be reproducible.

### Additional context

This patch works from a nixpkgs perspective:

```patch
diff --git a/pkgs/development/libraries/libgtop/default.nix b/pkgs/development/libraries/libgtop/default.nix
index 98b0dc89fee..5e0f53d3fa3 100644
--- a/pkgs/development/libraries/libgtop/default.nix
+++ b/pkgs/development/libraries/libgtop/default.nix
@@ -7,6 +7,7 @@
 , gobject-introspection
 , gnome
 , gtk-doc
+, autoreconfHook
 }:
 
 stdenv.mkDerivation rec {
@@ -24,12 +25,23 @@ stdenv.mkDerivation rec {
     perl
     gettext
     gobject-introspection
+
+    # required due to patching the Makefile.am file
+    autoreconfHook
   ];
 
   propagatedBuildInputs = [
     glib

   ];
 
+  postPatch = ''
+    substituteInPlace src/daemon/Makefile.am \
+      --replace "\`uname -s\`" "DUMMY_KERNEL_NAME" \
+      --replace "\`uname -r\`" "DUMMY_KERNEL_RELEASE" \
+      --replace "\`uname -v\`" "DUMMY_KERNEL_VERSION" \
+      --replace "\`uname -m\`" "DUMMY_KERNEL_MACHINE"
+  '';
+
```

However, it should ideally be reported and fixed upstream.

### Notify maintainers

@NixOS/gnome 

### Metadata

N/A

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute: libgtop
```

### PR DESCRIPTION
**Pull request by Artturin**
for reproducibility

based on https://github.com/NixOS/nixpkgs/pull/64258

Closes https://github.com/NixOS/nixpkgs/issues/140175 and probably more

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/build-support/fake-uname/fake-uname.sh [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+machine=0
+processor=0
+hardware_platform=0
+operating_system=0
+
+
+@getopt@/bin/getopt --test > /dev/null && rc=$? || rc=$?
+if [[ $rc -ne 4 ]]; then
+  # This shouldn't happen.
+  echo "Warning: Enhanced getopt not supported, please open an issue." >&2
```
Comment (Mindavi) [inline pkgs/build-support/fake-uname/fake-uname.sh:45]: An issue in nixpkgs, presumably?

File: pkgs/build-support/fake-uname/fake-uname.sh [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+
+KERNEL_NAME_VAL=@uSystem@
+NODENAME_VAL=nixpkgs
+KERNEL_RELEASE_VAL=@modDirVersion@
+# #1-NixOS SMP PREEMPT_DYNAMIC Wed Dec 14 10:41:06 UTC 2022
+KERNEL_VERSION_VAL="#1-NixOS Tue Jan 1 00:00:00 UTC 1980"
+MACHINE_VAL=@processor@
+PROCESSOR_VAL=unknown
+HARDWARE_PLATFORM_VAL=unknown
+OPERATING_SYSTEM_VAL=GNU/Linux
```
Comment (Artturin) [inline pkgs/build-support/fake-uname/fake-uname.sh:120]: we should add `uname -o` to
https://github.com/NixOS/nixpkgs/blob/23776053143c7cf4ac6f5c68c1779d278748cbd9/lib/systems/default.nix#L88-L115

File: pkgs/development/libraries/libgtop/default.nix [hunk 3]
```diff
@@ -26,6 +27,7 @@ stdenv.mkDerivation rec {
     perl
     gettext
     gobject-introspection
+    fake-uname
```
Comment (Mindavi) [inline pkgs/development/libraries/libgtop/default.nix:30]: How is it ensured that this uname takes precedence over other uname implementations?

File: pkgs/build-support/fake-uname/default.nix [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+  name = "uname";
+
+  src = ./fake-uname.sh;
+
+  dir = "bin";
+  isExecutable = true;
+
+  inherit coreutils getopt;
+
+  uSystem = stdenv.buildPlatform.uname.system;
```
Comment (Mindavi) [inline pkgs/build-support/fake-uname/default.nix:20]: Does this eval correctly if kernel is none? I never know exactly how that works.

File: pkgs/build-support/fake-uname/fake-uname.sh (hunk 1 above)
Comment (Artturin) [reply pkgs/build-support/fake-uname/fake-uname.sh]: added `in nixpkgs` to both here and lsb_release

**Review by Mindavi — COMMENTED** [review]
I approve of this as it's a lot less controversial that outright replacing uname everywhere. It might be a bit more annoying to apply to the right packages (less scalable), but it's a good first step towards solving impurity issues with uname. If this is applied in too many places we can always reconsider the replacement option.

File: pkgs/development/libraries/libgtop/default.nix (hunk 3 above)
Comment (Artturin) [reply pkgs/development/libraries/libgtop/default.nix:30]: https://github.com/NixOS/nixpkgs/blob/6abb95c34492ccdbee0f6595b07f798e7bb11e0f/pkgs/stdenv/linux/default.nix#L492-L493

https://github.com/NixOS/nixpkgs/blob/6abb95c34492ccdbee0f6595b07f798e7bb11e0f/pkgs/stdenv/generic/default.nix#L133-L134

https://github.com/NixOS/nixpkgs/blob/6abb95c34492ccdbee0f6595b07f798e7bb11e0f/pkgs/stdenv/generic/setup.sh#L274-L287

somehow PATH contains the nativeBuildInputs first and then common-path
```
declare -x PATH="/nix/store/k2vd7w2ixbqbgd9v88am8780111bng7j-pkg-config-wrapper-0.29.2/bin:/nix/store/lw5mv8qzyalks7w80a6615na48i8lny1-gtk-doc-1.33.2/bin:/nix/store/n48i43wkly6kfhxz4ypcxbsv2pr7ggzh-perl-5.36.0/bin:/nix/store/zms41v0fgzfq4z629kn5jrlcv7hf9w7v-gettext-0.21/bin:/nix/store/3qgzjk0i8g7gif5jly94nbph0jwx4d0s-gobject-introspection-wrapped-1.74.0-dev/bin:/nix/store/02ggkplpkvdjkr20bylnidhn7cyh66m4-glib-2.74.3-dev/bin:/nix/store/k886wb6j8m1jwxf5pf1d5mdmlyblyd1y-glib-2.74.3-bin/bin:/nix/store/g2nfbpind37b3v3y6zbszmcgfmrj5v7x-patchelf-0.15.0/bin:/nix/store/wn31i3dzwahz6ccws8bs1nwyqrpgsvj7-gcc-wrapper-11.3.0/bin:/nix/store/sxdx80lmk4zkhb51f4x5dgqvxgmx55wl-gcc-11.3.0/bin:/nix/store/s7ip867mrpnnjlppbnxlcsq10gv13x2x-glibc-2.35-224-bin/bin:/nix/store/h8gvq6r4hgpa71h44dmg9qfx03mj81sv-coreutils-9.1/bin:/nix/store/62fb427ncxaaksa2k59rhbilfg68v20x-binutils-wrapper-2.39/bin:/nix/store/frh9l9nrdysasdi2gs7i241s241ngjw2-binutils-2.39/bin:/nix/store/w73bxii8xlsm9459628glawfcjlci75d-gobject-introspection-1.74.0-dev/bin:/nix/store/h8gvq6r4hgpa71h44dmg9qfx03mj81sv-coreutils-9.1/bin:/nix/store/zml88vnkpm8if114qkbbqd1q7n3ypqqy-findutils-4.9.0/bin:/nix/store/49y3r0gr9m6k20d91kl6dgp4b9a6m72v-diffutils-3.8/bin:/nix/store/5dv5cq1lwvsijr9p16p2kp79g1dbajk3-gnused-4.8/bin:/nix/store/bcvccw6y9bfil6xrl5j7psza7hnd16ry-gnugrep-3.7/bin:/nix/store/l1fp0hyca54xbb85vfhppd16bskzx8dg-gawk-5.1.1/bin:/nix/store/89zbjdkb48ma61k76l2mzn3s0ra0wn2c-gnutar-1.34/bin:/nix/store/qs8qb1swpivkfq7i9yd52n0mw6z4ij81-gzip-1.12/bin:/nix/store/wwkyfg8b34xy16zzc9p6rkh59p4q37qx-bzip2-1.0.8-bin/bin:/nix/store/i0x4pzj96qwvkrm94317l6jbi53a2rdj-gnumake-4.4/bin:/nix/store/4xw8n979xpivdc46a9ndcvyhwgif00hz-bash-5.1-p16/bin:/nix/store/793iwfbjvg7wgpqq7r83a1qjl1yg02sf-patch-2.7.6/bin:/nix/store/a3mwv26f99ycsv9w6hrx0jjjjywvcb1n-xz-5.2.9-bin/bin:/nix/store/camlh5laf1wsklghk0vcaw7gvx4rpzd1-file-5.43/bin"
```

Comment (Artturin) [reply pkgs/development/libraries/libgtop/default.nix:30]: if someone does this then the fake-uname won't be used but if coreutils is after fake-uname then the fake is used
```
diff --git a/pkgs/development/libraries/libgtop/default.nix b/pkgs/development/libraries/libgtop/default.nix
index 59db7929240..8a256e5f811 100644
--- a/pkgs/development/libraries/libgtop/default.nix
+++ b/pkgs/development/libraries/libgtop/default.nix
@@ -8,6 +8,7 @@
 , gnome
 , gtk-doc
 , fake-uname
+, coreutils
 }:
 
 stdenv.mkDerivation rec {
@@ -27,6 +28,7 @@ stdenv.mkDerivation rec {
     perl
     gettext
     gobject-introspection
+    coreutils
     fake-uname
   ];
 ```

Comment (jtojnar) [reply pkgs/development/libraries/libgtop/default.nix:30]: Or possibly when one of the preceding dependencies propagates it?

Comment (jtojnar) [inline pkgs/development/libraries/libgtop/default.nix:30]: There needs to be a comment that this is to ensure reproducibility.

File: pkgs/build-support/fake-uname/default.nix (hunk 4 above)
Comment (Artturin) [reply pkgs/build-support/fake-uname/default.nix]: fix'd

File: pkgs/build-support/fake-uname/default.nix [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+  uSystem = if stdenv.buildPlatform.uname.system != null then stdenv.buildPlatform.uname.system else "unknown";
+  inherit (stdenv.buildPlatform.uname) system processor;
+
+  # in os-specific/linux module packages
+  # --replace '$(shell uname -r)' "${kernel.modDirVersion}" \
+  # is a common thing to do.
+  modDirVersion = if modDirVersion != "" then modDirVersion else "unknown";
+
+  meta = with lib; {
+    description = "Print certain system information (hardcoded with NixOS values)";
```
Comment (amjoseph-nixpkgs) [inline pkgs/build-support/fake-uname/default.nix:29]:
```suggestion
    description = "Print certain system information (hardcoded with <nixpkgs/lib/system> values)";
```

This package is definitely useful on non-NixOS Linux.  I'm guessing it's useful on Darwin too.

File: pkgs/build-support/fake-uname/default.nix [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+    license = [ licenses.mit ];
```
Comment (amjoseph-nixpkgs) [inline pkgs/build-support/fake-uname/default.nix:30]:
```suggestion
        Description = ''
      This package provides a replacement for `uname` whose output depends only
      on `stdenv.buildPlatform`.  It is meant to be used from within derivations.

      Many packages' build processes run `uname` at compile time and embed its
      output into the result of the build.  Since `uname` calls into the kernel,
      and the Nix sandbox currently does not intercept these calls, builds made
      on different kernels will produce different results.
    '';
    license = [ licenses.mit ];
```

File: pkgs/build-support/fake-uname/default.nix [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+    maintainers = with maintainers; [ artturin ];
+    platforms = platforms.unix;
```
Comment (amjoseph-nixpkgs) [inline pkgs/build-support/fake-uname/default.nix:32]:
```suggestion
    platforms = platforms.all;
```

File: pkgs/build-support/fake-uname/fake-uname.sh (hunk 2 above)
Comment (amjoseph-nixpkgs) [reply pkgs/build-support/fake-uname/fake-uname.sh:120]: IMHO there is no reason for a nixlang expression to need the value of `uname -o` at eval-time, is there?

Maybe put the table with those values in this package so people don't use it from random expressions without a good reason.  If a good reason appears we can always move it out of `fake-uname` into `lib/systems`.

File: pkgs/build-support/fake-uname/fake-uname.sh [hunk 8]
```diff
@@ -0,0 +1,175 @@
...
+
+
+if [[ "$version" = "1" ]]; then
+    # in case some script greps for GNU coreutils.
+    echo "uname (GNU coreutils) 9.1"
+    echo "NixOS fake-uname"
```
Comment (amjoseph-nixpkgs) [inline pkgs/build-support/fake-uname/fake-uname.sh:126]:
```suggestion
    echo "NixPkgs fake-uname"
```

**Review by ghost — COMMENTED** [review]
Apparently github no longer lets you leave resolvable comments without a "header" comment?  A glitch in the matrix.

File: pkgs/development/libraries/libgtop/default.nix (hunk 3 above)
Comment (amjoseph-nixpkgs) [reply pkgs/development/libraries/libgtop/default.nix]: Maybe `fake-uname` should be called `deterministic-uname`.

File: pkgs/build-support/fake-uname/fake-uname.sh (hunk 8 above)
Comment (Artturin) [reply pkgs/build-support/fake-uname/fake-uname.sh]: It's `Nixpkgs` btw

File: pkgs/development/libraries/libgtop/default.nix (hunk 3 above)
Comment (Artturin) [reply pkgs/development/libraries/libgtop/default.nix]: chose `deterministic-uname`

**Review by ghost — APPROVED** [review]

**Review by Mindavi — APPROVED** [review]

File: pkgs/build-support/deterministic-uname/default.nix [hunk 9]
```diff
@@ -0,0 +1,54 @@
...
+  # maybe add to lib/systems/default.nix uname attrset
+  # https://github.com/coreutils/coreutils/blob/7fc84d1c0f6b35231b0b4577b70aaa26bf548a7c/src/uname.c#L373-L374
+  # https://stackoverflow.com/questions/61711186/where-does-host-operating-system-in-uname-c-comes-from
+  # https://github.com/coreutils/gnulib/blob/master/m4/host-os.m4
+  operatingSystem =
+    if stdenv.buildPlatform.isLinux
+    then "GNU/Linux"
+    else if stdenv.buildPlatform.isDarwin
+    then "Darwin" # darwin isn't in host-os.m4 so where does this come from?
+    else "unknown";
```
Comment (Artturin) [inline pkgs/build-support/deterministic-uname/default.nix:33]: Added this

**Comment by Artturin** [comment]
sidenote

coreutils uname has basic supports for env vars but only on darwin since https://github.com/coreutils/coreutils/commit/e3d1ff04370b3e090e4cfeb8f6cc4a63590a516f

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/210569

**Comment by ajs124** [comment]
This seems to have broken the tarball job:
```
Nixpkgs is not allowed to use <nixpkgs> to refer to itself.
The offending files: /nix/store/79pm0hmza6jwi2swa62kzlh549ivy9jh-source/pkgs/build-support/deterministic-uname/default.nix
```

File: pkgs/build-support/deterministic-uname/default.nix [hunk 10]
```diff
@@ -0,0 +1,54 @@
...
+
+  # in os-specific/linux module packages
+  # --replace '$(shell uname -r)' "${kernel.modDirVersion}" \
+  # is a common thing to do.
+  modDirVersion = if modDirVersion != "" then modDirVersion else "unknown";
+
+  meta = with lib; {
+    description = "Print certain system information (hardcoded with <nixpkgs/lib/system> values)";
```
Comment (Artturin) [inline pkgs/build-support/deterministic-uname/default.nix:41]: @ajs124 it's catching the <> here, it should be changed to `with lib/system values`

Comment (Artturin) [reply pkgs/build-support/deterministic-uname/default.nix:41]: https://github.com/NixOS/nixpkgs/pull/210719

File: pkgs/build-support/deterministic-uname/deterministic-uname.sh [hunk 11]
```diff
@@ -0,0 +1,175 @@
...
+# output of the real uname from GNU coreutils
+# Darwin:
+#  Darwin *nodename* 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64 arm Darwin
+# NixOS:
+#  Linux *nodename* 6.0.13 #1-NixOS SMP PREEMPT_DYNAMIC Wed Dec 14 10:41:06 UTC 2022 x86_64 GNU/Linux
+if [[ "$all" = "1" ]]; then
+    echo -n "$KERNEL_NAME_VAL $NODENAME_VAL $KERNEL_RELEASE_VAL $KERNEL_VERSION_VAL $MACHINE_VAL"
+    # in help:  except omit -p and -i if unknown.
+    #echo -n "$PROCESSOR_VAL $HARDWARE_PLATFORM_VAL\n"
+    echo -n "$OPERATING_SYSTEM_VAL"
```
Comment (misuzu) [inline pkgs/build-support/deterministic-uname/deterministic-uname.sh:139]: Whitespace is missing:
```
$ nix shell nixpkgs#deterministic-uname -c uname -a
Linux nixpkgs unknown #1-NixOS Tue Jan 1 00:00:00 UTC 1980 x86_64GNU/Linux
```

Comment (Artturin) [reply pkgs/build-support/deterministic-uname/deterministic-uname.sh:139]: thanks fix in https://github.com/NixOS/nixpkgs/pull/213768

**Comment by Artturin** [comment]
> Would be awesome if this could be used in low-level packages (perl for example, adding `deterministic-uname` to `nativeBuildInputs` triggers infinite recursion) to build NixOS for armv7l-linux on aarch64 machines without [patching the kernel](https://github.com/nix-community/aarch64-build-box/pull/133).

for that we need to get rid of the coreutils and getopt dependencies or do something with bootstrapTools
