### PR TITLE
nixos/switch-to-configuration: Few minor/medium improvements

### LINKED ISSUE #116735: During nixos-rebuild: gitlab-runner.service is not active, cannot reload.
**Describe the bug**
When enabling `services.gitlab-runner` on a host with `virtualisation.docker` enabled, a `nixos-rebuild` encounters errors if `docker.service` needs to be restarted and `gitlab-runner.service` needs to be reloaded.

I'm seeing the following behavior:

```
stopping the following units: [...], docker.service, docker.socket, [...]
NOT restarting the following changed units: [...]
activating the configuration...
setting up /etc...
restarting systemd...
setting up tmpfiles
reloading the following units: [...], gitlab-runner.service, [...]
gitlab-runner.service is not active, cannot reload.
restarting the following units: [...]
starting the following units: [...], docker.socket, [...]
```

`gitlab-runner.service` seems to be inactive because it requires `docker.service`, which has been stopped earlier. After the rebuild, `gitlab-runner.service` is started correctly.

**To Reproduce**

Not sure how to trigger this combination of restarts and reloads, but I see this regularly on a `nixos-rebuild`.

**Expected behavior**
`nixos-rebuild` should not try to reload services it (transitively) shut down earlier.

**Notify maintainers**
- @zimbatm for gitlab-runner
- not sure who is responsible for the reload/restart logic in `nixos/modules/system/activation/switch-to-configuration.pl`

**Metadata**
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.97, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(root): `"nixos-20.03.2107.70717a337f7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
  - services.gitlab-runner
  - virtualisation.docker
```

### PR DESCRIPTION
**Pull request by dasJ**
###### Motivation for this change

Changeset is probably best reviewed by commit. In the order from oldest to newest:

1. Add a test for targets (people seem to like test coverage)
2. Ignore some keys in the `[Unit]` section of units. Should cut down even more on unnecessary service restarts
3. Fix a minor bug that I introduced regarding activation script restarts. See the commit message for details
4. Fixes #116735, so cc @kaldonir (and maybe @tfc?)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests)) → `switchTest`
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kaldonir** [comment]
>Fixes https://github.com/NixOS/nixpkgs/issues/116735, so cc @kaldonir

Thank you for taking a look at this! I'm actually not 100% sure this issue still applies to the specific combination of the gitlab-runner and docker services, because in our deployments, we had enabled `systemd.services.gitlab-runner.restartIfChanged` for unrelated reasons in the meantime. But it looks like a sensible fix in any case.

We had been seeing a kind of similar issue with `.automount` and `.mount` units, though: https://github.com/NixOS/nixpkgs/issues/155485. Would that issue be resolved with these changes as well?

**Comment by dasJ** [comment]
No, but I already have yet another patchset in the pipeline that fixes some mount/automount stuff ;)
There is no PR for that yet because it depends on this PR and I didn't want to bloat this one even more

File: nixos/modules/system/activation/switch-to-configuration.pl [hunk 1]
```diff
@@ -226,10 +239,20 @@ sub unrecord_unit {
...
+        IgnoreOnIsolate StopWhenUnneeded
+        RefuseManualStart RefuseManualStop
+        AllowIsolate CollectMode
+        SourcePath
+    );
 
     my $comp_array = sub {
       my ($a, $b) = @_;
-      return join("\0", @{$a}) eq join("\0", @{$b});
+      return join("\0", @{$a}) eq join "\0", @{$b};
```
Comment (stigtsp) [inline nixos/modules/system/activation/switch-to-configuration.pl:255]: Why drop the parens around the last join?

Comment (dasJ) [reply nixos/modules/system/activation/switch-to-configuration.pl:255]: That is a very good question. It's because of https://metacpan.org/pod/Perl::Critic::Policy::CodeLayout::ProhibitParensWithBuiltins

Now since there is no requirement to be 100% critic-compatible: Do you think we should just ignore this one rule in general? I somewhat understand their argument but when nesting builtin functions (like `join(split(…`) the code quickly becomes less readable imo
If you think we should ignore the rule I will rebase out that change

Comment (stigtsp) [reply nixos/modules/system/activation/switch-to-configuration.pl:255]: Imho; the `perlcritic` suggestion doesn't make sense in this case, as dropping the parens for the last join() call makes it inconsistent with the first, and makes them appear different.

**Review by cheriimoya — APPROVED** [review]

File: nixos/modules/system/activation/switch-to-configuration.pl (hunk 1 above)
Comment (dasJ) [reply nixos/modules/system/activation/switch-to-configuration.pl]: I agree with your point.
So much so that I didn't just rebase the change in but rather added another commit that adds parenthesis to **all** calls in the script.

**Comment by dasJ** [comment]
I also rebased in support for `RefuseManualStart` and `X-OnlyManualStart` when starting a non-reloadable unit, including a test case.

If nobody has objections, I'm inclined to merge this weekend.
@GrahamcOfBorg test switchTest

File: nixos/modules/system/activation/switch-to-configuration.pl (hunk 1 above)
Comment (stigtsp) [reply nixos/modules/system/activation/switch-to-configuration.pl]: :+1: Not my preference, but think [it's fine](https://en.wikipedia.org/wiki/There%27s_more_than_one_way_to_do_it) as long as it is consistent.

**Review by stigtsp — APPROVED** [review]
Diff LGTM

File: nixos/modules/system/activation/switch-to-configuration.pl [hunk 2]
```diff
@@ -104,14 +106,27 @@ sub getActiveUnits {
...
+# Returns whether a systemd unit is active
+sub unit_is_active {
+    my ($unit_name) = @_;
+
+    my $mgr = Net::DBus->system->get_service('org.freedesktop.systemd1')->get_object('/org/freedesktop/systemd1');
+    my $units = $mgr->ListUnitsByNames([$unit_name]);
+    if (scalar(@{$units}) == 0) {
+        return 0;
+    }
+    my $active_state = @{@{$units}[0]}[3]; ## no critic (ValuesAndExpressions::ProhibitMagicNumbers)
```
Comment (stigtsp) [inline nixos/modules/system/activation/switch-to-configuration.pl:118]: This could probably be written in a simpler way:

```suggestion
    my $active_state = $units->[0]->[3]; 
```

**Comment by ncfavier** [comment]
This seems to break biosCdrom https://hydra.nixos.org/build/169207916/nixlog/16

**Comment by ncfavier** [comment]
The single quotes around `@installBootLoader@` clash with the single quotes in the default value https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/activation/top-level.nix#L233

**Comment by dasJ** [comment]
Thank you for letting me know. If nobody is faster than me, I'll do a fixing PR first thing tomorrow morning
