### PR TITLE
prefetch-npm-deps: use isahc instead of ureq

### LINKED ISSUE #239190: buildNpmPackage / prefetch-npm-deps doesn't support proxy
### Describe the bug
`prefetch-npm-deps` doesn't support proxy. I have `http_proxy` and `https_proxy` environment variables defined, but it doesn't work which make it impossible to build something in closed corporate environments. Also I suspect that `NIX_SSL_CERT_FILE` environment (ca-certificates bundle) would not work also.

### Steps To Reproduce
1. A PC without direct Internet access. Only proxy is available for Internet access.
2. `http_proxy`, `https_proxy`, `NIX_SSL_CERT_FILE` environment variables are defined for nix-daemon.service.
3. Build any `buildNpmPackage` package. Or run `nix run nixpkgs#prefetch-npm-deps -- package-lock.json` inside some npm repository.

### Expected behavior
Npm dependencies successfully fetched.

### Screenshots
I've got an error "**Network is unreachable (os error 101)**". Example failed build log:

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/pgqsk8sdh6gg9kdqi8iijhw6sng6qwiv-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
node_modules/@babel/cli
node_modules/is-boolean-object
node_modules/@babel/plugin-transform-destructuring
node_modules/babel-plugin-dynamic-import-node
node_modules/string-width
node_modules/path-parse
Error: https://registry.npmjs.org/@babel/cli/-/cli-7.16.0.tgz: Connection Failed: Connect error: Network is unreachable (os error 101)

Caused by:
    Network is unreachable (os error 101)
```

### Additional context
Most of the fetchers work via proxy which intercepted ssl. This one not. I think all fetchers should support it.

### Notify maintainers

@winterqt 

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.18-59.34-default, SLES, 15-SP3, nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs-22.05pre338599.f6e14b6ada8"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by lilyinstarlight**
###### Description of changes

Ureq was giving us more problems than it was worth and couldn't easily support proxies or custom CA certs anyway

Isahc is based on libcurl and given we're linking it against nixpkgs curl, should support all of that with a few baked-in curl options that get set by the CLI in curl-based fetchers

@stasjok, could you test if this fixes your issue with fetching npm deps behind a proxy?
  - It should work the same as other fetchers now with the same env vars

@XYenon, could you test whether we need additional retry logic implemented by curl or if the defaults are sufficient?
  - I've only ever seen people really have trouble with connection errors, which should be alleviated by the use of libcurl. If we genuinely need to be detecting HTTP `503` or `429` too, then I'll update this code to deal with that case

Fixes #239190

Drive-by changes included: supporting `NIX_BUILD_CORES` in rayon, updating deps, adding `env_logger`, and supporting impure proxy variables in the fetcher

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/build-support/node/fetch-npm-deps/src/main.rs [hunk 1]
```diff
@@ -182,6 +182,15 @@ fn main() -> anyhow::Result<()> {
         process::exit(1);
     }
 
+    if let Ok(jobs) = env::var("NUM_JOBS") {
```
Comment (marsam) [inline pkgs/build-support/node/fetch-npm-deps/src/main.rs:185]: Shouldn't be `NIX_BUILD_CORES`?

Comment (lilyinstarlight) [reply pkgs/build-support/node/fetch-npm-deps/src/main.rs:185]: I thought stdenv set both, and figured this was a more general-use variable (I think `buildRustPackage` stuff uses `NUM_JOBS` too, but I'd have to double check when I'm not on mobile). I'm happy to change it though since I don't feel particularly strongly on it

Comment (lilyinstarlight) [reply pkgs/build-support/node/fetch-npm-deps/src/main.rs]: Done, thanks for catching that!

**Comment by XYenon** [comment]
I not really seen an HTTP `503` or `429` error, just copied from [ureq's example](https://docs.rs/ureq/latest/src/ureq/error.rs.html#39)

**Comment by XYenon** [comment]
I found it still has connection errors.
image

**Comment by lilyinstarlight** [comment]
> I found it still have connection errors. image

Oh heck, I thought I got the TLS stuff working :(
Can you share the command you ran or the derivation to get that?
Also can you try it from my `tmp/feature/prefetch-npm-deps-isahc` branch with the `RUST_LOG=trace` environment variable set and share those logs?

**Comment by stasjok** [comment]
> @stasjok, could you test if this fixes your issue with fetching npm deps behind a proxy?

It seems not working via proxy at all. For now I don't build anything. Just running `nix run github:NixOS/nixpkgs/5ebcf21ddc77b2174abcd7c28f750a14692ee2b4#prefetch-npm-deps -- package-lock.json`. It doesn't use proxy at all. I've got a bunch of errors like:

```
Connection Failed for https://registry.npmjs.org/@babel/plugin-transform-destructuring/-/plugin-transform-destructuring-7.16.5.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/babel-plugin-dynamic-import-node/-/babel-plugin-dynamic-import-node-2.3.3.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/plugin-syntax-class-static-block/-/plugin-syntax-class-static-block-7.14.5.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/plugin-proposal-async-generator-functions/-/plugin-proposal-async-generator-functions-7.16.5.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/cli/-/cli-7.16.0.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.2.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/plugin-transform-destructuring/-/plugin-transform-destructuring-7.16.5.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/babel-plugin-dynamic-import-node/-/babel-plugin-dynamic-import-node-2.3.3.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/plugin-proposal-async-generator-functions/-/plugin-proposal-async-generator-functions-7.16.5.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/plugin-syntax-class-static-block/-/plugin-syntax-class-static-block-7.14.5.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/cli/-/cli-7.16.0.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.2.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/babel-plugin-dynamic-import-node/-/babel-plugin-dynamic-import-node-2.3.3.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/plugin-transform-destructuring/-/plugin-transform-destructuring-7.16.5.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/plugin-syntax-class-static-block/-/plugin-syntax-class-static-block-7.14.5.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/plugin-proposal-async-generator-functions/-/plugin-proposal-async-generator-functions-7.16.5.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.2.tgz, retry in 5
Connection Failed for https://registry.npmjs.org/@babel/cli/-/cli-7.16.0.tgz, retry in 5
```

**Comment by stasjok** [comment]
OK. I've built npm package successfully. What I did:

* Run `nix repl github:NixOS/nixpkgs/d0ae6f88dac6573d72e796bc77a272f872760617#legacyPackages.x86_64-linux`
* `:bl vscode-langservers-extracted.override {vscode=pkgs.vscodium;}`

Package was built successfully. SSL part (ignoring SSL certificates completely if output hash is known) also works (my proxy intercepts ssl certificates, so cacert from nixpkgs wouldn't work).

**Comment by lilyinstarlight** [comment]
@stasjok So it works for you both standalone and inside a derivation then?

**Comment by stasjok** [comment]
> @stasjok So it works for you both standalone and inside a derivation then?

Yes. I think so.

**Comment by stasjok** [comment]
Actually looks like I didn't check ignoring SSL certificate, because my proxy somehow don't intercept connections to registry.npmjs.org. I've got a valid cloudflare certificate. But the derivation has `SSL_CERT_FILE=/no-cert-file.crt`, so I think it works anyway.

**Comment by XYenon** [comment]
> > I found it still have connection errors. image
> 
> Oh heck, I thought I got the TLS stuff working :( Can you share the command you ran or the derivation to get that? Also can you try it from my `tmp/feature/prefetch-npm-deps-isahc` branch with the `RUST_LOG=trace` environment variable set and share those logs?

I just run the `passthru.tests`. And I think it's caused by the unstable network, not really TLS problem.

**Comment by lilyinstarlight** [comment]
> I just run the `passthru.tests`. And I think it's caused by the unstable network, not really TLS problem.

Hmm, maybe openssl isn't that resilient then. I'll add some basic retry logic back then, thank you!

**Comment by lilyinstarlight** [comment]
@XYenon Can you test it with the retry logic I just pushed?

**Comment by XYenon** [comment]
> @XYenon Can you test it with the retry logic I just pushed?

LGTM : )

**Review by XYenon — APPROVED** [review]

File: pkgs/build-support/node/fetch-npm-deps/src/util.rs [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+            request = request.ssl_options(SslOption::DANGER_ACCEPT_INVALID_CERTS);
+        }
+    }
+
+    Ok(request.body(())?.send()?.into_body())
+}
+
+pub fn get_url_with_retry(url: &Url) -> anyhow::Result<Body> {
+    // Retry up to 4 times, returning any valid result
+    for _ in 0..4 {
```
Comment (RaitoBezarius) [inline pkgs/build-support/node/fetch-npm-deps/src/util.rs:29]: Appropriate exp backoff here would be a good thing on the long run

**Review by RaitoBezarius — APPROVED** [review]
LGTM modulo retry logic which is static rather than following exponential backoff techniques which I think are required on the long run.

File: pkgs/build-support/node/fetch-npm-deps/src/util.rs (hunk 2 above)
Comment (lilyinstarlight) [reply pkgs/build-support/node/fetch-npm-deps/src/util.rs]: Done! :)

**Comment by lilyinstarlight** [comment]
This has approval and seems good for merge now. I'm gonna go ahead and merge so it doesn't rot, and we can do follow-ups if there are further comments

**Comment by lilyinstarlight** [comment]
Manual backport at #242267
