### PR TITLE
semgrep{,-core}: 0.112.1 -> 1.0.0

### LINKED ISSUE #192149: Semgrep crashes on `semgrep scan`
### Describe the bug
When you run `semgrep scan` it crashes with `Permission denied`, due to it trying to execute the `semgrep-core` binary, which doesn't have  that doesn't have it's executable bit set.
The `semgrep-core` binary has permissions `-r--r--r--`.

### Steps To Reproduce
1. Get a hold of `semgrep` packaged by nix
  `nix-shell -p semgrep`
2. Make a valid semgrep config file, otherwise `semgrep` complains about this and exits before it has the chance to crash.
    ```sh
    cat <<EOF > rule.yaml
    rules:
      - id: test-rule
        patterns:
          - pattern: "test"
        message: This is a message
        severity: WARNING
        languages:
          - typescript
    EOF
    ```
4. Make an empty directory for semgrep to look through, this helps it to crash quickly.
    `mkdir emptydir`
5. Run semgrep
    `semgrep scan --config=rule.yaml emptydir`
6. See that semgrep crashed which `Permission denied: '/nix/store/...-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/bin/semgrep-core'`

### Expected behavior
Semgrep doesn't crash, and reports/acts as specified in the config file.

### Additional context
<details>
<summary>Full stderr output</summary>

```
[Errno 13] Permission denied: '/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/bin/semgrep-core'
Traceback (most recent call last):
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/commands/scan.py", line 817, in scan
    ) = semgrep.semgrep_main.main(
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 410, in main
    ) = run_rules(
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/semgrep_main.py", line 168, in run_rules
    ) = core_runner.invoke_semgrep(
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/core_runner.py", line 951, in invoke_semgrep
    ) = self._run_rules_direct_to_semgrep_core(
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/core_runner.py", line 869, in _run_rules_direct_to_semgrep_core
    returncode = runner.execute()
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/core_runner.py", line 396, in execute
    rc = asyncio.run(self._stream_exec_subprocess())
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/core_runner.py", line 307, in _stream_exec_subprocess
    process = await asyncio.create_subprocess_exec(
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/sz0j8k8ljh7y8qgyfxgqb3ws11bcy4gs-python3-3.10.6/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/nix/store/8br1kry2ww91q8pp46ljjm5c46hly6x9-semgrep-0.112.1/lib/python3.10/site-packages/semgrep/bin/semgrep-core'
```
</details>

### Notify maintainers
@06kellyjac @ambroisie 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.19.5, NixOS, 22.11 (Raccoon), 22.11pre405560.2da64a81275`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.11.0`
 - channels(user): `"home-manager"`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

### PR DESCRIPTION
**Pull request by 06kellyjac**
###### Description of changes

Bumped semgrep and added an update script

I have a different issue that is blocking me from checking if the issue above is fixed:
I've added `tomli` but it's not picking it up when running semgrep scan
It's also supprising that the pip hook doesn't complain if I don't include `tomli` even though setup.py asks for it...

To reproduce follow the same steps as the issue above & see issues with finding `tomli`

---

Update:

now resolves #192149
setup.py was copying semgrep-core and had issues keeping or setting the executable bit.
rather than mess about trying to fix it I went with the more desirable solution of providing semgrep-core via wrapping rather than copying it around

the `tomli` issue seems to have disappeared.

tested with https://semgrep.dev/docs/writing-rules/rule-ideas/#ban-dangerous-apis

```
λ /some/dir/nixpkgs/result/bin/semgrep scan --config=rule.yaml .
Scanning 1 file.

Blocking Findings:

  tmp.js 
     react-dangerouslysetinnerhtml
        Setting HTML from code is risky because it’s easy to inadvertently expose your users to a
        cross-site scripting (XSS) attack.

          3┆ return <div dangerouslySetInnerHTML={createMarkup()} />;

Blocking Rules Fired:
   react-dangerouslysetinnerhtml


Ran 1 rule on 1 file: 1 finding.
```

cc: @SuperSandro2000

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/tools/security/semgrep/update.sh [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+
+set -euxo pipefail
+
+ROOT="$(dirname "$(readlink -f "$0")")"
+NIXPKGS_ROOT="$ROOT/../../../.."
+NIX_DRV="$ROOT/default.nix"
+if [ ! -f "$NIX_DRV" ]; then
+  echo "ERROR: cannot find default.nix in $ROOT"
+  exit 1
+fi
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:12]: We don't need to check for this

File: pkgs/tools/security/semgrep/update.sh [hunk 2]
```diff
@@ -0,0 +1,149 @@
...
+
+COMMON_FILE="$ROOT/common.nix"
+
+instantiateClean() {
+    nix-instantiate -A "$1" --eval --strict | cut -d\" -f2
+}
+
+# get latest version
+NEW_VERSION=$(curl -s https://api.github.com/repos/returntocorp/semgrep/releases/latest | jq -r '.tag_name')
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:21]: This should optionally take a GITHUB_TOKEN

File: pkgs/tools/security/semgrep/update.sh [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+    nix --experimental-features nix-command hash to-sri "sha256:$1"
+}
+
+coreHash() {
+    instantiateClean semgrep.common.core.data."$1".sha256
+}
+coreSuffix() {
+    instantiateClean semgrep.common.core.data."$1".suffix
+}
+
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:45]:
```suggestion
```

File: pkgs/tools/security/semgrep/update.sh [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+echo "Updated src"
+
+# loop through platforms for core
+nix-instantiate -E "with import $NIXPKGS_ROOT {}; builtins.attrNames semgrep.common.core.data" --eval --strict --json \
+| jq '.[]' -r \
+| while read -r PLATFORM; do
+    echo "Updating core for $PLATFORM"
+    SUFFIX=$(coreSuffix "$PLATFORM")
+    OLD_HASH=$(coreHash "$PLATFORM")
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:78]:
```suggestion
    SUFFIX=$(instantiateClean semgrep.common.core.data."$PLATFORM".suffix)
    OLD_HASH=$(instantiateClean semgrep.common.core.data."$PLATFORM".sha256)
```

File: pkgs/tools/security/semgrep/update.sh [hunk 5]
```diff
@@ -0,0 +1,149 @@
...
+fi
+
+replace() {
+    sed -i "s@$1@$2@g" "$3"
+}
+
+to_sri() {
+    nix --experimental-features nix-command hash to-sri "sha256:$1"
+}
+
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:38]:
```suggestion
```

File: pkgs/tools/security/semgrep/update.sh [hunk 6]
```diff
@@ -0,0 +1,149 @@
...
+    OLD_REV=$(submoduleRev "$SUBMODULE")
+    echo "Old commit $OLD_REV"
+    OLD_HASH=$(submoduleHash "$SUBMODULE")
+    echo "Old hash $OLD_HASH"
+
+    NEW_REV=$(get_submodule_commit "$SUBMODULE")
+    echo "New commit $NEW_REV"
+
+    NEW_URL=$(submoduleNewUrl "$SUBMODULE" "$OLD_REV" "$NEW_REV")
+    NEW_HASH=$(to_sri "$(nix-prefetch-url "$NEW_URL")")
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:134]:
```suggestion
    NEW_HASH=$(nix --experimental-features nix-command hash to-sri "sha256:$(nix-prefetch-url "$NEW_URL")")
```

File: pkgs/tools/security/semgrep/update.sh [hunk 7]
```diff
@@ -0,0 +1,149 @@
...
+    instantiateClean semgrep.passthru.common.submodules."$1".outputHash
+}
+
+submoduleNewUrl() {
+    SUBMODULE="$1"
+    OLD_REV="$2"
+    NEW_REV="$3"
+    instantiateClean semgrep.passthru.common.submodules."$SUBMODULE".url | sed "s@$OLD_REV@$NEW_REV@g"
+}
+
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:119]:
```suggestion
```

File: pkgs/tools/security/semgrep/update.sh [hunk 8]
```diff
@@ -0,0 +1,149 @@
...
+    echo "Updating $SUBMODULE"
+    OLD_REV=$(submoduleRev "$SUBMODULE")
+    echo "Old commit $OLD_REV"
+    OLD_HASH=$(submoduleHash "$SUBMODULE")
+    echo "Old hash $OLD_HASH"
+
+    NEW_REV=$(get_submodule_commit "$SUBMODULE")
+    echo "New commit $NEW_REV"
+
+    NEW_URL=$(submoduleNewUrl "$SUBMODULE" "$OLD_REV" "$NEW_REV")
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:133]:
```suggestion
    NEW_URL=$(instantiateClean semgrep.passthru.common.submodules."$SUBMODULE".url | sed "s@$OLD_REV@$NEW_REV@g")
```

File: pkgs/tools/security/semgrep/update.sh [hunk 9]
```diff
@@ -0,0 +1,149 @@
...
+}
+
+submoduleRev() {
+    instantiateClean semgrep.passthru.common.submodules."$1".rev
+}
+
+submoduleHash() {
+    instantiateClean semgrep.passthru.common.submodules."$1".outputHash
+}
+
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:112]:
```suggestion
```

File: pkgs/tools/security/semgrep/update.sh [hunk 10]
```diff
@@ -0,0 +1,149 @@
...
+# loop through submodules
+nix-instantiate -E "with import $NIXPKGS_ROOT {}; builtins.attrNames semgrep.passthru.common.submodules" --eval --strict --json \
+| jq '.[]' -r \
+| while read -r SUBMODULE; do
+    echo "Updating $SUBMODULE"
+    OLD_REV=$(submoduleRev "$SUBMODULE")
+    echo "Old commit $OLD_REV"
+    OLD_HASH=$(submoduleHash "$SUBMODULE")
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:127]:
```suggestion
    OLD_REV=$(instantiateClean semgrep.passthru.common.submodules."$SUBMODULE".rev)
    echo "Old commit $OLD_REV"
    OLD_HASH=$(instantiateClean semgrep.passthru.common.submodules."$SUBMODULE".outputHash)
```

File: pkgs/tools/security/semgrep/update.sh [hunk 11]
```diff
@@ -0,0 +1,149 @@
...
+# loop through platforms for core
+nix-instantiate -E "with import $NIXPKGS_ROOT {}; builtins.attrNames semgrep.common.core.data" --eval --strict --json \
+| jq '.[]' -r \
+| while read -r PLATFORM; do
+    echo "Updating core for $PLATFORM"
+    SUFFIX=$(coreSuffix "$PLATFORM")
+    OLD_HASH=$(coreHash "$PLATFORM")
+    echo "Old hash $OLD_HASH"
+
+    # NEW_REV=$(get_submodule_commit "$SUBMODULE")
```
Comment (SuperSandro2000) [inline pkgs/tools/security/semgrep/update.sh:81]:
```suggestion
```

**Review by SuperSandro2000 — COMMENTED** [review]
I tried to simplify the update script a bit

Is the python script correct wrapped?

**Comment by 06kellyjac** [comment]
> Is the python script correct wrapped?

It was working fine until a couple versions ago when they added tomli as a dependency. tomli seems to be the only dependency with an issue 🤷‍♂️

File: pkgs/tools/security/semgrep/default.nix [hunk 12]
```diff
@@ -15,26 +15,53 @@ let
...
+  postPatch = (lib.concatStringsSep "\n" (lib.mapAttrsToList (
+    path: submodule: ''
+      # substitute ${path}
+      # remove git submodule placeholder
+      rm -r ${path}
+      # link submodule
+      ln -s ${submodule}/ ${path}
+    ''
+  ) common.submodules)) + ''
+    cd cli
```
Comment (06kellyjac) [inline pkgs/tools/security/semgrep/default.nix:29]: is there a more nix-ie way to do this? :shrug:

**Review by ambroisie — APPROVED** [review]

File: pkgs/tools/security/semgrep/default.nix (hunk 12 above)
Comment (RaitoBezarius) [reply pkgs/tools/security/semgrep/default.nix:29]: I don't think so, but a comment explaining what is going on and why this is needed would be helpful!

File: pkgs/tools/security/semgrep/update.sh [hunk 13]
```diff
@@ -0,0 +1,139 @@
...
+    NEW_REV=$(get_submodule_commit "$SUBMODULE")
+    echo "New commit $NEW_REV"
+
+    if [[ "$OLD_REV" == "$NEW_REV" ]]; then
+      echo "$SUBMODULE already up to date"
+      continue
+    fi
+
+    NEW_URL=$(instantiateClean semgrep.passthru.common.submodules."$SUBMODULE".url | sed "s@$OLD_REV@$NEW_REV@g")
+    NEW_HASH=$(nix --experimental-features nix-command hash to-sri "sha256:$(nix-prefetch-url "$NEW_URL")")
```
[the remark this answers is not in the document]
Comment (ambroisie) [reply pkgs/tools/security/semgrep/update.sh:124]: It's been done in other update scripts, IMO it is fine to use it in this instance.

Since this is only used to convert to the new-style hashes, it is not load-bearing and could be removed if need be.

[the remark this answers is not in the document]
Comment (RaitoBezarius) [reply pkgs/tools/security/semgrep/update.sh:124]: Fair

**Comment by SuperSandro2000** [comment]
@ofborg build semgrep

File: pkgs/tools/security/semgrep/default.nix (hunk 12 above)
Comment (Et7f3) [reply pkgs/tools/security/semgrep/default.nix:29]: Does `fetchSubmodules = true` is a viable option ?
https://github.com/NixOS/nixpkgs/blob/master/doc/builders/fetchers.chapter.md#fetchgit-fetchgit
