### PR TITLE
darwin (Big Sur): tbd based stdenv

### LINKED ISSUE #91748: impossible to link (ld / clang) liboping on macOS Big Sur 11 Beta
**Describe the bug**
Compilation fail

**To Reproduce**
1. add this line into `~/.config/nixpkgs/config.nix` otherwise it's impossible to install on macOS:
```
( pkgs.liboping.overrideDerivation (old: {NIX_CFLAGS_COMPILE = "";} ) )
```
2. nix-env -i all

**Expected behavior**
Don't fail and arrive to do the linking (ld)

**Output**
```
building '/nix/store/0psa9x9abc3yhv4r2pnw44q0ywi15v4y-liboping-1.10.0.drv'...
unpacking sources
unpacking source archive /nix/store/x1f1kszhpxb4x4c8j9dqag614kyx56d6-liboping-1.10.0.tar.bz2
source root is liboping-1.10.0
setting SOURCE_DATE_EPOCH to timestamp 1494487978 of file liboping-1.10.0/src/mans/ping_iterator_get_info.3
patching sources
configuring
fixing libtool script ./ltmain.sh
configure flags: --disable-static --disable-dependency-tracking --prefix=/nix/store/s45i6bciaw48mv9s0xfwhh3m7vpiqy8s-liboping-1.10.0
checking for a BSD-compatible install... /nix/store/j0xbl8447zrk5f97d6w55d2l8qaldjxy-coreutils-8.31/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/j0xbl8447zrk5f97d6w55d2l8qaldjxy-coreutils-8.31/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/var/folders/g5/ljjjnl3x4fq4x9tg69wy3lqh0000gn/T/nix-build-liboping-1.10.0.drv-0/liboping-1.10.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
builder for '/nix/store/0psa9x9abc3yhv4r2pnw44q0ywi15v4y-liboping-1.10.0.drv' failed with exit code 77
cannot build derivation '/nix/store/qbsyr9i6wrv43rnfjdw9v2nf9kgav62f-all.drv': 1 dependencies couldn't be built
error: build of '/nix/store/qbsyr9i6wrv43rnfjdw9v2nf9kgav62f-all.drv' failed
```

**Notify maintainers**

Contributors from https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/liboping/default.nix:
- @fpletz
- @bjornfor
- @volth
- @OmnipotentEntity
- @globin
- @Ericson2314

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.0.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(sycured): `"nixpkgs-20.09pre231837.2cd2e7267e5"`
 - nixpkgs: `/Users/sycured/.nix-defexpr/channels/nixpkgs`

host os detected isn't real because it's macOS 11.0 Beta, not 10.16 : 
Screen Shot 2020-06-28 at 23 00 37

### PR DESCRIPTION
**Pull request by thefloweringash**
###### Motivation for this change

This is an implementation of Text API (tapi, or `.tbd` files) based stdenv and Frameworks for Darwin. Closes #91748 and #19906.

As of Big Sur the macOS filesystem no longer contains `.dylib` files and instead has a precomputed dyld cache. As a result the nixpkgs stdenv cannot link on Big Sur which vastly reduces the usability.

Apple's SDK uses Text API descriptions of the contents of shared libraries.  These `.tbd` files are straightforward YAML, can be passed directly to the linker and behave exactly like having `.dylib` or framework files. The current implementation of the Darwin stdenv uses a combination of proxy dyld libraries and direct symlinks to system libraries. Switching from the proxy libraries and symlinks to linking against these `.tbd` files is an improvement to compatibility and reproducibility.

There are two main options for sources of `.tbd` files: Apple's SDK, or generating them from an existing installation of macOS via `tapi stubify`. I assert that generating them is less likely to cause legal complications than deriving them from Apple's SDK. The [darwin-stubs][] repository contains appropriate stubs generated from macOS 10.12.6. Technically either source should be trivially interchangeable so we're not locked into either here.

If this branch is merged, then nixpkgs will be usable on Big Sur but not bootstrappable. The bootstrap environment requires the construction of a libSystem proxy in order to run the bootstrap tools. This shouldn't be much of a problem since a usable stdenv will be available from the binary cache. The easy solution is to regenerate the bootstrap tools once again after these changes have propagated.

I've spent some time testing on Big Sur and have been able to build my regular nix-darwin system closure which includes components written in rust, go, haskell (ghc), ruby, python, and using qt5. Note that the qt5 patch included here is the simplest thing that can work and is not generally applicable to upstream. I'm assuming upstream will produce a correct fix soon.

Prerequisites:
 - [x] Transfer https://github.com/thefloweringash/darwin-stubs to the NixOS GitHub organization
 - [x] Wait for staging to be merged to master for bootstrap-tools changes in #93912
 - [ ] Review and merge "stdenv/darwin: put compiler-rt into bootstrap tarball" #94426
 - [x] Update bootstrap tools from hydra, ~including review and merge of "stdenv/darwin: assemble full clang toolchain" #94427~

This PR will need to be updated after these prerequisites are satisfied. Opening now as a draft to have a description of the overall plan and to tie the prerequisites together.

cc @matthewbauer and @LnL7

[darwin-stubs]: https://github.com/thefloweringash/darwin-stubs

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/os-specific/darwin/apple-sdk/cf-setup-hook.sh [hunk 1]
```diff
@@ -3,7 +3,7 @@ linkSystemCoreFoundationFramework() {
   # gross! many symbols (such as _OBJC_CLASS_$_NSArray) are defined in system CF, but not
   # in the opensource release
   # if the package needs private headers, we assume they also want to link with system CF
-  NIX_LDFLAGS+=" /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation"
+  NIX_LDFLAGS+=" @out@/Library/Frameworks/CoreFoundation.framework/CoreFoundation"
```
[the remark this answers is not in the document]
Comment (thefloweringash) [reply pkgs/os-specific/darwin/apple-sdk/cf-setup-hook.sh:6]: This path doesn't exist, but the linker resolves this path to the `.tbd` file. After some testing it seems like the linker behaves the same with all of `.../Foo`, `.../Foo.tbd` and even `.../Foo.some_other_extension`.

File: pkgs/stdenv/darwin/default.nix [hunk 2]
```diff
@@ -157,9 +180,26 @@ in rec {
...
+          libc         = self.pkgs.darwin.Libsystem;
+          bintools     = { name = "bootstrap-stag0-binutils"; outPath = bootstrapTools; };
+        };
       };
 
       llvmPackages_7 = {
+        clang-unwrapped = {
+          name = "bootstrap-stage0-clang";
+          outPath = bootstrapTools;
+          version = bootstrapClangVersion;
```
[the remark this answers is not in the document]
Comment (thefloweringash) [reply pkgs/stdenv/darwin/default.nix:200]: `mkExtraBuildCommands` uses this to get the correct path to clang headers. The stdenv is a little odd currently in that `llvmPackages_7` is actually llvm and friends version 4.0.1 from bootstrap tools, but I'm not addressing that here.

(This is really part of #94427)

File: pkgs/stdenv/darwin/default.nix [hunk 3]
```diff
@@ -157,9 +180,26 @@ in rec {
...
+
+        binutils = lib.makeOverridable (import ../../build-support/bintools-wrapper) {
+          shell = "${bootstrapTools}/bin/bash";
+          inherit (self) stdenvNoCC;
+
+          nativeTools  = false;
+          nativeLibc   = false;
+          inherit (self) buildPackages coreutils gnugrep;
+          libc         = self.pkgs.darwin.Libsystem;
+          bintools     = { name = "bootstrap-stag0-binutils"; outPath = bootstrapTools; };
```
[the remark this answers is not in the document]
Comment (thefloweringash) [reply pkgs/stdenv/darwin/default.nix]: Pushed as a fixup, will squash later

File: pkgs/top-level/darwin-packages.nix [hunk 4]
```diff
@@ -41,6 +41,8 @@ in
 
   DarwinTools = callPackage ../os-specific/darwin/DarwinTools { };
 
+  darwin-stubs = callPackage ../os-specific/darwin/darwin-stubs { };
```
[the remark this answers is not in the document]
Comment (thefloweringash) [reply pkgs/top-level/darwin-packages.nix:46]: This way makes it easy to provide to various libraries and does make debugging slightly easier in that you can `nix-build -A darwin.darwin-stubs`. Did you have another mechanism in mind? I can imagine like treating them a bit like bootstrap tools and only propagating them in the stdenv definition.

**Comment by LnL7** [comment]
I rebased this against an eval and updated using the official bootstrap tools from hydra here https://github.com/LnL7/nixpkgs/commit/d7befcad37ed8d9e36861302c940ce6da4349311.
This comparison should give a decent view of the general state of things with these changes.

- https://hydra.nixos.org/eval/1619750?compare=1617819

**Comment by domenkozar** [comment]
Note that installer changes have been merged in Nix, so we only need to get this merged (and hopefully backport to 20.09) cc @NixOS/nixos-release-managers

**Comment by thefloweringash** [comment]
I included a reversion of the cctools bump here since it seemed to be causing problems (#101330). That's being addressed in other tickets (like #103053). Before merging we should drop that commit. I'm avoiding rebasing/removing for now because this branch is [indirectly related to a hydra job set][hydra-eval] and I don't want to make it harder to debug. 

[hydra-eval]: https://github.com/NixOS/nixpkgs/pull/98541#issuecomment-711376380

**Comment by thefloweringash** [comment]
Closed by complete accident, sorry for the noise.

File: pkgs/os-specific/darwin/darwin-stubs/default.nix [hunk 5]
```diff
@@ -0,0 +1,20 @@
+{ stdenv, fetchFromGitHub }:
+
+stdenv.mkDerivation {
+  pname = "darwin-stubs";
+  version = "10.12";
+
+  src = fetchFromGitHub {
+    owner = "thefloweringash";
+    repo = "darwin-stubs";
```
Comment (worldofpeace) [inline pkgs/os-specific/darwin/darwin-stubs/default.nix:9]: if this is directly to support nixpkgs it would probably be a good idea to transfer the repo here? And also have darwin maintainers access to it

Comment (thefloweringash) [reply pkgs/os-specific/darwin/darwin-stubs/default.nix:9]: I would definitely like to do this. I included it in the "Prerequisites" section, which isn't quite panning out as I expected.

Comment (LnL7) [reply pkgs/os-specific/darwin/darwin-stubs/default.nix:9]: I think @domenkozar is one of the people with enough permissions to do that.

Comment (worldofpeace) [reply pkgs/os-specific/darwin/darwin-stubs/default.nix:9]: If someone PM's him on IRC it should be pretty easy to have done

Comment (domenkozar) [reply pkgs/os-specific/darwin/darwin-stubs/default.nix:9]: @thefloweringash if you add me to that repo I can transfer it.

File: pkgs/development/libraries/qt-5/5.12/default.nix [hunk 6]
```diff
@@ -72,6 +72,10 @@ let
         # See https://github.com/NixOS/nixpkgs/issues/52457
         ./qtbase.patch.d/0014-qtbase-pkg-config.patch
 
+        # Patch framework detection to support X.framework/X.tbd,
+        # extending the current support for X.framework/X.
+        ./qtbase.patch.d/0015-qtbase-tbd-frameworks.patch
```
Comment (ttuegel) [inline pkgs/development/libraries/qt-5/5.12/default.nix:77]: This patch needs to be ported to every version of Qt in Nixpkgs.

**Review by ttuegel — CHANGES_REQUESTED** [review]

File: pkgs/os-specific/darwin/apple-sdk/default.nix [hunk 7]
```diff
@@ -80,21 +94,28 @@ let
...
-          isChild=1
           cp -R "${sdk.out}/Library/Frameworks/$nested_path/Versions/$current/Headers" .
         elif [ -d "${sdk.out}/Library/Frameworks/$name.framework/Versions/$current/Headers" ]; then
           current="$(readlink "/System/Library/Frameworks/$name.framework/Versions/Current")"
           cp -R "${sdk.out}/Library/Frameworks/$name.framework/Versions/$current/Headers" .
         fi
-        ln -s -L "/System/Library/Frameworks/$nested_path/Versions/$current/$name"
+
+        local tbd_source=${darwin-stubs}/System/Library/Frameworks/$nested_path/Versions/$current
+        if [ "${name}" != "Kernel" ]; then
```
Comment (angerman) [inline pkgs/os-specific/darwin/apple-sdk/default.nix:110]: Why do we explicitly exclude `Kernel`? Should we codify this as a comment?

File: pkgs/os-specific/darwin/apple-sdk/print-reexports/main.c [hunk 8]
```diff
@@ -0,0 +1,129 @@
+#include <stdio.h>
```
Comment (angerman) [inline pkgs/os-specific/darwin/apple-sdk/print-reexports/main.c:1]: Can we add a small synposis as a comment what `print-reexports` is supposed to do? And why it's needed?

File: pkgs/top-level/darwin-packages.nix (hunk 4 above)
[the remark this answers is not in the document]
Comment (angerman) [reply pkgs/top-level/darwin-packages.nix:46]: I'm in favour of keeping this exposed. And if only it will make debugging easier.

**Review by angerman — APPROVED** [review]

File: pkgs/development/libraries/qt-5/5.12/default.nix (hunk 6 above)
Comment (thefloweringash) [reply pkgs/development/libraries/qt-5/5.12/default.nix]: It applies trivially to the other version, so I've copied it over and added it to the patch lists. However neither qt514.qtbase nor qt515.qtbase currently build on master, so I can't test this.

File: pkgs/os-specific/darwin/apple-sdk/default.nix (hunk 7 above)
Comment (thefloweringash) [reply pkgs/os-specific/darwin/apple-sdk/default.nix:110]: The Kernel doesn't have a framework / .tbd component. Added a comment.

File: pkgs/os-specific/darwin/apple-sdk/print-reexports/main.c (hunk 8 above)
Comment (thefloweringash) [reply pkgs/os-specific/darwin/apple-sdk/print-reexports/main.c:20]: Added a comment.

More generally, I don't know if this approach to cross-linking is desirable or feasible long term. I'll likely revisit it when working on arm64 support.

**Review by LnL7 — APPROVED** [review]
With the jobset completed I'm pretty confident that there will be minimal fallout. And I think all of the TODOs are done (at least for initial support).

Great work!

**Comment by dhess** [comment]
Thanks again for all the work on this!

I'm testing this out with a reasonably large macOS package set, and I'm encountering the following issues. I'll keep this updated as they occur:

* [`libu2f-host` tests fail with `Segmentation fault: 11`](https://gist.github.com/dhess/9b237322df8facd3792eb014ad1f73c1)

Can anyone else reproduce these? I'm on 986c2d36da97856f392dd66d265b7646b32fa3b9. The build hosts are running macOS 10.14 and 10.15.

**Comment by thefloweringash** [comment]
Thanks for the testing this out. I'm trying to keep an eye on hydra but appreciate pings for things it might have broken.

> Can anyone else reproduce this? I'm on [986c2d3](https://github.com/NixOS/nixpkgs/commit/986c2d36da97856f392dd66d265b7646b32fa3b9). The build hosts are running macOS 10.14 and 10.15.

I'm trying on the same commit and this builds for me on 10.15 and 11, even after a few `--check` runs. The [hydra build](https://hydra.nixos.org/build/130404694) also passed.

**Comment by angerman** [comment]
I've just tested this with @thefloweringash on a fresh macOS BigSur (x86_64) VM.

```
sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
```
worked out fine, and gave me `nix`.

```
nix-build -E '(import <nixpkgs> {}).hello.overrideAttrs (_: { HELLO = "WORLD"; })'
```
did fail as expected.

```
nix-build -I nixpkgs=https://github.com/nixos/nixpkgs/archive/master.tar.gz -E '(import <nixpkgs> {}).hello.overrideAttrs (_: { HELLO = "WORLD"; })'
```
did succeed and produce a workable `hello` executable.

**Comment by dhess** [comment]
I can confirm that the issue I was having with `libu2f-host` using `nixpkgs-staging` was just one of those transient issues I sometimes get on macOS builders. Working fine now, thanks!

**Comment by angerman** [comment]
I should add that the same works on arm64, if https://github.com/NixOS/nix/commit/4864df6d6b7f5fc5c0815bf7733c40663ea856d7 is applied. It still goes through rosetta, and build x86_64 code, but works perfectly fine.

**Comment by kfiz** [comment]
tested this with ``qt5.qtwebengine`` (qtwebengine-5.12.7) on macOS BigSur (x86_64). Fails with:
```
ninja: error: '../../../../../../../../../../../usr/lib/libsandbox.1.dylib', needed by 'obj/components/cdm/renderer/librenderer.a', missing and no known rule to make it
```
@thefloweringash: It looks like pkgs/development/libraries/qt-5/5.12/qtbase.patch.d/0015-qtbase-tbd-frameworks.patch doesn't catch this

**Comment by thefloweringash** [comment]
> tested this with `qt5.qtwebengine` (qtwebengine-5.12.7) on macOS BigSur (x86_64). Fails with:
> 
> ```
> ninja: error: '../../../../../../../../../../../usr/lib/libsandbox.1.dylib', needed by 'obj/components/cdm/renderer/librenderer.a', missing and no known rule to make it
> ```
> 
> @thefloweringash: It looks like pkgs/development/libraries/qt-5/5.12/qtbase.patch.d/0015-qtbase-tbd-frameworks.patch doesn't catch this

This is an explicit impure reference in qtwebengine itself. This should probably be a library in the `pkgs/os-specific/darwin` directory. Since I missed it from the stubs, we'll need to add it there first, and then wrap it as a library. See https://github.com/NixOS/darwin-stubs/pull/3.

**Comment by dhess** [comment]
Does this commit change the viability of building nixpkgs on macOS with sandboxing enabled? I've tried that in the past, but always end up disabling it, because eventually some important package breaks.

**Comment by angerman** [comment]
> Does this commit change the viability of building nixpkgs on macOS with sandboxing enabled? I've tried that in the past, but always end up disabling it, because eventually some important package breaks.

I doubt so, I believe for proper sandboxing we'll need to address how `nix` does sandboxing on macOS, as it keeps running into limits when it sets them up.

**Comment by dhess** [comment]
@angerman Ahh, right, it's some sort of limitation in Apple's own sandboxing mechanism. Now I remember :)

**Comment by FRidh** [comment]
There was a question on IRC if there is any plan on backporting this change to 20.09.

**Comment by angerman** [comment]
> @angerman Ahh, right, it's some sort of limitation in Apple's own sandboxing mechanism. Now I remember :)

I think it's more like: `nix` could be smarter about this. I believe @LnL7 had some ideas for this. But memory is fuzzy.

**Comment by angerman** [comment]
> There was a question on IRC if there is any plan on backporting this change to 20.09.

I'd like to see this as well. If not even 20.03 but that might be a too tall ask.

**Comment by matthewbauer** [comment]
Awesome work @thefloweringash! This improves things greatly!

**Comment by davidtwco** [comment]
> There was a question on IRC if there is any plan on backporting this change to 20.09.

That was me, I've opened #105799 to backport this.
