### PR TITLE
nvidia_x11: fix vulkan icd filename

### LINKED ISSUE #86620: nvidia_x11 uses non-standard ICD filename
nvidia_x11 uses a non-standard ICD filename: nvidia.json instead of nvidia_icd.json. This breaks applications that rely on nvidia_icd.json existing (e.g. NixGL).

https://github.com/NixOS/nixpkgs/blob/f2d1041b6b5ba35662d1ffd53d2cdfd89951807e/pkgs/os-specific/linux/nvidia-x11/builder.sh#L76

### PR DESCRIPTION
**Pull request by eadwu**
Haven't tested, which is why it's a draft right now.

###### Motivation for this change
Resolves https://github.com/NixOS/nixpkgs/issues/86620

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eadwu** [comment]
```
❯  tree /nix/store/7gzpbpxx607s2avdxfmly880w1rqgifk-nvidia-x11-440.82-5.6.10/share/vulkan
/nix/store/7gzpbpxx607s2avdxfmly880w1rqgifk-nvidia-x11-440.82-5.6.10/share/vulkan
├── icd.d
│   └── nvidia_icd.x86_64.json
└── implicit_layer.d
    └── nvidia_layers.json

2 directories, 2 files
```

File: pkgs/os-specific/linux/nvidia-x11/builder.sh [hunk 1]
```diff
@@ -73,8 +73,14 @@ installPhase() {
             else
                 sed -E "s#(libGLX_nvidia)#$i/lib/\\1#" nvidia_icd.json > nvidia_icd.json.fixed
             fi
-            install -Dm644 nvidia_icd.json.fixed $i/share/vulkan/icd.d/nvidia.json
+
+            if [ "$system" = "x86_64-linux" ]; then
+                install -Dm644 nvidia_icd.json.fixed $i/share/vulkan/icd.d/nvidia_icd.x86_64.json
+            elif [ "$system" = "i686-linux" ]; then
```
Comment (baracoder) [inline pkgs/os-specific/linux/nvidia-x11/builder.sh:79]: Unfortunately, this only works with the legacy driver versions. In the newer ones, the 32bit libs are bundeled in the x86_64 package, so `$system` will always be x86_64
```
$ nix-build -A linuxPackages.nvidia_x11.lib32
$ ls result-lib32/share/vulkan/icd.d
nvidia_icd.x86_64.json
```
See also https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/hardware/video/nvidia.nix#L28-L32

Comment (eadwu) [reply pkgs/os-specific/linux/nvidia-x11/builder.sh]: Updated as per https://github.com/NixOS/nixpkgs/issues/86620#issuecomment-624180239

Though if it isn't ideal, I'll change it again.

The conditional scheme should work fine, since the only way to get the non-bundled version is from building from i686 platform I believe. Though using `i686bundled` might be preferred?

**Review by baracoder — APPROVED** [review]
Like mentioned here https://github.com/NixOS/nixpkgs/issues/86620#issuecomment-624124497 tools should not rely on filenames, therefore this change should not break anything, but then again this change should not be required.
