### PR TITLE
clickhouse, clickhouse-lts: fix versioning

### LINKED ISSUE #89091: Incorrect version in release
### Company or project name

NixOS

### Describe the unexpected behaviour

The release bot doesn't seem to write the correct version string into releases:

```
$ /nix/store/w1ykmp3d2gihjhrzfr43vy55nmi6pmpr-clickhouse-25.8.11.66-lts/bin/clickhouse --version
ClickHouse local version 25.8.11.1.
```

- https://github.com/ClickHouse/ClickHouse/blob/v25.8.11.66-lts/cmake/autogenerated_versions.txt
- https://github.com/ClickHouse/ClickHouse/blob/v25.9.4.58-stable/cmake/autogenerated_versions.txt

### Which ClickHouse versions are affected?

All.

### How to reproduce

N/A

### Expected behavior

_No response_

### Error message and/or stacktrace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by thevar1able**
Fixes https://github.com/ClickHouse/ClickHouse/issues/89091.
Also fixes an issue where updater script would pick up LTS with lower version for stable package, just because it was released later.

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [x] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [x] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [ ] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by thevar1able** [comment]
cc @jpds

File: pkgs/by-name/cl/clickhouse/update.sh [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+    nix-build -A "$1" 2>&1 >/dev/null | grep "got:" | cut -d':' -f2 | sed 's| ||g'
+    set -eo pipefail
+}
+
+fname="$1"
+echoerr "Working on $fname"
+shift
+
+# Fetch latest tags from the repo, leave only stable and lts, use version sort in reverse order.
+all_tags=$(curl -s https://api.github.com/repos/ClickHouse/ClickHouse/tags \
```
Comment (jpds) [inline pkgs/by-name/cl/clickhouse/update.sh]: This should expand `GITHUB_TOKEN` where available (see my latest `prometheus` PR) - presumably the NixOS infra has one set with all the API calls it's doing.

**Review by jpds — APPROVED** [review]

File: pkgs/by-name/cl/clickhouse/generic.nix [hunk 2]
```diff
@@ -176,9 +207,11 @@ llvmStdenv.mkDerivation (finalAttrs: {
   passthru = {
     tests = if lts then nixosTests.clickhouse-lts else nixosTests.clickhouse;
 
-    updateScript = nix-update-script {
-      extraArgs = nixUpdateExtraArgs;
-    };
+    updateScript = [
+      ./update.sh
+
+      (if lts then ./lts.nix else ./package.nix)
```
Comment (misuzu) [inline pkgs/by-name/cl/clickhouse/generic.nix]:
```suggestion
      (if lts then "./lts.nix" else "./package.nix")
```
or
```suggestion
      "pkgs/by-name/cl/clickhouse/${if lts then "lts.nix" else "package.nix"}"
```

Comment (misuzu) [reply pkgs/by-name/cl/clickhouse/generic.nix]: OTOH it seems to work file as is, it might break in the future, but doesn't matter right now

**Review by misuzu — APPROVED** [review]

**Comment by jpds** [comment]
> good idea to implement https://github.com/NixOS/nixpkgs/pull/433674

This fails because we have `-stable` in our version (and not in `--version` output.

**Comment by thevar1able** [comment]
@jpds FYI https://github.com/NixOS/nixpkgs/pull/458726
