### PR TITLE
dotnet-sdk-setup-hook: add nuget.org as a package source when there is no <clear/>

### LINKED ISSUE #363497: `nuget-to-nix` fails only via `fetch-deps` on certain .NET project
## Describe the bug

From https://github.com/NixOS/nixpkgs/pull/337548#discussion_r1874346139: Running `nuget-to-nix` the old manual way works for this project, but not via `fetch-deps`.

[sample output when invoked as `./result`](https://gist.github.com/YoshiRulz/238884e8a9fecc7da06db881d9bbdfaf)

## Steps To Reproduce

1. Checkout https://github.com/diadatp/nixpkgs/commit/24c766462e3c3b4ff6b49523d0a9b4dadcaf2117 (packages https://github.com/AssetRipper/AssetRipper)
2. `nix-build --pure -A assetripper.fetch-deps && ./result`

## Expected behavior

"Succesfully wrote lockfile to .../pkgs/by-name/as/assetripper/deps.nix"

## Additional context

This seems to be a regression. At 0e5b1ff245cd4b03363a7bf093a094de0de1fc13 or e7fb591c9263c26b4a805c7c98e9c109cff83a88, it fails, but at 346e862689ec4942ce4fe4c4352564e8724d7ebf (`e7fb591c9^`) and earlier it succeeds. (If you copy the expression from the commit linked above, it will need changing slightly as it relies on newer features.)

## Metadata

- system: `"x86_64-linux"`
- host os: `Linux 6.6.32, NixOS, 24.05 (Uakari), 24.05beta403.67a8b308bae9`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.18.2`
- channels(root): `"nixos-24.05"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

## Notify maintainers

@corngood

---

Note for maintainers: Please tag this issue in your PR.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by js6pak**
Fixes #363497

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

File: pkgs/development/compilers/dotnet/dotnet-sdk-setup-hook.sh [hunk 1]
```diff
@@ -100,6 +101,18 @@ configureNuget() {
             -i /configuration/packageSources/__new -t attr -n value -v "$nugetSource"
             -r /configuration/packageSources/__new -v add)
 
+        if [[ -n ${keepNugetConfig-} ]] && ! xmlstarlet select -t -i "/configuration/packageSources/clear" -nl "$rootConfig"; then
+            @xmlstarlet@/bin/xmlstarlet ed --inplace \
```
Comment (corngood) [inline pkgs/development/compilers/dotnet/dotnet-sdk-setup-hook.sh:105]: can we use `dotnet nuget add source`  for this?

Comment (js6pak) [reply pkgs/development/compilers/dotnet/dotnet-sdk-setup-hook.sh:105]: The idea was that I wanted it to be always first, but if order doesn't matter, then I guess?

File: pkgs/development/compilers/dotnet/dotnet-sdk-setup-hook.sh [hunk 2]
```diff
@@ -100,6 +101,10 @@ configureNuget() {
             -i /configuration/packageSources/__new -t attr -n value -v "$nugetSource"
             -r /configuration/packageSources/__new -v add)
 
+        if [[ -n ${keepNugetConfig-} ]] && ! xmlstarlet select -t -i "/configuration/packageSources/clear" -nl "$rootConfig"; then
+            dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org --configfile nuget.config
```
Comment (corngood) [inline pkgs/development/compilers/dotnet/dotnet-sdk-setup-hook.sh:105]: should this use `$rootConfig`?

**Review by gepbird — CHANGES_REQUESTED** [review]
Changes related to the package I maintain, `ps3-disc-dumper` look good.

Can you rebase to fix the merge conflicts (beatsabermodmanager was removed) and trigger the eval check which was failing due to a GH bug?

**Review by gepbird — APPROVED** [review]

**Comment by gepbird** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 367544`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 25 packages marked as broken and skipped:</summary>
  <ul>
    <li>avalonia</li>
    <li>boogie</li>
    <li>dotnet-sdk_6</li>
    <li>dotnet-sdk_7</li>
    <li>dotnetCorePackages.sdk_6_0-bin</li>
    <li>dotnetCorePackages.sdk_6_0_1xx-bin</li>
    <li>dotnetCorePackages.sdk_6_0_4xx-bin</li>
    <li>dotnetCorePackages.sdk_7_0-bin</li>
    <li>dotnetCorePackages.sdk_7_0_1xx-bin</li>
    <li>dotnetCorePackages.sdk_7_0_3xx-bin</li>
    <li>dotnetCorePackages.sdk_7_0_4xx-bin</li>
    <li>dotnetPackages.Boogie</li>
    <li>eddie</li>
    <li>eventstore</li>
    <li>msbuild</li>
    <li>naps2</li>
    <li>networkminer</li>
    <li>openra</li>
    <li>python312Packages.pythonnet</li>
    <li>python312Packages.pythonnet.dist</li>
    <li>python313Packages.pythonnet</li>
    <li>python313Packages.pythonnet.dist</li>
    <li>roslyn</li>
    <li>spotlight-downloader</li>
    <li>wasabibackend</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 162 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>alcom</li>
    <li>alttpr-opentracker</li>
    <li>am2rlauncher</li>
    <li>audiothekar</li>
    <li>avalonia-ilspy</li>
    <li>azure-artifacts-credprovider</li>
    <li>azure-functions-core-tools</li>
    <li>bicep</li>
    <li>bililiverecorder</li>
    <li>blendfarm</li>
    <li>bms-to-osu</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>bump-my-version (python312Packages.bump-my-version)</li>
    <li>bump-my-version.dist (python312Packages.bump-my-version.dist)</li>
    <li>cavalier</li>
    <li>celeste64</li>
    <li>certdump</li>
    <li>clps2c-compiler</li>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>cyclonedx-cli</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>dependency-track</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>discordchatexporter-desktop</li>
    <li>docfx</li>
    <li>dotnet-ef</li>
    <li>dotnet-outdated</li>
    <li>dotnet-repl</li>
    <li>dotnet-sdk (dotnet-sdk_8, dotnetCorePackages.sdk_8_0, dotnetCorePackages.sdk_8_0
_4xx)</li>
    <li>dotnet-sdk_10 (dotnetCorePackages.dotnet_10.sdk, dotnetCorePackages.sdk_10_0, do
tnetCorePackages.sdk_10_0-source, dotnetCorePackages.sdk_10_0_1xx)</li>
    <li>dotnet-sdk_10.man (dotnetCorePackages.dotnet_10.sdk.man, dotnetCorePackages.sdk_
10_0-source.man, dotnetCorePackages.sdk_10_0.man, dotnetCorePackages.sdk_10_0_1xx.man)</
li>
    <li>dotnet-sdk_9 (dotnetCorePackages.sdk_9_0, dotnetCorePackages.sdk_9_0_2xx)</li>
    <li>dotnetCorePackages.sdk_8_0_1xx (dotnetCorePackages.dotnet_8.sdk)</li>
    <li>dotnetCorePackages.sdk_8_0_1xx.man (dotnetCorePackages.dotnet_8.sdk.man)</li>
    <li>dotnetCorePackages.sdk_9_0_1xx (dotnetCorePackages.dotnet_9.sdk)</li>
    <li>dotnetCorePackages.sdk_9_0_1xx.man (dotnetCorePackages.dotnet_9.sdk.man)</li>
    <li>dotnetCorePackages.sdk_10_0-bin (dotnetCorePackages.sdk_10_0_1xx-bin)</li>
    <li>dotnetCorePackages.sdk_8_0-bin (dotnetCorePackages.sdk_8_0_4xx-bin)</li>
    <li>dotnetCorePackages.sdk_8_0_1xx-bin</li>
    <li>dotnetCorePackages.sdk_8_0_3xx</li>
    <li>dotnetCorePackages.sdk_8_0_3xx-bin</li>
    <li>dotnetCorePackages.sdk_9_0-bin (dotnetCorePackages.sdk_9_0_2xx-bin)</li>
    <li>dotnetCorePackages.sdk_9_0_1xx-bin</li>
    <li>fable</li>
    <li>famistudio</li>
    <li>fantomas</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>garnet</li>
    <li>gh-gei</li>
    <li>git-credential-manager</li>
    <li>github-runner</li>
    <li>gitversion</li>
    <li>godot-mono (godot_4-mono, godot_4_4-mono)</li>
    <li>godot-mono.debug (godot_4-mono.debug, godot_4_4-mono.debug)</li>
    <li>godot-mono.man (godot_4-mono.man, godot_4_4-mono.man)</li>
    <li>godot3-mono</li>
    <li>godot3-mono-debug-server</li>
    <li>godot3-mono-export-templates</li>
    <li>godot3-mono-headless</li>
    <li>godot3-mono-headless.dev</li>
    <li>godot3-mono-headless.man</li>
    <li>godot3-mono-server</li>
    <li>godot3-mono.dev</li>
    <li>godot3-mono.man</li>
    <li>godot_4_3-mono</li>
    <li>godot_4_3-mono.debug</li>
    <li>godot_4_3-mono.man</li>
    <li>ilspycmd</li>
    <li>imewlconverter</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>jetbrains.clion</li>
    <li>jetbrains.rider</li>
    <li>juniper</li>
    <li>kavita</li>
    <li>knossosnet</li>
    <li>kryptor</li>
    <li>libation</li>
    <li>lubelogger</li>
    <li>lumafly</li>
    <li>marksman</li>
    <li>mesen</li>
    <li>mqttmultimeter</li>
    <li>msbuild-structured-log-viewer</li>
    <li>msgraph-cli</li>
    <li>n-m3u8dl-re</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>nexusmods-app</li>
    <li>nexusmods-app-unfree</li>
    <li>obj2tiles</li>
    <li>omnisharp-roslyn</li>
    <li>opentabletdriver</li>
    <li>openutau</li>
    <li>osu-lazer</li>
    <li>pablodraw</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>ps3-disc-dumper</li>
    <li>pupdate</li>
    <li>python312Packages.clr-loader</li>
    <li>python312Packages.clr-loader.dist</li>
    <li>python313Packages.bump-my-version</li>
    <li>python313Packages.bump-my-version.dist</li>
    <li>python313Packages.clr-loader</li>
    <li>python313Packages.clr-loader.dist</li>
    <li>qbittorrent-cli</li>
    <li>recyclarr</li>
    <li>retrospy</li>
    <li>rockstarlang</li>
    <li>roslyn-ls</li>
    <li>ryubing</li>
    <li>ryujinx</li>
    <li>rzls</li>
    <li>scarab</li>
    <li>seq-cli</li>
    <li>skeditor</li>
    <li>slskd</li>
    <li>smtp4dev</li>
    <li>sonarr</li>
    <li>sourcegit</li>
    <li>space-station-14-launcher</li>
    <li>tagger</li>
    <li>technitium-dns-server</li>
    <li>technitium-dns-server-library</li>
    <li>tests.dotnet.final-attrs.check-output</li>
    <li>tests.dotnet.final-attrs.output-matches-const</li>
    <li>tests.dotnet.final-attrs.override-has-no-effect</li>
    <li>tests.dotnet.final-attrs.override-modifies-output</li>
    <li>tests.dotnet.nuget-deps.derivation</li>
    <li>tests.dotnet.nuget-deps.json-file</li>
    <li>tests.dotnet.nuget-deps.list</li>
    <li>tests.dotnet.nuget-deps.nix-file</li>
    <li>tests.dotnet.nuget-deps.null</li>
    <li>tests.dotnet.project-references</li>
    <li>tests.dotnet.structured-attrs.check-output</li>
    <li>tests.dotnet.structured-attrs.no-structured-attrs</li>
    <li>tests.dotnet.use-dotnet-from-env.fallback</li>
    <li>tests.dotnet.use-dotnet-from-env.use-dotnet-path-env</li>
    <li>tests.dotnet.use-dotnet-from-env.use-dotnet-root-env</li>
    <li>tests.dotnet.use-dotnet-from-env.without-fallback</li>
    <li>tests.writers.simple.fsharpNoNugetDeps</li>
    <li>tone</li>
    <li>torrentstream</li>
    <li>upgrade-assistant</li>
    <li>v2rayn</li>
    <li>vrcadvert</li>
    <li>windmill</li>
    <li>wiseunpacker</li>
    <li>xivlauncher</li>
    <li>yafc-ce</li>
  </ul>
</details>

**Review by corngood — APPROVED** [review]
