### PR TITLE
chrootenv: resolve #32802, #32876, #32877, #32878

### LINKED ISSUE #32802: chrootenv: detect chrootenv-in-chrootenv scenario
## Issue description

chrootenv should detect chrootenv-in-chrootenv scenario and show a more useful error message than `unshare: Operation not permitted`. It took a lot of head-scratching to identify what's going on.

### Steps to reproduce

Run `chrootenv` inside `chrootenv`:

```
$ chrootenv=$(find /nix/store -name \*-chrootenv | head -1)
$ $chrootenv $chrootenv ls
/nix/store/d01wd24jkv781s2psvaccbw66zacxqyx-chrootenv:chrootenv.c:140: unshare: Operation not permitted
```

Thanks, @bkchr!

## Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.5, NixOS, 18.03.git.ab1d2a5 (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 1.11.16`
 - channels(root): `"overlay, nixos-18.03pre122666.afe9649210c"`
 - channels(chronos): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

### LINKED ISSUE #32876: chrootenv: more helpful error message for Debian users
https://github.com/NixOS/nixpkgs/pull/31182#discussion_r150328735

It would be user-friendlier to check `/proc/sys/kernel/unprivileged_userns_clone` and if it's disabled, print a `sysctl` command that user should run in order to enable it.

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

* Show error on chrootenv-inside-chrootenv (#32802)
* Show `sysctl` command when `kernel.unpriveleged_userns_clone` is available (#32876)
* Bind-mount all directories and symlink files in / (#32877)
* Replace `env_whitelist` with `env_blacklist` (currently empty) (#32878)

Formatted via `clang-format`. Valgrind reports "all heap blocks were freed". Steam still works!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 1]
```diff
@@ -20,56 +21,112 @@
...
+
+    for (size_t i = 0; i < LEN(env_blacklist); i++) {
+      if (!strncmp(*envp, env_blacklist[i], strlen(env_blacklist[i]))) {
+        blacklisted = true;
+        break;
+      }
+    }
+
+    if (!blacklisted) {
+      filtered_envp = realloc(filtered_envp, (n + 2) * sizeof(*envp));
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: Leaks old memory location of `filtered_envp` in the error case -> this would require a temporary variable that is only copied to `filtered_envp` in the success case

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 2]
```diff
@@ -20,56 +21,112 @@
...
+    envp++;
+  }
+
+  filtered_envp[n] = NULL;
+  return filtered_envp;
+}
+
+void bind(char *from, char *to) {
+  if (mkdir(to, 0755) < 0)
+    errorf(EX_IOERR, "mkdir");
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: it would be helpful here, which directory could have not been created in the error message:

```diff
-    errorf(EX_IOERR, "mkdir");
+    errorf(EX_IOERR, "could not create directory %s", to); 
```

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 3]
```diff
@@ -20,56 +21,112 @@
...
+
+  if (mount(from, to, "bind", MS_BIND | MS_REC, NULL) < 0)
+    errorf(EX_OSERR, "mount");
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: same here:

```diff
+    errorf(EX_OSERR, "mount"); 
-    errorf(EX_OSERR, "failed to mount '%s' to '%s'", from, to); 
```

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 4]
```diff
@@ -20,56 +21,112 @@
...
+}
+
+char *strjoin(char *dir, char *name) {
+  char *path = malloc(strlen(dir) + strlen(name) + 1);
+
+  if (path == NULL)
+    errorf(EX_OSERR, "malloc");
+
+  if (strcpy(path, dir) < 0)
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: `path` is not freed.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 5]
```diff
@@ -20,56 +21,112 @@
...
+    errorf(EX_IOERR, "strcpy");
+
+  if (strcat(path, name) < 0)
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: `path` is not freed

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 6]
```diff
@@ -20,56 +21,112 @@
...
   }
 
-  *ptr = NULL;
-  return ret;
+  return false;
+}
+
+bool isdir(char *path) {
+  struct stat buf;
+  stat(path, &buf);
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: Should check return value of `stat` -> buf could even contain the result of previous values stat calls.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 7]
```diff
@@ -20,56 +21,112 @@
...
 
-    if (mkdir(bind->to, 0755) < 0)
-      errorf(EX_IOERR, "mkdir");
+    if (isdir(prefix_dirent_path)) {
+      bind(prefix_dirent_path, prefix_dirent->d_name);
+    } else {
+      char *host_target = strjoin("host/", prefix_dirent->d_name);
+
+      if (symlink(host_target, prefix_dirent->d_name) < 0)
+        errorf(EX_IOERR, "symlink");
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: Directory is not closed and memory is not freed in error case.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 8]
```diff
@@ -170,7 +239,8 @@ int main(int argc, char *argv[]) {
   if (waitpid(cpid, &status, 0) < 0)
     errorf(EX_OSERR, "waitpid");
 
-  if (nftw(root, nftw_rm, getdtablesize(), FTW_DEPTH | FTW_MOUNT | FTW_PHYS) < 0)
+  if (nftw(root, nftw_rm, getdtablesize(), FTW_DEPTH | FTW_MOUNT | FTW_PHYS) <
+      0)
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: Write return code to a local variable instead of line wrapping here for readability.

**Review by Mic92 — DISMISSED** [review]

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 4 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: It should not be freed, the point is to allocate enough memory to hold combined string to reduce boilerplate. `free()` happens at other places.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 5 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: See above.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 9]
```diff
@@ -20,56 +21,112 @@
...
-        errorf(EX_OSERR, "asprintf");
+#define LEN(x) sizeof(x) / sizeof(*x)
+
+char *env_blacklist[] = {};
+
+char **env_filter(char *envp[]) {
+  char **filtered_envp = malloc(sizeof(*envp));
+  size_t n = 0;
+
+  while (*envp != NULL) {
```
[the remark this answers is not in the document]
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Agreed!

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 10]
```diff
@@ -20,56 +21,112 @@
...
+    bool blacklisted = false;
+
+    for (size_t i = 0; i < LEN(env_blacklist); i++) {
```
Comment (dezgeg) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: `LEN()` returns something completely wrong here.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 11]
```diff
@@ -20,56 +21,112 @@
...
+      if (!strncmp(*envp, env_blacklist[i], strlen(env_blacklist[i]))) {
```
[the remark this answers is not in the document]
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Because I only need to partially match the string. Example of valid entry in `env_blacklist` would be `PWD=`, example of `*envp` that would be blacklisted is `PWD=/home/user`.

[the remark this answers is not in the document]
Comment (dezgeg) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: The second parameter should be the index of the first '=' in the string indeed.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 1 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: I'm not sure I understand. Below, `filtered_envp == NULL` handles the error case.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 2 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: `errorf` macro handles that (errno, or `strerror` have that information).

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 3 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: See above.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 6 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: You are right, I'll reimplement this on top of `opendir`.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 12]
```diff
@@ -161,7 +230,7 @@ int main(int argc, char *argv[]) {
 
     argv++;
 
-    if (execvpe(*argv, argv, env_build(env_whitelist, LEN(env_whitelist))) < 0)
+    if (execvpe(*argv, argv, env_filter(environ)) < 0)
```
Comment (dezgeg) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: I think the code for the blacklist approach would be much simpler if you just used `execvp()` and just modified the current environment with `unsetenv()`.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 7 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: I don't understand why this has to be done. I'll read up on it.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 1 above)
Comment (dezgeg) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: `O(n^2)` :(

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 8 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Line wrapping will go away if I rename `nftw_rm`.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 13]
```diff
@@ -20,56 +21,112 @@
...
+
+void bind(char *from, char *to) {
+  if (mkdir(to, 0755) < 0)
+    errorf(EX_IOERR, "mkdir");
+
+  if (mount(from, to, "bind", MS_BIND | MS_REC, NULL) < 0)
+    errorf(EX_OSERR, "mount");
+}
+
+char *strjoin(char *dir, char *name) {
```
Comment (dezgeg) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: This whole function could just be `asprintf("%s%s", dir, name)`

or in C++: `dir + name`. ;)

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 14]
```diff
@@ -20,56 +21,112 @@
...
+  if (strcpy(path, dir) < 0)
+    errorf(EX_IOERR, "strcpy");
+
+  if (strcat(path, name) < 0)
+    errorf(EX_IOERR, "strcat");
+
+  return path;
+}
+
+char *bind_blacklist[] = {".", "..", "bin", "etc", "host", "usr"};
```
Comment (dezgeg) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: `const char * const bind_blacklist[] ` etc.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 10 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: I don't think so:

```
$ cat example.c
#include <stdio.h>

#define LEN(x) sizeof(x) / sizeof(*x)

char *zzz[] = {"a", "b", "c"};

int main() {
  printf("%lu\n", LEN(zzz));
  return 0;
}
$ nix-shell -p gcc gnumake --run 'make example'
$ ./example
3
```

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 15]
```diff
@@ -20,56 +21,112 @@
...
-  for (size_t i = 0; i < len; i++) {
-    if ((env = getenv(names[i]))) {
-      if (asprintf(ptr++, "%s=%s", names[i], env) < 0)
-        errorf(EX_OSERR, "asprintf");
+#define LEN(x) sizeof(x) / sizeof(*x)
+
+char *env_blacklist[] = {};
+
+char **env_filter(char *envp[]) {
+  char **filtered_envp = malloc(sizeof(*envp));
```
[the remark this answers is not in the document]
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Thanks!

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: @dezgeg I don't think I understand. Could you elaborate?

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 16]
```diff
@@ -20,56 +21,112 @@
...
-char **env_build(char *names[], size_t len) {
-  char *env, **ret = malloc((len + 1) * sizeof(char *)), **ptr = ret;
-
-  for (size_t i = 0; i < len; i++) {
-    if ((env = getenv(names[i]))) {
-      if (asprintf(ptr++, "%s=%s", names[i], env) < 0)
-        errorf(EX_OSERR, "asprintf");
+#define LEN(x) sizeof(x) / sizeof(*x)
+
+char *env_blacklist[] = {};
```
Comment (dezgeg) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: Isn't this variable totally unused?

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 12 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: I agree, I'm going to do that. Thanks!

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 16 above)
Comment (dezgeg) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Ah it's supposed to be a constant... `const char * const` then.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (dezgeg) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Brain fart of me, sorry.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 16 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: It's unused for now.

This variable is supposed to be filled in presumably when @abbradar gets better.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 1 above)
Comment (dezgeg) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: By the time `filtered_envp` is NULL you have leaked the old `filtered_envp` array.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 13 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: I know it could be `asprintf`, but it's cleaner this way. Check previous chrootenv version, I've used `asprintf`.

> or in C++: [...]

You won't succumb me to the dark side! Heh.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 1 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Dropping this code as you suggested.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 13 above)
Comment (dezgeg) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: How is it cleaner to write 13 lines of code to replace 1 line?

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 11 above)
[the remark this answers is not in the document]
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Yeah, the point was that `env_blacklist` elements would always end with an equal sign. But `unsetenv` approach is much better. I've discovered `environ` only today.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 1 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: > By the time filtered_envp is NULL you have leaked the old filtered_envp array.

I don't think I understand why this matters before an exit.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 4 above)
Comment (dezgeg) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: strcpy() can't fail, btw.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 5 above)
Comment (dezgeg) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Neither can strcat().

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 4 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Thanks!

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 13 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: It has better semantics. There is no template, only concatenation.

Comment (dezgeg) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: But every C programmer who reads `asprintf(&ret, "%s%s", x, y)` immediately knows it's just concatenating two strings.

And in fact you're using this in precisely one place, with a constant string as the other arg. Just
````
char *host_target = strjoin("host/", prefix_dirent->d_name)
````
->
````
char *host_target;
asprintf(&host_target, "host/%s", prefix_dirent->d_name);
````
to make it even more simpler.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 2 above)
Comment (Mic92) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Which one do you find more informative?

```diff
--- main.c      2017-12-21 01:04:18.626520276 +0100
+++ main2.c     2017-12-21 01:06:39.371742074 +0100
@@ -1,15 +1,15 @@
 #define _GNU_SOURCE
 #include <errno.h>
 #include <error.h>
 #include <sysexits.h>
 #include <sys/stat.h>
 #define errorf(status, fmt, ...)                                               \
   error_at_line(status, errno, __FILE__, __LINE__, fmt, ##__VA_ARGS__)
 int main(int argc, char *argv[])
 {
   mkdir("/foo/bar", 0755);
-  errorf(EX_OSERR, "mkdir");
+  errorf(EX_OSERR, "failed to create directory '%s'", "/foo/bar");
   return 0;
 }
```

```diff
- ./main:main.c:13: mkdir: No such file or directory
+ ./main:main2.c:13: failed to create directory '/foo/bar': No such file or directory
```

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 3 above)
Comment (Mic92) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: see above too

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 16 above)
Comment (Mic92) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Then I would add a TODO comment.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 2 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: `mkdir` vs. `failed to create directory`: first one. It gives function that fails right out of the bat.

I do agree that having argument information would be very helpful, e.g. see `spitf`. In this case it would be:

```
errorf(EX_OSERR, "mkdir(%s)", "/foo/bar");
```

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 16 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: Will do!

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 2 above)
Comment (Mic92) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: So you expect people to know about low-level syscalls to understand error messages?

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 13 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: OK, point taken. `errorf` uses the same DSL anyway so it seems there is not much use in implementing simpler `asprintf`.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c [hunk 17]
```diff
@@ -96,16 +153,24 @@ int nftw_rm(const char *path, const struct stat *sb, int type,
...
   }
 
+  if (getenv("NIX_CHROOTENV") != NULL)
+    errorf(EX_USAGE, "can't create chrootenv inside chrootenv");
+
+  if (setenv("NIX_CHROOTENV", "1", false) < 0)
+    errorf(EX_IOERR, "setenv");
+
   char tmpl[] = "/tmp/chrootenvXXXXXX";
   char *root = mkdtemp(tmpl);
```
Comment (Mic92) [inline pkgs/build-support/build-fhs-userenv/chrootenv.c]: `root` is only removed in the successful case.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 2 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: While technically `mkdir` is a low-level syscall, everyone knows what `mkdir` does, or they would not be able to install NixOS in the first place :-)

Also, I don't think you'd be able to come up with a more helpful message for `unshare` than we currently have. In fact, if I were to remove `unshare` from error messages that currently have it, it would make debugging harder for me.

Also, using function name makes error much more googleable, which helps if it's user-recoverable.

`strerror` is supposed to generate user-friendly messages, and I think it's doing a pretty good job. `mkdir(/foo/bar): no such file or directory` is a user-friendly message.

File: pkgs/build-support/build-fhs-userenv/chrootenv.c (hunk 7 above)
Comment (yegortimoshenko) [reply pkgs/build-support/build-fhs-userenv/chrootenv.c]: I think this should be handled by exit, not manually. Directories, files and memory are handled by default, if there's something that is not handled, `atexit` callback should be used.

**Comment by yegortimoshenko** [comment]
@dezgeg, @Mic92: again, thanks for the review. I've fixed most of the problems that you told me about in https://github.com/NixOS/nixpkgs/pull/32899/commits/08156be327054bf17bd746b26d56f08f926d1413 (see commit log) except where I explicitly disagree:

* I agree that it's preferable to free memory after it has been used but I don't think that memory (or any other resource) should be explicitly handled before exit. Kernel does that for us.
* I disagree with @Mic92 in https://github.com/NixOS/nixpkgs/pull/32899#discussion_r158158993: I believe that function name is more informative and better for error reports. However, I've implemented argument logging. Also, now user-targeted messages are printed via `fputs` and not `errorf`, i.e. without source filename, line and `strerror`, and on a separate line. Before:
  ```
  ./chrootenv ls
  unshare: run `sudo sysctl -w kernel.unprivileged_userns_clone=1`: operation not permitted
  ```
  After:
  ```
  $ ./chrootenv ls
  Run: sudo sysctl -w kernel.unprivileged_userns_clone=1
  unshare: operation not permitted
  ```
* `clang-format` might have its quirks, but it's a standard way to indent C code. It might handle one line out of 250 rather badly, but on average, it indents code way better than most people do / have time for.

**Comment by yegortimoshenko** [comment]
I plan to merge this tomorrow.
