### PR TITLE
setup-hooks/strip.sh: preserve file dates

### LINKED ISSUE #223709: python3Packages.distlib: embeds .exe files
Building this package twice does not produce the bit-by-bit identical result each time, making it harder to detect CI breaches. You can read more about this at https://reproducible-builds.org/ .

Fixing bit-by-bit reproducibility also has additional advantages, such as avoiding hard-to-reproduce bugs, making content-addressed storage more effective and reducing rebuilds in such systems.

### Steps To Reproduce

```
nix-build '<nixpkgs>' -A python3Packages.distlib --check --keep-failed
```

You can use `diffoscope` to analyze the differences in the output of the two builds.

To view the build log of the build that produced the artifact in the binary cache:

```
nix-store --read-log $(nix-instantiate '<nixpkgs>' -A python3Packages.distlib)
```

### Additional context

In the context of pip we previously deleted these files, #201146

### PR DESCRIPTION
**Pull request by raboof**
###### Description of changes

AFAIK this doesn't have a noticable effect for typical Linux executables, but will avoid setting the timestamp inside the file for Windows executables to the build date.

Fixes #223709

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: pkgs/build-support/setup-hooks/strip.sh [hunk 1]
```diff
@@ -39,8 +39,8 @@ _doStrip() {
         if [[ "${dontStrip-}" || "${flag-}" ]] || ! type -f "${stripCmd-}" 2>/dev/null 1>&2
         then continue; fi
 
-        stripDirs "$stripCmd" "$ranlibCmd" "$debugDirList" "${stripDebugFlags[*]:--S}"
-        stripDirs "$stripCmd" "$ranlibCmd" "$allDirList" "${stripAllFlags[*]:--s}"
+        stripDirs "$stripCmd" "$ranlibCmd" "$debugDirList" "${stripDebugFlags[*]:--S --p}"
+        stripDirs "$stripCmd" "$ranlibCmd" "$allDirList" "${stripAllFlags[*]:--s --p}"
```
Comment (SuperSandro2000) [inline pkgs/build-support/setup-hooks/strip.sh:43]: You are sure that it is a double dash for a one character option?

**Comment by SuperSandro2000** [comment]
I think we should do this in addition to the other PR that fixes the same issue to be on the safe side.

**Comment by raboof** [comment]
> I think we should do this in addition to the other PR that fixes the same issue to be on the safe side.

I agree: even though for *that* package on non-Windows platforms removing the files is probably the better option, but we don't want to leak build timestamps into the stripped files for any other packages either

File: pkgs/build-support/setup-hooks/strip.sh (hunk 1 above)
Comment (raboof) [reply pkgs/build-support/setup-hooks/strip.sh]: Nope, should have been `-p` indeed! (in fact `--p` does work, but let's not rely on that)

**Review by SuperSandro2000 — APPROVED** [review]

**Review by trofi — APPROVED** [review]
LGTM. Looks like `-p` is present both in `GNU` and `LLVM` `strip` tools.

**Comment by trofi** [comment]
Let's see if darwin can build any packages at all as a cheap test:

@ofborg build stdenv

**Comment by vcunat** [comment]
I have no idea why, but this merge apparently broke stdenv on x86_64-darwin, throwing
```
error: output '/nix/store/bkg25ggbi2yp5jdkg83mz8hxffqr0ac4-stdenv-darwin' is not allowed to refer to the following paths:
         /nix/store/dkzh4w5bvk3slw6p170gx558prs4afq9-SDKs
```
On the merge (commit 4806f626948500) `stdenv` fails and on the parent (e9a4c4bd49e) it builds.


The references in question:
```
$ grep c7ld8w5d3w9y074fpss6i3gfkrw5g6gz -R /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0
Binary file /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0/lib/darwin/libclang_rt.ubsan_osx.a matches
Binary file /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0/lib/darwin/libclang_rt.xray_osx.a matches
Binary file /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0/lib/darwin/libclang_rt.xray-fdr_osx.a matches
Binary file /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0/lib/darwin/libclang_rt.stats_client_osx.a matches
Binary file /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0/lib/darwin/libclang_rt.ubsan_minimal_osx.a matches
Binary file /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0/lib/darwin/libclang_rt.xray-basic_osx.a matches
Binary file /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0/lib/darwin/libclang_rt.fuzzer_osx.a matches
Binary file /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0/lib/darwin/libclang_rt.xray-profiling_osx.a matches
Binary file /nix/store/fm10agjd5brzd6y6vzba7nc6zjcqcpdj-compiler-rt-libc-11.1.0/lib/darwin/libclang_rt.fuzzer_no_main_osx.a matches
```
(I think these last hashes were on full `staging-next`.)

**Comment by vcunat** [comment]
Maybe some bootstrapping `strip` is being weird/buggy?  I don't like to spend much of my time on darwin stuff, so... I'm not sure what to do about this unless someone investigates in depth very soon.

**Comment by trofi** [comment]
Yeah, sounds about right. I'm surprised that `strip.sh` is used as is on `darwin`. But that makes sense after the fact.

I see that today we have a hack to override `stripAll` in `pkgs/stdenv/darwin/default.nix` as:

```
stripAllFlags=" " # the Darwin "strip" command doesn't know "-s"
```

I wonder if you add `stripDebugFlags` to the mix. Something like (untested):

```diff
--- a/pkgs/stdenv/darwin/default.nix
+++ b/pkgs/stdenv/darwin/default.nix
@@ -63,6 +63,7 @@ rec {
     unset SDKROOT

     stripAllFlags=" " # the Darwin "strip" command doesn't know "-s"
+    stripDebugFlags="-S" # the Darwin "strip" command does something odd with "-p"
   '';

   bootstrapTools = derivation ({
```

Maybe it's enough to untangle from non-`llvm` `strip`.
