### PR TITLE
stdenv: add isMachO helper function

### LINKED ISSUE #102044: wrapQtAppsHook broken on macOS
**Describe the bug**

The convenience function `wrapQtAppsHook` does not work on macOS. The calls `patchelf` like so:
```
            patchelf --print-interpreter "$file" >/dev/null 2>&1 || continue
```
If the calls succeeds `wrapQtApp` is called with`$file` as argument. Since `patchelf` is not installed, this always fails, skip all files, and binaries are not properly wrapped – and hence fail to execute.

As a work-around I had to call `wrapQtApp` manually in the `preFixup` phase. It did it's thing, wrapped the binary properly and I could run the binary without issues.

**To Reproduce**
1. Build an arbitrary Qt app on macOS (for example gpxlab or glogg, but really any Qt app works …)
2. Compile and install under Linux, to see wrapping working
3. Disable manual call to `wrapQtApp`
4. Compile and install under macOS to see wrapping via the hook doing nothing
5. Verify that the app under macOS is indeed not wrapped and fails to execute

**Expected behavior**

Properly wrapped application. Wrapping itself works, as evidenced by a manual call to `wrapQtApp`, but have the hook not depend on `patchelf` on macOS or at least ** give a warning **  and give a warning in the manual.

**Screenshots**

**Additional context**

**Notify maintainers**

**Metadata**
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```
nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/12pkkc7l378r75xz1kvh39wlk1p4gw7w-DarwinTools-1
  /nix/store/zvir75d0b5swjva0xkyxcidpagf7jpdv-nix-info
copying path '/nix/store/12pkkc7l378r75xz1kvh39wlk1p4gw7w-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/zvir75d0b5swjva0xkyxcidpagf7jpdv-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.7`
 - channels(hannesweisbach): `""`
 - channels(root): `"nixpkgs-20.09pre242465.bd649f4f55c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
Maintainer information:
```yaml
# a list of nixpkgs attributes affected by the problem
attribute:
# a list of nixos modules affected by the problem
module:
```

### PR DESCRIPTION
**Pull request by smancill**
Detect if a binary is a Mach-O file.

In #131378, @veprbl suggested detecting if the binaries are Mach-O files, since there is already an `isELF` function, so I added the missing function.

I cannot try directly though, because since I modified `stdenv` it wants me to rebuild absolutely everything, and it would never finish on my Macbook. I did try it by copying it to an external script:

```
$ ./is-macho ~/.nix-profile/bin/nix
N: 4
Bytes:  cf  fa  ed  fe
----
Mach-O

$ ./is-macho /bin/ls
N: 4
Bytes:  ca  fe  ba  be
----
Mach-O

$ ./is-macho /usr/local/bin/git
N: 4
Bytes:  cf  fa  ed  fe
----
Mach-O

$ ./is-macho ~/sample.pdf
N: 4
Bytes:  25  50  44  46
----

$ ./is-macho flake.nix
N: 4
Bytes:  23  20  45  78
----

```

But it needs `LC_ALL=C` in order to work, otherwise `read -n 4` would not read 4 bytes, and I am not sure why. I couldn't find information about what `stdenv` does regarding locale.

Also, I test for both `MAGIC` an `CIGAM` magic numbers, although it seems nixpkgs/Homebrew binaries are in `CIGAM` format. I added the check for 32-bit and fat binaries for completion.

-------

This should help with #102044, but it should require a new PR that supersedes #131378. I believe the fix could be as simple as:

``` diff
diff --git i/pkgs/development/libraries/qt-5/hooks/wrap-qt-apps-hook.sh w/pkgs/development/libraries/qt-5/hooks/wrap-qt-apps-hook.sh
index ce4d78fbb50..21de2a206f5 100644
--- i/pkgs/development/libraries/qt-5/hooks/wrap-qt-apps-hook.sh
+++ w/pkgs/development/libraries/qt-5/hooks/wrap-qt-apps-hook.sh
@@ -85,7 +85,7 @@ wrapQtAppsHook() {
 
         find "$targetDir" ! -type d -executable -print0 | while IFS= read -r -d '' file
         do
-            patchelf --print-interpreter "$file" >/dev/null 2>&1 || continue
+            { isELF "$file" || isMachO "$file"; } >/dev/null 2>&1 || continue
 
             if [ -f "$file" ]
             then

```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by smancill** [comment]
I don't understand why my single commit on top of current `master` (a43bfef8f16e0f5e71726e62a589116ec67781d4= became 232 commits.

**Comment by smancill** [comment]
I've rebased on top of `staging` and force-pushed the commit again.

File: pkgs/stdenv/generic/setup.sh [hunk 1]
```diff
@@ -199,6 +199,29 @@ isELF() {
     if [ "$magic" = $'\177ELF' ]; then return 0; else return 1; fi
 }
 
+# Return success if the specified file is a Mach-O object.
+isMACHO() {
```
Comment (veprbl) [inline pkgs/stdenv/generic/setup.sh:203]:
```suggestion
isMachO() {
```

**Review by veprbl — APPROVED** [review]

File: pkgs/stdenv/generic/setup.sh (hunk 1 above)
Comment (smancill) [reply pkgs/stdenv/generic/setup.sh]: Done.

File: pkgs/stdenv/generic/setup.sh [hunk 2]
```diff
@@ -199,6 +199,29 @@ isELF() {
     if [ "$magic" = $'\177ELF' ]; then return 0; else return 1; fi
 }
 
+# Return success if the specified file is a Mach-O object.
+isMachO() {
+    local fn="$1"
+    local fd
+    local magic
```
Comment (SuperSandro2000) [inline pkgs/stdenv/generic/setup.sh:206]:
```suggestion
    local fn="$1" fd magic
```

File: pkgs/stdenv/generic/setup.sh [hunk 3]
```diff
@@ -199,6 +199,29 @@ isELF() {
...
+    exec {fd}< "$fn"
+    read -r -n 4 -u "$fd" magic
```
Comment (SuperSandro2000) [inline pkgs/stdenv/generic/setup.sh:208]: We can't use file, can we?

File: pkgs/stdenv/generic/setup.sh (hunk 2 above)
Comment (smancill) [reply pkgs/stdenv/generic/setup.sh:206]: I just took the lines from `isELF`, I didn't want to do it differently. Then both functions should be updated.

File: pkgs/stdenv/generic/setup.sh (hunk 3 above)
Comment (smancill) [reply pkgs/stdenv/generic/setup.sh:208]: `isELF` is doing it with `read` so I just followed.

I don't know how robust is:

```
$ file ~/.nix-profile/bin/nix | grep -q 'Mach-O'
```

There is [`libmagic`](https://man7.org/linux/man-pages/man3/libmagic.3.html) too, provided by `file`.

Comment (SuperSandro2000) [reply pkgs/stdenv/generic/setup.sh:208]: > $ file ~/.nix-profile/bin/nix | grep -q 'Mach-O'

Doing this would be dirt cheap and would require zero maintenance.

Comment (veprbl) [reply pkgs/stdenv/generic/setup.sh:208]: > Doing this would be dirt cheap and would require zero maintenance.

So are you going to contribute a PR?

Comment (smancill) [reply pkgs/stdenv/generic/setup.sh:208]: I can update the PR but how to do it is not my decision. I just ensured to do it the same way as `isELF`, which seems to work just fine, and use the proper magic numbers.

Here are the `isELF` usages:

```
$ rg --sort=path 'isELF '
pkgs/applications/misc/blender/default.nix
152:      isELF "$program" || continue

pkgs/applications/science/machine-learning/sc2-headless/default.nix
43:      isELF "$file" || continue

pkgs/build-support/add-opengl-runpath/setup-hook.sh
24:        if ! isELF "$file"; then continue; fi

pkgs/build-support/setup-hooks/audit-blas.sh
10:        if ! isELF "$i"; then continue; fi

pkgs/build-support/setup-hooks/audit-tmpdir.sh
22:        if isELF "$i"; then

pkgs/build-support/setup-hooks/auto-patchelf.sh
220:      isELF "$file" || continue

pkgs/build-support/setup-hooks/separate-debug-info.sh
19:        if ! isELF "$i"; then continue; fi

pkgs/development/compilers/cudatoolkit/common.nix
189:      if ! isELF "$i"; then continue; fi

pkgs/development/compilers/ghc/8.10.2-binary.nix
290:        if isELF "$p"; then
299:        if isELF "$p"; then

pkgs/development/compilers/ghc/8.6.5-binary.nix
138:      if isELF "$p"; then

pkgs/development/compilers/openjdk/bootstrap.nix
35:      isELF "$elf" || continue

pkgs/development/tools/misc/patchelf/setup-hook.sh
16:        if ! isELF "$i"; then continue; fi
```

Comment (veprbl) [reply pkgs/stdenv/generic/setup.sh:208]: @smancill Sorry, that question was to @SuperSandro2000

Comment (veprbl) [reply pkgs/stdenv/generic/setup.sh:208]: > Here are the `isELF` usages:

Yes, so the reason to have isELF in stdenv is for use inside the setup hooks. Same is the plan for isMachO.

Comment (SuperSandro2000) [reply pkgs/stdenv/generic/setup.sh:208]: > So are you going to contribute a PR?

I don't really have the time for that.

Comment (veprbl) [reply pkgs/stdenv/generic/setup.sh:208]: `file` is not part of stdenv, adding it there is not dirt cheap. You can find any PR for file and see that it's not an stdenv rebuild. Sending people down that path is not respectful of their time, would you agree @SuperSandro2000?

Comment (SuperSandro2000) [reply pkgs/stdenv/generic/setup.sh:208]: Well, if it is not part of stdenv and this approach is alright. In most other scenarios this would be an unnecessary workaround. I don't know which tools are exactly part of stdenv but file seems to be unix-core enough that it could have been.

**Comment by vcunat** [comment]
FYI, reverted in PR #138186 (for now?)

**Comment by veprbl** [comment]
@vcunat 
I must say I don't understand why it has to be done this way. A perfectly valid bash code is removed for the sake of covering up bugs in experimental code. This is putting the burden on the wrong shoulders.

**Comment by vcunat** [comment]
I don't consider the current state to be permanent.  It seems to be a Nix bug primarily, so I'd expect this back after Nix is fixed, unless a better workaround presents in the meantime.  (e.g. similar bash code that doesn't trigger the bug)

**Comment by winterqt** [comment]
@vcunat I believe I have found a proper fix to this issue on the stdenv side. (code that produces same result but doesn't interfere with the underlying Nix issue)

Pending some testing, I'll make a PR that re-adds the function with my fixes.

Since you merged #138186 into `staging-next`, should I base my PR off that branch? I'm not sure if it'll cause merge conflicts if I do it off `master` or `staging`, so just want to make sure.

**Comment by vcunat** [comment]
Yes, on `staging-next` then.  I hope we can get some review fast.

**Comment by vcunat** [comment]
Or if having this function isn't urgent, we can take time and leave it for the next staging iteration.  (I don't know how much it's urgent.)

**Comment by winterqt** [comment]
I would say it's not urgent, personally. Nothing in stdenv uses it, and I can't find any [public code on GitHub](https://grep.app/search?q=isMachO&case=true) that uses it either.

What branch should I base it off then, `master`?

**Comment by veprbl** [comment]
How can we use it if it was just added.

**Comment by smancill** [comment]
> (I don't know how much it's urgent.)

It was supposed to provide the helper function that would serve as the base for a simpler fix to #102044, instead of #131378.

But I wasn't expecting total breakage of the Nix ecosystem with normal Bash code.

**Comment by r-burns** [comment]
Well, no breakage occurred for people not using experimental features...

**Comment by winterqt** [comment]
> It was supposed to provide the helper function that would serve as the base for a simpler fix to #102044, instead of #131378.

But that fix isn't currently in Nixpkgs, right?

So we should be fine letting it go into the next staging iteration, I think.

**Comment by smancill** [comment]
Yes, I guess it is not urgent. It was just a nice-to-have function, and it would make the fix to `wrapQtAppsHook` trivial, that's all.

**Comment by winterqt** [comment]
> What branch should I base it off then, `master`?

Not sure what I was thinking when I said that. I should base it off `staging`, right?
