### PR TITLE
nixos/update-users-groups: /etc/shadow owned by root:shadow

### LINKED ISSUE #93580: /etc/shadow should belong to the shadow group
**Describe the bug**

Currently, /etc/shadow belongs to the root group. For many use cases, this poses no problems, but when some program needs to use PAM to authenticate on the behalf of multiple users, the program needs to be executed as root (which seems generally unacceptable security-wise). One example is PAM authentication in Nginx, where the [NixOS wiki currently recommends running Nginx as root](https://nixos.wiki/wiki/Nginx#Authentication_via_PAM) (see discussion [here](https://discourse.nixos.org/t/nginx-pam-access-to-etc-shadow/6218) on this).

**Expected behavior**

I think it's reasonable for /etc/shadow to belong to a group called "shadow" so users can make the decision on letting some programs/users read /etc/shadow. [Debian seems to do this as well](https://wiki.debian.org/SystemGroups#Groups_without_an_associated_user).

If maintainers agree this is a reasonable thing to do, and if someone can confirm if this change is as simple as adding a group called shadow and adding a line in update-users-group.pl chown-ing /etc/shadow to root:shadow, then I'll create a PR.

**Notify maintainers**

@edolstra @adisbladis

### PR DESCRIPTION
**Pull request by cole-h**
###### Motivation for this change

Closes https://github.com/NixOS/nixpkgs/issues/93580.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

~~I tried using Perl's `chown` with `getpwnam`/`getgrnam`, but `getpwnam "root"` and `getgrnam "shadow"` didn't work... So, I had to use `system` and call out to the `chown` binary.~~

cc @NixOS/nixos-release-managers (since this is on the 20.09 blockers list).

### CODE REVIEW

**Comment by aanderse** [comment]
> I tried using Perl's `chown` with `getpwnam`/`getgrnam`, but `getpwnam "root"` and `getgrnam "shadow"` didn't work... So, I had to use `system` and call out to the `chown` binary.

@volth or @stigtsp any interest in taking a look at this?

**Comment by cole-h** [comment]
FWIW, the problem was that the script would say `Argument "root" isn't numeric in chown at ....`:

```perl
chown getpwnam "root", getgrnam "shadow", "/etc/shadow";
```

So, for some reason, `getpwnam "root"` and `getgrnam "shadow"` aren't resolving the numeric ids.

**Comment by cole-h** [comment]
The output of `print getpwnam "root"` and `print getgrnam "shadow"`, respectively (the root password is just a crypted ` `, so doesn't matter that it's revealed here, probably):

image

**Comment by cole-h** [comment]
Ah, I think I found my problem: if I use `my $uid = getpwnam "root";`, `$uid` becomes the `$uid` returned by the list of `getpwnam` (same for `$gid`).

Now this can be totally in Perl :)

**Comment by stigtsp** [comment]
> ```perl
> chown getpwnam "root", getgrnam "shadow", "/etc/shadow";
> ```

This might be because `getpwnam` and `getgrnam` are called in list context sending a list of 10 items to chown:

```
perl -MData::Dumper -E 'say Dumper getpwnam "root", getgrnam "shadow", "/etc/shadow"'
$VAR1 = 'root';
$VAR2 = 'x';
$VAR3 = 0;
$VAR4 = 0;
$VAR5 = '';
$VAR6 = '';
$VAR7 = 'System administrator';
$VAR8 = '/root';
$VAR9 = '/run/current-system/sw/bin/bash';
$VAR10 = '/etc/shadow';
```

Your patch with `my $uid = getpwnam "root";` calls it in scalar context which returns what's expected. :)

```
$ perldoc -f getpwnam
[..]        
            In scalar context, you get the name, unless the function was a
            lookup by name, in which case you get the other thing, whatever
            it is. (If the entry doesn't exist you get the undefined value.)
[..]
```

**Comment by cole-h** [comment]
@ofborg eval

(I think I broke it by force-pushing too fast :P)

File: nixos/modules/config/update-users-groups.pl [hunk 1]
```diff
@@ -281,6 +281,11 @@ sub parseUser {
 }
 
 updateFile("/etc/shadow", \@shadowNew, 0600);
+{
+    my $uid = getpwnam "root";
+    my $gid = getgrnam "shadow";
+    chown $uid, $gid, "/etc/shadow";
```
Comment (stigtsp) [inline nixos/modules/config/update-users-groups.pl:287]:
```suggestion
    chown($uid, $gid, "/etc/shadow") || die $!;
```
To trigger a fatal error if chown() fails somehow.

Comment (cole-h) [reply nixos/modules/config/update-users-groups.pl]: Done, thanks.

image

**Comment by worldofpeace** [comment]
@ofborg test installer.simple

**Comment by jluttine** [comment]
Hi! I just encountered the issue that this PR solved when I was using a bit old nixpkgs version. I now used this patch to fix the issue, thanks! However, I'm wondering why the permissions are still kept at `0600` instead of `0640`? I would have expected this patch to give read-access to `/etc/shadow` file, what's the purpose of setting the group otherwise? So, probably I'm missing something and I'd like to understand. Thanks for help!
