### PR TITLE
nixos/users-groups: expand subuid/subgid ranges to fix UID allocation errors

### LINKED ISSUE #437870: NixOS 25.05 allows max 100 users
I'm upgrading nixos 24.05 to 25.05 and the rebuild fails if I have more than 100 users on the server:

```
...
/nix/store/7sb1nkpf82nb5kj7qc4bbqkwj1l1mdv9-update-users-groups.pl: out of free UIDs or GIDs
Activation script snippet 'users' failed (2)
...
Failed to run activate script
reloading user units for root...
restarting sysinit-reactivation.target
the following new units were started: set-disk-quotas.service
warning: error(s) occurred while switching to the new configuration
Error: Process completed with exit code 1.
```

If I'm not mistaken, this change https://github.com/NixOS/nixpkgs/commit/46600598f1344d4c5029a883103b0b4bd1728235#diff-d019ca3e4041b6a9883c95ca3098db7477255070ad92cdb6d2c3ef7a04b38773R338 made it so that by using autoSubUidGidRange we only can have up to 100 users. If we have more `allocId` will raise `out of free UIDs or GIDs`. This error is a bit misleading because the problem is subuid/subgid ranges.

I think we need to change it:

from `my ($min, $max, $delta) = (100000, 100000 + 100 * 65536, 65536);` to  `my ($min, $max, $delta) = (100000, 100000 + 10000 * 65536, 65536);`.

After further investigation I realised that even if I don't have +100 users on a server I could enounter this issue. If I had 100 users in any time on my nixos server I get this error because the historic data is stored in `/var/lib/nixos/auto-subuid-map`.

To see how many users we have we can run `jq 'length' /var/lib/nixos/auto-subuid-map`. If you have more than 100 you need to `mv /var/lib/nixos/auto-subuid-map /var/lib/nixos/auto-subuid-map.bak`. On the next nixos rebuild it will be recreated with the current users.

I also had to define subUidRanges and subGidRanges for every user. This can become a bit tricky if you have a lot of them or they are semi-dynamically created. This code works for me (I have 100 users):

```
...
  indexOf = x: xs:
    let
      len = builtins.length xs;
      indices = builtins.genList (i: i) len;
      matches = builtins.filter (i: builtins.elemAt xs i == x) indices;
    in
      if matches == [] then null else builtins.head matches;
  count = 10000;

  # attribute set
  users = builtins.listToAttrs (builtins.map (dbUser: {
    name = dbUser.user;
    value = {
      ...
    };
    # we don't need subuid ranges for now because we don't use docker/podman
    # but we need to define them to avoid error when running nixos rebuild
    # "update-users-groups.pl: out of free UIDs or GIDs"
    autoSubUidGidRange = false;
    subUidRanges = [{startUid = 100000 + (indexOf dbUser allUsers) * count; count = count;}];
    subGidRanges = [{startUid = 100000 + (indexOf dbUser allUsers) * count; count = count;}];
  }) allUsers);
...
```

### PR DESCRIPTION
**Pull request by jmholla**
Resolves "update-users-groups.pl: out of free UIDs or GIDs" error by increasing the hardcoded UID ranges to match the limitations of UIDs established by shadow.nix. Without this change, regular user creation is limited to 100 total users across the lifetime of a NixOS system.

Fixes: #437870

## Things done

- Built on platform:
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [ ] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by jmholla** [comment]
This change supersedes the change in [PR 437870](https://github.com/NixOS/nixpkgs/issues/437870). I think it should also be backported to NixOS 25.05.

File: nixos/modules/config/update-users-groups.pl [hunk 1]
```diff
@@ -334,8 +334,11 @@ sub parseUser {
 sub allocSubUid {
     my ($name, @rest) = @_;
 
-    # TODO: No upper bounds?
-    my ($min, $max, $delta) = (100000, 100000 + 100 * 65536, 65536);
+    # The upper bound of 29000 users comes is derived from limits in
```
Comment (zupo) [inline nixos/modules/config/update-users-groups.pl:337]: The wording here is a bit off?

Comment (jmholla) [reply nixos/modules/config/update-users-groups.pl]: Good catch. I reworked this comment a few times. I removed "comes" in my latest change which should clear up the verbiage. Thanks!

**Comment by jmholla** [comment]
Does anyone know if there's something going on with the Mac tests? This has been pending for almost two weeks now. :/

**Comment by arianvp** [comment]
Ignore the mac runners

**Review by eclairevoyant — COMMENTED** [review]
Please note we don't use Conventional Commits; the format should be `nixos/users-groups: ...` not `fix: ...`

https://github.com/NixOS/nixpkgs/blob/bce664dbeaa1ec3f04251c3f16dd8b738b8e10d8/nixos/README.md#commit-conventions

https://github.com/NixOS/nixpkgs/blob/bce664dbeaa1ec3f04251c3f16dd8b738b8e10d8/CONTRIBUTING.md#commit-conventions

**Review by eclairevoyant — APPROVED** [review]

File: nixos/modules/config/update-users-groups.pl [hunk 2]
```diff
@@ -334,8 +334,11 @@ sub parseUser {
 sub allocSubUid {
     my ($name, @rest) = @_;
 
-    # TODO: No upper bounds?
-    my ($min, $max, $delta) = (100000, 100000 + 100 * 65536, 65536);
+    # The upper bound of 29000 users is derived from limits in
+    # nixos/modules/programs/shadow.nix which allocates the UID ranges
+    # 1000-29999 for regular users. System users are not allocated
```
[the remark this answers is not in the document]
Comment (jmholla) [reply nixos/modules/config/update-users-groups.pl]: Nope. It's because 29999-999 is 29000 users. Here, 999 is the system users that are not allocated sudUIDs and subGUIDs. I'll rework the comment to make it more clear.

**Review by Ericson2314 — APPROVED** [review]
