### PR TITLE
tree-wide: nixos: /var/run -> /run

### LINKED ISSUE #51800: Deprecated /var/run being used for tmpfiles.d
## Issue description

Currently there are a number of services that define something inside `/var/run` inside `/etc/tmpfiles.d/*.conf`. One example I ran into was kubernetes. Upon running `nixos-rebuild` it would show the following warning:

```
setting up tmpfiles
[/etc/tmpfiles.d/nixos.conf:6] Line references path below legacy directory /var/run/, updating /var/run/kubernetes → /run/kubernetes; please update the tmpfiles.d/ drop-in file accordingly.
```

`/etc/tmpfiles/nixos.conf` contained the following lines:

```
# This file is created automatically and should not be modified.
# Please change the option ‘systemd.tmpfiles.rules’ instead.

D! /tmp 1777 root root
d /opt/cni/bin 0755 root root -
d /var/run/kubernetes 0755 kubernetes kubernetes -
d /var/lib/kubernetes 0755 kubernetes kubernetes -
d /var/cache 0755 root root -
```

Apparently `/var/run/kubernetes` is deprecated and should be `/run/kubernetes`. I'll make a PR for this particular instance, but there are probably more instances of this happening.

Alternatively, #40594 might help in this regard as well as upstream projects will run into the same issue and will resolve this for themselves. We currently cannot always ride along with them.

## Steps to reproduce

`/etc/nixos/configuration.nix`:

```
...
  services.kubernetes.roles = ["master" "node"];
...
```

Run `nixos-rebuild switch` and notice the warning.

### PR DESCRIPTION
**Pull request by bobvanderlinden**
###### Motivation for this change

Fixes #51800 
Continuation of #47856 

`/var/run` is deprecated in `tmpfiles.d` and `/run` should be used. Currently this produces a warning every time `nixos-rebuild switch` runs for each service that uses `tmpfiles.d` with an entry for `/var/run`.

This PR changes `/var/run` instances into `/run` across nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by grahamc** [comment]
I'm not sure the individual commits with all the same commit message are usefully separate? May be good to squash them all together, or make their commit messages more specific about what they're doing.

File: nixos/modules/system/boot/stage-2-init.sh [hunk 1]
```diff
@@ -85,15 +85,15 @@ install -m 0755 -d /var/{log,lib,db} /nix/var /etc/nixos/ \
...
-rm -rf /var/run /var/lock
+rm -rf /run /var/lock
 rm -f /etc/{group,passwd,shadow}.lock
 
 
 # Also get rid of temporary GC roots.
 rm -rf /nix/var/nix/gcroots/tmp /nix/var/nix/temproots
 
 
-# For backwards compatibility, symlink /var/run to /run, and /var/lock
```
Comment (worldofpeace) [inline nixos/modules/system/boot/stage-2-init.sh]: This comment could be left as is

File: pkgs/tools/networking/network-manager/default.nix [hunk 2]
```diff
@@ -94,7 +94,7 @@ in stdenv.mkDerivation rec {
   doCheck = false; # requires /sys, the net
 
   preInstall = ''
-    installFlagsArray=( "sysconfdir=$out/etc" "localstatedir=$out/var" "runstatedir=$out/var/run" )
+    installFlagsArray=( "sysconfdir=$out/etc" "localstatedir=$out/var" "runstatedir=/run" )
```
Comment (worldofpeace) [inline pkgs/tools/networking/network-manager/default.nix]: This probably should be:
```suggestion
    installFlagsArray=( "sysconfdir=$out/etc" "localstatedir=$out/var" "runstatedir=$out/run" )
```

File: nixos/modules/misc/locate.nix [hunk 3]
```diff
@@ -76,7 +76,7 @@ in {
 
     prunePaths = mkOption {
       type = listOf path;
-      default = ["/tmp" "/var/tmp" "/var/cache" "/var/lock" "/var/run" "/var/spool" "/nix/store"];
+      default = ["/tmp" "/run" "/var/tmp" "/var/cache" "/var/lock" "/var/run" "/var/spool" "/nix/store"];
```
Comment (worldofpeace) [inline nixos/modules/misc/locate.nix]: This probably should be
```suggestion
      default = ["/tmp" "/var/tmp" "/var/cache" "/run/lock" "/run" "/var/spool" "/nix/store"];
```

Comment (bobvanderlinden) [reply nixos/modules/misc/locate.nix]: Ah, `lock` is part of `run`. Looked it up, yes indeed.

File: pkgs/tools/networking/network-manager/default.nix (hunk 2 above)
Comment (bobvanderlinden) [reply pkgs/tools/networking/network-manager/default.nix]: Keeping the old code in mind, your comment makes sense. However, I do wonder whether `runstatedir` should just be `/run` instead of `$out/run`.

Comment (worldofpeace) [reply pkgs/tools/networking/network-manager/default.nix]: Judging from the `installFlagsArray` it's so things get installed to $out/run and not /run which is outside the build prefix.

File: nixos/modules/programs/zsh/zsh.nix [hunk 4]
```diff
@@ -203,7 +203,7 @@ in
 
     environment.shells =
       [ "/run/current-system/sw/bin/zsh"
-        "/var/run/current-system/sw/bin/zsh"
+        "/run/current-system/sw/bin/zsh"
```
Comment (bobvanderlinden) [inline nixos/modules/programs/zsh/zsh.nix]:
```suggestion
```

**Comment by bobvanderlinden** [comment]
What needs to be done to get this merged? If doing this tree-wide is making the decision harder, I can split things up in separate PRs as well. For instance, I can do `/{var/,}run/kubernetes` separate from `/{var/,}run/current-system`

File: pkgs/applications/display-managers/lightdm/run-dir.patch [hunk 5]
```diff
@@ -6,7 +6,7 @@ index 16b80f7..b3af435 100644
  #guest-account-script=guest-account
  #logind-check-graphical=false
  #log-directory=/var/log/lightdm
--#run-directory=/var/run/lightdm
```
Comment (globin) [inline pkgs/applications/display-managers/lightdm/run-dir.patch]: That looks incorrect

File: pkgs/applications/networking/remote/teamviewer/default.nix [hunk 6]
```diff
@@ -39,8 +39,6 @@ stdenv.mkDerivation rec {
 
     substituteInPlace $out/share/teamviewer/tv_bin/script/tvw_aux \
       --replace '/lib64/ld-linux-x86-64.so.2' '${glibc.out}/lib/ld-linux-x86-64.so.2'
-    substituteInPlace $out/share/teamviewer/tv_bin/script/tvw_config \
-      --replace '/var/run/' '/run/'
```
Comment (globin) [inline pkgs/applications/networking/remote/teamviewer/default.nix]: That should probably be kept

File: pkgs/build-support/vm/default.nix [hunk 7]
```diff
@@ -111,7 +111,7 @@ rec {
     mkdir -p /fs/tmp /fs/run /fs/var
     mount -t tmpfs -o "mode=1777" none /fs/tmp
     mount -t tmpfs -o "mode=755" none /fs/run
-    ln -sfn /run /fs/var/run
```
Comment (globin) [inline pkgs/build-support/vm/default.nix]: Have you checked that this works correctly?

**Comment by bobvanderlinden** [comment]
Thanks a lot @globin for the review. I reverted the changes that you mentioned.  That made me realize there are a number of changes in here that are just wrong or edge cases. I went through the changes again, removed anything that seemed fishy and committed them separately.

Let me know whether this makes more sense.

**Comment by Mic92** [comment]
That needs to go to staging.

**Comment by bobvanderlinden** [comment]
Rebased this and removed conflicting kubernetes commit, as the kubernetes module is now already using `/run`.

What can I do to move this forward?

**Comment by oxij** [comment]
IMHO all the commit messages touching nixos subtree should be formatted as "nixos/<module>: ..." or similar (they should mention "nixos" at the very least). Also "tree-wide", not "tee-wide". Similarly, changes to pkgs should be formatted as "<package name>: ...".

Run

$ git filter-branch --msg-filter 'sed "1 { s%^module: %nixos/% ; s%^pkg: %% ; s%^test: %nixos/tests: % ; s%^tee-wide: %tree-wide: % ; }"' c18bb57627a87c6f03877386ecbc2e22d81d8afd..HEAD

and then fix the odd ones like "wpa_supplicant: ..." by hand.

As to the diffs, changes to nixos subtree LGTM. Changes to pkgs subtree are a mass rebuild so they should be split into a separate PR against staging.

**Comment by bobvanderlinden** [comment]
@oxij Thanks a lot of the feedback! I've split the packages off to a separate PR: https://github.com/NixOS/nixpkgs/pull/58222

I split the wpa_supplicant and the asterisk commits in 2 (a nixos and a pkgs commit). The pkgs commit of those were also moved to #58222. It _should_ still be compatible if `/var/run` is indeed linked to `/run`

**Review by globin — APPROVED** [review]
Will merge in a few days if no other issues are brought up.

**Comment by bobvanderlinden** [comment]
@globin merging would be awesome! :D
