### PR TITLE
CoreFoundation: use rpath to fix issues when using frameworks

### LINKED ISSUE #12346: Darwin packages get linked with two different copies of system framework, causing strange runtime errors
I spent the past eight hours figuring out why my built phantomjs2 kept segfaulting. The root cause of the segfault was the usage of NSString constants; I'm not completely sure why this happened, but I'm guessing the compiled string constant has an `isa` member pointing to the wrong memory location. Once I rewrite the link reference in phantomjs, from nix-built CF to system CF, everything works.

The problem can be fixed by rewriting/removing the duplicate links, but I think a more viable long-term solution is in order to avoid future confusing bugs.

### PR DESCRIPTION
**Pull request by LnL7**
###### Motivation for this change

Implementation of #24693

This allow a binary to decide what version of CoreFoundation is loaded based on it's rpath. This allows binaries to use the version from `/System/Library/Frameworks` and propagate that down to all dylibs, including libraries that are built against the pure version.

I think keeping the setup hook from #22571 might still be useful, since a dylib that depends on frameworks won't work with the pure CF and hook might not get propagated all the way to the binary to set the rpath. /cc @NixOS/darwin-maintainers  

Fixes #12346, #24124, #24127, #27353 

```
$ otool -L ./result/bin/duti
./result/bin/duti:
        /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
        @rpath/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1153.18.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1258.1.0)
        /nix/store/adl0qydsan3cb16wwdl9j77ny7mpky50-Libsystem-osx-10.11.6/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
        /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 728.13.0)
```

```
$ otool -l ./result/bin/duti
Load command 17
          cmd LC_RPATH
      cmdsize 80
         path /nix/store/2k1h8pafhw1z754jz155ax7q03amgkhj-duti-1.5.4pre/lib (offset 12)
Load command 18
          cmd LC_RPATH
      cmdsize 40
         path /System/Library/Frameworks (offset 12)
```

###### Things done

Please check what applies. Note that these are not hard requirements but mereley serve as information for reviewers.

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
  - [ ] ~~anki~~ (python needs a wrapper)
  - [x] duti (see #27376)
  - [x] go get
  - [x] gnupg
  - [x] graphviz
  - [x] racket
  - [x] xournal
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by LnL7** [comment]
Waiting for the results of https://hydra.nixos.org/eval/1378812?compare=1378396#tabs-new to make sure nothing breaks.

**Comment by mstone** [comment]
@LnL7 -- thanks for publishing; these changes got me unstuck by fixing a busted go1.8 binary installed from recent nixpkgs on macOS 10.12.6 earlier this weekend.

**Comment by LnL7** [comment]
That's great! Did you notice issues with any other packages?

**Comment by ajbouh** [comment]
I'm also getting bitten by a busted go1.8. Is there a plan to merge this soon?

Also, how can I apply this change locally and help test?

**Comment by LnL7** [comment]
I'll probably merge this to staging soon. You can test it by using my fork, eg.

```
nix-build https://github.com/LnL7/nixpkgs/archive/darwin-cf-rpath.tar.gz -A hello
```

**Comment by copumpkin** [comment]
Sounds good!

**Comment by copumpkin** [comment]
Awesome awesome awesome

File: pkgs/build-support/cc-wrapper/ld-wrapper.sh [hunk 1]
```diff
@@ -145,6 +145,10 @@ if [ "$NIX_@infixSalt@_DONT_SET_RPATH" != 1 ]; then
             fi
         done
     done
+
+    if [ -n "${NIX_COREFOUNDATION_RPATH:-}" ]; then
```
Comment (Ericson2314) [inline pkgs/build-support/cc-wrapper/ld-wrapper.sh]: Oh, I missed this before, but this should have probably done the `@infixSalt@` thing, to support darwin->darwin cross compilation where the path may not be the same.

Comment (LnL7) [reply pkgs/build-support/cc-wrapper/ld-wrapper.sh]: I wrote this before the salts where added. Not sure if it really matters since it will only point to `/System/Library/Frameworks`, similar to the dyld path with `LD_DYLD_PATH`.

Comment (Ericson2314) [reply pkgs/build-support/cc-wrapper/ld-wrapper.sh]: Oh, my bad @LnL7. I thought this was from the PR you just merged in the last 24 hours, and never double checked!
