### PR TITLE
Limit exclusion of info/dir in builder.pl, fixes #242394

### LINKED ISSUE #242394: Emacs dired-x.info is not symlinked in profile
### Describe the bug
The emacs package installs about 66 info files into `$out/share/info`. All of them are then symlinked into the system (or home) profile at, e.g., `/run/current-system/sw/share/info` **except** for `dired-x.info`. The Emacs manual (`emacs.info`) and the source file both reference this manual, but it's not to be found in the info directory.

### Steps To Reproduce
Something like this, I guess…

1. `environment.systemPackages = [ pkgs.emacs29 ];`
2. `nixos-rebuild build`
3. `ls result/sw/share/info | grep dir` shows only `dir`
4. `ls $(dirname $(readlink result/sw/share/info/emacs.info.gz)) | grep dir` shows `dir` and `dired-x.info.gz`

### Expected behavior

The output of step 3 should also contain `dired-x.info.gz`.

### Additional context
It occurred to me that the filename beginning with the letters `dir` may not be a coincidence. We exclude the dir file from the profile, generating it instead. Indeed, the relevant part of [`builder.pl`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/buildenv/builder.pl#L125)  seems to be:

```pl
    # Urgh, hacky...
    return if
        $relName eq "/propagated-build-inputs" ||
        $relName eq "/nix-support" ||
        $relName =~ /info\/dir/ ||                # <---------- HERE ----------
        ( $relName =~ /^\/share\/mime\// && !( $relName =~ /^\/share\/mime\/packages/ ) ) ||
        $baseName eq "perllocal.pod" ||
        $baseName eq "log" ||
        ! (hasPathsToLink($relName) || isInPathsToLink($relName));
```

The commented line is intended to exclude `info/dir` but also ends up excluding `info/dired-x.info.gz`. I'm not sure, is something like `$relName =~ /info\/dir$/` appropriate?

### Notify maintainers

@edolstra wrote that part of `builder.pl`

### Metadata

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.31, NixOS, 23.05 (Stoat), 23.05.20230605.1e13eca`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `""`
 - channels(league): `""`
 - nixpkgs: `not found`
```

### PR DESCRIPTION
**Pull request by league**
###### Description of changes

While trying to exclude a generated `/share/info/dir` in a package from symlinking into a profile, we also ended up excluding the Emacs info manual for `dired-x`.  This change excludes only the dir file.

This entails rebuild-the-world, but I've verified with the following small flake that it can rebuild up to emacs and exhibits the desired fix. Just set `inputs.nixpkgs.url` to this commit vs base commit.

```nix
{
  outputs = { nixpkgs, ... }: {
    packages.x86_64-linux.builder-bug =
      let pkgs = nixpkgs.legacyPackages.x86_64-linux; in
      pkgs.buildEnv {
        name = "build-emacs";
        # Need emacs and one other package that puts something in /share/info.
        paths = [ pkgs.emacs29 pkgs.time ];
      };
  };
}
```

```
% ls result-before/share/info/dir*
zsh: no matches found: result-before/share/info/dir*

% ls result-after/share/info/dir*
result-after/share/info/dired-x.info.gz@
```

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Artturin** [comment]
Should target staging, check CONTRIBUTING.md for how to rebase without mass pinging

commit title should be `buildenv: Limit exclusion of info/dir`

File: pkgs/build-support/buildenv/builder.pl [hunk 1]
```diff
@@ -126,7 +126,7 @@ sub findFiles {
     return if
         $relName eq "/propagated-build-inputs" ||
         $relName eq "/nix-support" ||
-        $relName =~ /info\/dir/ ||
```
Comment (Artturin) [inline pkgs/build-support/buildenv/builder.pl:129]: used to include $ https://github.com/nixos/nixpkgs/commit/a6fcf45726bc75c0c7014ac6b5bedd56d649ca08#diff-1967dcc359700a88592924a2e08cc397d4c8ccedec0717a5f96bafc33ece5e53L61

but it was removed in 2010 https://github.com/nixos/nixpkgs/commit/a6fcf45726bc75c0c7014ac6b5bedd56d649ca08#diff-1967dcc359700a88592924a2e08cc397d4c8ccedec0717a5f96bafc33ece5e53R53

guessing he accidentally removed it when he changed the others to eq, while this was intentionally not changed

Comment (league) [reply pkgs/build-support/buildenv/builder.pl:129]: Thanks. Now I'm wondering why it shouldn't be `$relName eq "/share/info/dir"` unless there may be a package with info files under some other prefix.

Comment (Artturin) [reply pkgs/build-support/buildenv/builder.pl:129]: I checked with nix-index and there's some that aren't under toplevel share
