### PR TITLE
nixos/wrappers: fix applying capabilities

### LINKED ISSUE #108228: libcap 2.27 -> 2.44: breaks security wrapper for cap_dac_override
**Describe the bug**
After update libcap from `2.27` to `2.44` error working capabilites.
```
2021-01-02 18:10:15: /nix/store/xl0n8dqgrqvcr5ypk5n1apdna2q861lh-wrapped-plugins/libexec/netdata/plugins.d/slabinfo.plugin ERROR : MAIN : PROCFILE: Cannot open file '/proc/slabinfo' (errno 13, Permission denied)
2021-01-02 18:10:15: /nix/store/xl0n8dqgrqvcr5ypk5n1apdna2q861lh-wrapped-plugins/libexec/netdata/plugins.d/slabinfo.plugin ERROR : MAIN : <- Cannot open file '/proc/slabinfo
```
and
```
cat /proc/slabinfo
cat: /proc/slabinfo: Permission denied
```

Netdata configuration:
```
  services.netdata = {
    enable = true;
    config = {
      plugins = {
        "enable running new plugins" = "no";
        "proc" = "yes";
        "diskspace" = "no";
        "cgroups" = "no";
        "tc" = "no";
        "idlejitter" = "no";
        "slabinfo" = "yes";
        "ebpf_process" = "no";
        "charts.d" = "no";
        "nfacct" = "no";
        "fping" = "no";
        "go.d" = "no";
        "ioping" = "no";
        "python.d" = "no";
        "node.d" = "no";
        "perf" = "no";
        "freeipmi" = "no";
        "apps" = "no";
      };
    };
  };
```

Wrappers cat:
```
    security.wrappers.cat = {
      source = "${pkgs.coreutils}/bin/cat";
      capabilities = "cap_dac_override=ep";
    };

```
**Notify maintainers**
cc @Mic92 @flokli @ajs124

### PR DESCRIPTION
**Pull request by Mic92**
With libcap 2.41 the output of cap_to_text changed, also the original
author of code hoped that this would never happen.
To counter this now the security-wrapper only relies on the syscall
ABI, which is more stable and robust than string parsing. If new
breakages occur this will be more obvious because version numbers will
be incremented.
Furthermore all errors now make execution explicitly fail instead of
hiding errors behind debug environment variables. The code style was made
more consistent with no goto fail; goto fail; vulnerabilities (https://gotofail.com/)

###### Motivation for this change

fixes https://github.com/NixOS/nixpkgs/issues/108228

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Mic92** [comment]
cc @Izorkin

File: nixos/modules/security/wrappers/wrapper.c [hunk 1]
```diff
@@ -23,182 +25,173 @@ extern char **environ;
...
+            continue;
+        }
+        if (prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_RAISE, (unsigned long) cap, 0, 0)) {
+            fprintf(stderr, "cannot raise the capability %d into the ambient set: %s\n", cap, strerror(errno));
+            return 1;
+        }
+        if (getenv(wrapper_debug)) {
+            fprintf(stderr, "raised %d into the ambient capability set\n", cap);
+        }
+>>>>>>> f4f3d559c0f (nixos/wrappers: fix applying capabilities)
```
Comment (Mic92) [inline nixos/modules/security/wrappers/wrapper.c:136]: dough!

File: nixos/modules/security/wrappers/wrapper.c [hunk 2]
```diff
@@ -23,182 +25,172 @@ extern char **environ;
...
-
-    if (capng_update(CAPNG_ADD, CAPNG_INHERITABLE, (unsigned long) cap))
-    {
-        perror("cannot raise the capability into the Inheritable set\n");
-        exit(1);
+static char *wrapper_debug = "WRAPPER_DEBUG";
+
+#define CAP_SETPCAP 8
+
+#if __BYTE_ORDER == __BIG_ENDIAN
```
Comment (cole-h) [inline nixos/modules/security/wrappers/wrapper.c:35]: Unfamiliar with C best practices (or if this would even work), but maybe byteswap should be `include`d in here, rather than unconditionally?

```suggestion
#if __BYTE_ORDER == __BIG_ENDIAN
#include <byteswap.h>
```

File: nixos/modules/security/wrappers/wrapper.nix [hunk 3]
```diff
@@ -0,0 +1,21 @@
+{ stdenv, linuxHeaders, parentWrapperDir, debug ? false }:
+# For testing:
+# $ nix-build -E 'with import <nixpkgs> {}; pkgs.callPackage ./wrapper.nix { parentWrapperDir = "/run/wrappers"; debug = true; }'
+stdenv.mkDerivation {
+  name = "security-wrapper";
+  buildInputs = [ linuxHeaders ];
+  dontUnpack = true;
+  hardeningEnable = [ "pie" ];
+  CFLAGS = [
+    "-DWRAPPER_DIR=\"${parentWrapperDir}\""
```
Comment (cole-h) [inline nixos/modules/security/wrappers/wrapper.nix:10]: Any reason to not do:

```suggestion
    ''-DWRAPPER_DIR="${parentWrapperDir}"''
```

?

File: nixos/modules/security/wrappers/wrapper.c (hunk 2 above)
Comment (Mic92) [reply nixos/modules/security/wrappers/wrapper.c:35]: I think it is better to always include it so errors, so potential errors from including are catched on little endian as well. It won't have any runtime overhead in any case.

**Comment by Izorkin** [comment]
Thanks, worked!

**Review by cole-h — APPROVED** [review]
Diff LGTM. Tested locally and all my wrappers function as expected.

**Review by Izorkin — APPROVED** [review]

**Comment by vcunat** [comment]
_I'm sorry; I most likely won't have time soon to review these nontrivial changes._

**Comment by Mic92** [comment]
Can someone at least test if it still works on aarch64 because of big endian.

**Comment by vcunat** [comment]
I believe that (normal) aarch64 is little endian.
```
[vcunat@aarch64.nixos.community:~]$ lscpu | grep Endian
Byte Order:          Little Endian
```
