### PR TITLE
yandex-music:  workaround of release circle

### LINKED ISSUE #401199: Build failure: yandex-music
### Nixpkgs version

- Unstable (25.11)

### Steps to reproduce

No unusual action was taken.

Package was included in environment.systemPackages as pkgs.yandex-music

### Relevant log output

```console
error: hash mismatch in fixed-output derivation '/nix/store/8vkm5hn1xxnbbqv2bf0187v18mx8950f-source.drv':
         specified: sha256-xn/9LjRLm6CNLrnrLiYr9deeo09iRMEKCRFuM3SELjw=
            got:    sha256-g6CGk3wdv1IS54OT5wH4VS41XYUdKHXnUaStTsLgEc4=
<.....>
error: 1 dependencies of derivation '/nix/store/wv1p4dbvsr3qi71r13asanb3jbivjjah-yandex-music-5.50.0.drv' failed to build
```

### Additional context

A bit like #357707 
**Reopened as issue persists through upgrades and therefore is likely still present upstream**

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.28, NixOS, 25.11 (Xantusia), 25.11.20250518.292fa7d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.28.3`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/wkjmkjrfr9ik1blw8zmv9g5xjl412py8-source`

### Notify maintainers

@ein-shved 

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [x] I assert that this is a bug and not a support request.
- [x] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+build+failure%22). 
- [x] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by ein-shved**
The [repacker project](https://github.com/cucumber-sp/yandex-music-linux) have release circle with moving tags, which breaks package distribution in nixpkgs. This replaces fixing revisions with hashes and implements automatically counting of "rc" parts of version for case of moving tags.

Fixes #401199 
Instead of #435967 and #437151 
Workaround for https://github.com/cucumber-sp/yandex-music-linux/issues/177

## Things done

- Built on platform:
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- Tested, as applicable:
  - [ ] [NixOS tests] in [nixos/tests].
  - [ ] [Package tests] at `passthru.tests`.
  - [ ] Tests in [lib/tests] or [pkgs/test] for functions and "core" functionality.
- [ ] Ran `nixpkgs-review` on this PR. See [nixpkgs-review usage].
- [ ] Tested basic functionality of all binary files, usually in `./result/bin/`.
- Nixpkgs Release Notes
  - [ ] Package update: when the change is major or breaking.
- NixOS Release Notes
  - [ ] Module addition: when adding a new NixOS module.
  - [ ] Module update: when the change is significant.
- [x] Fits [CONTRIBUTING.md], [pkgs/README.md], [maintainers/README.md] and other READMEs.

[NixOS tests]: https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests
[Package tests]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests
[nixpkgs-review usage]: https://github.com/Mic92/nixpkgs-review#usage

[CONTRIBUTING.md]: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md
[lib/tests]: https://github.com/NixOS/nixpkgs/blob/master/lib/tests
[maintainers/README.md]: https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md
[nixos/tests]: https://github.com/NixOS/nixpkgs/blob/master/nixos/tests
[pkgs/README.md]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md
[pkgs/test]: https://github.com/NixOS/nixpkgs/blob/master/pkgs/test

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

**Comment by ein-shved** [comment]
> WDYM they move tags?

mmm... This is what means. Robot pushes commits to [wrapper project](https://github.com/cucumber-sp/yandex-music-linux) upon updating package by Yandex and adds tags. Then maintainer fixes wrapper code (in case of some bugs) and moves release tag to new commit. This procedure brakes nixpkgs package build when it uses tag as `rev`.

**Comment by SuperSandro2000** [comment]
As far as I can see the tags for older versions exist and are not moved https://github.com/cucumber-sp/yandex-music-linux/commits/master/

**Comment by SuperSandro2000** [comment]
Ah, I think 5.61.1 was retagged from https://github.com/cucumber-sp/yandex-music-linux/commit/784d747d85e0d1bdca80ff9eaa8a83b05d150fd4 to a later commit. Can we try to talk to upstream to stop doing this first?

**Comment by ein-shved** [comment]
> Can we try to talk to upstream to stop doing this first?

Already tried [here](https://github.com/cucumber-sp/yandex-music-linux/issues/177) author ignores this issue =(

**Comment by qweered** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review-gha`](https://github.com/Defelo/nixpkgs-review-gha)

Command: `nixpkgs-review pr 438943`
Commit: [`e6814a8b368368fb4eda300afdab3b07c0e8d341`](https://github.com/NixOS/nixpkgs/commit/e6814a8b368368fb4eda300afdab3b07c0e8d341) ([subsequent changes](https://github.com/NixOS/nixpkgs/compare/e6814a8b368368fb4eda300afdab3b07c0e8d341..pull/438943/head))
Merge: [`473a49893d15ebc7c0a7c00533093f0ddf8694c9`](https://github.com/NixOS/nixpkgs/commit/473a49893d15ebc7c0a7c00533093f0ddf8694c9)

Logs: https://github.com/qweered/nixpkgs-review-gha/actions/runs/17461083431


---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>yandex-music</li>
  </ul>
</details>

---
<details>
<summary>Error logs: `x86_64-linux`</summary>
<details>
<summary>yandex-music</summary>
<pre>Blocks = 75

  0%      6% 7 - icudtl.dat                    10% 23 - locales/fa.pak                         16% 46 - locales/pt-PT.pak                            21% 63 - resources.pak                        28% 65 - resources/app.asar                             36% 71        39% 74        43% 77 - ?????? ??????.exe                            45% 77 - ?????? ??????.exe                            48% 77 - ?????? ??????.exe                            50% 77 - ?????? ??????.exe                            52% 77 - ?????? ??????.exe                            55% 77 - ?????? ??????.exe                            58% 77 - ?????? ??????.exe                            61% 77 - ?????? ??????.exe                            64% 77 - ?????? ??????.exe                            67% 77 - ?????? ??????.exe                            71% 77 - ?????? ??????.exe                            74% 77 - ?????? ??????.exe                            77% 77 - ?????? ??????.exe                            80% 77 - ?????? ??????.exe                            82% 77 - ?????? ??????.exe                            86% 77 - ?????? ??????.exe                            90% 77 - ?????? ??????.exe                            93% 77 - ?????? ??????.exe                            97% 77 - ?????? ??????.exe                           Everything is Ok

Folders: 3
Files: 75
Size:       345941451
Compressed: 103012523
Patching .js chunks
.js chunks patched
Fixing Title
Title Fixed
Replacing Icons
Replaced Icons
Applying patch &#x27;/build/source/patches/0001-Dev-Tools-from-config.patch&#x27;
patching file main/config.js
Hunk #1 FAILED at 4.
1 out of 1 hunk FAILED -- saving rejects to file main/config.js.rej
patching file main/lib/preload.js
Hunk #1 succeeded at 9 with fuzz 1.</pre>
</details>
</details>


---
### `aarch64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>yandex-music</li>
  </ul>
</details>

---
<details>
<summary>Error logs: `aarch64-linux`</summary>
<details>
<summary>yandex-music</summary>
<pre>Blocks = 75

  0%      8% 12 - locales/bn.pak                         16% 47        23% 65 - resources/app.asar                             35% 70 - d3dcompiler_47.dll                             40% 75 - vk_swiftshader.dll                             45% 77 - ?????? ??????.exe                            49% 77 - ?????? ??????.exe                            52% 77 - ?????? ??????.exe                            56% 77 - ?????? ??????.exe                            60% 77 - ?????? ??????.exe                            63% 77 - ?????? ??????.exe                            67% 77 - ?????? ??????.exe                            72% 77 - ?????? ??????.exe                            77% 77 - ?????? ??????.exe                            81% 77 - ?????? ??????.exe                            85% 77 - ?????? ??????.exe                            91% 77 - ?????? ??????.exe                            95% 77 - ?????? ??????.exe                           Everything is Ok

Folders: 3
Files: 75
Size:       345941451
Compressed: 103012523
Patching .js chunks
.js chunks patched
Fixing Title
Title Fixed
Replacing Icons
Replaced Icons
Applying patch &#x27;/build/source/patches/0001-Dev-Tools-from-config.patch&#x27;
patching file main/config.js
Hunk #1 FAILED at 4.
1 out of 1 hunk FAILED -- saving rejects to file main/config.js.rej
patching file main/lib/preload.js
Hunk #1 succeeded at 9 with fuzz 1.</pre>
</details>
</details>

**Comment by ein-shved** [comment]
@qweered @iedame oh! My bad! I've tested build and then - tested update script. Update script updated hashes and I forgot to switch them back. Now should work =)

**Comment by ein-shved** [comment]
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 438943`
Commit: `e32a5d8dfdaa13c4b2008baec19e9d1b1ba77fe8`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>yandex-music</li>
  </ul>
</details>

**Review by iedame — APPROVED** [review]
LGTM, builds okay now.

**Comment by ein-shved** [comment]
@pbsds Hi! The maintainer of github repo continue moving tag. Instead of archiving I am trying to fix by sha1. Can you merge this if it is okay for you?

File: pkgs/by-name/ya/yandex-music/update.sh [hunk 1]
```diff
@@ -19,8 +20,23 @@ date=$(jq -r '.created_at' <<<"$latest_release")
...
+if [ "$oldVersionRc" == "$oldVersion" ]; then
+  oldVersionRc="0"
+fi
+oldVersion="${oldVersion%%rc*}"
+
+rc=""
+
+if [ "$version" == "$oldVersion" ]; then
+  rc="rc$((oldVersionRc + 1))";
+fi
```
Comment (pbsds) [inline pkgs/by-name/ya/yandex-music/update.sh:36]: please document what these bash variable transforms are used for. The `##*` and `%%*` are difficult to remember.

File: pkgs/by-name/ya/yandex-music/update.sh [hunk 2]
```diff
@@ -8,6 +8,7 @@ REPO="yandex-music-linux"
 URL="https://api.github.com/repos/$OWNER/$REPO"
 RAW="https://raw.githubusercontent.com/$OWNER/$REPO"
 
+pname="yandex-music"
```
Comment (pbsds) [inline pkgs/by-name/ya/yandex-music/update.sh:11]: pname has a semantically different meaning

```suggestion
attrname="yandex-music"
```

File: pkgs/by-name/ya/yandex-music/ym_info.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 {
-  "version": "5.57.0",
-  "exe_name": "Yandex_Music_x64_5.57.0.exe",
-  "exe_link": "https://music-desktop-application.s3.yandex.net/stable/Yandex_Music_x64_5.57.0.exe",
-  "exe_hash": "sha256-FIr77eH0ksKSLDJBbyTSd/Qkwd1UFc/VFJ3GEnbOD90="
+  "version": "5.63.1",
+  "exe_name": "Yandex_Music_x64_5.63.1.exe",
+  "exe_link": "https://music-desktop-application.s3.yandex.net/stable/Yandex_Music_x64_5.63.1.exe",
```
Comment (pbsds) [inline pkgs/by-name/ya/yandex-music/ym_info.json:4]: If the tag is unstable, can we assume this one is stable?

**Review by pbsds — COMMENTED** [review]
please address the merge conflict.

I'd also love a follow-up from @supersandro2000

**Review by pbsds — CHANGES_REQUESTED** [review]
It seems the update in `ym_info.json` is gone after the rebase

**Comment by ein-shved** [comment]
> It seems the update in `ym_info.json` is gone after the rebase

Yes. Because someone merged auto-update pach, instead of which I've made this one

File: pkgs/by-name/ya/yandex-music/ym_info.json (hunk 3 above)
Comment (ein-shved) [reply pkgs/by-name/ya/yandex-music/ym_info.json]: This is more stable. This is binary distribution by Yandex, the only problem with which can be - is its deletion on Yandex servers.

While tags are for the [repacker](https://github.com/cucumber-sp/yandex-music-linux) (from exe to linux) project, the release circle of which is:
* automatically update hashes and tag once new binary appeared on servers
* fixes by hand and moving tags on new fixes commits.

File: pkgs/by-name/ya/yandex-music/update.sh (hunk 1 above)
Comment (ein-shved) [reply pkgs/by-name/ya/yandex-music/update.sh]: Done!

**Review by SuperSandro2000 — APPROVED** [review]

**Review by pbsds — APPROVED** [review]
