### PR TITLE
k3s: fix update script

### LINKED ISSUE #430227: k3s: update script is broken at images-versions
k3s: update script is broken at images-versions

See:
- https://github.com/NixOS/nixpkgs/pull/429806#discussion_r2248867826 
- https://github.com/NixOS/nixpkgs/pull/429505#discussion_r2248869354
- https://github.com/NixOS/nixpkgs/pull/430620

I did try to fix this, my fix attempt went:
```
IMAGES_ARCHIVES=$($CURL "https://api.github.com/repos/k3s-io/k3s/releases/tags/v${K3S_VERSION}" | \
    # Filter the assets so that only zstd archives and text files that have "images" in their name remain
    jq -r '.assets[] | select(.name | (contains("images") and (endswith(".tar.zst") or endswith("k3s-images.txt")))) |
        "\(.name) \(.browser_download_url)"')
```
Which gets to list the 4 expected files. Then there is something I don't understand:
- How [images-list](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/k3s/update-script.sh#L79) / `k3s-images.txt` hash is being generated?
  - https://github.com/NixOS/nixpkgs/pull/375610

I made this work by injecting: 
> $($CURL "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/k3s-images.txt" | sha256sum | cut -d' ' -f1)  k3s-images.txt"

into $SHA256_HASHES, but does that make sense?
Humm... I don't fully understand the INITIAL problem. Confused.

But I seem to have restored the functionality of update script in PR [#430720](https://github.com/NixOS/nixpkgs/pull/430720) but my understanding of fundamental issue is faulty.

CC @NixOS/k3s

### PR DESCRIPTION
**Pull request by superherointj**
k3s: fix update script

Fixes #430227

CC @NixOS/k3s

### CODE REVIEW

File: pkgs/applications/networking/cluster/k3s/update-script.sh [hunk 1]
```diff
@@ -76,15 +76,16 @@ EOF
...
 
 # Concatenate all sha256sums, one entry per line
-SHA256_HASHES="$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-amd64.txt")
-    \n$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-arm64.txt")
-    \n$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-arm.txt")"
+SHA256_HASHES="\
+$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-amd64.txt")
+$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-arm64.txt")
+$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-arm.txt")
+$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/k3s-images.txt" | sha256sum | cut -d' ' -f1)  k3s-images.txt"
```
Comment (superherointj) [inline pkgs/applications/networking/cluster/k3s/update-script.sh:83]:
```suggestion
$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/k3s-images.txt" | sha256sum | cut -d' ' -f1)  k3s-images.txt"
```
I manually inject `k3s-images.txt` hash here. Is this expected? I have no idea how this hash was being generated before. This is the part I don't really understand how was working before.

File: pkgs/applications/networking/cluster/k3s/update-script.sh [hunk 2]
```diff
@@ -76,15 +76,16 @@ EOF
 mv chart-versions.nix.update chart-versions.nix
 
 # Concatenate all sha256sums, one entry per line
-SHA256_HASHES="$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-amd64.txt")
-    \n$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-arm64.txt")
-    \n$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-arm.txt")"
+SHA256_HASHES="\
```
Comment (superherointj) [inline pkgs/applications/networking/cluster/k3s/update-script.sh:79]:
```suggestion
SHA256_HASHES="\
```
The text file was not being properly generated, it was including "extra spaces" and "\n".

File: pkgs/applications/networking/cluster/k3s/update-script.sh [hunk 3]
```diff
@@ -76,15 +76,16 @@ EOF
...
+$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-arm64.txt")
+$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/sha256sum-arm.txt")
+$(curl -L "https://github.com/k3s-io/k3s/releases/download/v${K3S_VERSION}/k3s-images.txt" | sha256sum | cut -d' ' -f1)  k3s-images.txt"
 
 # Get all airgap images files associated with this release
 IMAGES_ARCHIVES=$(curl "https://api.github.com/repos/k3s-io/k3s/releases/tags/v${K3S_VERSION}" | \
     # Filter the assets so that only zstd archives and text files that have "images" in their name remain
-    jq -r '.assets[] | select(.name | contains("images")) |
-        select(.content_type == "application/zstd" or .content_type == "text/plain; charset=utf-8") |
+    jq -r '.assets[] | select(.name | (contains("images") and (endswith(".tar.zst") or endswith("k3s-images.txt")))) |
```
Comment (superherointj) [inline pkgs/applications/networking/cluster/k3s/update-script.sh:88]: Replaces reliance on `content_type` to file name. At GitHub, last release did not show `application/zstd` as `content_type` but `octect-stream`. Well, a bit weird. I need to double check this.

Comment (rorosen) [reply pkgs/applications/networking/cluster/k3s/update-script.sh:90]: I like this, the update script should have very little expectations about how assets are organized. Relying only on the asset name is good, maybe the update script now doesn't break when assets are changed next time.

**Review by rorosen — APPROVED** [review]
This are good fixes.

File: pkgs/applications/networking/cluster/k3s/update-script.sh (hunk 1 above)
Comment (rorosen) [reply pkgs/applications/networking/cluster/k3s/update-script.sh]: I think the hash was there before but they removed it now

**Review by wrmilling — APPROVED** [review]
LGTM
