### PR TITLE
setup.sh: avoid running the same hook twice

### LINKED ISSUE #41340: GCC fails because argument list created by nix is too long
### Quick summary

* nix blows up number of `-L` flags passed to GCC
* GCC passes all `-L` flags to its subprogram `cc1` via an environment variable
* If that's longer than 128 KB, then everything crashes with `E2BIG`

### Details

So once again, I'm building some Haskell with lots of library dependencies.

Trying to upgrade this build to 18.03, the `nix-build` of the Haskell package newly fails with

```
Setup: Missing dependencies on foreign libraries:
* Missing C libraries: glog
```

This error message is wrong (cabal doesn't correctly propagate the `argument list too long` error shown below; I filed a bug about it being misleading at https://github.com/haskell/cabal/issues/5355); the dependency exists.

The problem is that because in some eventual `gcc` invocation the amount of arguments passed to GCC turns out to be very long.

`strace` confirms:

```
strace -fye execve -s 100000000 -v runhaskell Setup.hs build 2>&1 | grep E2BIG
```

```
execve("cc1", [arguments here], [env vars here, "COLLECT_GCC_OPTIONS='-fno-stack-protector -L... 150KB of -L flags here'"] = -1 E2BIG (Argument list too long)
```

`E2BIG (Argument list too long)`, in this case because `COLLECT_GCC_OPTIONS` is longer than 128 KB (32 * 4 KB pages, see [here](https://unix.stackexchange.com/a/120842/100270)).

What is the `COLLECT_GCC_OPTIONS` environment variable? [It is](https://gcc.gnu.org/ml/gcc-help/2013-05/msg00093.html) an environment variable set by `gcc` before calling out to `cc1`, over which it communicates flags to `cc1`. Most (if not all?) flags given to gcc will make it into this variable. So it can grow very big (easily larger than the 128 KB limit, especially on nix).

Note that even flags given in a "response file" via `gcc @myresponsefile.rsp` (which was designed to pass GCC flags via a file instead of command line args to circumvent command line arg limits) will be put into `COLLECT_GCC_OPTIONS` by `gcc` itself to communicate them to `cc1` (I have just confirmed that with a small example on my Ubuntu 16.04). So using `@myresponsefile.rsp` is _not_ a workaround. (Yes, this seems to defeat the purpose of response files, but I suspect those were originally made to circumvent a much smaller limit of command line argument on Windows, where the limit is well below the 128 KB limit for environment variable lengths on Linux).

---

Aside: nix inflates the number of `-L` flags by the fact that each `-L` option to gcc is present multiple times, but those duplicates make only for factor 4x or so; even if they were deduplicated, I'd already be at half of [`MAX_ARG_STRLEN`](https://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument/120842#120842) with my medium-size Haskell project; so if I added a couple more dependencies to my Haskell project (all _recursive_ nix Haskell dependencies make it as `-L` options into the gcc command line), I'd quickly exceed that limit again even without duplication.

---

### Problems to fix

1. Deduplicating the `-L` flags passed to GCC will help the issue by a small constant factor and make a couple more projects compile, but won't help with projects with many dependencies.
2. The fundamental issue seems to be a GCC problem (its way of passing arbitrarily sized information via environment variables to a direct child program doesn't work), so technically it's not nix's department. But we need to do something about it, because otherwise we can't build large Haskell projects (on nix or otherwise).

### Steps to reproduce

* Build a Haskell project with lots of dependencies on nixpkgs 18.03.
  * **update:** and lots of native C dependencies, and lots of `executable` sections in the cabal file, see [comment](https://github.com/NixOS/nixpkgs/issues/41340#issuecomment-393887066) below

## Environment

* on top of nixpkgs commit a0b977bdb461a756047adb1dcbb70d7c106507da; tested on both NixOS and Ubuntu 16.04

### PR DESCRIPTION
**Pull request by matthewbauer**
In strictDeps=false, we don’t want the same package hook to be run
twice, otherwise we get duplicates in some flags.

Fixes #41340

### CODE REVIEW

**Comment by cdepillabout** [comment]
Any update on getting this into staging?

I've been running into #41340 on darwin and it would be really nice to have it finally fixed!

**Comment by Infinisil** [comment]
I don't think this solves https://github.com/NixOS/nixpkgs/issues/27533, right? Seems related

**Comment by matthewbauer** [comment]
No it won't fix that issue. But it shouldn't be too hard to fix...

File: pkgs/stdenv/generic/setup.sh [hunk 1]
```diff
@@ -562,6 +562,10 @@ _addToEnv() {
             (( "$depHostOffset" <= "$depTargetOffset" )) || continue
             local hookRef="${hookVar}[$depTargetOffset - $depHostOffset]"
             if [[ -z "${strictDeps-}" ]]; then
+
+                # Keep track of which packages we have visited before.
+                local visitedPkgs=""
```
Comment (dtzWill) [inline pkgs/stdenv/generic/setup.sh]: (I'm not an expert, but would it be better to use an array instead of building/scanning a string? IIRC there are some issues with some shell features so maybe it's a bad idea for those or other reasons)

File: pkgs/stdenv/generic/setup.sh [hunk 2]
```diff
@@ -574,7 +578,11 @@ _addToEnv() {
                     ${pkgsHostTarget+"${pkgsHostTarget[@]}"} \
                     ${pkgsTargetTarget+"${pkgsTargetTarget[@]}"}
                 do
+                    if [[ "$visitedPkgs" = *"$pkg"* ]]; then
```
Comment (dtzWill) [inline pkgs/stdenv/generic/setup.sh]: Is this susceptible to false matches when package is a substring of another?

Oh, nevermind, these are probably store paths so that can't happen, right? :)

**Review by dtzWill — COMMENTED** [review]
Small questions, more than a review really :).
