### PR TITLE
cc-wrapper: use a temporary file for reponse file

### LINKED ISSUE #245167: gccStdenv on Darwin broken (locally?)
### Describe the bug
Trying to use a `gccStdenv` on Darwin locally is broken for me. A good test for this is `acme-client`.

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/yhgcqdkp09pxcihllw2b1j3h8645y7hf-acme-client-1.3.2.tar.gz
source root is acme-client-1.3.2
setting SOURCE_DATE_EPOCH to timestamp 1686437304 of file acme-client-1.3.2/usr.sbin/acme-client/parse.c
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
configure flags: --disable-dependency-tracking --prefix=/nix/store/p5y4jvndi9p9qjlmvr6lnwjx0wm6vwah-acme-client-1.3.2
checking build system type... i386-apple-darwin17.7.0
checking host system type... i386-apple-darwin17.7.0
checking for a BSD-compatible install... /nix/store/8fr8kndrn5ga5agybsnncl966spqs5fv-coreutils-9.3/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /nix/store/8fr8kndrn5ga5agybsnncl966spqs5fv-coreutils-9.3/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/private/tmp/nix-build-acme-client-1.3.2.drv-2/acme-client-1.3.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

```
configure:3244: checking for C compiler version
configure:3253: gcc --version >&5
ld: unknown option: -fPIC
```

But fetching built derivations from cache.nixos.org works fine?

### Steps To Reproduce
1. Nixpkgs https://github.com/NixOS/nixpkgs/commit/9ca785644d067445a4aa749902b29ccef61f7476
2. `nix-build -A acme-client` downloads fine from cache.nixos.org
3. `nix-build -A acme-client --check` fails with the above error

### Expected behavior
`gccStdenv` works locally.

### Screenshots
n/a

### Additional context
- Disabling PIC hardening instead makes it complain about `-O2`.
- Starts to fail between 69eb0416d54 and 2bc2bf30f78 on nixos-unstable, trying to bisect.

### Notify maintainers
I'm not sure what broke this & where, and the stdenvs & cc-wrapper derivations & files don't have any listed maintainers. Maybe @reckenrode because you recently touched Darwin stdenv?

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
- system: `"x86_64-darwin"`
- host os: `Darwin 17.7.0, macOS 10.13.6`
- multi-user?: `no`
- sandbox: `no`
- version: `nix-env (Nix) 2.13.3`
- channels(puna): `"nixpkgs"`
- nixpkgs: `/users/puna/.nix-defexpr/channels/nixpkgs`
```

### PR DESCRIPTION
**Pull request by reckenrode**
The Darwin stdenv rework conditionally sets `NIX_CC_USE_RESPONSE_FILE` depending on the `ARG_MAX` of the build system. If it is at least 1 MiB, the stdenv passes the arguments on the command-line (like Linux). Otherwise, it falls back to the response file. This was done to prevent intermitent failures with clang 16 being unable to read the response file. Unfortunately, this breaks `gccStdenv` on older Darwin platforms.

Note: While the stdenv logic will also be reverted, this change is needed for compatibility with clang 16.

GCC is capable of using a response file, but it does not work correctly when the response file is a file descriptor. This can be reproduced using the following sequence of commands:

```
$ nix shell nixpkgs#gcc; NIX_CC_USE_RESPONSE_FILE=1 gcc
# Linux
/nix/store/9n9gjvzci75gp2sh1c4rh626dhizqynl-binutils-2.39/bin/ld: unrecognized option '-B/nix/store/vnwdak3n1w2jjil119j65k8mw1z23p84-glibc-2.35-224/lib/'
/nix/store/9n9gjvzci75gp2sh1c4rh626dhizqynl-binutils-2.39/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
# Darwin
ld: unknown option: -mmacosx-version-min=11.0
collect2: error: ld returned 1 exit status
```

The fix is to create a temporary file instead and remove it in a trap. This should also prevent intermitent failures with clang 16 on older Darwin systems.

Tested by building acme-client with NIX_CC_USE_RESPONSE_FILE=1 set. `$TMP` was reviewed afterward to confirm no files, and `fswatch` was used to confirm that temporary response files were used.

Fixes #245167

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by amjoseph-nixpkgs** [comment]
TIL what a "response file" is.  Thanks!  [For the benefit of others](https://github.com/NixOS/nixpkgs/pull/245297).

> The fix is to create a temporary file instead and remove it in a trap.

Do we need to remove it?

Debugging failed sandboxed builds in Nix is notoriously difficult.  Really the only reliable tool is `--keep-failed`, and we'd like to leave behind as much useful data as possible for diagnosis (since there's really no reliable way to get a shell inside the sandbox at the point of failure -- I've tried a lot of tools that claim to offer this and none of them really works robustly).

LGTM other than this, but somebody with Darwin hardware should review this.

**Comment by reckenrode** [comment]
> Do we need to remove it?

When I was exploring solutions to the clang 16 issue, I tried leaving the temporary files around (with the idea they would be cleaned up when the whole build is cleaned up). Unfortunately, not every build is well-behaved. I found temporary response files in `/tmp` (e.g., while building GHC). I also expect it would be an issue for users with dev shells. `/tmp` is cleaned automatically on Darwin, but user-private temporary directories are not.

> Debugging failed sandboxed builds in Nix is notoriously difficult. Really the only reliable tool is `--keep-failed`, and we'd like to leave behind as much useful data as possible for diagnosis (since there's really no reliable way to get a shell inside the sandbox at the point of failure -- I've tried a lot of tools that claim to offer this and none of them really works robustly).

Given my work recently on the Darwin stdenv and having to fix the fallout of updating clang, I’m sympathetic to that. However, I don’t think the trade-offs are worth it. It’s usually been possible to debug interactively (e.g., source `env-vars` with `--keep-failed` or use `nix develop`), so I wouldn’t want to fill up users’ temporary directories with junk (especially since this is only going to be used on older systems, who may not have a lot of storage to start).

**Comment by reckenrode** [comment]
I’m going to open a PR to revert the `NIX_CC_USE_RESPONSE_FILE` logic in the stdenv. It turns out qtwebengine is failing to build even on new versions of macOS with 1 MiB `ARG_MAX`. This commit will still be needed by clang 16 and should provide compatibility for GCC should it ever need to use response files.

File: pkgs/build-support/cc-wrapper/cc-wrapper.sh [hunk 1]
```diff
@@ -246,10 +246,13 @@ if [[ -e @out@/nix-support/cc-wrapper-hook ]]; then
 fi
 
 if (( "${NIX_CC_USE_RESPONSE_FILE:-@use_response_file_by_default@}" >= 1 )); then
-    exec @prog@ @<(printf "%q\n" \
+    responseFile=$(mktemp --tmpdir cc-params.XXXXXXXXXX)
```
Comment (Artturin) [inline pkgs/build-support/cc-wrapper/cc-wrapper.sh:249]:
```suggestion
    responseFile=$(mktemp --tmpdir cc-params.XXXXXX)
```
https://github.com/NixOS/nixpkgs/pull/178626

**Comment by reckenrode** [comment]
I was going to update the PR when I got home tonight, but thanks for pushing an updated commit.
