### PR TITLE
nixos-prepare-root: chmod if dir already exists, fixes #22413

### LINKED ISSUE #22413: /tmp has wrong permissions on install
## Issue description

My /tmp was set to be root writable only after install, which broke a lot of things. I assume that's because I had created the tmp folder myself as root before running nixos-install while creating a btrfs subvolume hierarchy for the install. 

https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/nixos/modules/installer/tools/nixos-install.sh#L93 apparently creates, but if's already there I think the permission doesn't change

### Steps to reproduce

Run the unstable usb installer.
Format a partition as btrfs, and create subvolumes, including /tmp as root.
Finish installing.
Try running things that use /tmp as user, for example lxqt's menu or pulseaudio.

## Technical details

* System: 17.03pre99759.f66d782 (Gorilla)  - same version installer

### PR DESCRIPTION
**Pull request by lukateras**
###### Motivation for this change

Fixes #22413. Please note that while I have tested the new `setupDir` function separately, I haven't tested `nixos-install` or `nixos-prepare-root`, so testing is appreciated!

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

File: nixos/modules/installer/tools/nixos-prepare-root.sh [hunk 1]
```diff
@@ -30,25 +30,39 @@ if ! test -e "$mountPoint"; then
     exit 1
 fi
 
+setupDir() {
+    mode="$1"
+    shift
+
+    for dir in $@; do
+	if [ -d "$dir" ]; then
```
Comment (copumpkin) [inline nixos/modules/installer/tools/nixos-prepare-root.sh]: Odd indentaton

File: nixos/modules/installer/tools/nixos-prepare-root.sh [hunk 2]
```diff
@@ -30,25 +30,39 @@ if ! test -e "$mountPoint"; then
...
+    done
+}
+
+
 # Create a few of the standard directories in the target root directory.
-mkdir -m 0755 -p $mountPoint/dev $mountPoint/proc $mountPoint/sys $mountPoint/etc $mountPoint/run $mountPoint/home
-mkdir -m 01777 -p $mountPoint/tmp
-mkdir -m 0755 -p $mountPoint/tmp/root
-mkdir -m 0755 -p $mountPoint/var
-mkdir -m 0700 -p $mountPoint/root
```
Comment (Mic92) [inline nixos/modules/installer/tools/nixos-prepare-root.sh]: I think the `install` command does both creating a directory and change permission in one shot.

Comment (yegortimoshenko) [reply nixos/modules/installer/tools/nixos-prepare-root.sh]: You are right, `install -d` does that.

**Comment by yegortimoshenko** [comment]
Switched to `install`. Is there a way to test this script in a prefix without running `nixos-install`?

**Comment by Mic92** [comment]
we have `nix-build nixos/tests/installer.nix` for nixos-install tests.

**Comment by copumpkin** [comment]
Looks good to me if the tests pass 👍

**Comment by orivej** [comment]
NixOS installer tests pass. Thank you!

**Comment by copumpkin** [comment]
Thanks!
