### PR TITLE
pkgs/build-support/php/builders/v2: copy installer-paths to the output

### LINKED ISSUE #373626: php: `buildComposerProject2` does not work with Drupal projects
### Nixpkgs version

- Unstable (25.05)

### Describe the bug

Composer puts Drupal project dependencies into directories under `/web`, and not `/vendor` as `buildComposerProject2` seems to expect. So, building a Drupal project completes, but most of the files are missing.

### Steps to reproduce

I'm listing roughly the commands I ran to reproduce this bug:
```bash
nix run nixpkgs#phpPackages.composer create-project drupal/recommended-project foo
cd foo
# Grab a recommended .gitignore
wget https://git.drupalcode.org/issue/drupal-3082958/-/blob/3082958-add-gitignores-to/composer/Template/RecommendedProject/.gitignore
# Require a module dependency
nix run nixpkgs#phpPackages.composer require drupal/admin_menu
ls web/modules/contrib
# ^ will print 'admin_toolbar'
nix flake init
git init
git add .
```

Change the flake outputs to look something like this:

```flake.nix
    packages.x86_64-linux.default = self.packages.x86_64-linux.composer;

    packages.x86_64-linux.composer = nixpkgs.legacyPackages.x86_64-linux.php.buildComposerProject2 (finalAttrs: {
      pname = "foo";
      version = "1.0.0";
      src = ./.;
      # Please fix the hash in the usual way :)
      vendorHash = "";
      # Whether these are false or true seems to make no difference.
      composerNoPlugins = false;
      composerNoScripts = false;
    });
```

Then run:

```bash
nix build
ls result/share/php/foo/
```

### Expected behaviour

`ls result/share/php/foo/` should include Drupal's file structure under `/web`

### Screenshots

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### System metadata

 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.0-50-generic, Ubuntu, 24.04.1 LTS (Noble Numbat), nobuild`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.5`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

### Notify maintainers

---

**Note for maintainers:** Please tag this issue in your pull request description. (i.e. `Resolves #ISSUE`.)

### I assert that this issue is relevant for Nixpkgs

- [X] I assert that this is a bug and not a support request.
- [X] I assert that this is not a [duplicate of an existing issue](https://github.com/NixOS/nixpkgs/issues?q=is%3Aopen+is%3Aissue+label%3A%220.kind%3A+bug%22+-label%3A%226.topic%3A+darwin%22+-label%3A%226.topic%3A+nixos%22). 
- [X] I assert that I have read the [NixOS Code of Conduct](https://github.com/NixOS/.github/blob/master/CODE_OF_CONDUCT.md) and agree to abide by it.

### Is this issue important to you?

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

### PR DESCRIPTION
**Pull request by coffeeispower**
I made it copy all directories specified in `extra.installer-paths` in `composer.json` file along with the vendor directory.

Fixes #373626
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [X] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

### CODE REVIEW

File: pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh [hunk 1]
```diff
@@ -96,9 +96,23 @@ composerVendorInstallHook() {
     mkdir -p $out
 
     cp -ar composer.json $(composer config vendor-dir) $out/
+    mapfile -t installer_paths < <(jq -r '(.extra."installer-paths" // {}) | keys[]' composer.json)
```
Comment (drupol) [inline pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh:99]: Where is `mapfile` coming from? What if `.extra` or `.extra.installer-paths` does not exists?

**Review by drupol — COMMENTED** [review]
Is this supposed to be taken in account by the `composer/installers` plugin? Are we ignoring it somehow?

File: pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh (hunk 1 above)
Comment (coffeeispower) [reply pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh:99]: 1. mapfile is a bash builtin command
2. It's already handled by the `// {}` part

**Comment by coffeeispower** [comment]
> Is this supposed to be taken in account by the `composer/installers` plugin? Are we ignoring it somehow?

It installs to the build directory, not the output, so we do need to copy all packages to the output

File: pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh (hunk 1 above)
Comment (drupol) [reply pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh:99]: 1. fait enough, TIL
2. You could use `try` so that it is consistent with the rest ? (https://github.com/coffeeispower/nixpkgs/blob/08522a1ed6f73bc24ba733d5e3ee27b6ca2e86a3/pkgs/build-support/php/builders/v2/hooks/composer-install-hook.sh#L63)

**Comment by liammcdermott** [comment]
> > Is this supposed to be taken in account by the `composer/installers` plugin? Are we ignoring it somehow?
> 
> It installs to the build directory, not the output, so we do need to copy all packages to the output

Yeah, it's basically doing the same thing as this [existing code that copies the contents of `vendor` into `$out`](https://github.com/NixOS/nixpkgs/pull/375311/files#diff-46c1968dfc7464095069c9e93e963ae59edf2374ef6435c2948ee6645c6a4c18R98).

Sorry for the naive question, but are `web/{modules,themes,profiles}/contrib` included in the calculation of the vendor hash Nix uses to ensure the build is reproducible?

**Comment by coffeeispower** [comment]
> Sorry for the naive question, but are `web/{modules,themes,profiles}/contrib` included in the calculation of the vendor hash Nix uses to ensure the build is reproducible?
> 
> Edit: Maybe they don't need to be, if the modules are installed into `vendor` as well as those directories?

Yes they are included

**Review by drupol — APPROVED** [review]
I have tested this PR. I built PHPStan, PHPunit, Psalm and it seems that it works.

File: pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh [hunk 2]
```diff
@@ -96,9 +96,23 @@ composerVendorInstallHook() {
...
+    for installer_path in "${installer_paths[@]}"; do
+        # Remove everything after {$name} placeholder
+        installer_path="${installer_path/\{\$name\}*/}";
+        out_installer_path="$out/${installer_path/\{\$name\}*/}";
+        # Copy the installer path if it exists
+        if [[ -d "$installer_path" ]]; then
+            mkdir -p $(dirname "$out_installer_path")
+            cp -ar "$installer_path" "$out_installer_path"
+            # Strip out the git repositories
+            find $out_installer_path -name .git -type d -prune -print -exec rm -rf {} ";"
```
Comment (drupol) [inline pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh:110]: Why would need to do that here? Aren't `.git` directory stripped out already?

Comment (drupol) [reply pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh:110]: What is the command that `composer` runs that uses `git` ? Can you show us an example? Maybe it has a flag to strip those?

Comment (drupol) [reply pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh:110]: For example, using `--prefer-dist` ? (https://stackoverflow.com/questions/25981292/how-to-make-composer-not-create-a-git-directory-for-a-package)

Comment (piotrkwiecinski) [reply pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh:110]: It's a preference but it doesn't guarantee all .git directories get removed if someone builds a project from for example private repositories. I don't think it's a bad thing to have.

**Review by piotrkwiecinski — APPROVED** [review]

File: pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh (hunk 2 above)
Comment (drupol) [reply pkgs/build-support/php/builders/v2/hooks/composer-vendor-hook.sh:110]: allrighty let's keep it.

**Comment by drupol** [comment]
I decided to merge this thing, let's improve it step by step.

**Comment by drupol** [comment]
Can't wait to see a Drupal site running in Nix though ! :)
