### PR TITLE
makeWrapper: Fail loudly when misused

### LINKED ISSUE #24445: Emacs complains about missing arch-dependent data dir
Running `emacs` from current `master` gives the following (non-fatal) warning:

~~~
$ emacs
Warning: arch-dependent data dir '/nix/store/9ng0phrd7gx72r2gk78lfpcav4k84sl4-emacs-25.1/libexec/emacs/25.1/x86_64-unknown-linux-gnu/': Not a directory
~~~

### PR DESCRIPTION
**Pull request by ahmedtd**
###### Motivation for this change

On Wednesday, I tried to run `hexl-mode` in emacs, and four days later, here I am.

This pull request does two things to `makeWrapper` and `wrapProgram`:
  - First, `makeWrapper` checks that the file it is trying to wrap is a normal, executable file.  If not, it dies with a (sometimes) useful backtrace.  This prevents us from trying to wrap insane things like directories and `.pyc` files.
  - Secondly, `makeWrapper` dies with a backtrace on unsupported arguments.

Additionally, there are some follow-on commits that resolve misuses of `makeWrapper` that I ran into while getting emacs to build.

This pull request resolves #24445 and #3277.

Open question: This pull request will convert a lot of currently-silent breakage into build failures.  Will `nox-review wip` be sufficient to shake all of these issues out?

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

### CODE REVIEW

**Comment by ahmedtd** [comment]
Hmmm, it looks like the set of packages that `nox-review pr 24944` wants to build is a little large for me to be comfortable doing so from my laptop.  If need be, I can spin up a VM somewhere to crank it out.

**Comment by FRidh** [comment]
I'm okay with the changes in `pkgs/development/interpreters/python/wrapper.nix`. I have no opinion on the other changes.

File: pkgs/build-support/setup-hooks/wrap-gapps-hook.sh [hunk 1]
```diff
@@ -36,9 +36,12 @@ wrapGAppsHook() {
   done
 
   if [ -z "$dontWrapGApps" ]; then
-    for i in $prefix/bin/* $prefix/libexec/*; do
-      echo "Wrapping app $i"
-      wrapProgram "$i" "${gappsWrapperArgs[@]}"
+    # Loop over files, without falling prey to filenames containing
+    # newlines, backslashes, or other horrible things.
+    find "${prefix}/bin" "${prefix}/libexec" -type f -executable -print0 \
+    | while IFS= read -r -d '' file; do
```
Comment (Mic92) [inline pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: Are you sure `-d ''` is correct here and not `-d '\0'`

File: pkgs/development/interpreters/python/wrapper.nix [hunk 2]
```diff
@@ -23,17 +23,29 @@ let
...
+      # executables will be used, so it doesn't hurt anything --- it's just a
+      # little distressing.
+      #
+      # The "wrapped wrappers" will not function correctly, since they might
+      # immediately set PYTHONHOME to be something else.
+      srcstores=(${stdenv.lib.concatStringsSep " " paths})
+      for srcstore in "''${srcstores[@]}"; do
+        if [[ -d "$srcstore"/bin ]]; then
+          find "$srcstore"/bin -type f -executable -print0 \
+          | while read -d "" srcfile; do
```
Comment (Mic92) [inline pkgs/development/interpreters/python/wrapper.nix]: same question here regarding `-d`

File: pkgs/build-support/setup-hooks/wrap-gapps-hook.sh (hunk 1 above)
Comment (Mic92) [inline pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: Ok. Probably works. I was just reading this [FAQ](http://mywiki.wooledge.org/BashFAQ/020), where variables were set in the loop, which is not the case here.

File: pkgs/development/interpreters/python/wrapper.nix (hunk 2 above)
Comment (Mic92) [inline pkgs/development/interpreters/python/wrapper.nix]: The delimiter is probably ok, but I wonder why IFS is not unset here.

Comment (ahmedtd) [inline pkgs/development/interpreters/python/wrapper.nix]: You're correct, according to that link, IFS should be set.

**Comment by ahmedtd** [comment]
Hmmm, it looks like nox-review chokes on this PR, because it tries to pull in `lispPackages.hu.dwim.asdf`, which doesn't exist (the correct attribute is `lispPackages."hu.dwim.asdf"`).

The fundamental problem seems to be that nix-env doesn't properly quote that attribute when dumping it with `-qa`.

**Comment by volth** [comment]
It could make sense to make ```substituteInPlace``` fail loudly as well (when it found nothing to replace).
Some usages may be needless now or do something unexpected.

**Comment by ahmedtd** [comment]
According to [nix issue 1342](https://github.com/NixOS/nix/issues/1342), dots are not allowed in attribute names.  I guess I will open a PR to fix the packages identified there as being problematic.

**Comment by ahmedtd** [comment]
@volth, I would be fine adding that to this commit series, but I'm worried that making it affect more packages will make it even harder to merge.

What can I do to help move this PR forward?

**Comment by volth** [comment]
Ok, it could be postponed to another PR

File: pkgs/build-support/setup-hooks/make-wrapper.sh [hunk 3]
```diff
@@ -32,26 +36,20 @@ makeWrapper() {
...
-
-        if test "$p" = "--run"; then
+        elif [[ "$p" == "--run" ]]; then
             command="${params[$((n + 1))]}"
             n=$((n + 1))
             echo "$command" >> "$wrapper"
-        fi
-
-        if test "$p" = "--suffix" -o "$p" = "--prefix"; then
+        elif [[ ("$p" == "--suffix") || ("$p" == "--prefix") ]]; then
```
Comment (peti) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: It's very unfortunate that unrelated changes likes this one are mixed into a PR that's supposed to be about `makeWrapper`, really. These changes needlessly increase the size of the patch and make it harder to review, which is going to delay a successful merge (or even prevent it from happening altogether). 😞

File: pkgs/build-support/setup-hooks/wrap-gapps-hook.sh [hunk 4]
```diff
@@ -36,9 +36,12 @@ wrapGAppsHook() {
   done
 
   if [ -z "$dontWrapGApps" ]; then
-    for i in $prefix/bin/* $prefix/libexec/*; do
-      echo "Wrapping app $i"
-      wrapProgram "$i" "${gappsWrapperArgs[@]}"
+    # Loop over files, without falling prey to filenames containing
```
Comment (peti) [inline pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: I don't believe the problem this change attempts to fix actually exists:

~~~
$ touch "this is a test"
$ for n in *this*; do echo "$n"; done
this is a test
~~~

File: pkgs/development/interpreters/python/wrapper.nix [hunk 5]
```diff
@@ -23,17 +23,29 @@ let
...
 
-      for path in ${stdenv.lib.concatStringsSep " " paths}; do
-        if [ -d "$path/bin" ]; then
-          cd "$path/bin"
-          for prg in *; do
-            if [ -f "$prg" ]; then
-              rm -f "$out/bin/$prg"
-              makeWrapper "$path/bin/$prg" "$out/bin/$prg" --set PYTHONHOME "$out"
-            fi
+      # Generate new wrapper scripts for the all the executables found in our
```
Comment (peti) [inline pkgs/development/interpreters/python/wrapper.nix]: I don't understand why this modification is a part of this PR. Is this change *necessary* after the modification of `makeWrapper`? Does it depend on the change of `makeWrapper`? If either of these answers is "no", then this modification should be a separate PR.

**Review by peti — CHANGES_REQUESTED** [review]
I am very much in favor of this modification. I'm not thrilled by the fact that seemingly unrelated changes are mixed up in one PR though.

File: pkgs/development/interpreters/python/wrapper.nix (hunk 5 above)
Comment (ahmedtd) [inline pkgs/development/interpreters/python/wrapper.nix]: It is necessary --- before, this code would try to wrap anything at top level in `$path/bin`, including non-executable files (in this case, `.pyc` files) and directories.

Comment (ahmedtd) [inline pkgs/development/interpreters/python/wrapper.nix]: Sorry, it wouldn't try to wrap directories, but it would ignore any files in subdirectories of `$path/bin` (strange, but some packages do this).

File: pkgs/build-support/setup-hooks/wrap-gapps-hook.sh (hunk 4 above)
Comment (ahmedtd) [inline pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: Before, it was attempting to wrap all files in `$prefix/bin` and `$prefix/libexec`, including non-executable files and directories.  Additionally, it ignored files in subdirectories of these roots.

`emacs`, in particular, was broken because of the attempt to wrap directories.

File: pkgs/build-support/setup-hooks/make-wrapper.sh (hunk 3 above)
Comment (ahmedtd) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: I don't think this increases the size of the rebuild... the PR would include that first hunk (calling `die` for improper targets) regardless, so the rebuild set already includes all packages using `makeWrapper`.

I can split the argument strictness commit into a separate PR, though.

File: pkgs/build-support/setup-hooks/wrap-gapps-hook.sh (hunk 4 above)
Comment (peti) [inline pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: Well, then maybe the comment is misleading since it suggests the change is intended to fix handling of file names that contain white space? Am I missing something?

File: pkgs/development/interpreters/python/wrapper.nix (hunk 5 above)
Comment (peti) [inline pkgs/development/interpreters/python/wrapper.nix]: Could this change conceivably be applied to Nixpkgs without having the change to `makeWrapper` first?

File: pkgs/build-support/setup-hooks/make-wrapper.sh (hunk 3 above)
Comment (peti) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: I am not talking about rebuilds. I'm talking about the size of the patch that constitutes this PR i.e. the diff you're suggesting be committed to Nixpkgs.

File: pkgs/development/interpreters/python/wrapper.nix (hunk 5 above)
Comment (ahmedtd) [inline pkgs/development/interpreters/python/wrapper.nix]: Yes, it could.  Is that your preferred route?

File: pkgs/build-support/setup-hooks/make-wrapper.sh (hunk 3 above)
Comment (ahmedtd) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: Sure, it can be split out

File: pkgs/build-support/setup-hooks/wrap-gapps-hook.sh (hunk 4 above)
Comment (ahmedtd) [inline pkgs/build-support/setup-hooks/wrap-gapps-hook.sh]: I agree, the comment is misleading.  I will remove it.

**Comment by ahmedtd** [comment]
OK, everything is separated.  This PR now depends on [https://github.com/NixOS/nixpkgs/pull/25185](PR25185), for the `die` utility function.

File: pkgs/build-support/setup-hooks/make-wrapper.sh [hunk 6]
```diff
@@ -24,6 +24,10 @@ makeWrapper() {
     local params varName value command separator n fileNames
     local argv0 flagsBefore flags
 
+    # We should only be wrapping executable files.
+    [[ -f "${original}" && -x "${original}" ]] || \
+        die "makeWrapper cannot be invoked on ${prog} because it is not an executable file"
```
Comment (peterhoeg) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: Shouldn't that be ```${original}``` instead of ```${prog}``` ?

File: pkgs/build-support/setup-hooks/make-wrapper.sh [hunk 7]
```diff
@@ -131,6 +135,11 @@ filterExisting() {
 wrapProgram() {
     local prog="$1"
     local hidden
+
+    # We should only be wrapping executable files.
+    [[ -f "${prog}" && -x "${prog}" ]] || \
+        die "wrapProgram cannot be invoked on ${prog} because it is not an executable file"
+
```
Comment (peterhoeg) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: I would personally prefer moving this into a function to avoid the duplication.

**Review by peti — APPROVED** [review]

**Review by peti — CHANGES_REQUESTED** [review]
Once https://github.com/NixOS/nixpkgs/pull/24944#discussion_r129479438 is addressed, this patch is ready for merging (into `staging`) IMHO.

**Comment by ahmedtd** [comment]
OK, the patch is rebased on staging and the check has been broken out into its own function, `assertExecutable`.

`nox` is broken right now, but I built a few packages that use `makeWrapper` and they seem to be fine.

**Comment by peti** [comment]
@ahmedtd, we cannot merge this patch without https://github.com/NixOS/nixpkgs/pull/25185, and that PR has had merge conflicts and hasn't seen any update since a long time. I would really like to see both PRs merged, like, soon, but I need your help to get that done. If we cannot make progress with these patches in the next couple of days, then I am inclined to declare this a lost cause and to close both PRs.

**Comment by ahmedtd** [comment]
Oh, it looks like I missed the activity on the other PR.   I will update it
tonight.

File: pkgs/build-support/setup-hooks/make-wrapper.sh (hunk 6 above)
Comment (peti) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: Please address https://github.com/NixOS/nixpkgs/pull/24944/files#r129479438.

**Review by peti — CHANGES_REQUESTED** [review]
I'll merge once that typo pointed out in https://github.com/NixOS/nixpkgs/pull/24944/files#r129479438 is fixed.

**Comment by ahmedtd** [comment]
I'm sorry, it looks like I messed up my rebase on to staging.  I had meant to address that in my last push to the branch.

The branch is now properly rebased on staging, and has the check broken out into an `assertExecutable` function.

File: pkgs/build-support/setup-hooks/make-wrapper.sh [hunk 8]
```diff
@@ -1,3 +1,12 @@
+# Assert that FILE exists and is executable
+#
+# assertExecutable FILE
+assertExecutable() {
```
Comment (peti) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: What happens if the given path is a symlink to an executable?

Comment (ahmedtd) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: It is handled properly.  Cases I just tested:

  * non-executable file: Assertion failure
  * symlink to non-executable file: Assertion failure
  * executable file: Success
  * symlink to executable file: Success
  * traversable directory: Assertion failure
  * symlink to traversable directory: Assertion failure

**Comment by FRidh** [comment]
`help2man`:
```
Builder called die: Cannot wrap  because it is not an executable file
Backtrace:
7 assertExecutable /nix/store/rp2928gdi9x9n8ragk7804nf4msmhrr8-hook/nix-support/setup-hook
36 makeWrapper /nix/store/rp2928gdi9x9n8ragk7804nf4msmhrr8-hook/nix-support/setup-hook
143 wrapProgram /nix/store/rp2928gdi9x9n8ragk7804nf4msmhrr8-hook/nix-support/setup-hook
73 _callImplicitHook /nix/store/0ifjmsk5s6nqxz5wlkb2c78xf1213dkc-stdenv/setup
86 _eval /nix/store/0ifjmsk5s6nqxz5wlkb2c78xf1213dkc-stdenv/setup
36 runHook /nix/store/0ifjmsk5s6nqxz5wlkb2c78xf1213dkc-stdenv/setup
821 installPhase /nix/store/0ifjmsk5s6nqxz5wlkb2c78xf1213dkc-stdenv/setup
977 genericBuild /nix/store/0ifjmsk5s6nqxz5wlkb2c78xf1213dkc-stdenv/setup
2 main /nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh

builder for ‘/nix/store/dy9xw4d9swsj5ynjkw2q2snz5n01hn3v-help2man-1.47.4.drv’ failed with exit code 1
error: build of ‘/nix/store/dy9xw4d9swsj5ynjkw2q2snz5n01hn3v-help2man-1.47.4.drv’ failed

```
https://nix-cache.s3.amazonaws.com/log/dy9xw4d9swsj5ynjkw2q2snz5n01hn3v-help2man-1.47.4.drv

**Comment by FRidh** [comment]
The same happens with `wrapPython` that is used by `buildPythonPackage`.
In this case its `bootstrapped-pip` that fails which is essential for building Python packages.
```
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing

Builder called die: Cannot wrap  because it is not an executable file
Backtrace:
7 assertExecutable /nix/store/rp2928gdi9x9n8ragk7804nf4msmhrr8-hook/nix-support/setup-hook
36 makeWrapper /nix/store/rp2928gdi9x9n8ragk7804nf4msmhrr8-hook/nix-support/setup-hook
143 wrapProgram /nix/store/rp2928gdi9x9n8ragk7804nf4msmhrr8-hook/nix-support/setup-hook
986 genericBuild /nix/store/0ifjmsk5s6nqxz5wlkb2c78xf1213dkc-stdenv/setup
2 main /nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh

builder for ‘/nix/store/xv54v5jjdyb4q59my0sikdpy8mkpp2vq-python2.7-bootstrapped-pip-9.0.1.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/6nnj7rishdc06gflj2j4pmi2aq9bx48g-python2.7-pytest-3.0.7.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/6nnj7rishdc06gflj2j4pmi2aq9bx48g-python2.7-pytest-3.0.7.drv’ failed
```
The wrapper is defined at https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/wrap.sh

**Comment by peti** [comment]
@ahmedtd, I wonder why those error message don't contain the path that was supposed to be wrapped?

File: pkgs/build-support/setup-hooks/make-wrapper.sh [hunk 9]
```diff
@@ -24,6 +33,8 @@ makeWrapper() {
     local params varName value command separator n fileNames
     local argv0 flagsBefore flags
 
+    assertExecutable "${file}"
```
Comment (FRidh) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: I think this should be `original` instead of `file`

Comment (ahmedtd) [inline pkgs/build-support/setup-hooks/make-wrapper.sh]: Oh, how embarrassing.  Sorry.

**Comment by Mic92** [comment]
Dropbox build is affected by this change:

```
Builder called die: Cannot wrap /nix/store/g7fnci9zvasw0jqb6a33f49hx72y58hy-dropbox-32.4.23/opt/dropbox/dropbox because it is not an executable file
Backtrace:
7 assertExecutable /nix/store/4j3i3dggkig9hy6mgf9iwraf1y932s1q-hook/nix-support/setup-hook
36 makeWrapper /nix/store/4j3i3dggkig9hy6mgf9iwraf1y932s1q-hook/nix-support/setup-hook
1001 genericBuild /nix/store/xa5a2jlryx7mwadpxg0zgn83rpf66qxy-stdenv/setup
2 main /nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh
```
